### ISSUE TITLE
Possible double reporting in 0.3.7

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-python#100]
We have a simple test that verifies the Sentry SDK is capturing Flask errors because we had some configuration/PyPy issues in the past:

https://github.com/getsentry/snuba/blob/fd44ec8880240575ee2cb05bfc87e4cfd1d0e853/tests/test_api.py#L928-L936

As of this writing we don't pin the `sentry-sdk` version:

https://github.com/getsentry/snuba/blob/fd44ec8880240575ee2cb05bfc87e4cfd1d0e853/setup.py#L80

The test started failing because it seems that as of `0.3.7` (I tried `0.3.6` and wasn't able to reproduce the issue) the `transport` is being called twice for the same exception, causing the number of reported issues to be `2` instead of `1`.

Maybe this is a false alarm but I think our integration is relatively simple so this may be signs of a larger issue?

**Comment by untitaker** [comment]
Hi, thanks for raising this issue. This is a design flaw in how
integrations work, but it has nothing to do with either the lgoging

**Comment by untitaker** [comment]
Hi, thanks for raising this issue. This uncovered a rather big design flaw in how the dedupe integration works, for now I would suggest not to create a separate hub for your test but rather use `Hub.current.bind_client` to set your new client and restore the old one.

**Comment by mitsuhiko** [comment]
@untitaker why does it only run for one hub?

**Comment by untitaker** [comment]
`install` is called once and that calls `configure_scope()`, which uses whatever is the current hub. In pytest that is not even the main one.

**Comment by mitsuhiko** [comment]
@untitaker generally the integrations should not patch one specific hub. I think the solution will be an internal api to have global event handlers that integrations can register.

**Comment by untitaker** [comment]
What do you think about changing `copy(scope)` such that `self._error_processors` is not shallow-copied, but child scopes keep a reference to the list? That would mean running `Hub.main.add_error_processor` would propagate down to all child scopes.

**Comment by mitsuhiko** [comment]
@untitaker i rather not do that particularly because there is no requirement to inherit the same scope.

**Comment by untitaker** [comment]
@mitsuhiko I mean to have a list of lists of scopes. The first scope has this:

    processors1 = [[fn_1]]

the child scope is created like this:

   processors2 = processors1 + [[]]

`add_event_processor` would append to the last sub-list.

Each `push_scope` increases the number of sub-lists of the current scope, because the scope has a list of processor lists: Its own processor list at the end and all the processor lists from its parents.

Or it just has a pointer to the parent scope.

**Comment by nhymxu** [comment]
I get same error today with newest sentry sdk + flask

**Comment by untitaker** [comment]
@nhymxu I believe this is fixed in 0.4.0
