### ISSUE TITLE
How can I send events to two different projects from my python code

### ISSUE THREAD

**Issue by yossivainshtein** [getsentry/sentry-python#1000]
Currently, I write error events from my python component to a sentry project.
The way I do this is by adding to logger a handler which writes to sentry.

The code is along those lines:
 
```
   class _SentryioHandler(logging.Handler):
        def emit(self, record):
            sentry_sdk.capture_message(self.format(record))
...
    def initialize_logger():
       sentry_sdk.init(dsn=SENTRY_URL,
                            release=f"{env}@{release_major_version}",
                            environment=env,
                            integrations=[SqlalchemyIntegration(), TornadoIntegration(), AioHttpIntegration()])
       with sentry_sdk.configure_scope() as scope:
                scope.set_tag("release-version", release_version)
                scope.set_tag("backend-version", backend_version)

        handler_sentryio = self._SentryioHandler()
        handler_sentryio.setLevel(logging.ERROR)

        self.default_logger = logging.getLogger("default_logger")
        self.default_logger.addHandler(handler_sentryio)
```

Now I'd like to send some events to a different project, depending on some condition (In my case, one of the event sources sends a lot of events and I want to separate them for clarity, but it can be any condition).

Is there a recommended/supported way to do this?
because the way I use it right now, I call `sentry_sdk.init`just once with the project URL, and then use `sentry_sdk.capture_message` to send it. 

I saw [this issue](https://github.com/getsentry/sentry-python/issues/198), but I'm not sure whether the ways suggested there are officially supported? Also, they rely quite a bit on the current implementation. Is there a recommended way to achieve this?

Thanks

**Comment by untitaker** [comment]
both the solution by saifelse and the one I posted should work. We don't have a recommended way to do this, but are working on serverside solutions to throttle traffic based on conditions at the moment.

Aside I would use [our own log handlers](https://docs.sentry.io/platforms/python/guides/logging/#handler-classes) instead of writing your own.
