### ISSUE TITLE
Supporting type imports

### ISSUE THREAD

**Issue by paavanb** [getsentry/sentry-python#1002]
I am currently working in a Python project with strict mypy typechecking that requires functions to be fully typed. In order to implement the `before_send` callback, I need access to the `EventProcessor`, `Event`, and `Hint` types in order to properly annotate the function's signature, like so:

```
def create_handler(exceptions_to_ignore: List[Type[Exception]]) -> EventProcessor:
    def before_send(event: Event, hint: Hint) -> Optional[Event]:
        if "exc_info" in hint:
            _, exc_value, _ = hint["exc_info"]
            if any([isinstance(exc_value, exc) for exc in exceptions]):
                return None
        return event
    return before_send
```

However, all three of these types are defined in `sentry_sdk._types`, and the leading underscore implies I should not be importing from that file. Are there any plans to make these (and other) types part of the public API? At the moment, I am forced to use extremely permissive types (like `Any`), which means my code can't be statically checked by mypy for correctness.

**Comment by untitaker** [comment]
I think the core problem is that those types are not fully fleshed out, and if they were public, changes/refinements of the types can amount to a breaking change in the API

**Comment by paavanb** [comment]
Aren't those types already implicitly public, since users have to implement `before_send`? For example, if `Hint["exc_info"]` changed, it would also break existing code.

**Comment by untitaker** [comment]
I'm not talking about changes to the actual runtime types but rather refinements in the static type hints. This can lead to breaking changes if the return type of before_send becomes more specific (making Hint more specific is unlikely to break stuff). I think before I'd feel comfortable with making those types public, they need to improve significantly and some of that improvement is blocked on improvements in the typing system itself.

**Comment by paavanb** [comment]
Ah I see, do you have an example? My thinking has been that the static type hints reflect the actual runtime types, so if the runtime types didn't change then the static types shouldn't either.

**Comment by untitaker** [comment]
`Event` is currently `Dict[str, Any]`, which is not wrong, but if we changed that to be a TypedDict, before_send's return type would stop typechecking for some people.

That's a very simple example. We may also just say that type hints are exempt from semver. Not sure.

**Comment by antonpirker** [comment]
As this issue was resolved in Feb 2021 and the original poster was happy with the resolution, I close this issue.
