### ISSUE TITLE
sync_and_async_middleware throws exception

### ISSUE THREAD

**Issue by Speedy1991** [getsentry/sentry-python#1014]
Which SDK and version?
sentry_sdk==0.20.0
uvicorn==0.13.3
gunicorn==20.0.4
django==3.1.6

### Steps to Reproduce

copy the middleware example from django [docs](https://docs.djangoproject.com/en/dev/topics/http/middleware/#asynchronous-support):
```
import asyncio
from django.utils.decorators import sync_and_async_middleware

@sync_and_async_middleware
def simple_middleware(get_response):
    # One-time configuration and initialization goes here.
    if asyncio.iscoroutinefunction(get_response):
        async def middleware(request):
            # Do something here!
            response = await get_response(request)
            return response

    else:
        def middleware(request):
            # Do something here!
            response = get_response(request)
            return response

    return middleware
```
Run django async
```
uvicorn.run(
        "apps.asgi:application",
        host="0.0.0.0", port=8000, lifespan='off', loop='asyncio', reload=True,
        ...
    )
```

### Actual Result
```
...
File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/integrations/django/asgi.py
Exception Value: 'function' object has no attribute '__acall__'
```

The problem is, that the decorator style has no `__acall__` and the middleware is a function (not a class)

No problems in 0.19.x
This bug was introduced with this PR https://github.com/getsentry/sentry-python/pull/992

**Comment by ahmedetefy** [comment]
Hey @Speedy1991 Thanks for opening this issue
Looking into it

**Comment by Speedy1991** [comment]
thanks for the quick fix!
Any idea when this will be released?

**Comment by ahmedetefy** [comment]
Anytime, It is already released :)
