### ISSUE TITLE
There is no wheel for 0.20.1

### ISSUE THREAD

**Issue by Mogost** [getsentry/sentry-python#1022]
![image](https://user-images.githubusercontent.com/721963/107932207-58c0c680-6f8e-11eb-9434-8f64ed3e4512.png)

The previous version had
![image](https://user-images.githubusercontent.com/721963/107932291-7130e100-6f8e-11eb-8b42-0b72c51bee0f.png)

The issue most likely came from one of these PRs.
https://github.com/getsentry/sentry-python/pull/1001
https://github.com/getsentry/sentry-python/pull/1012

**Comment by ahmedetefy** [comment]
Hey @Mogost, Thanks for opening the issue 
This should be fixed now, here -> https://pypi.org/project/sentry-sdk/#files
