### ISSUE TITLE
Match old Transactions in Django

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-python#103]
We only report the local function name in old transactions for django. David wants this to be the URL rule for Django. We should port the old resolver over to it (https://github.com/getsentry/raven-python/blob/03559bb05fd963e2be96372ae89fb0bce751d26d/raven/contrib/django/resolver.py).

**Comment by untitaker** [comment]
A solution for this is implemented at #105. It adds a flag to enable the raven behavior but by default still uses the function names (because it's simpler and more consistent with what AWS Lambda, Flask and Sanic do)

**Comment by dcramer** [comment]
@untitaker we need to enable it by default as we need the user experience to be on par or better than the current SDK. We can detect lambda and change the default based on that, but for normal Django users, which is the vast majority of Django users, the function name is a very poor experience.

**Comment by untitaker** [comment]
We discussed this extensively in Slack and I think the agreement is that Django needs to behave like in Raven but we can still switch Flask to use `endpoint` instead of `rule`. Is that accurate?

**Comment by untitaker** [comment]
Fixed by #105
