### ISSUE TITLE
Health check

### ISSUE THREAD

**Issue by ProstoMaxim** [getsentry/sentry-python#1033]
Is there a way to check current sentry connection through client? Whether dsn value been valid at all?

**Comment by untitaker** [comment]
Can you explain which conditions you want to monitor for, specifically?

**Comment by ProstoMaxim** [comment]
I plan to check in separate job whether sentry configuration, that I set with sentry_sdk.init is correct and my sentry host is up. 
Simple requests to dsn would do, but they just redirect from my project to /auth/login/sentry/

**Comment by untitaker** [comment]
> that I set with sentry_sdk.init is correct

I think that's the problem though, it's hard to tell for me what this means. I think the best way would be to send an actual event every 1h and use [Metric Alerts](https://docs.sentry.io/product/alerts-notifications/metric-alerts/) to check if they arrive.

**Comment by ProstoMaxim** [comment]
Initializing sentry_sdk - it's example right from README from this repository:
```
from sentry_sdk import init, capture_message
init("https://mydsn@sentry.io/123")
```
I want to know whether sentry service is healthy. So I try requests.get("https://mydsn@sentry.io/123") - and it redirects to https://mydsn@sentry.io/auth/login/sentry
So I know that host is up if status code is 200, but I don't know whether "mydsn" value is correct or my project number "123" is correct.
Is there a way to validate mydsn and maybe somehow I can know whether my host is up without using of request.get(), but with help of sentry_sdk.Client

**Comment by untitaker** [comment]
The DSN is not a valid URL in the sense that `/123` is a valid path, or that `mydsn@` is actually sent via HTTP auth.

The only way to really validate the DSN is correct is via some static analysis or by sending in events. As I mentioned you can send one test event regularly and use Sentry's own alerting functionality to message you when the event does not arrive all the time.

**Comment by untitaker** [comment]
ps, if you want to verify via some external monitoring you could hit Sentry's REST API to query for events, but it would involve writing more code

**Comment by ProstoMaxim** [comment]
Writing code would not be a problem. Are there endpoints that I can use to validate mydsn or that project actually exists?
https://docs.sentry.io/api/events/

**Comment by untitaker** [comment]
So the idea would be that you start a service that basically does this:

```
while True:
    time.sleep(3600)
    capture_message("test event")
```

All of those test messages would go into a single issue based on the message string.

You can use https://docs.sentry.io/api/events/list-an-issues-events/ to get the latest event, and check it is not older than one hour.

---

I think there are generally two things you want to monitor:

1. whether your app is reporting correctly
2. whether your sentry app is accepting events correctly

you can obviously monitor both in a simple way with this approach. In sentry.io, we basically solve 2) for you, and 1) you will notice easily with a metric alert like "alert me if there have not been errors in past 24h", which will be enough for larger projects.
