### ISSUE TITLE
Add `capture_exceptions` decorator

### ISSUE THREAD

**Issue by hoou** [getsentry/sentry-python#104]
Please, I'm missing this feature from `raven`.
https://github.com/getsentry/raven-python/blob/4206873d63c461ffe6944029d36951514157928e/raven/base.py#L842

**Comment by untitaker** [comment]
Hi @hoou, could you show me the code where you need this?

**Comment by hoou** [comment]
Hello @untitaker. Unfortunately I can't. It's just general requirement. When I have some function and I wan't to capture all exceptions that I don't catch manually, I want to use decorator instead of try-except block.

**Comment by untitaker** [comment]
We're just generally reluctant to add more functionality that is (trivial) syntactic sugar for existing functionality. I'll just keep this open though.

Generally we try to enable workflows that don't require you to wrap everything with try-catch, but via proper integrations, not syntactic sugar around try-catch

**Comment by untitaker** [comment]
Hey @hoou, we have this now specifically for serverless: https://docs.sentry.io/platforms/python/serverless/

this configures the proper transport (or rather does an equivalent thing) and captures exceptions.

I think serverless was the most popular usecase by far in Raven, so let's close this.
