### ISSUE TITLE
DedupeIntegration causing events not to send 

### ISSUE THREAD

**Issue by mitchfriedman** [getsentry/sentry-python#1043]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
python sentry-sdk==1.0.0 (and previous versions had the same issue - we tried upgrading but still seeing it)
flask, sqlalchemy, redis, celery integrations - haven't touched default integrations settings

We are using gunicorn + heroku with 3 workers.

We are using `ignore_logger` on 1 logger (that seems to work as expected), and the rest of the config is:

```
    sentry_sdk.init(
        os.environ["SENTRY_DSN"],
        integrations=[
            FlaskIntegration(),
            CeleryIntegration(),
            SqlalchemyIntegration(),
            RedisIntegration(),
        ],
        debug=True,
        environment=os.environ["RUNTIME_CONTEXT"],
        ignore_errors=[Unauthorized, Retry],
    )
```

### Steps to Reproduce

```
sentry_sdk.capture_exception(e)
```

in a Flask route handler (or any uncaught exception as well).

### Expected Result

Seeing the result in sentry.

### Actual Result

Nothing in sentry, and logs like:

```
[sentry] INFO: event processor (<function DedupeIntegration.setup_once.<locals>.processor at 0x7fe26bbd9e50>) dropped event
```

Note: our exceptions in our celery worker are being sent completely fine, so we do have the correct DSN/other setup.

**Comment by untitaker** [comment]
if you run with `default_integrations=False`, the dedupe integration is disabled. Can you check whether that actually resolves your issue?

**Comment by mitchfriedman** [comment]
I tried this and unfortunately the events still don't send to sentry.

I ended up resolving this by creating a new project in sentry - it appears it wasn't anything related to my client/config, since the new project "just worked" 🤷‍♂️ Looks like a bug on the sentry SAAS itself.

Thanks for the help though.

**Comment by untitaker** [comment]
ok let me know if anything else comes up
