### ISSUE TITLE
Please detail breaking changes

### ISSUE THREAD

**Issue by philgyford** [getsentry/sentry-python#1046]
The [release notes for v1.0](https://github.com/getsentry/sentry-python/blob/master/CHANGELOG.md#100) say "This release contains breaking changes". 

But what are the breaking changes? Are all six features/fixes going to cause breakages to any pre 1.0 installation? Or only one of them, in certain situations? What do I need to do to prevent things breaking?

**Comment by ahmedetefy** [comment]
Hey @philgyford 
Thanks for bringing that to my attention!

The breaking changes:
- The experimental flag `auto_session_tracking` has been moved to a proper option that is set to `True` by default
- The experimental flag `session_mode` has been removed in favor of auto detecting the mode from within the sdk

Let me know if you have another questions
