### ISSUE TITLE
Django template span has invalid description

### ISSUE THREAD

**Issue by OutOfFocus4** [getsentry/sentry-python#1048]
### Environment

How do you use Sentry?
Self-hosted, version 21.2.0

Which SDK and version?
Python 1.0.0

### Steps to Reproduce

1. Set up performance tracing for a Django application
2. Send performance data for a view which is a subclass of `TemplateView`
3. View the performance information for the view in Sentry

### Expected Result

Sentry accepts all of the submitted performance data.

### Actual Result

The following alert appears above the performance information:

<img width="1304" alt="Sentry Error" src="https://user-images.githubusercontent.com/50265209/110369051-d15bf580-8017-11eb-80c4-b983385d9a21.png">

This is caused by #957.

At https://github.com/Christophe31/sentry-python/blob/db2d87e503b0178a7d56bdedb00db19ac6ddc9d8/sentry_sdk/integrations/django/templates.py#L60, a span is created with the description `self.template_name`. If the `TemplateResponse` was created by a Django `TemplateView`, `template_name` will be a list, not a string.

A similar error can occur with `django.shortcuts.render`, but I don't use it, so I haven't experienced the issue there.

**Comment by untitaker** [comment]
@Christophe31 do you have time to look into this?

**Comment by Christophe31** [comment]
If not string but simple iterable get first  element if string sounds good to you? Or I should try to find which filename was matched? I didn't know we can use template_name lists there. I hope I didn't break any production environment there.

**Comment by Christophe31** [comment]
I don't have test env localy on my laptop anymore but here what would be my patch: https://github.com/Christophe31/sentry-python/commit/501e2d2971b00c90336870d4b5ef627e0a90f948
I suppose it needs to be in a pull request to trigger testing pipeline?
