### ISSUE TITLE
Include Django settings in report

### ISSUE THREAD

**Issue by ziima** [getsentry/sentry-python#1052]
We are trying to switch Django error emails for Sentry, but I noticed, the current Django settings are not recorded. Since they often provide clues for possible errors, it would be helpful to provide them also in Sentry.

**Comment by untitaker** [comment]
That makes sense but you know you can attach them yourself, right?
https://docs.sentry.io/platforms/python/enriching-events/context/

**Comment by ziima** [comment]
Yes, but it seemed to me, it would be useful for Django projects in general.

**Comment by antonpirker** [comment]
Hello @ziima 
We are going to update the integration to support Django 4.0 in full and I think this Issue will then also be a good candidate to include in that update.

So sit tight.

**Comment by ziima** [comment]
@antonpirker Glad to hear that. :+1:

**Comment by sentrivana** [comment]
This is a lot of information to include in the payload for each event. Since there's a working way to do this on demand (https://github.com/getsentry/sentry-python/issues/1052#issuecomment-796777586) I don't think we need to add this to all events.
