### ISSUE TITLE
GCP Integration captures all http errors

### ISSUE THREAD

**Issue by mebibou** [getsentry/sentry-python#1059]
### Environment

Sentry on GCP Function
Sentry SDK latest version (installed today)
GCP on runtime python37

### Steps to Reproduce

In one of my function, I make some requests to an external API, which might return a response 400.
In my code, I ignore those errors with `try: except Exception` as I know these are not actual errors
I **do not** send any errors to Sentry manually, my complete sentry code is:
```python
import sentry_sdk
from sentry_sdk.integrations.gcp import GcpIntegration
sentry_sdk.init(
    dsn=SENTRY_DSN,
    integrations=[GcpIntegration()],
    traces_sample_rate=1.0,
    environment=STAGE,
    release=VERSION
)
```

### Expected Result

Since I am try/catching the code where the HTTP response is 400, nothing should happen on Sentry

### Actual Result

Sentry actually catches those HTTP 400 errors, even my function returns correctly since I handled those errors. It is polluting my sentry dashboard for no reason and I dont know how to turn them off.

<img width="1511" alt="Screen Shot 2021-03-18 at 11 22 08 AM" src="https://user-images.githubusercontent.com/305342/111610951-34017e00-87dc-11eb-809f-e356ffc4a27d.png">

**Comment by ahmedetefy** [comment]
Hey @mebibou 
Thanks for opening this issue!

To be able to help you, I need a bit more information, 
Can you please provide a full screenshot of that error to be able to tell which integration captured this, and please provide the code snippet causing this error

**Comment by mebibou** [comment]
@ahmedetefy I don't think the code will help you much, it is a code to query on google Earth Engine:
```python
ee.FeatureCollection([feature]).getInfo()
```
The `geInfo` method runs a query against the rest API as you can see in the screenshot I sent, it seems to be using `httplib` behind?

The screenshot I shared is the last bit of the breadcrumbs, the rest is just more similar calls to the same API but which return 200 instead of 400.

A few more screenshots:
<img width="1534" alt="Screen Shot 2021-03-18 at 5 12 10 PM" src="https://user-images.githubusercontent.com/305342/111659255-5d86cd80-880d-11eb-9189-53dcda3f6bd7.png">
<img width="1482" alt="Screen Shot 2021-03-18 at 5 13 50 PM" src="https://user-images.githubusercontent.com/305342/111659261-5f509100-880d-11eb-8094-3b64511c9d50.png">

Maybe you could access the error itself?

**Comment by ahmedetefy** [comment]
I am interested to see what the `mechanism` field states

Sure, can you share the url for the error?

**Comment by mebibou** [comment]
I cant find `mechanism` in the page: https://sentry.io/organizations/university-of-oxford-k9/issues/2279264033/events/c461594387d94a8b89cc36e759b34fee/?project=5614659

**Comment by ahmedetefy** [comment]
In the issue you just passed along, there is a `logger` tag, we also capture exceptions via logging integration which why even though you are wrapping your logic in a `try.. catch`, the errors are still sent to sentry 

Here is a link to our docs on how to disable to that: https://docs.sentry.io/platforms/python/guides/logging/#ignore_logger

Let me know if this solves your problem

**Comment by mebibou** [comment]
So to get this straight, as long as I am logging the errors using the `logging` module, Sentry will automatically log these? it would be nice to:
- have this clearly stated in the docs
- have a simple way to disable that, like `disable_logging_module_integration=True` or something?

But for now I will try to do:
```python
from sentry_sdk.integrations.logging import ignore_logger

ignore_logger('my_logger')
```

Just to make sure, I can call this anywhere? or after `init`?

**Comment by untitaker** [comment]
@mebibou you can call this anywhere, and you can globally disable logging integration with `integrations=LoggingIntegration(event_level=None)`.

**Comment by mebibou** [comment]
@untitaker even better, thanks!

**Comment by untitaker** [comment]
(updated parent comment) to fix type error
