### ISSUE TITLE
Gevent, SentryAsgiMiddleware and ContextVars are not working together

### ISSUE THREAD

**Issue by wearebasti** [getsentry/sentry-python#1063]
It seems to me that #630 re-opened, when using most up to date gevent with current sentry-sdk. The culprit seems to be that the sdk calls `_is_contextvars_broken` in `utils.py` which itself uses gevent's `is_object_patched` function to determine if contextvars was indeed patched.

If I understand the gevent sources correctly they indeed do no longer patch contextvars on python versions >= 3.7 (https://github.com/gevent/gevent/blob/83c9e2ae5b0834b8f84233760aabe82c3ba065b4/src/gevent/monkey.py#L604)

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io), but error happens (already) on local installation

Which SDK and version?
python 3.9.0
sentry-sdk 1.0.0
gevent 21.1.2

### Steps to Reproduce

1. Set up gunicorn with gevent workers, use SentryAsgiMiddleware
2. Try to start gunicorn with gevent (monkey patching activated)
3. Error about missing contextvar support is thrown

### Expected Result

Sentry should work just fine as stated in https://docs.sentry.io/platforms/python/troubleshooting/ for gevent since version 20.5

### Actual Result

Gunicorn workers die with the message

> RuntimeError: The ASGI middleware for Sentry requires Python 3.7+ or the aiocontextvars package.
>
> With asyncio/ASGI applications, the Sentry SDK requires a functional
> installation of `contextvars` to avoid leaking scope/context data across
> requests.

> Please refer to https://docs.sentry.io/platforms/python/contextvars/ for more information.

**Comment by indiejohnny** [comment]
I've got the same issue.

**Comment by tiangolo** [comment]
I implemented a potential fix for this in https://github.com/getsentry/sentry-python/pull/1157 :rocket:

**Comment by tiangolo** [comment]
This was fixed (at least for me) in Sentry Python SDK version `1.3.1` released today. :tada:
