### ISSUE TITLE
`Application instance ... took too long to shut down and was killed` when using Sentry

### ISSUE THREAD

**Issue by WhyNotHugo** [getsentry/sentry-python#1069]
### Environment

I'm using Sentry SaaS (**sentry.io**) and **sentry-python v1.0.0**.

From my `DJANGO_SETTINGS_MODULE`:

```python
from sentry_sdk import init as init_sentry
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import ignore_logger
from sentry_sdk.integrations.logging import LoggingIntegration

# ...

init_sentry(
    attach_stacktrace=True,
    before_send=before_send,
    integrations=[
        CeleryIntegration(),
        DjangoIntegration(),
        LoggingIntegration(event_level=logging.WARNING),
    ],
    release=version,
    in_app_exclude=["logging"],
    ignore_errors=["idf.core.views.TestException"],
    traces_sample_rate=0.2,
)

ignore_logger("django.security.DisallowedHost")
# CeleryIntegration gets us far better logging than this one (it includes
# arguments and variables, and finer grained detail). Since celery events get
# duplicated, ignore this other one:
ignore_logger("celery.app.trace")
```

### Steps to reproduce

I haven't found a way to reliable reproduce this in isolation yet.

For several months now, I'd seen lots of warnings like this (which also results in my users seeing an error):

> Application instance "<Task pending name='Task-40' coro=<patch_django_asgi_handler_impl.<locals>.sentry_patched_asgi_handler() running at /usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/asgi.py:36> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.9/asyncio/futures.py:384, <TaskWakeupMethWrapper object at 0x7fbd9050a610>()]>>" for connection <WebRequest at 0x7fbd919125e0 method=GET uri=/ clientproto=HTTP/1.1> took too long to shut down and was killed.

This has gotten a lot worse recently since I've had heavier load, so set out to debug what's causing this.

Since Sentry wraps the original function here, I can't easily see what was underneath (that timed out), so I temporarily removed sentry in an attempt to see these logs without Sentry's wrappers in the way. This was really me experimenting with little idea where to look.

However, removing sentry makes the problem go away completely. My logs show 0 occurrences of this (the usual is several hundred per day, and this warning has actually eaten most of my Sentry quota a few months already).

So, it seems that Sentry causes the issue here (or, to be accurate, removing sentry makes the problem go away), but I'm not at all sure why or how. I'm not sure how to debug this better though.

Looking at the logs, it seems that sentry does lots of http requests. Is it possible that these are made in a blocking way in the middle of a request-response cycle? If not, do you have any pointers on how to better debug around this?

```
[ WARNING 2021-03-30 12:36:07] daphne.server:270  Application instance <Task pending name='Task-78' coro=<ASGIStaticFilesHandler.__call__() running at /usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py:96> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.9/asyncio/futures.py:384, <TaskWakeupMethWrapper object at 0x7f5e74ee82e0>()]>> for connection <WebRequest at 0x7f5e7481d430 method=GET uri=/admin/idf/order/ clientproto=HTTP/1.1> took too long to shut down and was killed.
[   DEBUG 2021-03-30 12:36:08] urllib3.connectionpool:452  https://o58074.ingest.sentry.io:443 "POST /api/124552/store/ HTTP/1.1" 200 41
[   DEBUG 2021-03-30 12:36:08] urllib3.connectionpool:452  https://o58074.ingest.sentry.io:443 "POST /api/124552/store/ HTTP/1.1" 200 41
[   DEBUG 2021-03-30 12:36:08] asyncio:59  Using selector: EpollSelector
[ WARNING 2021-03-30 12:36:09] daphne.server:270  Application instance <Task pending name='Task-83' coro=<ASGIStaticFilesHandler.__call__() running at /usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py:94> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.9/asyncio/futures.py:384, <TaskWakeupMethWrapper object at 0x7f5e74c1ca90>()]>> for connection <WebRequest at 0x7f5e52020610 method=GET uri=/static/debug_toolbar/js/utils.js clientproto=HTTP/1.1> took too long to shut down and was killed.
[   DEBUG 2021-03-30 12:36:09] urllib3.connectionpool:452  https://o58074.ingest.sentry.io:443 "POST /api/124552/store/ HTTP/1.1" 200 41
[   DEBUG 2021-03-30 12:36:09] urllib3.connectionpool:452  https://o58074.ingest.sentry.io:443 "POST /api/124552/store/ HTTP/1.1" 200 41
[ WARNING 2021-03-30 12:36:10] daphne.server:270  Application instance <Task pending name='Task-79' coro=<ASGIStaticFilesHandler.__call__() running at /usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py:96> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.9/asyncio/futures.py:384, <TaskWakeupMethWrapper object at 0x7f5e537ac9d0>()]>> for connection <WebRequest at 0x7f5e748920d0 method=GET uri=/admin/idf/order/ clientproto=HTTP/1.1> took too long to shut down and was killed.
[   DEBUG 2021-03-30 12:36:10] urllib3.connectionpool:452  https://o58074.ingest.sentry.io:443 "POST /api/124552/store/ HTTP/1.1" 403 61
[   DEBUG 2021-03-30 12:36:10] urllib3.connectionpool:452  https://o58074.ingest.sentry.io:443 "POST /api/124552/store/ HTTP/1.1" 200 41
[   DEBUG 2021-03-30 12:36:12] asyncio:59  Using selector: EpollSelector
172.29.0.1:57722 - - [30/Mar/2021:12:36:12] "GET /admin/jsi18n/" 200 7094
[   DEBUG 2021-03-30 12:36:12] asyncio:59  Using selector: EpollSelector
[ WARNING 2021-03-30 12:36:14] daphne.server:270  Application instance <Task pending name='Task-90' coro=<ASGIStaticFilesHandler.__call__() running at /usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py:94> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.9/asyncio/futures.py:384, <TaskWakeupMethWrapper object at 0x7f5e74c29070>()]>> for connection <WebRequest at 0x7f5e53d38f10 method=GET uri=/static/admin/css/base.css clientproto=HTTP/1.1> took too long to shut down and was killed.
[   DEBUG 2021-03-30 12:36:14] urllib3.connectionpool:452  https://o58074.ingest.sentry.io:443 "POST /api/124552/store/ HTTP/1.1" 403 61
[   DEBUG 2021-03-30 12:36:14] urllib3.connectionpool:452  https://o58074.ingest.sentry.io:443 "POST /api/124552/store/ HTTP/1.1" 403 61
[   DEBUG 2021-03-30 12:36:16] asyncio:59  Using selector: EpollSelector
```

**Comment by WhyNotHugo** [comment]
Disabling traces seems to have made the issue vanish. I applied this to the above config:

```diff
     release=version,
     in_app_exclude=["logging"],
     ignore_errors=["idf.core.views.TestException"],
-    traces_sample_rate=0.2,
+    traces_sample_rate=0,
 )

 ignore_logger("django.security.DisallowedHost")
```

There have been 0 instances of this issue in 7 hours.

**Comment by untitaker** [comment]
"took too long to shut down", does this mean this happens only when you deploy your app? You could get around this by using `init(shutdown_timeout=0.1)` which will lower the time the SDK blocks process shutdown when events are still in the queue. I'm not sure if that's what you're experiencing though.

**Comment by untitaker** [comment]
to answer this part:

>Is it possible that these are made in a blocking way in the middle of a request-response cycle? If not, do you have any pointers on how to better debug around this?

Sentry spawns an additional thread within the process and executes blocking IO on that thread. I am not sure how that could collide with whatever is going on on other threads.

I am looking at Daphne's code and it's not obvious to me what Daphe's criteria for an application shutdown are, and if it's really only the `Future.done()` how would the SDK influence that:

https://github.com/django/daphne/blob/18f2d67f34e33a5f8c87a7bca093dfffea44d7a7/daphne/server.py#L266

**Comment by WhyNotHugo** [comment]
> "took too long to shut down", does this mean this happens only when you deploy your app?

I believe these tasks shut down after each request. Definitely not at application shutdown, since I've seen hundreads happen at times when django was _not_ about to exit.

> Sentry spawns an additional thread within the process and executes blocking IO on that thread. I am not sure how that could collide with whatever is going on on other threads.

I don't _think_ that should block the main/asyncio thread. The blocking IO only blocks that thread but other threads continue normally, right? :thinking:

**Comment by WhyNotHugo** [comment]
I've confirmed that the urllib3 calls happen on a different thread, so that shouldn't be blocking.

**Comment by untitaker** [comment]
If you use `init(traces_sample_rate=0.2, transport=lambda _: None)`, does the issue also disappear?
