### ISSUE TITLE
CeleryIntegration is not capturing locals

### ISSUE THREAD

**Issue by Alexander3** [getsentry/sentry-python#107]
sentry-sdk==0.3.9
When Exception happens inside celery task, I can see traceback in sentry, but without local variables.
As a workaround, I am capturing exception directly, in `BaseTask` and it works.

```
class BaseTask(Task):
    def on_failure(self, exc, task_id, *args, **kwargs):
        """When passing raw exception to sentry we will get local variable values instead of just message"""
        with push_scope() as scope:
            scope.set_extra('task_id', task_id)
            scope.set_extra('retries', self.request.retries)
            capture_exception(exc)
        super().on_failure(exc, task_id, *args, **kwargs)
```
usage: `@shared_task(base=BaseTask)`

In `CeleryIntegration` `def _process_failure_signal(self, sender, task_id, einfo, **kw):` gets `einfo`, so I don't know why it's not working out of the box.

**Comment by untitaker** [comment]
Thanks, will fix in next release
