### ISSUE TITLE
Pylint complaining `abstract-class-instantiated` because of type hint stunt for `init`

### ISSUE THREAD

**Issue by pcorpet** [getsentry/sentry-python#1081]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
**Saas**

Which SDK and version?
**python-sdk v1.0.0 in Python 3.9**

### Steps to Reproduce

In my code, I call
```py
sentry_sdk.init(dsn=os.getenv('SENTRY_DSN')
```

I use [pylint](https://github.com/PyCQA/pylint/) that just released a version `2.7.4` to statically check my code for lint errors

### Expected Result

No lint error found (that was the case three weeks ago)

### Actual Result

I get this pylint error
```
E0110: Abstract class 'init' with abstract methods instantiated (abstract-class-instantiated)
```

I believe this is due to the [stunt](https://github.com/getsentry/sentry-python/blob/19fa43fec5a20b3561a16970ce395c93ac1be57d/sentry_sdk/hub.py#L120) to have nicer autocompletion that is now detected by pylint.

**Comment by craiga** [comment]
FWIW, I've just started seeing this with an update from Python 3.8 to 3.9.

**Comment by JulienPalard** [comment]
Yes, it happen only on Python 3.9+ (on 3.10 too), it boils down to:
```python
from typing import ContextManager, Any


class init(ContextManager[Any]):
    pass


init()
```

**Comment by belm0** [comment]
isn't the fix straightforward?

```python
if MYPY:
    class _MyContextManager(ContextManager[Any]):
        def __exit__(self, exc_type, exc_value, traceback):
            pass

    class init(ClientConstructor, _MyContextManager):  # noqa: N801
        pass

```

**Comment by ava7** [comment]
Up. @belm0's fix seems to be sorting out the problem

**Comment by nadasaiyed** [comment]
@sl0thentr0py @belm0 @ava7 
I am running into the same issue. `Python 3.6.15`, `sentry-sdk==0.20.3`
I have a module level functions where i am calling 
```
sentry_logging = LoggingIntegration(
            level=logging.INFO,
            event_level=logging.ERROR
        )

sentry_sdk.init(
            dsn=dsn,
            attach_stacktrace=True,
            integrations=[sentry_logging]
        )
```
and pylint is complaining with
``` E0110: Abstract class 'init' with abstract methods instantiated (abstract-class-instantiated)```

we are using `github/super-linter@v4.8.5` for linting in our CI

any idea how to proceed?

**Comment by sl0thentr0py** [comment]
xref to #1415
