### ISSUE TITLE
How does sentry gets access to request body in the asgi middleware?

### ISSUE THREAD

**Issue by stefanondisponibile** [getsentry/sentry-python#1083]
Hello, I was reading through the [asgi middleware](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/asgi.py) and it's not clear to me: how is the request data (i.e. the *json* payload of a POST request, for example) accessed to be sent by sentry, since all that's accessible there is the `scope`, passing `receive` and `send` downstream?

Thank you!

**Comment by untitaker** [comment]
You are right, we are not doing that in the ASGI middleware. I think the docs may be wrong.

**Comment by untitaker** [comment]
https://github.com/getsentry/sentry-docs/pull/3393

**Comment by stefanondisponibile** [comment]
I see! Do you think there's a way to include that too? Or maybe @thomchristie does?

**Comment by untitaker** [comment]
Unfortunately I don't think this is possible in a memory-efficient way. In framework integrations we can piggyback on the in-memory buffering of the framework itself but in a middleware we would have to wrap the bytestream and keep our own copy, which is expensive.

**Comment by stefanondisponibile** [comment]
Thank you :)
