### ISSUE TITLE
Document scope_kwargs on capture_message 

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#1086]
The documentation steers for using `sentry_sdk.set_tag` instead of `sentry_sdk.capture_message(..., tags={..})`. This is a good default but we should be exhaustive in documenting options.

* `sentry_sdk.set_tag`
* `configure_scope()` can stay undocumented where global functions are available
* keyword arguments on capture_message
* `push_scope` should be better documented (outside Hubs/Scopes docs)

**Comment by sentrivana** [comment]
Closing in favor of https://github.com/getsentry/sentry-python/issues/2196
