### ISSUE TITLE
sentry don't reuse connection for errors

### ISSUE THREAD

**Issue by horpto** [getsentry/sentry-python#1087]
### Environment

How do you use Sentry?
self-hosted Sentry 10.1.0

Which SDK and version?
Python sentry-sdk==1.0.0

I was profiling my program and noticed that sentry_sdk were  closing connection after reporting error. It may slow down program quite hard. I suggest make the other alternative transport that will reuse existing connection if there is. Programmer will allowed to choose better transport. I understand that for a rarely occurring errors current transport is maybe the best.
![Peek 2021-04-15 13-46](https://user-images.githubusercontent.com/7109350/114857640-2cd88a80-9df1-11eb-9c2f-a10acf7c2b67.gif)

**Comment by horpto** [comment]
@sl0thentr0py  what's reason of closing issue ?

**Comment by sl0thentr0py** [comment]
Hey @horpto, this was open for a long time and I'm cleaning up stale issues here.
As to why, we already use [`urllib3.PoolManager`](https://github.com/getsentry/sentry-python/blob/c64a1a4c779f75ddb728c843844187006c160102/sentry_sdk/transport.py#L441) which should do most of the connection handling optimization for us, so not sure what more we can do here.
