### ISSUE TITLE
Type hinting for traces_sampler

### ISSUE THREAD

**Issue by Ogaday** [getsentry/sentry-python#1090]
I'm finding the the type declaration of the `traces_sampler` argument to the `sentry_sdk.init` constructor a bit problematic.

### Environment

- Sentry SaaS (sentry.io)
- Python: `sentry-sdk[flask]==0.19.4`
- `mypy==0.812`
- `mypy-extensions==0.4.3`

### Steps to Reproduce
I can't get any variations of the following code to appease mypy:

```python
from typing import Any, Dict, Union
import sentry_sdk


def sampler(context: Dict[str, Any]) -> Union[float, bool]:
    return 1.0


sentry_sdk.init(dsn='', traces_sampler=sampler)
```

I think think the type declaration (`... -> Union[float, bool]`) here is sensible. However, because of the declaration [here](https://github.com/getsentry/sentry-python/blob/4c09f3203d6d19789c6fa729a2e46557ad4ea913/sentry_sdk/_types.py#L35), mypy complains as follows:

```
sentry.py:9: error: Argument "traces_sampler" to "init" has incompatible type "Callable[[Dict[str, Any]], Union[float, bool]]"; expected "Optional[Callable[[Dict[str, Any]], Union[Real, bool]]]"
```

If I try something like this instead:
```python
from numbers import Real
from typing import Any, Dict, Union
import sentry_sdk


def sampler(context: Dict[str, Any]) -> Union[Real, bool]:
    return 1.0


sentry_sdk.init(dsn='', traces_sampler=sampler)
```
I get a different error:

```
sentry.py:7: error: Incompatible return value type (got "float", expected "Union[Real, bool]")
```

Which makes sense to me. I also can't delare my return type as Real:

```python
    proba: Real = 1.0
    return proba
```
gives 
```
sentry.py:7: error: Incompatible types in assignment (expression has type "float", variable has type "Real")
```

So what is the solution here? Is there a reason `Real` was chosen as the return type instead of `float`?

Thanks in advance.

**Comment by untitaker** [comment]
Yeah that type hint is just plain wrong. Can you file a PR for using a
union of float, int and bool instead?

**Comment by Ogaday** [comment]
Done, please let me know if I need to change anything.

In the mean time, I found a workaround for typing a custom `traces_sampler` as follows:

```python
def traces_sampler(context: Dict[str, Any]) -> Any:
    ...
```

Which isn't ideal but at least mypy doesn't complain.
