### ISSUE TITLE
parent_span_id being attached to root celerybeat transactions

### ISSUE THREAD

**Issue by wmak** [getsentry/sentry-python#1096]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-python==1.0.0

### Steps to Reproduce

https://gist.github.com/wmak/fffab40bdbe5329f2ef8bd0a4ff44659
1. Repro project attached, a very basic flask app with an endpoint that starts a celery task + a celerybeat that starts the same task
2. Setup the repro project
3. Run redis on 6379
4. Start the celery worker `celery -A main.celery worker`
5. Start celery beat `celery -A main.celery beat --loglevel=INFO --pidfile=''`
6. Wait for the task to be scheduled

### Expected Result

I don't expect for celery tasks started by celerybeat to have the parent_span_id set to a span_id, especially when there isn't a corresponding transaction with that span to make the association, the repro attached here is flask + celerybeat. But also happens with Django + celerybeat

### Actual Result

The parent_span_id was set in the trace context, so the transaction appears to be orphaned, when it in fact should be a root event instead
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/4205004/115637367-fd88b880-a2dd-11eb-875d-592aae657bd8.png">

**Comment by antonpirker** [comment]
Hello @wmak 
Thanks for writting in. Sorry this issue slipped through the cracks.
This is a really good point, and I think this is a bug that we should address.

As this bug report is already quite old, could you please verify this with the latest Sentry SDK? Thanks!
