### ISSUE TITLE
AWS Lambda integration not working with AWS Chalice

### ISSUE THREAD

**Issue by alonre** [getsentry/sentry-python#110]
When trying to deploy a "Chalice" serverless App, getting exception:
```
    File "/Users/cookie/.virtualenvs/abc/lib/python3.6/site-packages/sentry_sdk/integrations/aws_lambda.py", line 21, in install
    old_make_final_handler = lambda_bootstrap.make_final_handler
AttributeError: module '__main__' has no attribute 'make_final_handler'
```

sentry-python version: 0.3.9
Code in `app.py`:
```python
import sentry_sdk
from sentry_sdk.integrations.aws_lambda import AwsLambdaIntegration

sentry_sdk.init(
    dsn="https://abcdefghac844d2ad72e2d12345678@sentry.io/12345678",
    integrations=[AwsLambdaIntegration()]
)
```

**Comment by alonre** [comment]
FYI: I tried to bypass the exception it didn't seem to work:
```python
    def install(self):
        if not hasattr(lambda_bootstrap, 'make_final_handler'):
            setattr(lambda_bootstrap, 'make_final_handler', None)
        old_make_final_handler = lambda_bootstrap.make_final_handler
```

**Comment by untitaker** [comment]
Hi,

could you tell me how you create a Lambda function? Are you testing this in
some kind of local emulator? I tried to reproduce this issue earlier with
the Python 3.6 and 2.7 runtimes but I couldn't.

**Comment by untitaker** [comment]
also please tell me the output of the following on AWS (without sentry-sdk installed):

```
import sys
import __main__
print(__main__.__file__)
print(list(
  (n, m.__file__) for n, m in sys.modules.items()
))
```

**Comment by untitaker** [comment]
Oh! @alonre, I'm sorry, it wasn't clear that you were getting this exception while deploying! I'll push out a fix soon, hang tight.

**Comment by untitaker** [comment]
I just release 0.3.11. If that doesn't fix the issue please give me the output of the `print`s above.

**Comment by hoou** [comment]
Will this work on localhost when testing? I mean, I want to run my functions, but not in AWS lambda.

**Comment by untitaker** [comment]
It will just disable the integration if it's not in AWS Lambda. What are you testing your application with?

**Comment by alonre** [comment]
Thanks @untitaker, `chalice deploy` now works with 0.3.11.
However, I'm not sure I'm getting exceptions sent to Sentry.

I've disabled the integration and got the printouts you requested (attached).
Thanks for looking into this!
[sentry_sdk_debug_print.txt](https://github.com/getsentry/sentry-python/files/2461461/sentry_sdk_debug_print.txt)

**Comment by untitaker** [comment]
Could you enable `debug=True` in your call to `init` and get me the output? I wonder if the integration thinks it's not on AWS

**Comment by alonre** [comment]
This is what I got (tested couple of times).
Does this make sense?

```
[sentry] DEBUG: Shutting down HTTP transport orderly
[sentry] DEBUG: background worker got shutdown request
[sentry] DEBUG: background worker shut down
[sentry] DEBUG: Killing HTTP transport
[sentry] DEBUG: background worker got kill request
[sentry] DEBUG: Shutting down HTTP transport orderly
[sentry] DEBUG: background worker got shutdown request
[sentry] DEBUG: background worker shut down
[sentry] DEBUG: Killing HTTP transport
[sentry] DEBUG: background worker got kill request
```

**Comment by untitaker** [comment]
Hmm sorry, I forgot about another bug the sdk has. Could you check if this
condition is true or false:
https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/aws_lambda.py#L22

I would expect it to return early on your local machine but not in aws

**Comment by alonre** [comment]
Running in AWS:
```
[DEBUG]	2018-10-09T21:00:04.298Z	__main__ hasattr('make_final_handler'): True
```

**Comment by untitaker** [comment]
Hmm, that sucks. So to summarize, you have a Lambda function that works normally but doesn't send events? Could you share the code?

**Comment by alonre** [comment]
1. Yes - the Lambda is working great
2. No - can't share code* (proprietary)
(* I'll try creating a simple "chalice" App and verify I can reproduce the same behavior - and will share that code)

However, I wrote a tiny wrapper to workaround this and managed to get events:
```python
def capture_exceptions(function):
    @functools.wraps(function)
    def wrapper(*args, **kwargs):
        try:
            return function(*args, **kwargs)
        except Exception as ex:
            sentry_sdk.capture_exception(ex)
            raise ex
    return wrapper
```

**Comment by untitaker** [comment]
Ah, then it's probably related to chalice. We would need a proper
integration for it. I think your workaround is fine.

**Comment by alonre** [comment]
Ok cool.
I opened #117.
I might be able to help with the integration.

**Comment by untitaker** [comment]
Closing as remaining AWS Lambda issues should be about missing framework support
