### ISSUE TITLE
Revive Spark integration

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#1102]
the spark integration is currently unmaintained and we don't have the resources to fix the testsuite. The last pieces of it have been removed from CI in https://github.com/getsentry/sentry-python/pull/1101

**Comment by pvanderlinden** [comment]
It would be good to update the documentation? The integration currently actually causes a lot of exception, see the above Issue.

**Comment by sentrivana** [comment]
Will close this since we revived the test suite in https://github.com/getsentry/sentry-python/commit/bcc563cd79873cb81ebb59fd218c2e35d97762bf

We'll deal with the specific problems with the integration in the individual issues.
