### ISSUE TITLE
serverless: Add test(s) for sentry_lambda_handler

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-python#1112]
To avoid regressions, add test to cover the bug fix in https://github.com/getsentry/sentry-python/pull/1106.

**Comment by antonpirker** [comment]
So this is basically just a "todo" item, that we do not forget about adding tests. We are starting to work on a update to the AWS Lambda integration, so maybe this can be done during this update.

**Comment by antonpirker** [comment]
ok, closing for now.
