### ISSUE TITLE
Improve feedback/information with "broken repr"

### ISSUE THREAD

**Issue by blueyed** [getsentry/sentry-python#1118]
If the `__repr__` of a local object fails, it gets reported as "`<broken repr>`":
https://github.com/getsentry/sentry-python/blob/d7cf16cd28248e0c12aa71e92ee9b2606a6a7400/sentry_sdk/utils.py#L416-L451

It would be more helpful if it would include more information there, e.g. at least the class name of the exception.
It could also be something more sophisticated like:
```python
def _try_repr_or_str(obj):
    try:
        return repr(obj)
    except (KeyboardInterrupt, SystemExit):
        raise
    except BaseException:
        return '{}("{}")'.format(type(obj).__name__, obj)


def _format_repr_exception(exc: BaseException, obj: Any) -> str:
    try:
        exc_info = _try_repr_or_str(exc)
    except (KeyboardInterrupt, SystemExit):
        raise
    except BaseException as exc:
        exc_info = "unpresentable exception ({})".format(_try_repr_or_str(exc))
    return "<[{} raised in repr()] {} object at 0x{:x}>".format(
        exc_info, type(obj).__name__, id(obj)
    )
```
(via https://github.com/blueyed/pytest/blob/8eb380425395332ffdf2cd42b8d7cf8ffab2ea2e/src/_pytest/_io/saferepr.py#L6-L24)

This would help with investigating why a `repr` is broken actually, e.g. with https://github.com/celery/py-amqp/issues/361.

(slightly related: there was some related (still open) PR for raven-python about this already: https://github.com/getsentry/raven-python/pull/1294)

**Comment by sl0thentr0py** [comment]
hi @blueyed, we released an undocumented feature `def sentry_repr` in https://github.com/getsentry/sentry-python/pull/1322.
Could you try it out and see if it fixes your problem?
