### ISSUE TITLE
set_tag() on Span

### ISSUE THREAD

**Issue by alippai** [getsentry/sentry-python#1125]
Using the python SDK I tried to use the syntax below (based on autocomplete as `Span.set_tag(self, key, value)` is not marked private): 
```python
with sentry_sdk.start_span() as span:
    span.set_tag(key, value)
```
But it looks like the tag is not set.
### Expected Result
The tag appearing on the span collected.

### Actual Result
No tag available on the span.

I believe the syntax shown in the docs works:
```python
from sentry_sdk import set_tag
set_tag("page.locale", "de-at")
``` 
However setting tag only for the span / event needs some boilerplate (`push_scope()`) and the method name `Span.set_tag` is error-prone, confusing as the call is ignored. Is this supposed to work already or is this a feature request?

**Comment by sl0thentr0py** [comment]
Hey @alippai, this is very old so I'm closing it.
We use the same construct internally in several places ([example](https://github.com/getsentry/sentry-python/blob/a3170d932b141209ef3e8f05075768f2652ccb9e/sentry_sdk/integrations/redis.py#L90-L92)) so this should work.

Maybe there's something wrong with what you do with the span/transaction to the span later.
