### ISSUE TITLE
stats

### ISSUE THREAD

**Issue by mfatemipour** [getsentry/sentry-python#1129]
Hi, Is there any stats in sdk that maintain count of susscceded/failed sent events, in apps we could use them in monitoring and alerting systems.

**Comment by ahmedetefy** [comment]
Hello @mfatemipour 
Currently we are not storing any of these stats, but if you'd like to capture them, you can always implement a Custom Transport class to capture these stats. 

Also, if all you care about are the failed events, you can probably just extend our `HTTPTransport` class and use the `on_dropped_event` hook that we have there.
Ref PR: https://github.com/getsentry/sentry-python/pull/1100/files
