### ISSUE TITLE
Add extra data to event or message

### ISSUE THREAD

**Issue by ahivert** [getsentry/sentry-python#113]
With raven-python we could add `extra` param to `captureMessage`. Now with sentry-python `capture_message` does not accept extra param.

Can we add extra data to event or message ?

**Comment by untitaker** [comment]
Hi, it's no longer available as kwargs, but you can do this: https://docs.sentry.io/learn/context/?platform=python#extra-context

```python
from sentry_sdk import configure_scope

with configure_scope() as scope:
    scope.set_extra("character_name", "Mighty Fighter")

# all capture_message here have the extra set

with push_scope() as scope:
    scope.set_extra("character_name", "All Might")
    # different extra value inside of this with-statement
```

**Comment by untitaker** [comment]
Right now this doesn't work, you'd have to write something like this:

```python

with push_scope() as scope:
    scope.set_extra(..)
    log.debug("hi")
```

We will probably try to add this at some later point but we don't want too many APIs for doing the same thing

**Comment by untitaker** [comment]
@mitsuhiko any opinion on this?

**Comment by mitsuhiko** [comment]
@untitaker extra from log records should be added automatically.

**Comment by untitaker** [comment]
@mitsuhiko do we want to support more than `event.extra`? Like, user, request, tags...

**Comment by untitaker** [comment]
We internally decided to just support extra and nothing else FWIW

**Comment by untitaker** [comment]
@danielcompton  you would have to modify the event payload in before_send for either usecase

**Comment by EralpB** [comment]
thank you, I hated that I had the option to add some extra information to help me debug the warnings without writing any extra line of code. Forcing us to upgrade helped us to reap this benefit.

**Comment by untitaker** [comment]
@EralpB instead of leaving this kind of comment please describe the actual problem you have. We do our best to balance api simplicity with convenience, and as such the sdk has come a long way since the issue you're commenting on has been created.
