### ISSUE TITLE
Quart ASGI treated as ASGI2 when it should be treated as ASGI3

### ISSUE THREAD

**Issue by gtsatsis** [getsentry/sentry-python#1135]
### Environment

How do you use Sentry?
**Sentry SaaS (sentry.io)**

Which SDK and version?
**sentry-sdk 1.1.0 (pypi)**

### Steps to Reproduce

Using the [Quart framework](https://gitlab.com/pgjones/quart), and the ASGI integration provided in the SDK [(docs)](https://docs.sentry.io/platforms/python/guides/asgi/), as well as following the [Quart middleware documentation](https://pgjones.gitlab.io/quart/how_to_guides/middleware.html), `quart_app.asgi_app` is treated as an ASGI 2 app while it should be treated as an ASGI 3 app.

### Expected Result

The SDK should work, providing request context for errors.

### Actual Result

It seems like [integrations/asgi.py#L53](https://github.com/getsentry/sentry-python/blob/4c09f3203d6d19789c6fa729a2e46557ad4ea913/sentry_sdk/integrations/asgi.py#L53) is causing `quart_app.asgi_app` to report as an ASGI 2 application, erroring out with `_run_asgi2() takes 2 positional arguments but 4 were given`.

Additionally, creating a new variable based on `quart_app`, instead of `quart_app.asgi_app` (`sentry_app = SentryAsgiMiddleware(quart_app`) and serving that seems to work.

Quoting @pgjones from the Quart Gitter
> Ideally it should work with the `app.asgi_app`, which I think (if it works with `app`) is the crucial part to put in the bug report to sentry

**Comment by pgjones** [comment]
Please note that [Quart recommends](https://pgjones.gitlab.io/quart/how_to_guides/middleware.html) that middleware wraps the `app.asgi_app` attribute rather than the `app` directly as the former means that the middleware is correctly invoked in all circumstances - most notably when testing.

**Comment by arusahni** [comment]
I just encountered this issue. I'm currently working around it by patching Sentry's middleware to force it to run as ASGI 3.

```python
SentryAsgiMiddleware._run_asgi2 = SentryAsgiMiddleware._run_asgi3
quart_app.asgi_app = SentryAsgiMiddleware(quart_app.asgi_app)
```

Obviously this is not a long term solution.

**Comment by gtsatsis** [comment]
@arusahni: @augustozanellato had actually posted a cleaner solution in the Quart Gitter; Directly invoking `._run_asgi3` like this: `app.asgi_app = SentryAsgiMiddleware(app.asgi_app)._run_asgi3`. Again, a preferred solution would be to have the root cause of the issue fixed, but this'll work for now :)

**Comment by augustozanellato** [comment]
> @arusahni: @augustozanellato had actually posted a cleaner solution in the Quart Gitter; Directly invoking `._run_asgi3` like this: `app.asgi_app = SentryAsgiMiddleware(app.asgi_app)._run_asgi3`. Again, a preferred solution would be to have the root cause of the issue fixed, but this'll work for now :)

I’m 100% sure I found that somewhere on the internet so don’t credit me for that :P

**Comment by pgjones** [comment]
See also #1248

**Comment by pgjones** [comment]
Could this be labelled as `Status: Backlog`?

**Comment by antonpirker** [comment]
Hello! As time has passed and Quart has now evolved. 
Is this still an issue, or can we close this?

**Comment by pgjones** [comment]
I think this is still a sentry bug, however Sentry now ships a Quart integration which doesn't trigger this bug.

**Comment by antonpirker** [comment]
Ok, thanks for the feedback. Because the QuartIntegration solves this problem I will close this issue. 

If you came across this Issue and want to help fix the issue, please create a new Issue and link to this one. Thanks!
