### ISSUE TITLE
CeleryIntegration wrongly reporting errors for tasks with custom __call__ method

### ISSUE THREAD

**Issue by nbrede** [getsentry/sentry-python#1137]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Python 1.1.0

### Steps to Reproduce

1. Create a custom celery base task class
2. Implement a custom `__call__` method on that base task class
3. Catch and handle certain exceptions in that `__call__` method
4. Raise a different exception from the custom `__call__` method

Example code:

```python
from celery import Task

class CustomBaseTask(Task):
    def __call__(self, *args, **kwargs):
        try:
            super().__call__(*args, **kwargs)
        except CustomExceptionA:
            # do sth
            raise SpecialException()
        except CustomExceptionB:
            pass


@shared_task(base=CustomBaseTask, bind=True)
def some_actual_task(self, ...):
   ...  # do sth here

```

### Expected Result

- Errors caught in the custom `__call__` method should not be sent to sentry (i.e., `CustomExceptionA`, `CustomExceptionB`)
- Errors raised in the custom `__call__` method should be sent to sentry (i.e., `SpecialException`)

### Actual Result

 - `CustomExceptionA` and `CustomExceptionB` are shown by sentry as unhandled (although in fact they are as our other monitoring systems confirm)
 - `SpecialException` is never shown in sentry, although it is being raised (confirmed by our other monitoring systems)

From debugging it seems that sentry wraps the task's `run` method, which is called by the `celery.Task.__call__` method and thus at a lower level than the custom __call__ method.

Also it seems that sentry's attempted wrap of the task's `__call__` method is not working, since `SpecialException` is never sent to sentry.

**Comment by anthonyp97** [comment]
We're having the same issue as well, sentry's blocking of retry errors doesn't work when we define a custom base class that handles errors.

**Comment by Jakeway** [comment]
Bumping this

**Comment by antonpirker** [comment]
Quick update: I am looking into this

**Comment by antonpirker** [comment]
I was trying to reproduce this and the correct exceptions ended up in Sentry. So I looked at the code an there was a contribution two months ago: https://github.com/getsentry/sentry-python/pull/1287

@nbrede the above linked merge request fixes the problem you described. Can you please try with the newest SDK and confirm, that the problem is solved?

This the code I tested it with: https://github.com/antonpirker/sample-projects-for-sentry/blob/main/django3-project/demosite/web/tasks.py
Only `SHOULDShowUpExceptions` ends up in Sentry

**Comment by antonpirker** [comment]
If nothing is replied here the stale bot will close this issue in one month.
