### ISSUE TITLE
Catch crashing threads

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#114]
since `sys.excepthook` is not called for threads that crash, we should write a separate integration for this (turned on by default)

**Comment by mmerickel** [comment]
I noticed some crashing threads that weren't getting reported to sentry and was surprised. I've updated my code to catch them myself but I agree that sentry could try harder here.

Sentry should be able to monkeypatch `threading.Thread._bootstrap_inner`. Unfortunately there is not a good spot to monkeypatch `Thread.run` (which a public api overridable by users) which `Thread._bootstrap_inner` calls directly. Is there a standard approach sentry uses to monkeypatching without vendoring the current `_bootstrap_inner` code into sentry? So far that seems to me to be the only option.

**Comment by untitaker** [comment]
Two ideas:

* Patch `Thread._exc_info` to capture the exception (it gets called in `_bootstrap_inner`)
* Patch `Thread._bootstrap_inner`, but inside the patched function patch `self.run` and just call the old `_bootstrap_inner`.

There is no standard approach to this. An established rule is to patch public/stable APIs rather than private/unstable ones but it seems like we have no choice here.

**Comment by untitaker** [comment]
Actually we can do something that uses only public API: Patch `Thread.start`, patched functions patches `self.run` and calls old `Thread.start`.
