### ISSUE TITLE
Setting transaction name doesn't work from child span.

### ISSUE THREAD

**Issue by CoatedMoose** [getsentry/sentry-python#1155]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Python/Django: django-sentry-1.13.5, sentry-sdk-1.3.0 (also tried sentry-sdk-1.1.0)

### Steps to Reproduce

We're using Sentry in Django and Graphene (for GraphQL support). We would like to set the transaction name based on GraphQL operation name.

```python

urlpatterns = [
    # ...snip
    path(
        'graphql',
        csrf_exempt(MyGraphQLView.as_view(graphiql=settings.GRAPHIQL_ENABLED)),
    ),
]

class MyGraphQLView(graphene_django.views.GraphQLView):
    def execute_graphql_request(
        self, request, data, query, variables, operation_name, show_graphiql=False
    ):
        with sentry_sdk.configure_scope() as scope:
            transaction_name = f'graphql.{operation_name}' # graphql.OperationName
            scope.transaction = transaction_name
            # This works:
            scope._span._containing_transaction.name = transaction_name
            return super().execute_graphql_request(
                request, data, query, variables, operation_name, show_graphiql
            )
```

From the trace view in Sentry, the GraphQLView span is nested several spans down (in Django middlewares). From my understanding of the [sentry documentation: set transaction name](https://docs.sentry.io/platforms/python/enriching-events/transaction-name/) It seems like the `scope.transaction = 'name'` setter should be enough, but doesn't seem to work from child spans.

### Expected Result

Sentry transaction name updated to `graphql.OperationName`.

### Actual Result

Sentry transaction name stays as `/graphql`

**Comment by HazAT** [comment]
Thanks for reporting, we'll take a look

**Comment by CoatedMoose** [comment]
Resetting that clock...

**Comment by sl0thentr0py** [comment]
Hi @CoatedMoose, is this still a problem in the latest SDK version?

**Comment by CoatedMoose** [comment]
I'm in the middle of some tasks and I can't check right now, but will hopefully be able to later in the week.

**Comment by CoatedMoose** [comment]
There doesn't seem to be any improvement with version `1.5.7`. The workaround from my initial report is still working.

**Comment by sl0thentr0py** [comment]
@CoatedMoose yes you're right that the `transaction` getter and setter on `scope` have different behaviour, I'll try to understand why this is the way this is and get back to you, hopefully with a fix. Thx for reporting!

**Comment by lobsterkatie** [comment]
Hi, @CoatedMoose. While you're not wrong in your expectation, given the docs, making `scope.transaction = new_name` work means you're relying on the weird type mismatch between the `transaction` getter and setter. Much better to do `scope.transaction.name`, both because it makes more sense and it future-proofs you for the day when we finally fix that mismatch.

I'll fix the docs to reflect this.
