### ISSUE TITLE
Event attribute `logentry` has no documentation.

### ISSUE THREAD

**Issue by WloHu** [getsentry/sentry-python#1156]
I wanted to filter out events by logger name and log message.

I've tried to figure out attributes available for `Event` object or rather keys of `event` parameter used in function passed to `sentry_sdk.init(..., before_send=the_function)`. It turns out that in my specific case when error log has created an event, it had `logentry.message` keys which I was looking for.
For some reason `logentry` attribute is not mentioned in documentation: https://develop.sentry.dev/sdk/event-payloads/

Moreover I found it very frustrating to look for details about classes (`Event` and `Breadcrumb` in this case) used in your app just by using online documentation. Digging into source code is not ideal I prefer to have some online documentation of types like e.g. `pytest` module has: https://docs.pytest.org/en/6.2.x/reference.html?highlight=fixture%20class#function

**Comment by HazAT** [comment]
Thanks for reporting, we'll try to document this better.

**Comment by antonpirker** [comment]
Thank you @WloHu for suggesting the documentation update. I think we will collect all the documentation issues in one place and try do overhaul our Python SDK documentation.

As for your suggestion about "not digging into the code". Yes, I totally feel you. We also have started (a long time ago) an initiative to have proper API docs. But all we have right now is an empty shell where we need to fill in information: https://getsentry.github.io/sentry-python/

But we will get there. Please be patient.

**Comment by szokeasaurusrex** [comment]
Documentation is now available here: https://develop.sentry.dev/sdk/event-payloads/types/
