### ISSUE TITLE
Add ability to configure transaction style to ASGI integration 

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-python#1165]
In the bottle integration, we can set a transaction style to either `endpoint` or `url` based on integration setting. We should add the same to ASGI.

See: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/bottle.py#L45

**Comment by antonpirker** [comment]
A lot of our Integrations have this feature, so it makes sense to add it to the ASGI Integration.

**Comment by antonpirker** [comment]
This is done.
