### ISSUE TITLE
Add Redis Pipeline to RedisIntegration

### ISSUE THREAD

**Issue by dimastbk** [getsentry/sentry-python#1169]
Hi! Pipeline in redis-py has also have method [execute_command](https://github.com/andymccurdy/redis-py/blob/e19a76c58f2a998d86e51c5a2a0f1db37563efce/redis/client.py#L1531). Can you add redis.client.Pipeline to patching in RedisIntegration? It work: all Z* command on screenshot from one pipeline.
![image](https://user-images.githubusercontent.com/3132181/130817271-df53d5e4-c956-4653-82cd-e75895b73fc9.png)

And maybe PubSub.

**Comment by antonpirker** [comment]
Hello @dimastbk !
Thanks for reporting this.
Just a wild guess, but maybe adding something like `patch_redis_client(redis.client.Pipeline)` after this line: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/redis.py#L45 could be what your are looking for?

Could you try this and see if this is what your are looking for?

**Comment by sl0thentr0py** [comment]
implemented in #1543
