### ISSUE TITLE
AWS Chalice support

### ISSUE THREAD

**Issue by alonre** [getsentry/sentry-python#117]
Chalice defines itself as "Python Serverless Microframework for AWS": https://github.com/aws/chalice

Some relevant information here: #110.

----

**EDIT**: Please vote on this issue with 👍 for Chalice support.

**Comment by untitaker** [comment]
FWIW I don't think this is going to happen within the core package (sentry-sdk).

**Comment by Gleekzone** [comment]
Hi folks!! We, Cuenca, developed an external package for supporting Chalice in AWS (https://pypi.org/project/sentry-chalice/). What would be the steps to integrate this code to sentry-python integrations?

**Comment by untitaker** [comment]
@Gleekzone api in readme looks good but I can't look at your code (repo private?)

I think opening a PR would be the next step. Here's a detailed checklist: https://github.com/getsentry/sentry-python/blob/fcc06d5b5fe6bf05a6292ae0d3a805d76824e4ca/CONTRIBUTING.md#adding-a-new-integration-checklist

**Comment by Gleekzone** [comment]
Here is the correct URL: https://github.com/cuenca-mx/sentry-chalice

**Comment by untitaker** [comment]
https://docs.sentry.io/platforms/python/guides/chalice/

**Comment by alonre** [comment]
Hooray! thanks @untitaker and @Gleekzone !
