### ISSUE TITLE
Django integration: connect Javascript SDK

### ISSUE THREAD

**Issue by danielmanser** [getsentry/sentry-python#1171]
I'm completely stuck with connecting the Python SDK (I'm using Django) and the Javascript SDK. I've installed `sentry-python` and it sends events to my onPrem Sentry installation. Now I want to connect it with the Frontend using Sentry SDK.

I followed the docs and I think I need to add the `trace_id` as a `<meta>` tag in my template. Either I'm too dumb or the docs could be improved, but I've spent 3+hrs trying to get it done with no success.

### Environment

How do you use Sentry?
Sentry onPrem, version 21.8.0, installed with the recommended Docker service using `install.sh`. Sentry seems to work, I can receive errors.

Which SDK and version?
Backend: Python 3.8.5, Django 3.2.6 using sentry-sdk, version 1.3.1
Frontend: Basic HTML, Bootstrap, nothing fancy

Python virtual environment:
```
asgiref==3.4.1
certifi==2021.5.30
Django==3.2.6
django-appconf==1.0.4
django-compressor==2.4.1
django-debug-toolbar==3.2.2
django-extensions==3.1.3
django-honeypot==1.0.1
psycopg2-binary==2.9.1
pytz==2021.1
rcssmin==1.0.6
rjsmin==1.1.0
sentry-sdk==1.3.1
six==1.16.0
sqlparse==0.4.1
urllib3==1.26.6
```

### Steps to Reproduce

1. Set up the Django integration following [the official docs](https://docs.sentry.io/platforms/python/guides/django/). Unhandled errors in Django are working and being sent to my Sentry instance, so I guess this part is not in question.
2. Following [Connecting Services](https://docs.sentry.io/platforms/python/performance/#connecting-services), I decided it would be easiest to add a `<meta>` tag in my Django template, so I followed [this](https://docs.sentry.io/platforms/javascript/performance/connect-services/#pageload):

```html
<meta name="sentry-trace" content="{{ span.toSentryTrace() }}" />
```

I understand that the docs are not Django-specific and I can't call a function within a template in Django. So I've tried a lot of different things, but I don't seem to have the `trace_id` available in my template, nor in the Python environment.

Do I need to add it using a custom template tag? Or is there a middleware I'm not aware of? I've googled for "Django Sentry trace_id" and a lot of other things, searched Github for examples, but didn't find anything that worked.

How do I get that to work? I suspect other Django developers are struggling with that as well, and I hoped it was in the documentation, especially because Django is listed as an integration. I'm willing to contribute this to the docs if appreciated and someone can tell me a recommended way :-)

### Expected Result

Docs including best-practice Instructions for connecting Django templates.

### Actual Result

🙇‍♂️

**Comment by tony** [comment]
@AbhiPrasad I think it'd valuable to have some documentation or examples with django. I'm equally curious.

Thank you for your example at https://github.com/getsentry/sentry-python/issues/1171#issuecomment-906687493

I am curious, what would be the difference between:


```python
def some_view(request):
    with sentry_sdk.configure_scope() as scope:
        span = scope.span
        return render(request, 'template.html', {'sentry-trace': span.to_traceparent()})
```

and 

```python
def some_view(request):
    span = sentry_sdk.Hub.current.scope.span    
    return render(request, 'template.html', {'sentry-trace': span.to_traceparent()})
```

Are there any risks from grabbing it via sentry_sdk.Hub.current.scope.span?  Could that potentially cause issues if it was running on a server with multiple threads/workers/etc?

**Comment by sl0thentr0py** [comment]
@tony they're functionally equivalent but the first one (`configure_scope`) is more 'canonical' usage and is what we do internally in integrations as well.

**Comment by tbrlpld** [comment]
The ["connecting services" section](https://docs.sentry.io/platforms/javascript/performance/connect-services/#pageload) mentions that apart from the `sentry-trace` meta tag you also need to set a `baggage` meta tag. 

```html
<html>
  <head>
    <meta name="sentry-trace" content="{{ span.toTraceparent() }}" />
    <meta name="baggage" content="{{ serializeBaggage(span.getBaggage()) }}" />
    <!-- ... -->
  </head>
</html>
```


I just tried and it looks like `sentry_sdk.Hub.current.scope.span` does not have a `get_baggage()` method as it apparently should have. Also where would the equivalent of `serializeBaggage()` come from?

**Comment by sl0thentr0py** [comment]
hey @tbrlpld sorry I haven't gotten around to documenting this, my bad!

but there's a new helper you can simply inject now which will [generate both those meta tags for you](https://github.com/getsentry/sentry-python/blob/ff60906fcb9af3db9cda245288f2e49f70ee432f/sentry_sdk/hub.py#L737-L748).
```
Hub.current.trace_propagation_meta()
```

 We will eventually probably auto-inject these into django/flask etc wherever possible so nobody has to think about this.

**Comment by tbrlpld** [comment]
@sl0thentr0py It looks like the `trace_propagation_meta` has not made it into the last release (`1.16.0`), right?

**Comment by sl0thentr0py** [comment]
@tbrlpld this helper exists since quite a few versions

**Comment by tbrlpld** [comment]
Wow, weird. I could swear I tested this with the latest version installed. Looks like my environment must have been off. It's all there. 

Thanks @sl0thentr0py.
