### ISSUE TITLE
Support for tracing GRPC requests

### ISSUE THREAD

**Issue by craigds** [getsentry/sentry-python#1185]
We use sentry performance monitoring for our user-facing API running Django REST Framework. However, behind that we also have an internal API using GRPC that we're hitting via a grpcio client wrapper.

It'd be very useful for us to be able to (automatically?) instrument the GRPC API, and for those traces to appear as subtraces of the user-facing API.

**Comment by AbhiPrasad** [comment]
Thanks for writing in, we've put this in the teams backlog, but in the time being contributions are welcome if anyone wants to submit a PR!

**Comment by yswtrue** [comment]
waiting for this function too

**Comment by stijntratsaertit** [comment]
Any news or other workarounds/alternatives regarding this? I'm working with a similar setup and this would be very helpful

**Comment by antonpirker** [comment]
Hey @craigds @yswtrue @stijntratsaertit @dmitry-vlt 

We have a grpc intregration now. Have a look here: https://docs.sentry.io/platforms/python/configuration/integrations/grpc/
