### ISSUE TITLE
Sentry is not logging ERROR logs by default

### ISSUE THREAD

**Issue by sliwinski-milosz** [getsentry/sentry-python#1191]
Hi!

I have realised lately that not all of the events from my service were reaching Sentry.

I noticed that the event didn't reach the Sentry server when I was testing some case for which I was expecting to see the alarm. The alarm was not triggered and the event was not in Sentry even when I was able to see the service error log.
I started to dig depper [by enabling DEBUG logs](https://docs.sentry.io/platforms/python/guides/logging/configuration/options/#debug).

It turned out that rarely, when Sentry was trying to send an event, it was failiing with "Connection reset by peer" error.
This was most like caused by following issue (just in case if someone bumped into the same problem):
Issue: https://github.com/urllib3/urllib3/issues/944#issuecomment-237471302
Workaround: https://github.com/psf/requests/issues/4937#issuecomment-788899804

The problem I see here is that I have been using Sentry for 3 years not realising that some events were not passed to the Sentry server.

Do you think it would make sense to actually enable Sentry ERROR logs by default so we are aware if the integration is not working as expected?

**Comment by sl0thentr0py** [comment]
No I don't think we want to enable logs by default, having it as a config for debugging is fine.
What we do have now are [Client Reports](https://develop.sentry.dev/sdk/client-reports/) which collect statistics about event drops due to several reasons and adds some transparency on what is happening inside the SDK. Exposing these stats on the user interface is also on the pipeline.

**Comment by sliwinski-milosz** [comment]
Then is there a way to set logging level from config? I'd like to enable only ERROR logs, not the DEBUG ones?

**Comment by sl0thentr0py** [comment]
It's not exposed as config but you can just import the logger and do whatever you want with it.
```
from sentry_sdk.utils import logger

logger.removeFilter
logger.removeHandler
logger.setLevel
```

**Comment by sliwinski-milosz** [comment]
Thank you! I will use that approach.
