### ISSUE TITLE
it's hard to disable specific integrations

### ISSUE THREAD

**Issue by belm0** [getsentry/sentry-python#1192]
* sentry_sdk.init() has only an all-or-nothing option for default integrations (`default_integrations=False`)
  * if the `integrations` option is used, the user has to explicitly import, instantiate, and enumerate all the integrations he wants, rather than specify the ones he doesn't want.  This means that when the python client adds new important default integrations in the future, the user will miss them.  He's also prone to breakage from renaming, etc.

example of tedious opt-in:

```python
# these imports are needed because `integrations` doesn't load these modules by default
import sentry_sdk.integrations.atexit
import sentry_sdk.integrations.excepthook
import sentry_sdk.integrations.dedupe
import sentry_sdk.integrations.modules
import sentry_sdk.integrations.argv

sentry_sdk.init(
    SENTRY_DSN,
    default_integrations=False,
    integrations=[
        sentry_sdk.integrations.atexit.AtexitIntegration(),
        sentry_sdk.integrations.excepthook.ExcepthookIntegration(),
        sentry_sdk.integrations.dedupe.DedupeIntegration(),
        sentry_sdk.integrations.modules.ModulesIntegration(),
        sentry_sdk.integrations.argv.ArgvIntegration(),
    ],
```

wanted:  a way to opt-out of a specific default integration, such as threading

The Java SDK init() has a way to filter default integrations, etc.

**Comment by antonpirker** [comment]
Hello @belm0 ! Thanks for bringing this up. You are right, we do not have this feature currently in our Python SDK.
But I agree this is a bit tedious how it works now. 

Here is how we load integrations right now:
https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/__init__.py#L87/L144

We have a lot on our plates right now, so this feature will not see the light of day in the next couple of months. Sorry.

But we are always more than happy to accept pull requests! ;-)

I will close this issue now. In case we get a PR for this, we can reopen the issue.
