### ISSUE TITLE
Flask Traces Sampler Function seems to have no effect

### ISSUE THREAD

**Issue by AdamUrbanJungle** [getsentry/sentry-python#1208]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-sdk[flask]==1.4.1

### Steps to Reproduce

1. Changed from previous code:
```    
    sentry_sdk.init(
        dsn=sentry_dsn,
        traces_sample_rate=0.1,
        environment=sentry_environment,
        attach_stacktrace=True,
        integrations=[
            FlaskIntegration(),
            sentry_logging,
        ],
    )
```
to
```
    sentry_sdk.init(
        dsn=sentry_dsn,
        traces_sampler=sentry_traces_sampler,
        environment=sentry_environment,
        attach_stacktrace=True,
        integrations=[
            FlaskIntegration(),
            sentry_logging,
        ],
    )
```
where
```
def sentry_traces_sampler(sampling_context):
    try:
        # wsgi_environ is populated by sentry flask integration
        # https://docs.sentry.io/platforms/python/guides/flask/configuration/sampling/
        request_uri = sampling_context['wsgi_environ']['REQUEST_URI']
    except KeyError:
        return 0.1

    if request_uri == "/ping":
        # very low rate as these are extremely frequent and pretty useless
        return 0.001

    if request_uri in {
        "/api/xml/home_aaa_request",
        "/api/xml/home_bbb_request",
        "/api/xml/home_ccc_request",
        "/api/xml/home_ddd_request",
    }:
        # lower rate as these are very frequent
        return 0.01

    # default sample rate
    return 0.1
```
2. tested locally with Postman to confirm that `sentry_traces_sampler` goes down correct route for each endpoint
3. released to production

### Expected Result

Number of traced requests to API endpoints should drop to < 10% of previous value.

### Actual Result

Number of transactions stays roughly same as before. Screenshots showing the release which was roughly 10:00 (28/09/2021):

![Screenshot 2021-09-28 at 14-31-59 Performance - urban-jungle - Sentry](https://user-images.githubusercontent.com/35955299/135096847-cb58087e-7d4c-40cc-a7a7-fed2bb67547e.png)
![Screenshot 2021-09-28 at 14-30-51 Performance - urban-jungle - Sentry](https://user-images.githubusercontent.com/35955299/135096834-b18cdbf1-870a-4548-a9f8-3650184e7e0e.png)

Assuming that requests haven't spiked hugely, we should expect to see a dramatic drop in transactions per minute around that time, but it is roughly the same. 

One hypothesis is that the try/except catch default value of 0.1 is being hit in production but not locally (I'll test this now), but it seems possible that the `sentry_traces_sampler` return values are not being interpreted correctly?

**Comment by antonpirker** [comment]
Hey @AdamUrbanJungle 
Sorry for taking so long to reply.
Can you confirm that this is still an Issue in our newest SDK? If yes, I will try to reproduce this. Thanks!

**Comment by mfumagalli68** [comment]
Hi i'm having same issue as described ( with FastApi)

**Comment by AbhiPrasad** [comment]
Hey @mfumagalli68 - could you open a new issue to track with code snippets, versions of sdk + fastapi you're using, and your traces sampler config? Thanks!
