### ISSUE TITLE
Using SCRIPT_NAME breaks transaction grouping

### ISSUE THREAD

**Issue by JannKleen** [getsentry/sentry-python#1217]
### Environment

How do you use Sentry?
Self-hosted, 21.9.0

Which SDK and version?
Python (Django / DRF), 1.4.3

### Steps to Reproduce

1. Host Django using Gunicorn
2. Pass `SCRIPT_NAME` header with HTTP request 

### Expected Result

Requests to `/api/endpoint/123/` and `/api/endpoint/456/` should be aggregated as either `/api/endpoint/{pk}/` or `/endpoint/{pk}/`.

### Actual Result

Requests appear as `/api/endpoint/123/` and `/api/endpoint/456/` because `RavenResolver` doesn't seem to take into account the `SCRIPT_NAME` contained in the WSGI request object.

**Comment by iker-barriocanal** [comment]
@sl0thentr0py do you have any insights about this?

**Comment by sl0thentr0py** [comment]
Hi @JannKleen, we just pick up the url patterns from the django resolver [here](https://github.com/getsentry/sentry-python/blob/54fc66c1edd1a4a6f0cc43ff11f142a51e4d97e1/sentry_sdk/integrations/django/transactions.py#L101).

I'm not sure what `SCRIPT_NAME` would do here? What is the value of `SCRIPT_NAME` in your example?

**Comment by sl0thentr0py** [comment]
An alternative here is to add an event processor and manually set the transaction names.
There are docs for javascript [here](https://sentry-docs-git-patch-1.sentry.dev/platforms/javascript/performance/capturing/group-transactions/). The python version would look like

```python
from sentry_sdk.scope import add_global_event_processor

@add_global_event_processor
def processor(event, hint):
    if event.get("type") == "transaction":
        event["transaction"] = sanitize_transaction_name(event["transaction"])

    return event
```
