### ISSUE TITLE
Minimum supported Django version

### ISSUE THREAD

**Issue by jameysharp** [getsentry/sentry-python#1223]
The documentation for the Django integration says the minimum version required is 1.6, and tox.ini and various bits of the code apparently agree. But setup.py says the minimum version is 1.8, if you use the Django extra. I guess setup.py should be fixed to match what's actually being tested, right? It looks like it's been wrong ever since the extra was added.

I saw there's discussion about dropping support for these ancient versions, which is fair. It would be nice to get a release out with this dependency corrected first though, so dependency resolvers can pick a correct version of sentry-sdk to match whatever version of Django somebody is actually using.

I'm currently working through the upgrade path for an old project. When (not if) I screw that up and visitors hit bugs, I want Sentry to give me as much information as it can. So I want to get new Sentry bits as early as possible in the upgrade process. I've almost made it to Django 1.6… 😅

**Comment by smeubank** [comment]
thank you for your contribution we will update the docs

**Comment by antonpirker** [comment]
(and we will probably just move everything to Django 1.8, because 1.6 is really ancient)
