### ISSUE TITLE
TypeError json.encoder in default instead of real error

### ISSUE THREAD

**Issue by benzkji** [getsentry/sentry-python#1224]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. have an URL triggering an error that contains special chars, for example an "!"
2. in sentry, I'll get a strange `TypeError json.encoder in default`
3. with an epic long stacktrace, that goes through all my django middlewares and more
4. using gunicorn. not sure if on my side something is configured wrong? as far as I can see, I use a very basic default configuration

python sentry-sdk: 1.4.2

```
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        release=VERSION,
        integrations=[DjangoIntegration()],
    )
```

### Expected Result

Report `AttributeError 'NoneType' object has no attribute 'url_name'` as is the orginal error in this case. 

### Actual Result

`TypeError json.encoder in default`

the (probably) payload, that is wanted to be json serialized:
```
{
environment: 'production', 
public_key: 'blbalbalbablaFOOOOO, 
release: b'0.0.1-178-g889a3c7', 
trace_id: 'the-trace-id', 
transaction: '/medien/Pressedossier_PENG!_PALAST.pdf'
}

**Comment by benzkji** [comment]
keep getting more of these. could it be that this came in with newer sdk version?

**Comment by benzkji** [comment]
probably the same: https://github.com/getsentry/sentry-python/issues/1222

**Comment by benzkji** [comment]
pinning the sdk to `sentry-sdk<1.4` has normal/expected behaviour.

**Comment by ibushong** [comment]
@benzkji, I had the same issue, with this same apparent cause. Your `release` argument to `init()` is of type `bytes`. You should add `decode()` after it to convert it to a string. That resolved the issue for me. Though it is interesting that this only happened as of v1.4.0
