### ISSUE TITLE
Allow more configuration via environment variables

### ISSUE THREAD

**Issue by mccutchen** [getsentry/sentry-python#1225]
As the operator of a platform on which many different Python services are deployed, it would be enormously helpful to be able to configure more sentry SDK options via environment variables, in addition to the currently-supported `SENTRY_DSN`, `SENTRY_ENVIRONMENT`, and `SENTRY_RELEASE` options.

In particular, we would like to be able to set the value of the `request_bodies` and `with_locals` config options via environment variables, which we disable in production to help mitigate the risk of accidentally capturing PII, so that we can control them at the platform level rather than needing to copy/paste (and maintain) the same boilerplate code across each codebase.

We currently have the equivalent of this boilerplate code copy/pasted across the fleet of Python apps:

```python
# SENTRY_DSN, SENTRY_ENVIRONMENT, and SENTRY_RELEASE are already set
# automatically in the process's environment at deploy time.

sentry_sdk.init(
    integrations=[DjangoIntegration()],
    request_bodies="never" if DEPLOY_ENV == "production" else "small",
    with_locals=DEPLOY_ENV != "production",
)
```

It would be nice to replace that with something more like

```python
sentry_sdk.init(
    integrations=[DjangoIntegration()],
)
```

which is less complex and less prone to accidental misconfiguration.

**Comment by rhcarvalho** [comment]
This is a fine idea. The only caveat I can think of right now is that explicit `init` options take precedence over environment variables.

For example, `sentry_sdk.init(dsn="...")` will always initialize the SDK to the given DSN and ignore the `SENTRY_DSN` environment variable.

With this precedence order, an operator cannot use env vars to enforce a particular configuration without trusting/reviewing the code to ensure it doesn't set the particular options inline.

If this is more about convenience than enforcement/trust, I think looking up env vars for other options is perfectly fine and we could take in PRs for that.

**Comment by n1ngu** [comment]
I am facing the same need. I think the main challenge is the same as in https://github.com/getsentry/sentry-python/issues/1133#issuecomment-870467228 : all "primitive" parameters of the sentry_sdk.init call (integers, floats, strings, etc) can easily be fetched from env vars.

But for parameters requiring function objects like `traces_sampler` or `before_send` it'd be necessary that the init call could resolve string import paths into objects, and possibly offer some kind of eval environment? (that would be if it was desired that the envvar--parameter mapping was exhaustive in configuration options)

**Comment by sl0thentr0py** [comment]
@n1ngu I don't think we'll ever do an _exhaustive_ environment config mapping, that doesn't make sense to me. A few key options are fine to expose as env values for convenience but generalizing even function configs is overkill in my opinion.

**Comment by antonpirker** [comment]
I think loading config from the environment is not part of the SDKs job. If we add all the config parameters to be loaded from the environment some users will still need to do something like this:

```python
import os

request_bodies = os.environ.get("SENTRY_REQUEST_BODIES")
if something_is_true:
    request_bodies = "some-other-value"

sentry_sdk.init(
    integrations=[DjangoIntegration()],
    request_bodies=request_bodies,
)
```
So no matter how we would implement this, it would never make everybody happy.

So imho the preferred way to do this would be something like this:
```python
import os
dsn = os.environ.get("SENTRY_DSN", "[default-dsn]")
debug = os.environ.get("SENTRY_DEBUG", True)
release = os.environ.get("SENTRY_RELEASE", "x.x.x")
environment = os.environ.get("SENTRY_ENVIRONMENT, "local")
sample_rate = os.environ.get("SENTRY_SAMPLE_RATE", 0.2)

sentry_sdk.init(
    dsn=dsn,
    integrations=[DjangoIntegration()],
    debug=debug,
    release=release,
    environment=environment,
    sample_rate=sample_rate,
)
```

This way you can see what environment variables the config expects to be set and what default values are used in case they are not set. Makes the configuration explicit and not implicit. See also https://www.python.org/dev/peps/pep-0020/

**Comment by antonpirker** [comment]
As we will not implement this enhancement, because there is no chance in doing it right and it also overkill, I will close this issue. 
Thanks everyone for bringing this up and discussing this!
