### ISSUE TITLE
How to scrub/sanitise transactions

### ISSUE THREAD

**Issue by i-am-david-fernandez** [getsentry/sentry-python#1226]
I have only just begun evaluating Sentry (in a `python`/`django` backend context, to be expanded to cover a `javascript`/`angular` frontend/client), and so far I am very impressed. One thing stopping me from using it fully, however, and as CISO recommending its use in our products, is the seeming inability to scrub/sanitise performance data (transactions, I believe). The `before_send` and `before_breadcrumb` callbacks appear to be more than flexible enough to scrub events and breadcrumbs before they leave the application, but there appears to be no equivalent for scrubbing performance data. As a result, the data available via sentry.io contains things I do not wish it to (e.g., sensitive data within request bodies). The result is that I simply cannot use performance monitoring outside, perhaps, development environments with toy/non-sensitive data.

The documentation (https://develop.sentry.dev/sdk/performance/#interaction-with-beforesend-and-event-processors) states this:
> Transactions should not go through beforeSend.

which makes me confident I haven't simply missed something (though I'd be more than happy to be corrected here).

My request, then, is for the SDK to provide an equivalent to `before_send` that allows complete control over what data gets sent via performance monitoring. More broadly, it should be possible to scrub _any_ and _all_ data that is being sent (which at this stage appears to be only `events`, `breadcrumbs` and `transactions`, but perhaps the list is longer). I can't consider Sentry to be a security-compliant tool without such facilities, and quite frankly, given the obvious awareness of the importance of managing PII, I'm surprised that this problem exists.

I'd love to make full use of Sentry, as I think it's both a brilliant idea and, above issue not-withstanding, well executed, so I hope this request is thoughtfully considered.

Thank-you.

**Comment by rhcarvalho** [comment]
@i-am-david-fernandez 

> This line is particularly problematic:
> 
> https://github.com/getsentry/sentry-python/blob/cad2f65316bab4ee5792b1b788c32c57293eea5e/sentry_sdk/scope.py#L392

As you noted, that line means global event processors run before scope event processors (as designed/intended).

For the Python SDK, I see that the web framework integrations like WSGI (used by Django) are setting an event processor in the scope:

https://github.com/getsentry/sentry-python/blob/cad2f65316bab4ee5792b1b788c32c57293eea5e/sentry_sdk/integrations/wsgi.py#L119-L123

That could be revisited, as it might be possible to make them global, but that doesn't change the solution for your use case.

The outgoing flow is:

```

  Global Event Processors   ->  Scope Event Processors   ->  Before Send   ->  Transport
       (all events)                (all events)              (errors-only)     (everything)

```

So you have two possibilities:

1. **Scope Event Processor** can be added from a middleware, making sure every request's scope gets the event processor as the last processor in the chain.
2. **Custom Transport** gives you total control on how data goes out of the SDK.

I'd suggest you start with (1), by adding a Django Middleware as the last middleware.

**Comment by i-am-david-fernandez** [comment]
Thanks for the details @rhcarvalho . Could you please provide a pointer (perhaps a link to the relevant documentation) to how I might add a scope event processor from/via middleware? I'm familiar enough with middleware in Django, but I'm assuming you're referring to Sentry middleware (is that the same as Integrations?). It's a bit unclear from your particular wording above.

Thank-you.

**Comment by rhcarvalho** [comment]
Sorry for the delay --

I meant Django middleware.

```python
@sentry_sdk.Hub.current.scope.add_event_processor
def sanitizer(event, hint):
    # TODO: sanitize event here
    return event
```

**Comment by i-am-david-fernandez** [comment]
@rhcarvalho Certainly no apologies are needed! Conversely, thank-you for the continued support.

I think I've got things working according to you suggestion (until something more robust is introduced in the SDK).

For future reference (or hopefully to help others), my django middleware is this:

```python
class SanitisationMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):

        ## Pass down to any other middlewares
        response = self.get_response(request)

        ## We are now in the middleware unwinding phase.
        ## We add/register the event sanitiser as late as possible to ensure it
        ## has access to all and any event fields added by other processors,
        ## allowing it to properly clean.
        sentry_sdk.Hub.current.scope.add_event_processor(self.event_sanitiser)

        return response

    def event_sanitiser(self, event, hint):
        if event.get("type") == "transaction":
            ## Sanitise/handle here

        return event
```

This middleware is registered as the _first_ middleware in the django middleware stack (as best as one can do). This is easier to manage, as I can more easily control the initial order in the configuration (other things may append to this list, though this is imperfect as other things could potentially insert earlier middlewares). To ensure the processor is registered _last_, I add it in the middleware unwinding phase.

This does appear to work, in as much as the fields I'm currently concerned with have been populated by the time my handler is hit, though I'd still very much like something more robust. When it comes to security, I really want auditable guarantees, not just "it happens to work for the moment if things are lined up just so.".

I can see in the documentation, code and commit comments that it is the design intent that `before_send` is _not_ applied to transactions, but I'd like to understand why. I have created a fork of this repo where I've replicated the logic in `_Client._prepare_event(...)` to apply a second processor (`before_send_transaction`) to transactions only. While this appears to work, I can't help but wonder why transactions were excluded from `before_send`, and consequently I assume that there's something I have missed that means my changes could break something.

Again, thank-you for the support and for helping me find an interim solution. Your time is appreciated.

**Comment by antonpirker** [comment]
Hello @i-am-david-fernandez 

I have read your comments and I think what you are looking for is Sentry Relay. It is basically some piece of software that you can run on your server. Your Sentry SDK is then sending all the data only to your Relay server on your infrastructure. And there all the data is scrubbed and just after doing this the Relay server on your infrastructure is sending the data to sentry.io. 

So Relay was build exactly for your use case.

Have a look at this: https://docs.sentry.io/product/relay/
