### ISSUE TITLE
Add support to change how a URL is displayed in a custom tag

### ISSUE THREAD

**Issue by chingc** [getsentry/sentry-python#1232]
Sorry if this is already possible but I can't find anything in the docs.  It would be very nice to be able to provide an optional argument that changes the hyperlink text.

```
sentry.set_tag('test_tag', 'https://really_long_and_ugly_url.com', display_as='shorter.com')
```

**Comment by sl0thentr0py** [comment]
hey @chingc, thanks for the suggestion.
We'll move this to our feature backlog but we can't promise when we'll get to that because this would entail larger changes end-to-end since we'd have to also store this information somewhere and propagate it all the way to the UI.

**Comment by sentrivana** [comment]
Hey @chingc, I'll close this now, we decided to not do this because of the changes necessary vs. the benefit it brings. You might consider adding a custom context to the event, though it behaves and displays differently in the UI: https://docs.sentry.io/platforms/python/enriching-events/context/
