### ISSUE TITLE
Sentry SDK 407 Proxy Auth

### ISSUE THREAD

**Issue by atlys-osmar** [getsentry/sentry-python#1246]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
sentry-sdk>=0.17.

### Steps to Reproduce

1. I setup a docker running python3.7 image
2. I initialized the Sentry sdk with Google Cloud Functions integration
3. When an error comes it fails to send the messages to sentry.

### Expected Result

I expect the errors to appear in sentry.

### Actual Result
```
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /api/6048080/store/
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /api/6048080/store/
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /api/6048080/store/
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /api/6048080/envelope/
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /api/6048080/envelope/
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /api/6048080/envelope/
```

**Comment by atlys-osmar** [comment]
It looks like it is failing because I have `logging.basicConfig(stream=sys.stdout, level=logging.INFO)`. When I remove that line, everything works. I tried adding the `LoggingIntegration` and included that line but it still gives me those errors.

**Comment by antonpirker** [comment]
Hey @atlys-osmar !
Thanks for reporting this and sorry for getting back at you that late.

One thought: Could it be that setting this `logging.basicConfig` sets the logging in Google Cloud Platform to log to a Google Logging service, and you do not have permissions or the setup for this logging service?
(I am just guessing here, I have no clue about Google Cloud Platform :-) )

As you are using a quite old SDK try to upgrade to the newest version. 

Or maybe you have already solved your issue? If yes, I would be curious how you fixed this problem?

**Comment by atlys-osmar** [comment]
Oops, actually the sdk we used is 1.4.3. I still have not been able to set it up so we haven't been using sentry for our project :(. Would still like to set it up but it still wont work with google cloud functions.

**Comment by antonpirker** [comment]
The HTTP 407 means "indicating that the server is unable to complete the request because the client lacks proper authentication credentials for a proxy server that is intercepting the request between the client and server."

So I am guessing that is is not problem in the SDK but something that is in between the SDK running in the Google cloud function an sentry.io.

Can you run the cloud function locally to test if it works when not running in Googles Cloud?

**Comment by atlys-osmar** [comment]
It works when I run it locally, but when it is running on google cloud it does not send any messages.

**Comment by antonpirker** [comment]
So I guess it is some problem with your Google Cloud configuration. There is something needing authentication between your function and sentry.io that you have not configured correctly.
