### ISSUE TITLE
Drop support for Python 3.4 and 3.5

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-python#1255]
See: https://endoflife.date/python

**Comment by alippai** [comment]
That means that python 2.7 should be dropped as well, right?

**Comment by AbhiPrasad** [comment]
We probably can’t think about dropping 2.7 support, a ton of users still rely on it.

It is important to note that 3.5 and 3.4 might stick around for a while. This issue exists to make sure we adequately track progress when we eventually make the decision to phase them out.

**Comment by alippai** [comment]
I understand it, I was just interested because of the linked page. Do you have public sentry specific python version usage stats available?

**Comment by beliaev-maksim** [comment]
it is important to track down the version of the package used. 
For example PyPi tracks Python version (eg 2.7) but lots of projects with Py27 are frozen/security maintenance projects. So, most probably they are not interested in new features and new stats are triggered by pipelines or package is installed but using some old fixed version.
