### ISSUE TITLE
missing ssl_cert_reqs kwarg in monkey patched Redis connection

### ISSUE THREAD

**Issue by rosscdh** [getsentry/sentry-python#1257]
### Environment

saas

due to changes in dango_redis supporting ssl_cert_reqs

https://github.com/rq/django-rq/blob/11527cfdc6408b9c23c24255f8684b61860cc671/django_rq/queues.py#L83

released 14 hours ago.. the monkey patched redis handler seems to break on start.

Which SDK and version?

sentry-sdk==1.5.0

### Steps to Reproduce

latest django_rq with sentry python package
and redis integration

### Expected Result

connect to redis

### Actual Result

```
  File "/venv/lib/python3.9/site-packages/sentry_sdk/integrations/redis.py", line 101, in sentry_patched_execute_command
    return old_execute_command(self, name, *args, **kwargs)
  File "/venv/lib/python3.9/site-packages/redis/client.py", line 1067, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/venv/lib/python3.9/site-packages/redis/connection.py", line 1172, in get_connection
    connection = self.make_connection()
  File "/venv/lib/python3.9/site-packages/redis/connection.py", line 1212, in make_connection
    return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl_cert_reqs'
```

**Comment by antonpirker** [comment]
Hello @rosscdh !
Thanks for the report! Sorry for not replying sooner.
Do I get this right. Right now it is impossible to use Sentry with Django-RQ?
Is this still the case with an updated Sentry SDK to the newest version?

**Comment by sl0thentr0py** [comment]
@rosscdh I tried to repro this today and with latest `django-rq` [here](https://github.com/sl0thentr0py/sentry_sample_apps/commit/3ec34a5666854557fa50dc9c3da47dea6a370f8c) and I'm not able to repro this, both errors and transactions work successfully. Please give us more repro steps/a sample app if this is still a problem.

**Comment by sl0thentr0py** [comment]
this is infact fixed [upstream](https://github.com/rq/django-rq/blob/master/django_rq/queues.py#L86-L90) so closing.
