### ISSUE TITLE
Prioritize certain parts of sentry issue information when performing truncation

### ISSUE THREAD

**Issue by DanCardin** [getsentry/sentry-python#1259]
# Problem
Specifically, my problem is that i'm calling
```
with push_context() as scope:
    scope.set_extra(x, y)
    # ... for some set of extras larger than 10
    # or
    scope.set_extra('json_blob', json_blob) # where json_blob has more than 10 keys
```

I'm reasonably certain this is essentially the same as https://github.com/getsentry/sentry-python/issues/1041, and that we're talking about this: https://github.com/getsentry/sentry-python/blob/4c09f3203d6d19789c6fa729a2e46557ad4ea913/sentry_sdk/serializer.py#L72.

What's kind of frustrating about this is that I can
```
from sentry_sdk import serializers
serializers.MAX_DATABAG_BREADTH = 20
```
and it works just fine, so it's clearly not actually a hard limit. I'm guessing it's either just easier to truncate everything to 10, or else maybe it's a performance consideration to avoid needing to precalculate a bunch of lengths of things.

# Thoughts
If I were **actually** running up against the limit, I would much rather it truncated (or completely dropped!) things like the list of packages, debug breadcrumbs, the tops of my stacktraces, or locals outside the bottom...5 levels of stacktrace (in that order!)

The absolute last things I want it to be truncating are message, tags, and info, and top-level locals (in that order!).

Options that come to mind (probably in reverse order of realisticness/complexity)
* make the truncation logic would be smart enough to avoid truncating things in situations where it doesn't need to, by calculating the lengths of what it's collecting and truncating things opportunistically.
* prioritize certain info (like message/tags/info), and only truncate those things when it would push the request over the limit
* prioritize certain info (like message/tags/info), and set their truncation lengths much higher (and/or allow me to set them)
* prioritize certain info (like message/tags/info), and dont truncate them at all (optionally) and if my request fails, so be it.

**Comment by DanCardin** [comment]
This is still a problem I'd love a solution to...please go away bot

**Comment by antonpirker** [comment]
We are thinking about adding a option to disable trimming of event payloads. (and other possible solutions) We will close this issue in favor of the other one: 
https://github.com/getsentry/sentry-python/issues/2223
