### ISSUE TITLE
Tracking exceptions which are suppressed by middleware(process_exception)

### ISSUE THREAD

**Issue by DmytroLitvinov** [getsentry/sentry-python#1270]
### Environment

Q: How do you use Sentry?
A: Sentry SaaS

Q: Which SDK and version?
A: Python SDK v.1.5.0

How we setup Sentry:
```python
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration(), CeleryIntegration(), RedisIntegration()],
        traces_sample_rate=0.0,
        send_default_pii=True,
    )
```

Hi there,

We are using Django 3.2 and package django-concurrency and the package has [raising an error](https://github.com/saxix/django-concurrency/blob/60e81ebcc638760acc976349b020494cb954e37b/src/concurrency/views.py#L15) and there is [the middleware ConcurrencyMiddleware](https://github.com/saxix/django-concurrency/blob/60e81ebcc638760acc976349b020494cb954e37b/src/concurrency/middleware.py#L25) which has process_exception method and handle it accordingly. 

From my point of it should not be tracked into the system because there is a process_exception that returns actually view. But I can be wrong I would like to hear the correct answer about it.

I assumed that I might have the wrong opinion about middleware and I tried to find how to suppress it but there is only [documentation "Error Handling Middleware"](https://docs.sentry.io/clients/python/integrations/#error-handling-middleware) for legacy library raven and no information for supported library.

**Comment by sl0thentr0py** [comment]
Hey @DmytroLitvinov, not sure I understand fully. Do you want the error to be suppressed in sentry or be visible?

**Comment by DmytroLitvinov** [comment]
Hi @sl0thentr0py ,

I suppose it should be suppressed because [ConcurrencyMiddleware](https://github.com/saxix/django-concurrency/blob/60e81ebcc638760acc976349b020494cb954e37b/src/concurrency/middleware.py#L25)  handles exception and return HttpResponse. But I am not sure so I opened issue here.

**Comment by sl0thentr0py** [comment]
We cannot assume across all middlewares if this is desirable behavior, so we just react to the django signal if the middleware sends it. This is the decision of the middleware and we respect it.

If you still want to suppress the exception as an end-user, you can always use the `ignore_errors` config parameter.
```python
sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration(), CeleryIntegration(), RedisIntegration()],
        traces_sample_rate=0.0,
        send_default_pii=True,
        ignore_errors=[RecordModifiedError]
    )
```

**Comment by DmytroLitvinov** [comment]
Ohh..
Thank you for your answer, @sl0thentr0py .
I already answered my question where there is a mention about `got_request_exception` with comment about it:
```python
# Make sure the exception signal is fired for Sentry
got_request_exception.send(sender=self, request=request)
```
