### ISSUE TITLE
if sample_rate setting is not defined it defaults to trace_sample_rate

### ISSUE THREAD

**Issue by alvaromlg** [getsentry/sentry-python#1271]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Define simple sentry config disabling transactions

```
sentry_sdk.init(
    dsn="dns url",
    integrations=[DjangoIntegration()],

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True,
    environment='production'
)
```

As stated on the documentation sample_rate should default to 1 if not defined:

https://docs.sentry.io/platforms/python/guides/bottle/configuration/options/#sample-rate
sample_rate
Configures the sample rate for error events, in the range of 0.0 to 1.0. The default is 1.0 which means that 100% of error events are sent. If set to 0.1 only 10% of error events will be sent. Events are picked randomly.

### Expected Result

With that given configuration apart from transaction also no errors are received.

A given configuration of `traces_sample_rate=0,` and no sample_rates setting should return 100% of errors reported.

### Actual Result

No errors are received.

If trace_sample_rate is modified to 0.1 for example then it also affect sample_rate and some errores are received.

Documentation seems unclear about this if intended.

**Comment by AbhiPrasad** [comment]
Hey thanks for writing in. `trace_sample_rate` should have no effect on `sample_rate`. See the logic around using `sample_rate` here: https://github.com/getsentry/sentry-python/blob/5bd47750871a392be4ed2632b70c444990844b51/sentry_sdk/client.py#L233-L259

As a demo, please see this Python repl for an example: https://replit.com/@AbhiPrasad/WhichCrookedCarrier#main.py

```py
import sentry_sdk

sentry_sdk.init(
    # A Fake DSN value
    "https://123456789@123456.ingest.sentry.io/12346",

    debug=True,

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=0,
)

division_by_zero = 1 / 0
```

Running the above script gives:

```
[sentry] DEBUG: Setting up previously not enabled integration logging
 [sentry] DEBUG: Setting up previously not enabled integration stdlib
 [sentry] DEBUG: Setting up previously not enabled integration excepthook
 [sentry] DEBUG: Setting up previously not enabled integration dedupe
 [sentry] DEBUG: Setting up previously not enabled integration atexit
 [sentry] DEBUG: Setting up previously not enabled integration modules
 [sentry] DEBUG: Setting up previously not enabled integration argv
 [sentry] DEBUG: Setting up previously not enabled integration threading
 [sentry] DEBUG: Setting up previously not enabled integration aiohttp
 [sentry] DEBUG: Setting up previously not enabled integration sqlalchemy
 [sentry] DEBUG: Enabling integration logging
 [sentry] DEBUG: Enabling integration stdlib
 [sentry] DEBUG: Enabling integration excepthook
 [sentry] DEBUG: Enabling integration dedupe
 [sentry] DEBUG: Enabling integration atexit
 [sentry] DEBUG: Enabling integration modules
 [sentry] DEBUG: Enabling integration argv
 [sentry] DEBUG: Enabling integration threading
 [sentry] DEBUG: Enabling integration aiohttp
 [sentry] DEBUG: Enabling integration sqlalchemy
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    division_by_zero = 1 / 0
ZeroDivisionError: division by zero
 [sentry] DEBUG: Sending event, type:null level:error event_id:76bf74b4c8cb4e0b8ee8866de533a066 project:12346 host:123456.ingest.sentry.io
```

Could you try running your sdk in debug mode to see what is happening to the errors?

**Comment by alvaromlg** [comment]
Hello @AbhiPrasad , I can confirm that setup is working, probably we had some issues when testing the sdk with actual errors.
I think some shell errors by default might get ignored by the sdk and that's fine.
