### ISSUE TITLE
Bad name for url match in django 2.2.25 integration, graphql/ becames graphql/Z on issues

### ISSUE THREAD

**Issue by fredgido** [getsentry/sentry-python#1275]
### Environment

sentry-python latest
django 2.2.25
issues page on sentry website

### Steps to Reproduce

1. install django 2.2.25, ( I have same issue on new 3.2.10 but haven't fully dived into)
2. enable django integration
3. capture and error so its sent to sentry
4. go on sentry and see the error 

### Expected Result

url path is properly printed

### Actual Result

url path on error has a Z in the end
![2021-12-09_21-07](https://user-images.githubusercontent.com/17598829/145475916-c19b67a4-edf4-4a3a-984b-08eafdc3b66f.png)

### details
django 2.2.24
![2021-12-09_21-10](https://user-images.githubusercontent.com/17598829/145476202-1d649a55-4767-46a8-9398-f7b0b6c009d8.png)
django 2.2.25
![2021-12-09_21-09](https://user-images.githubusercontent.com/17598829/145476247-ccce8672-6864-4351-b122-d0fc6340669c.png)

**Comment by sl0thentr0py** [comment]
hi @fredgido, we just released 1.5.1 with a fix for this
https://github.com/getsentry/sentry-python/pull/1272
