### ISSUE TITLE
Support for Sanic v21.12.0

### ISSUE THREAD

**Issue by Basit-qc** [getsentry/sentry-python#1290]
Raising custom exceptions in Sanic's latest version (which shouldn't be logged to Sentry), getting **IndexError: pop from empty list**

```
File "/app/.heroku/python/lib/python3.9/site-packages/sentry_sdk/integrations/sanic.py", line 184, in _hub_exit
     request.ctx._sentry_hub.__exit__(None, None, None)
File "/app/.heroku/python/lib/python3.9/site-packages/sentry_sdk/hub.py", line 247, in __exit__
     old = self._old_hubs.pop()
IndexError: pop from empty list
```

**Comment by ahopkins** [comment]
@Basit-qc Do you know how to trigger this? Is it when raising _any_ exception that derives from `SanicException`?

**Comment by ahopkins** [comment]
Okay, I think I see what is happening. It is because this was included in the LTS: https://github.com/sanic-org/sanic/issues/2297

**Comment by Basit-qc** [comment]
Yes @ahopkins, I got this raising Unauthorized, NotFound, InvalidUsage exceptions.

**Comment by ahopkins** [comment]
@Basit-qc I believe this will happen on _ANY_ exception where you have a custom error handler enabled. It is not specific to `SanicException`. PR #1292 should solve this.

**Comment by ahopkins** [comment]
In the meantime, if someone wants to get this working with Sanic v21.12 you can monkeypatch it like this:

```python
from contextlib import suppress

async def _hub_exit_modified(request, **_):
    # type: (Request, **Any) -> None
    with suppress(IndexError):
        request.ctx._sentry_hub.__exit__(None, None, None)


sentry_sdk.integrations.sanic._hub_exit = _hub_exit_modified
```

**Comment by Basit-qc** [comment]
Awesome. Thank you @ahopkins for all the help.

**Comment by cnicodeme** [comment]
Quick question @ahopkins : When should we remove the monkey patch? 

Am I right to say when Sentry version will be > 1.5.1 ?

**Comment by ahopkins** [comment]
> Quick question @ahopkins : When should we remove the monkey patch?
> 
> Am I right to say when Sentry version will be > 1.5.1 ?

Yes. Whenever the next SDK is released. The monkeypatch should also not harm this even once it is released. Just an alternative solution.

**Comment by cnicodeme** [comment]
Perfect! Thanks !

**Comment by cnicodeme** [comment]
I have re-opened a ticket at #1303 as I still encounter the issue with the latest, v1.5.2.

**Comment by ahopkins** [comment]
Thanks, I will take a look.

**Comment by kolszewskaa** [comment]
Any update on this? I upgraded to 1.5.10 and still encounter the issue.

**Comment by ahopkins** [comment]
Thanks for the reminder. I'll take a look at it this week and add a patch (unless someone else does first).

**Comment by msy01071998** [comment]
I am using sanic==22.12.0 and sentry-sdk==1.7.0 and still facing the same issue. 
<img width="593" alt="Screenshot 2023-07-28 at 9 49 34 AM" src="https://github.com/getsentry/sentry-python/assets/49150544/f486858e-85dd-4483-9275-dbe7777394c9">
