### ISSUE TITLE
M1 mac: Illegal instruction: 4 on import under 3.9.7

### ISSUE THREAD

**Issue by vega-polaris** [getsentry/sentry-python#1301]
### Environment
M1 Mac 12.0.1

Which SDK and version?
Python SDK version 1.5.2

### Steps to Reproduce

1. Set up a virtual env with python 3.9.7 `pyenv install 3.9.7`
2. `python -m venv --prompt foo .venv`
3. `activate pyenv 3.9.7`
4. `pip install sentry-sdk==1.5.2`
5. `python -c 'import sentry_sdk'`

### Expected Result

Successful import of sentry sdk

### Actual Result

`Illegal instruction: 4`

**Comment by antonpirker** [comment]
I just tried this similar to your way (but without the `activate pyenv 3.9.7` command but rather calling `source .venv/bin/activate` ) 
And it works over here. See this screenshot:

![Screenshot 2022-02-01 at 15 23 29](https://user-images.githubusercontent.com/202325/151988047-3619f7be-816f-4a9c-a687-4ce0e3f967e7.jpeg)

Are your you have activated the virtual env and installed the package correctly?
