### ISSUE TITLE
Database connections being left open

### ISSUE THREAD

**Issue by jkeyes** [getsentry/sentry-python#132]
Python: 3.6.5
Django: 2.1.2
sentry-sdk: 0.4.2

I upgraded from raven to sentry-sdk yesterday and noticed my app was now keeping database connections open rather than closing them per request.

I wrote a tiny view to test this:

    def sentry_test(request):
        """Return the password reset form."""
        from django.contrib.auth.models import User
        print(User.objects.all())
        return HttpResponse("<h1>Hello</h1>")

and when GET the URL repeatedly I see the subsequent connections remain idle after the request has completed:

```
=> SELECT state, query FROM pg_stat_activity WHERE client_addr IS NOT NULL;
 state  | query
--------+-----------------------------------------------------
 idle   | SELECT "auth_user"."id", "auth_user"."password", ...
 active | SELECT state, query FROM pg_stat_activity WHERE client_addr IS NOT NULL;
 idle   | SELECT "auth_user"."id", "auth_user"."password", ...
 idle   | SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"
 idle   | SELECT "auth_user"."id", "auth_user"."password", ...
 idle   | SELECT "auth_user"."id", "auth_user"."password", ...
 idle   | SELECT "auth_user"."id", "auth_user"."password", ...
```

As you can see the connection from the migrate query on startup has remained open too.

If I use raven this behaviour is not exhibited.

I suspect this won't help much, but if I use sentry-sdk and comment out:

```
        WSGIHandler.__call__ = sentry_patched_wsgi_handler
```

Then the problem doesn't manifest itself but I've basically turned off sentry at this stage.

**Comment by untitaker** [comment]
Thank you, I can reproduce this. Apparently `sentry_sdk.integrations._wsgi._ScopePoppingResponse.close` does not behave correctly.

**Comment by jkeyes** [comment]
@untitaker yeah when it's converted to an iterator it's no longer a response so no `close` method. I hacked this together to run a quick test:

```
@implements_iterator
class _ScopePoppingResponse(object):
    __slots__ = ("_response", "_hub", "_original_response")

    def __init__(self, hub, response):
        self._hub = hub
        self._response = response
        self._original_response = response

    def __iter__(self):
        try:
            self._response = iter(self._response)
        except Exception:
            reraise(*_capture_exception(self.hub))
        return self

    def __next__(self):
        try:
            return next(self._response)
        except StopIteration:
            raise
        except Exception:
            reraise(*_capture_exception(self.hub))

    def close(self):
        self._hub.pop_scope_unsafe()
        if hasattr(self._original_response, "close"):
            try:
                self._original_response.close()
            except Exception:
                reraise(*_capture_exception(self.hub))
```

and the connection was closed correctly.

**Comment by untitaker** [comment]
Thanks for the separate investigation :) will release asap

**Comment by untitaker** [comment]
0.4.3 is otu

**Comment by jkeyes** [comment]
Tested and verified connections are being closed correctly.
