### ISSUE TITLE
How to block an error with a particular message?

### ISSUE THREAD

**Issue by prashantsengar** [getsentry/sentry-python#1327]
I am using Celery for one of my projects and several times it raises this error:

`child process exiting after exceeding memory limit (xyzKiB / abcKiB)`

It does not have any other detail except `level=error`, `logger=multiprocessing`, `runtime` and `server name`. The only unique thing that is shown here is the message field.

I would not like to block all the multiprocessing logger errors. Instead, what I wish to do is to not send errors which contain the text:
`child process exiting after exceeding memory limit`

Is it possible to do that?

I have tried using the `before_send` argument. 

```python
def remove_unnecessary_exceptions(event, hint):
    if 'message' in event:
        if 'child process exiting after exceeding memory limit' in event['message']:
            return None
    return event

sentry_sdk.init(
        dsn=SENTRY_DSN,
        before_send=remove_unnecessary_exceptions
)
```

But the errors still go through

**Comment by sl0thentr0py** [comment]
if it's an exception, try this
```

def remove_unnecessary_exceptions(event, hint):
    if 'exc_info' in hint:
        exc_type, exc_value, tb = hint['exc_info']
        if 'child process exiting after exceeding memory limit' in exc_value:
            return None
    return event
```

**Comment by prashantsengar** [comment]
It seems that half of them are `exceptions` and the other half are just error messages (as described in the original comment). Is there a way to block just the messages as well?

**Comment by sl0thentr0py** [comment]
then your snippet is fine, maybe the text is not an exact match?
