### ISSUE TITLE
How to use second project in the same application?

### ISSUE THREAD

**Issue by lega911** [getsentry/sentry-python#1328]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
python2, sentry-sdk  1.5.4

**Problem:** there is sentry-integration in an application, I need to send events to another project without breaking main integration, so I'm trying to create local client + scope + hub, but it has problems - an event not always displayed and tags can be wrong.

### Steps to Reproduce

```python
    scope = sentry_sdk.Scope()
    scope.set_tag('hostname', 'local.host.se')
    scope.set_tag('key', 'value')

    client = sentry_sdk.Client("https://99ae@o.ingest.sentry.io/123", release='8.5')
    
    hub = sentry_sdk.Hub(client, scope)
    hub.capture_event(dict(
        message='test11',
        level='error'
    ))
```

### Expected Result

event is appeared on page 'issues'

### Actual Result

event not always added, and if it's added it can contains wrong tags

**Comment by sl0thentr0py** [comment]
hi @lega911, can you try the following out

```
    client = sentry_sdk.Client("https://99ae@o.ingest.sentry.io/123", release='8.5')
    hub = sentry_sdk.Hub(client, scope)

    with hub.configure_scope() as scope:
      scope.set_tag('hostname', 'local.host.se')
      scope.set_tag('key', 'value')

      hub.capture_event(dict(
          message='test11',
          level='error'
      ))
```

**Comment by lega911** [comment]
I found the problem - an event is not sent if script finishes immediately, so background worker didn't have time to send it.
But if I add time.sleep after capture_event, it works fine.

@sl0thentr0py seems sentry_sdk.Hub is useless here, because at sending moment global Hub is used instead of local one:
```python
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/hub.py", line 322, in capture_event
    rv = client.capture_event(event, hint, scope)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/client.py", line 383, in capture_event
    self.transport.capture_event(event_opt)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/transport.py", line 450, in capture_event
    hub = self.hub_cls.current  <-- here, global Hub is taken instead of local one
```
proof:
```python
print('global', id(sentry_sdk.Hub.current), sentry_sdk.Hub.current)

hub = sentry_sdk.Hub(client)
print('local', id(hub), hub)

hub.capture_event(...)

> global 140425242919888 <sentry_sdk.hub.Hub object at 0x7fb74cb8c3d0>
> local 140425166831440 <sentry_sdk.hub.Hub object at 0x7fb7482fbf50>
> sending-hub: 140425242919888 <sentry_sdk.hub.Hub object at 0x7fb74cb8c3d0>
```

so this code gives the same result:
```python
client = sentry_sdk.Client("https://99ae@o.ingest.sentry.io/123", release='8.5')
client.capture_event(dict(message=message, level=level), None, scope)
```

**Comment by lega911** [comment]
@sl0thentr0py for now the main problem for me is Sentry put all events to the same issue, even if message and tags different. do you know what to do to make Sentry produces different issues?

**Comment by sl0thentr0py** [comment]
The correct usage in that case is
```
print('global', id(sentry_sdk.Hub.current), sentry_sdk.Hub.current)

hub = sentry_sdk.Hub(client)
print('local', id(hub), hub)

with hub:
  hub.capture_event(...)
```

> all events to the same issue
for a separate issue, please make another issue or contact support. Github issues are generally for feature requests/bug reports, we entertain questions once in a while but please keep them in scope.

**Comment by lega911** [comment]
@sl0thentr0py thank you for help
