### ISSUE TITLE
Make DjangoIntegration support Django 4.0 & 4.1

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-python#1335]
After this is merged:
- [ ] - @vladanpaunovic to make tests for Django 4.0 & 4.1 required

**Comment by antonpirker** [comment]
Maybe we can also try to integrate the work done here #956 to make it a Django 4 and Template performance stuff update to DjangoIntegraton. (Just posting this here, so we do think about the other issue when working on Django 4 update)

**Comment by smeubank** [comment]
https://www.djangoproject.com/weblog/2022/aug/03/django-41-released/

**Comment by antonpirker** [comment]
- [x] The async class based views and the async orm functions show up in the performance page as expected.
- [x] All the tests pass
- [ ] When running Gunicorn in Uvicorn there is an error because the body is read multiple times. This needs some fixing
