### ISSUE TITLE
Add meta tag helper for trace propagation to Django.

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-python#1341]
Add `sentry_trace()` template helper for Django

We should make it easy to add sentry trace meta header OOB in Django. See feedback: https://github.com/getsentry/sentry-python/issues/1171

Similar to work done in https://github.com/getsentry/sentry-python/pull/1336

EDIT(neel): just start injecting the meta tags automatically

**Comment by pickfire** [comment]
There is now `trace_propagation_meta` to help for this https://github.com/getsentry/sentry-python/issues/1171, probably need to add a middleware for sentry.

**Comment by antonpirker** [comment]
Yes, to solve this issue we just need to inject the result of `trace_propagation_meta()` into Django responses.

Maybe this can be done in here: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/django/views.py#L32-L38

Want to give it a go @pickfire ?

**Comment by pickfire** [comment]
Sorry, I am not interested in working on this myself, given that it's already working for us.

**Comment by antonpirker** [comment]
Hey @pickfire 

It's fine if you do not want to work on it.
Internernally we will work on something in the next couple of weeks, where we will this feature here, so I guess it will be solved soonish.

**Comment by sentrivana** [comment]
Closing in favor of https://github.com/getsentry/sentry-python/issues/2186
