### ISSUE TITLE
traceback limit

### ISSUE THREAD

**Issue by rebx** [getsentry/sentry-python#1347]
Hi,

Is it possible to make the traceback limit size configurable? At the moment I just see a "removed because of size limit" warning in sentry. I would appreciate it if someone can let me know how it can be done. Alternatively, if it is not possible currently, can we please allow it to be configurable? 

Many thanks

**Comment by sl0thentr0py** [comment]
@rebx could you post a screenshot/link of the sentry issue?

**Comment by rebx** [comment]
Thanks for your reply. Please see below
![Screen Shot 2022-02-23 at 7 22 20 AM](https://user-images.githubusercontent.com/105413/155195086-696d8d3c-53ce-4f44-b99d-16d6290565a1.png)

**Comment by sl0thentr0py** [comment]
@rebx I need to see what part of the UI you are talking about, this tiny screenshot is not informative, please post a link or something where I can clearly see what you are referring to.

**Comment by sl0thentr0py** [comment]
ok nvm, I checked and this is a hard limit imposed by our ingestion pipeline that we do not allow users to customize. Closing, sorry.

**Comment by rebx** [comment]
I understand it's not customisable now, but can be made configurable in the future?

**Comment by sl0thentr0py** [comment]
@rebx no, unfortunately server side limits can not be exposed to the user because they are necessary to protect our infrastructure from bad payloads.
