### ISSUE TITLE
Sentry incorrectly captures "safe" exceptions raised by Celery tasks

### ISSUE THREAD

**Issue by willcroft** [getsentry/sentry-python#1355]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.6

### Steps to Reproduce

1. Add Celery integration to the SDK init:

```python
sentry = sentry_sdk.init(
    dsn='...',
    integrations=[
        sentry_celery.CeleryIntegration(),
        ...,
    ],
)
```

(If it makes a difference, we are also integrating with Flask, Redis and SQLAlchemy. Celery is set up during Flask's init using an app factory pattern.)

2. Create a Celery task with a `throws` tuple of allowable exceptions:

```python
@celery.task(throws=(TaskParseError,))
def process_stuff(input):
    if something_is_wrong_with_input:
        raise TaskParseError('Unexpected format for input')
```

3. Execute an instance of the task with any standard Celery mechanism:

```python
result = tasks.process_stuff.delay(input=...)
```

### Expected Result

Sentry does not capture or log `TaskParseError`.

### Actual Result

Sentry captures and logs `TaskParseError`. If it helps, it appears as if Sentry is capturing the exception as raised during _worker_ execution (as opposed to capturing the exception on calling `result = ...`), which makes sense since Celery is not re-raising this "safe" exception.

It also appears there was an [integration step](https://docs.sentry.io/clients/python/integrations/#setup-1) required for this scenario (`ignore_expected=True`) in the legacy client, but I can find no reference to such configuration in the modern client, so I assume this is meant to be handled automatically?

**Comment by sl0thentr0py** [comment]
Hi @willcroft, we in fact still check for `throws`(https://github.com/getsentry/sentry-python/blob/b63b5ae32d254771cbd027009d0b6def7e2e07fb/sentry_sdk/integrations/celery.py#L247-L248) and even have a [test case](https://github.com/getsentry/sentry-python/blob/b63b5ae32d254771cbd027009d0b6def7e2e07fb/tests/integrations/celery/test_celery.py#L229-L238).

If you can provide with a repro sample, I can try to take a look at why your particular problem occurs.

**Comment by willcroft** [comment]
Thanks for confirming @sl0thentr0py! That definitely helps narrow it down. I see now the "exception" has lost its type when I compare the Sentry issue to others, and there is no top-level `exception` attribute in the issue JSON payload.

Of the attributes that are present in the JSON, the `title` is `Unexpected format for input` rather than `TaskParseError: Unexpected format for input` (as per the example above). I imagine this is the format used for generic logging, so I'll check for any double logging that is happening for exceptions in our set up.

**Comment by willcroft** [comment]
Uh, yeah... so our workers were also pushing exceptions to the error logger:

```
[2022-03-03 17:13:22,657: ERROR/ForkPoolWorker-8] Unexpected format for input
```

Sorry about that! And thanks for pointing us in the right direction, much appreciated!
