### ISSUE TITLE
Flask - user is not captured in Release Health

### ISSUE THREAD

**Issue by sunny-repo88** [getsentry/sentry-python#1356]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.5.6

### Steps to Reproduce

Follow - https://docs.sentry.io/platforms/python/guides/flask/enriching-events/identify-user/

```
import os
import sentry_sdk
from flask import Flask
from sentry_sdk.integrations.flask import FlaskIntegration
from sentry_sdk import set_user

sentry_sdk.init(
    dsn="xxxx", #replace dsn
    integrations=[FlaskIntegration()],
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0,

    release="flask@0.0.0",
    environment= "production",
    auto_session_tracking=True,
    debug=True,
)

app = Flask(__name__)
env_port = os.getenv("PORT")
@app.route('/')
def hello_world():
    set_user({"email": "john.doe@example.com"})
    return 'Hello World! '


@app.route('/error')
def trigger_error():
    set_user({"email": "flask.doe@example.com"})
    division_by_zero = 1 / 0

app.run(host='0.0.0.0', port=5000, debug=True)

````

### Expected Result

should capture user in Releases.

### Actual Result

0 adoption rate, 0 users is captured.

**session**
![image](https://user-images.githubusercontent.com/30856837/156512204-9352af72-6835-4150-b0da-b8cba74fc1d0.png)

**user**
![image](https://user-images.githubusercontent.com/30856837/156512272-f838a5f8-8f06-4b65-b77e-34a70234ed77.png)

![image](https://user-images.githubusercontent.com/30856837/156512389-f9516f9a-65fd-4f63-b04b-008e09e84a7a.png)

**Comment by sl0thentr0py** [comment]
Hi @sunny-repo88, this is because on server SDKs we [aggregate sessions](https://develop.sentry.dev/sdk/sessions/#pre-aggregation-of-sessions) due to ingestion scale concerns. This means that unique session info such as user is thrown away and only counts of successful/errored/crashed sessions are kept.
