### ISSUE TITLE
Chalice integration does not work in local without a timeout config'ed

### ISSUE THREAD

**Issue by b4stien** [getsentry/sentry-python#1357]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.6

### Steps to Reproduce

The steps lined out in Sentry's docs for Chalice integration does not work, nothing is pushed on Sentry.

The error is Chalice side and [I've submitted a PR there](https://github.com/aws/chalice/pull/1896) but you might want to mitigate on your side.

```
import sentry_sdk

from boto3.dynamodb.conditions import Key
from chalice import Chalice
from sentry_sdk.integrations.chalice import ChaliceIntegration

sentry_sdk.init(
    dsn="A_PROPER_DSN",
    integrations=[ChaliceIntegration()],
    debug=True,
)

app = Chalice(app_name="the_app")

@app.route("/boom")
def boom():
    raise Exception("boom goes the dynamite!")
```

With debug enabled we get:

```
Internal error in sentry_sdk
Traceback (most recent call last):
  File "/Users/bastien/.pyenv/versions/3.9.7/envs/ouihelp-dsit/lib/python3.9/site-packages/sentry_sdk/integrations/chalice.py", line 67, in wrapped_view_function
    configured_time = app.lambda_context.get_remaining_time_in_millis()
  File "/Users/bastien/.pyenv/versions/3.9.7/envs/ouihelp-dsit/lib/python3.9/site-packages/chalice/local.py", line 299, in get_remaining_time_in_millis
    return self._max_runtime - runtime
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

### Expected Result

You'd expect an error to pop in Sentry.

### Actual Result

Nothing happens.

**Comment by antonpirker** [comment]
Hey @b4stien 

I have a sample Chalice project here:
https://github.com/antonpirker/sample-projects-for-sentry/blob/main/chalice-project/helloworld/app.py

I get the error in Sentry:
![Screenshot 2022-03-04 at 09 59 12](https://user-images.githubusercontent.com/202325/156732380-8d15848e-61ee-4b85-a3b6-8dcd31ed23e1.png)

Do you have any special configurations or settings in your AWS account? Maybe some permissions or Security Groups that prevent your Lambda to send data to Sentry.io?

**Comment by b4stien** [comment]
Hi Anton, I've probably confused something between my issues (https://github.com/getsentry/sentry-python/issues/1358 and https://github.com/aws/chalice/pull/1896). I've modified the title to specify that the issue happens "in local" and not once deployed to AWS Lambda.

Sorry for the misdirection.

**Comment by antonpirker** [comment]
Ok, got it. 

Did you already do some digging on why this is happening? It would be great if you could submit a PR for fixing this!

**Comment by b4stien** [comment]
I did submit a PR (https://github.com/aws/chalice/pull/1896) on chalice and it got merged, I think we can close here?
