### ISSUE TITLE
Chalice integration does not report exception in authorizer

### ISSUE THREAD

**Issue by b4stien** [getsentry/sentry-python#1358]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.6

### Steps to Reproduce

Chalice integration does not report exceptions raised during an `authorizer`. I digged (quite a bit I must admit) but Chalice lifecycle around authorizers are pretty obscure.

```
import sentry_sdk

from boto3.dynamodb.conditions import Key
from chalice import Chalice
from sentry_sdk.integrations.chalice import ChaliceIntegration

sentry_sdk.init(
    dsn="A_PROPER_DSN",
    integrations=[ChaliceIntegration()],
    debug=True,
)

app = Chalice(app_name="the_app")

@app.authorizer()
def custom_authorizer(auth_request):
    raise Exception("Authorizer exception")

@app.route("/boom", authorizer=custom_authorizer)
def boom():
    return Response(body="")
```

### Expected Result

I'd expect such an error to be tracked by Sentry.

### Actual Result

No issue is reported

**Comment by antonpirker** [comment]
Hey @b4stien !
Thanks for writting in. I am currently working on something else that uses a Chalice project, so maybe I can try to reproduce this today!

**Comment by b4stien** [comment]
Let me know if I can help somehow. My investigations stopped around https://github.com/aws/chalice/blob/master/chalice/app.py#L1253-L1298 which is not instrumented by the chalice integration afaik.

**Comment by antonpirker** [comment]
Could you please test this:
If your authorizer does not raise an Exception but your `boom()` method does raise an Exception. Is this exception ending up in Sentry?
This is just to see if the authorizer decorator somehow swallows all exceptions.

**Comment by b4stien** [comment]
> If your authorizer does not raise an Exception but your boom() method does raise an Exception. Is this exception ending up in Sentry?

From memory it does end up in Sentry, I'll re-test asap.

The "Authorizer" part in Chalice (and AWS Lambda subsequently) is very specific, it's a different AWS Lambda called internally by AWS API Gateway. As far as I understood the code, Sentry's Chalice Integration does not instrument this "other AWS Lambda", hence the no report. But as soon as we go back to the "main" AWS Lambda (in the endpoint/route itself) the integration works.

**Comment by antonpirker** [comment]
Ok, thanks for the info. So it is not as trivial as I thought. I am putting this in our low prio backlog and we will see.

**Comment by josiahcoad** [comment]
Hey this is happening for me too.

**Comment by b4stien** [comment]
For the record we ended up phasing out Chalice completely and wrote a pure WSGI app (Flask), wrapped with [apig-wsgi](https://github.com/adamchainz/apig-wsgi) and deployed with pulumi.

Imo Chalice should stop being recommanded, it's riddled with bugs, half documented at best and not maintened anymore.
