### ISSUE TITLE
Celery: Ignore loggers `celery.worker.job` and `celery.worker.strategy` for breadcrumbs

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#136]
Those two loggers completely flood the breadcrumb buffer. I suspect that they "drive out" other events as well. Some people were complaining about junk breadcrumbs in celery from those loggers.

It's possible that we have a bug where we leak breadcrumbs between threads (and that's what's causing this issue), but I don't see how. If so we should see breadcrumbs from other loggers "leaked" between tasks, not just these two celery loggers.

Fix: call `ignore_logger` for both `celery.worker.job` and `celery.worker.strategy` in the celery integration

**Comment by untitaker** [comment]
cc @mitsuhiko since you showed me this issue in our internal project. We have a customer with the same issue.

**Comment by mitsuhiko** [comment]
I am in favour of ignoring those by default.

**Comment by untitaker** [comment]
Decided to leave out `celery.worker.strategy` as that one is not too verbose. It's really just `celery.worker.job` that spams
