### ISSUE TITLE
Incorrect test command in CONTRIBUTING.md

### ISSUE THREAD

**Issue by targhs** [getsentry/sentry-python#1360]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.6

### Steps to Reproduce

1. Go to CONTRIBUTING.md
2. Under **Running tests** command says 
> make tests

### Expected Result

Correct command should be 

> make test

### Actual Result

![image](https://user-images.githubusercontent.com/34231252/156876179-06a2e973-e6a5-4efa-9b43-4b42ef837c05.png)

**Comment by targhs** [comment]
I am happy to submit a PR for this.

**Comment by antonpirker** [comment]
Hi @targhs !
Oops, thanks for pringing this up!
Yes, please submit a PR for this!
