### ISSUE TITLE
python traceback locals cut off after a variable fails repr

### ISSUE THREAD

**Issue by agroszer** [getsentry/sentry-python#1365]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

9.1.2

### Steps to Reproduce

python-pseudo code:
```
def test():
    a = 1
    b = ObjectThatRaisesOnRepr()
    c = 3
    1 / 0  # raise, cause a sentry
```

### Expected Result

locals list of:
```
a           1
c           3
```

or even better, ideally
```
a           1
b           <variable failed repr>
c           3
```

### Actual Result

locals list of:
```
a           1
```

**Comment by sl0thentr0py** [comment]
thx for reporting @agroszer, we'll take a look eventually but PRs always welcome!

**Comment by szokeasaurusrex** [comment]
@agroszer I attempted to reproduce this bug in the current latest version of the Python SDK, and it appears to be working as expected, with "<broken repr>" being output for the variable whose `__repr__` function fails. So, I am closing this issue. 

If you continue to experience the problem when using the latest Python SDK, please reopen the issue and provide a code snippet I can run to observe the same result that you are. Any additional information about your configuration that you are able to share would help me to reproduce the bug.
