### ISSUE TITLE
Update all dependencies

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#1373]
### Problem Statement

Dependencies are outdated. There are a lot of dependabot PRs in the repo.

### Solution Brainstorm

Update dependencies one by one.

**Comment by ivellios** [comment]
Agreed. Just came across an issue with tornado not supporting python 3.10 stuff. I had to pin tornado to 6.1 (in sentry-sdk it is `>=5` which is not supporting python 3.10 I believe)

**Comment by kasium** [comment]
Same for flask. Flask 2.1.1 is out but cannot be used

**Comment by antonpirker** [comment]
This will be done in separate pull requests. Thanks @ivellios and @kasium for your input.
