### ISSUE TITLE
Sentry print output to console upon terminate

### ISSUE THREAD

**Issue by shayownbackup** [getsentry/sentry-python#138]
When sentry python is terminating 'raven-python/raven/transport/threaded.py', method 'main_thread_terminated'.

Sentry is printing to output. 
This cause damage to our process who relies on system output.

how can I solve this  ?

thank you

**Comment by untitaker** [comment]
Please file this issue against https://github.com/getsentry/raven-python, the legacy Python SDK

This repo is for the new SDK, documented at https://docs.sentry.io/platforms/python/
