### ISSUE TITLE
Sentry is not filtering out NotAuthenticatedError from Django

### ISSUE THREAD

**Issue by mshoaibpro** [getsentry/sentry-python#1380]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.8

### Steps to Reproduce

I am using Django(2.0.13) with graphql. 
Steps: 

1. Init sentry with before_send method and filter out NotAuthenticated Exception i.e. return None for this error. 
2. Raise an NotAuthenticated exception in your code for a request. 
3. Notice that error is still reported to sentry.io and not filtered out. 

Code sample:

```
from django.core.exceptions import PermissionDenied
from rest_framework.exceptions import NotAuthenticated, AuthenticationFailed

def before_send(event, hint):
        """Filter out following exceptions from sentry, since these are quite common"""
        if 'exc_info' in hint:
            exc_type, exc_value, tb = hint['exc_info']
            if isinstance(exc_value, (
                    NotAuthenticated,
                    AuthenticationFailed,
                    PermissionError,
                    PermissionDenied,
            )):
                return None
        return event


sentry_sdk.init(
            dsn=env("DJANGO_SENTRY_DSN"),
            integrations=[DjangoIntegration(), CeleryIntegration()],
            send_default_pii=True,
            debug=env.bool('DJANGO_SENTRY_DEBUG', default=False),
            before_send=before_send,
        )
```

### Expected Result

NotAuthenticated exception should not be sent to sentry.io.

### Actual Result

NotAuthenticated sent to sentry.io.

**Comment by sl0thentr0py** [comment]
@mshoaibpro don't see anything obviously wrong with your config. Can you send a link with the issue in sentry? You can use the public share link on the issue details page.

![image](https://user-images.githubusercontent.com/6536764/161138917-a18bbdb2-c19c-42b1-8b41-8501f07645b3.png)

**Comment by mshoaibpro** [comment]
@sl0thentr0py Here is the link: https://sentry.io/share/issue/a382543609fe40e7af5ed7e7593e3ea0/

**Comment by mshoaibpro** [comment]
Answering one question beforehand: I know for sure that my code containing sentry's send_method is deployed. This method was added a couple of commits anyway so I don't have any doubt that this config is deployed.

**Comment by sl0thentr0py** [comment]
This is not an exception but a message sent with `sentry_sdk.capture_message` which is why the hint in `before_send` has no exception object attached.

**Comment by mshoaibpro** [comment]
It answers my question - if you like, you can close this issue or perhaps leave it open for enhancement. It's all up to you.

**Comment by emadimehrdad** [comment]
Hi
I have the same problem with my project. I ignore some custom exceptions and don't want to send them to the sentry and also have not used capture_message in my code, but it is still sent.
Here is my before_send method:

```
ignore_logger('graphql.execution.utils')

def sentry_exception_handler(event, hint):
    exception_type, exception_class, tc = hint['exc_info']
    if isinstance(exception_class, (KubitValidationError, InvalidInputError)):
        return None
    elif isinstance(exception_class, (AccessDenied, UserDoesNotAuthenticated, UserNotFoundError)):
        return None
    elif isinstance(exception_class, ObjectNotFoundError):
        return None
    return event
```
