### ISSUE TITLE
`LoggingIntegration(event_level=logging.INFO)` doesn't work as advertised (no event created from `logging.info()`)

### ISSUE THREAD

**Issue by zevaverbach** [getsentry/sentry-python#1387]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.8

### Steps to Reproduce

In a Python module, I do something like:

```python
import logging

import sentry_sdk
from sentry_sdk.integrations.logging import LoggingIntegration

sentry_logging = LoggingIntegration(
    level=logging.INFO,
    event_level=logging.INFO 
)

sentry_sdk.init(
    dsn='https://blah@blah.ingest.sentry.io/123456',
    integrations=[sentry_logging],
    traces_sample_rate=1.0,
)

logging.info('hi mom')
```

### Expected Result

I expect an entry to show up in the Sentry dashboard with the level "info" and the message "hi mom".

### Actual Result

Nothing arrives!

**Comment by sl0thentr0py** [comment]
hi @zevaverbach, you need to set the logging level as well, this works

```
import logging

import sentry_sdk
from sentry_sdk.integrations.logging import LoggingIntegration

logging.basicConfig()
logging.getLogger().setLevel(logging.INFO)

sentry_logging = LoggingIntegration(
    level=logging.INFO,
    event_level=logging.INFO
)

sentry_sdk.init(
    integrations=[sentry_logging],
    traces_sample_rate=1.0,
)

logging.info('hi mom')
```

**Comment by zevaverbach** [comment]
thanks @sl0thentr0py for the quick response! Can I suggest that Sentry's documentation be updated with this info? Those two lines you suggested [are missing from it here](https://docs.sentry.io/platforms/python/guides/logging/).

```
logging.basicConfig()
logging.getLogger().setLevel(logging.INFO)
```
