### ISSUE TITLE
Events getting silently dropped

### ISSUE THREAD

**Issue by blaketeres** [getsentry/sentry-python#1389]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.6

### Steps to Reproduce

Unfortunately I haven't figured out how to reproduce this. 99.9% of errors (not a real stat) get sent as expected. It seems to happen randomly. I am logging exceptions to a custom logger in the `before_send` function like this, followed by my `init` call:

```python
import traceback

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.flask import FlaskIntegration
from sentry_sdk.integrations.redis import RedisIntegration

sentry_sent_logger = logging.getLogger('sentry-sent')


def before_send(event, hint):
    tb = '\n'.join(traceback.format_tb(hint['exc_info'][2]))
    log_str = f'\ntraceback: {tb}\n-----'

    sentry_sent_logger.info(log_str)
    return event


sentry_sdk.init(
    dsn=env.get_sentry_io_url(),
    integrations=[DjangoIntegration(), FlaskIntegration(), RedisIntegration()],
    debug=True,
    traces_sample_rate=0.0,
    send_default_pii=True,
    before_send=before_send
)

```
I am always returning the event from `before_send`. At 04:07 EST this morning a stack trace of an exception was written to my logs by the `sentry_sent_logger`. This error does not exist in my sentry.io UI.

I have been running with `debug=True` since I have noticed this happening before. Below are the `sentry_sdk` logs at the same time. There is nothing logged by `sentry_sdk` at the time of the dropped exception.

```python
2022-04-08 00:04:04,682 - sentry_sdk.errors - DEBUG - [Tracing] Discarding <http.server> transaction <generic WSGI request> because traces_sample_rate is set to 0
2022-04-08 00:04:04,684 - sentry_sdk.errors - DEBUG - Discarding transaction because sampled = False
2022-04-08 00:04:04,684 - sentry_sdk.errors - INFO - Discarded session update because of missing release
2022-04-08 00:04:06,275 - sentry_sdk.errors - DEBUG - [Tracing] Discarding <http.server> transaction <generic WSGI request> because traces_sample_rate is set to 0
2022-04-08 00:04:06,277 - sentry_sdk.errors - DEBUG - Discarding transaction because sampled = False
2022-04-08 00:04:06,277 - sentry_sdk.errors - INFO - Discarded session update because of missing release
2022-04-08 00:04:10,850 - sentry_sdk.errors - DEBUG - [Tracing] Discarding <http.server> transaction <generic WSGI request> because traces_sample_rate is set to 0
2022-04-08 00:04:10,852 - sentry_sdk.errors - DEBUG - Discarding transaction because sampled = False
2022-04-08 00:04:10,852 - sentry_sdk.errors - INFO - Discarded session update because of missing release
```

I honestly cannot figure out what is happening. I have to assume something is happening between the `before_send` function and the event actually sending. Please let me know if you need more info.

### Expected Result

Sentry sends the errors to sentry.io.

### Actual Result

Sentry does not send the errors to sentry.io.

**Comment by sl0thentr0py** [comment]
@blaketeres does it work without the `before_send`?

**Comment by blaketeres** [comment]
> @blaketeres does it work without the `before_send`?

No. The reason I added the logger in the `before_send` was because we had suspicions errors were getting dropped. We have other error logs that were logging errors that were not making it to Sentry. I added this logger here to eliminate our app as the possible culprit for what is preventing the errors from getting to Sentry.

**Comment by sl0thentr0py** [comment]
you have both django and flask in there, what is your setup like?

**Comment by blaketeres** [comment]
> you have both django and flask in there, what is your setup like?

We are using flask as our web framework and django as our database ORM only. I am using the `DjangoIntegration` to capture django logs as breadcrumbs automatically.

**Comment by sl0thentr0py** [comment]
and it's not a quota problem? can you send me your organization slug?

**Comment by blaketeres** [comment]
> and it's not a quota/rate limit problem? can you send me your organization slug?

I've checked. We occasionally do get rate limited but these are accounted for. There is no rate limiting that is matched up with this event. The organization slug is `vectorworks`

**Comment by sl0thentr0py** [comment]
ok these are stats from the last 2 days

![image](https://user-images.githubusercontent.com/6536764/162476529-3eba6796-6528-4b6f-b2be-2e26d8e5e844.png)

![image](https://user-images.githubusercontent.com/6536764/162476574-a434e391-11f6-4c7b-bd77-fa1796cfa0be.png)

and there's a bunch of `Network Errors` though if that is the case there should be some logs of either of these forms
```
        logger.error("Internal error in sentry_sdk", exc_info=exc_info)
        logger.error("Unexpected status code: %s (body: %s)", response.status, response.data)
```

**Comment by blaketeres** [comment]
> ok these are stats from the last 2 days.
> 
> ![image](https://user-images.githubusercontent.com/6536764/162476529-3eba6796-6528-4b6f-b2be-2e26d8e5e844.png)
> 
> ![image](https://user-images.githubusercontent.com/6536764/162476574-a434e391-11f6-4c7b-bd77-fa1796cfa0be.png)
> 
> and there's a bunch of `Network Errors` though if that is the case there should be some logs of either of these forms.
> 
> ```
>         logger.error("Internal error in sentry_sdk", exc_info=exc_info)
>         logger.error("Unexpected status code: %s (body: %s)", response.status, response.data)
> ```
> 
> Also as a side note, it is advised to contact support in such cases. Github is mainly intended for issues/bugs/feature requests.

Thanks for looking into this. I assumed it was an issue with the client. I'll contact support.

**Comment by blaketeres** [comment]
@sl0thentr0py Hi, I'm curious how I can access the data from the screenshots you posted here? https://github.com/getsentry/sentry-python/issues/1389#issuecomment-1093025427
Is this available to me as an end user? I would like to see updated figures here.

**Comment by sl0thentr0py** [comment]
@blaketeres exposing these stats to the end user is on the product roadmap, but I can't give you an ETA on when that will be shipped unfortunately.

here's a couple of days in the last week, you still have a lot of `Network Error`s. 

<img width="319" alt="image" src="https://user-images.githubusercontent.com/6536764/171002388-bb0caf60-9723-4b8f-a391-839835ade16b.png">


<img width="319" alt="image" src="https://user-images.githubusercontent.com/6536764/171002415-c37ba750-9559-4511-8274-e56221417f81.png">
