### ISSUE TITLE
Breadcrumbs dropped when using decorators

### ISSUE THREAD

**Issue by juanbenitezdev** [getsentry/sentry-python#1405]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

0.18.0

### Steps to Reproduce

I have a code like following.

```python
def validate(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        try:
            func(*args, **kwargs)
        except Exception as e:
            logger.error("An error occurred while executing function.", error=e) # This is sent to Sentry
    return wrapper

@validate
def my_function():
    logger.info("Logging something") # this is not being logged as a breadcrumb but it needs to be

    # Do something that could raise an exception

    return
```

I'm using the decorator to catch those errors in multiples functions, I want to get the exceptions in Sentry and the breadcrumbs as well.

### Expected Result

The expected result will be to have in Sentry

- `Level: info, category: my_function, description: "Logging something"`
- `Level: error, category: validate, description: "An error occurred while executing function."`

### Actual Result

The actual result is that only the exception in the decorator is being sent

- `Level: error, category: validate, description: "An error occurred while executing function."`

**Comment by antonpirker** [comment]
Hello @juanbenitezdev 

Thanks for reporting this. 

I have a couple of questions:
- Are both log messages (the info and the warning) showing up in your console (or your log file?)
- Can you try this behavior with the newest SDK and see if it also happening there?

Thanks,
Anton

**Comment by juanbenitezdev** [comment]
Hey @antonpirker 

Thanks for answering.

After some testing on my side, I came to the conclusion that in version 0.18.0 only 10 breadcrumbs were being sent to Sentry and that is why I couldn't see my logs there, I tested it with the latest version 1.5.10 and it works perfectly. So I supposed this issue was already solved. I'm gonna close this one.
