### ISSUE TITLE
Add FastAPI and Starlette Landing Page

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#1408]
### Problem Statement

Have something like this for FastAPI: https://sentry.io/for/django/

### Solution Brainstorm

* clone Django one and adapt it for FastAPI

**Comment by smeubank** [comment]
This is underway already

https://github.com/getsentry/static-sites/pull/1111

**Comment by antonpirker** [comment]
Also created a page for Starlette:
https://github.com/getsentry/static-sites/pull/1125

**Comment by antonpirker** [comment]
Both landing pages are live!
