### ISSUE TITLE
sentry_sdk.init fails mypy checks

### ISSUE THREAD

**Issue by dhuckins** [getsentry/sentry-python#1415]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.10

### Steps to Reproduce

1. `$ python3.10 -m venv venv`
2. `$ source ./venv/bin/activate  # assuming unix`
3. `[venv] $ pip install sentry-sdk==1.5.10 mypy==0.950` (currently the latest versions of sentry-sdk and mypy)
4. create file to test (`mytest.py` for example purposes)
```python
# mytest.py
import sentry_sdk

sentry_sdk.init(dsn="this is a string")
```
5. `[venv] $ mypy mytest.py`

### Expected Result

no errors

### Actual Result

```
❯ mypy mytest.py                                        
mytest.py:3: error: Cannot instantiate abstract class "init" with abstract attribute "__exit__"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by vladanpaunovic** [comment]
Thanks @dhuckins , we are on this and we expect to have a fix for this by Wednesday.

**Comment by dhuckins** [comment]
> Thanks @dhuckins , we are on this and we expect to have a fix for this by Wednesday.

awesome! thank you!

**Comment by dhuckins** [comment]
thanks for taking care of this so quickly! when is the next release (with these changes) planned?

**Comment by sl0thentr0py** [comment]
@dhuckins released 1.5.11

**Comment by dhuckins** [comment]
Thanks!

**Comment by takeda** [comment]
@sl0thentr0py any reason why https://peps.python.org/pep-0612 was not used as a fix? I was looking at https://github.com/python/typing/issues/270 and saw that @untitaker was involved in discussion about it so I assumed that it would be the fix.

**Comment by untitaker** [comment]
Honestly I can't wrap my head around that PEP right now so if you think you have a better solution i'd create a patch.

**Comment by takeda** [comment]
@untitaker I took a closer I guess PEP 612 does not apply.

How I understand that could work, is to remove the hacks with `_Client` and `Client` make the class simply being called `Client` and `_get_options` and `get_options` then copy all of the parameters from the mockup Client to `get_options` (alternatively use `TypedDict`).

then add:

```python
F = TypeVar('F', bound=Callable[..., Any])

class copy_signature(Generic[F]):
    def __init__(self, target: F) -> None: ...
    def __call__(self, wrapped: Callable[..., Any]) -> F: ...
```

As mentioned in the comment, and add then `@copy_signature(get_options)` to the `init()` function.

**Comment by sl0thentr0py** [comment]
@takeda if you make a PR, I'll happy to merge in the changes

**Comment by untitaker** [comment]
I think using a decorator instead of a class hierarchy to patch in the signature might be a good idea that makes things more legible, but I think TypedDict (still) cannot be used to type out kwargs.
