### ISSUE TITLE
Package not classified as Python 3 compatible 

### ISSUE THREAD

**Issue by pwmedia** [getsentry/sentry-python#142]
* `sentry-sdk` is classified as not Python 3 compatible by [pyup](https://pyup.io) when it actually is - e.g. [https://pyup.io/repos/github/pushresume/backend](https://pyup.io/repos/github/pushresume/backend)

![image](https://user-images.githubusercontent.com/19856859/47429544-63446a00-d79f-11e8-8f9b-ac6d2bd3b805.png)

* `setup.py` classifiers should be updated with `Programming Language :: Python :: 3`

**Comment by untitaker** [comment]
You're right. This package is actually missing all classifiers
