### ISSUE TITLE
Align SDK with docs regarding session update for dropped events

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-python#1424]
### Description

We've updated the docs (https://github.com/getsentry/develop/pull/551) to explain how we would like to handle event filter order, updating of sessions for dropped events and sending of session updates. We should check if we're aligned and adapt if necessary. 

### Solution Brainstorm

Here's the issue from the Java SDK where all of this started: https://github.com/getsentry/sentry-java/issues/1916

**Comment by stephanie-anderson** [comment]
Closed as discussed with Steven
