### ISSUE TITLE
sentry-sdk not informing that messages can't be delivered

### ISSUE THREAD

**Issue by kbakk** [getsentry/sentry-python#1437]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.11

### Steps to Reproduce

Sentry is right now [having an outage](https://status.sentry.io/incidents/zwlnckpsrb6l). Not sure how to reproduce this when this is not the case.

Here's a test app I ran:

<details>
<summary>`app.py`</summary>

```py
from fastapi import FastAPI
import sentry_sdk
from sentry_sdk.integrations.asgi import SentryAsgiMiddleware
from starlette.middleware import Middleware
import logging

logging.basicConfig(level=logging.DEBUG)

sentry_sdk.init(dsn="https://my-dsn")

app = FastAPI(middleware=[Middleware(SentryAsgiMiddleware)])

@app.get("/err_raise")
def raise_err():
    raise ValueError("Foo")

```

</details>

It depends on having run `pip install fastapi uvicorn sentry-sdk`. Run it with `uvicorn app:app --reload --host 0.0.0.0 --port 8000`

If I call the /err_raise endpoint, it will raise an exception.

```
...
  File "./app.py", line 15, in raise_err
    raise ValueError("Foo")
ValueError: Foo
DEBUG:urllib3.connectionpool:https://<redacted>.ingest.sentry.io:443 "POST /api/<redacted>/store/ HTTP/1.1" 502 332
...
^CINFO:     Shutting down
INFO:uvicorn.error:Shutting down
...
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
INFO:     Stopping reloader process [13842]
```

### Expected Result

In case the errors can't be submitted, it would be nice with a warning/error log message.

### Actual Result

Sentry outputs to stdout (err?), and if you have `urllib3` logging enabled, you'll find a log entry indicating a 502 error.

**Comment by sl0thentr0py** [comment]
@kbakk what's the output with `init(debug=True)`?

**Comment by kbakk** [comment]
(Un?)fortunately I'm not able to reproduce it now, as the issue causing the 500 server error has been [resolved](https://status.sentry.io/incidents/zwlnckpsrb6l).

**Comment by sl0thentr0py** [comment]
@kbakk I believe with `debug` on, the sdk will log network failures, so closing this. We don't want it to log by default though, so this is a design choice.
