### ISSUE TITLE
queue time and time since job started on RQ integration

### ISSUE THREAD

**Issue by samuelcolvin** [getsentry/sentry-python#144]
(moved from #128)

as per discussion on rq/rq#1003, the following would be very useful (and I think aren't implemented at present):
* time since the job started
* job queue time

You should be able to get the required data from [`enqueued_at` and `started_at`](https://github.com/rq/rq/blob/master/rq/job.py#L315-L316).

**Comment by antonpirker** [comment]
Quick Status update:

I put this on the internal backlog at a low priority. In the next couple of weeks we will have some roadmap planning where we decide what we tackle next. I"ll keep you posted.
