### ISSUE TITLE
capture_exception does not set mechanism.error.unhandled so it does not appear as unhandled issue in UI

### ISSUE THREAD

**Issue by torstenrudolf** [getsentry/sentry-python#1442]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.12

### Steps to Reproduce

catch an exception and send to sentry using `capture_exception(exc)`.

example:
```python
from sentry_sdk import capture_exception

try:
    1 / 0
except Exception as e:
    capture_exception(e)
```

### Expected Result

issue should appear in sentry's UI project page as an unhandled issue

### Actual Result

the issue doesn't appear in the project UI page. It seems this is because this page filters for issues with`error.unhandled: true`.

This happens because [capture_exception](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/hub.py#L369) does not set the `mechanism.handled: false` when calling `event_from_exception`. Integrations like [ExceptHookIntegration](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/excepthook.py#L59) however are setting this field.

When we re-engineer this by using `event_from_exception(exc_info, mechanism={"type": "custom", "handled": False})` and sending it via `Hub.current.capture_event` the issue pops up as unhandled like we expect.

**Comment by antonpirker** [comment]
Hey @torstenrudolf !

Thanks for bringing this up. This is actually intended behavior.

If you look at (for example) the Flask integration, there is a custom `_capture_exception` method that does set `handled` to `False`: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/flask.py#L201-L215

All the integration do this. So maybe you can also create a custom `capture_exception` method for your project.

Hope this helps!
