### ISSUE TITLE
SDK downloads complete s3fs contents with default with_locals value

### ISSUE THREAD

**Issue by thomas-bottesch** [getsentry/sentry-python#1448]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.5.6

### Steps to Reproduce

```import s3fs
import sentry_sdk

def test():
    #setup sentry
    sentry_sdk.init(..., with_locals=True)
    s3fs_obj = s3fs.S3FileSystem(client_kwargs={"region_name": "eu-central-1"})
    s3fs_map = s3fs.S3Map(
        root="some_bucket/some_folder", s3=s3fs_obj, create=True
    )
    
    # raise some exception
    assert False

test()
```

### Expected Result

Sentry should just print some info about the s3fs_map object like the memory address or so.

### Actual Result

The with_locals flag does gather information from local variables by doing something like this:
`dict(iteritems(s3fs_map))`

For s3fs_map this means that the complete contents of what lies within that bucket/folder is downloaded to memory.
For us this means that sentry will try to create a dict with millions of entries and download 4 TB from a bucket into memory.
In the documentation I did not find any way to disable selectively for one specific class the "with_locals" behavior. For us this means that we have to disable with_locals everywhere which makes sentry much less usable since the local variables are not displayed anymore.

It would be great if there was either a possibility to exclude a class or if the sdk itself would realize that it does not make sense to create a dict with millions of entries since they wont be uploaded anyway.

**Comment by antonpirker** [comment]
Hey @thomas-bottesch 

Thanks for bringing this up. 
As I understand the `s3fs_map` object is transparent so when it is converted into a dict it is downloaded. I can understand that this is not what you want.

You could monkey batch `s3fs_map` so it is returning exactly what you want when serialized by Sentry SDK.
