### ISSUE TITLE
Example traces_sampler for Django

### ISSUE THREAD

**Issue by robd003** [getsentry/sentry-python#1451]
### Problem Statement

I'd like to see an example of how to configure traces_sampler on Django to ignore hot paths.

For instance I never have a need to see traces for sharing static HTML content, however I'd like 100% traces on certain API calls.

### Solution Brainstorm

Make an example Django project and show how traces_sampler works

**Comment by antonpirker** [comment]
Hey @robd003 !

Have a look at this documentation, there is a example trace_sampler function defined: https://docs.sentry.io/platforms/python/configuration/sampling/#setting-a-sampling-function

Look into the `sampling_context` object the function is given to see where the path is stored and then if it is a hot path do a `return 0`.

Hope this helps!

**Comment by melchoir55** [comment]
> Hey @robd003 !
> 
> Have a look at this documentation, there is a example trace_sampler function defined: https://docs.sentry.io/platforms/python/configuration/sampling/#setting-a-sampling-function
> 
> Look into the `sampling_context` object the function is given to see where the path is stored and then if it is a hot path do a `return 0`.
> 
> Hope this helps!

There is no concrete example on this doc page. I strongly recommend replacing the "..." with actual concrete examples to avoid confusion.
