### ISSUE TITLE
Prose documentation for non-global-state usage

### ISSUE THREAD

**Issue by Julian** [getsentry/sentry-python#146]
Hi!

Exciting to see a new SDK.

It'd be great to have prose documentation for how to use this without relying on global state. It seems likely that making things easy was a core thing that this new SDK was trying to address, but for those of us that prefer to avoid magic, would be great to see a page on how to use the non-global state API (i.e., not calling `sentry_sdk.init`).

I haven't spent time yet to identify what specifically is involved there, but given what I assume `sentry_sdk.init` must be doing (mucking with sys.excepthook?) I assume that what's involved is "construct a `Client`, add that to a logging framework that the app is using, and have that logging handler call `someclient.capture_event` each time an exception is raised", similar to the way the old Raven API works). Most of that seems to already exist as API documentation, so I'm sure we could figure such a thing out, but yeah just filing this in case it's not already on the radar.

And again thanks for what looks like some nice new tooling!

**Comment by untitaker** [comment]
Hi @Julian,

If you could share more about your concrete usecase that requires this I think we would be able to write better prose docs. We want to avoid having pages that go "here's how you do this" and don't include "this is when/why you want this" (although I am sure there are plenty such pages already)

**Comment by Julian** [comment]
Yep makes sense -- it's hard to describe one single use case, because essentially the use case is "I want to use this library, but I'm not comfortable calling a function that clearly has side effects".

So I guess the use case is "I want to instrument an app to send tracebacks to sentry, and do so in the most explicit manner possible" -- does that make sense?

**Comment by Julian** [comment]
And of course the reasoning for the first paragraph is the usual -- e.g., because I have tests that want to make assertions about things being sent to sentry that I want to intercept, or because I want all my side effects to be clearly noticeable (and minimized) so they don't happen when unexpected, or etc.

**Comment by Julian** [comment]
And yeah apologies for triple posting, but maybe yet another way of putting this is "what does a replacement of [this page](https://docs.sentry.io/clients/python/integrations/logging/) look like" (which is similar to how we currently use Raven, though we don't necessarily use stdlib logging).

**Comment by untitaker** [comment]
Yeah, I think we'll have two pages "how to test with the sdk" and "how to use in a library". Needs to be aligned with other SDKs though.

In case this helps right now, this is the easiest way to isolate state without having to change too much code:

```python

from sentry_sdk import *

with Hub(Client(<init args here>)):
    capture_exception(ValueError())

# here the SDK is unconfigured again. Next line will be a noop
capture_exception(ValueError())
```

The side effects (fiddling with excepthook) only "exist" within the with-statement, within that current thread as well. Of course that's a convenient lie I am telling you (some monkeypatches, e.g. excepthook can't be undone) but that's how it is supposed to behave at a high level. Anything else is a bug.

>"what does a replacement of this page look like"

Well, technically here is the logging integration in the new SDK: https://docs.sentry.io/platforms/python/logging/ But it works differently than what you seem to want.

**Comment by Julian** [comment]
Nice! Thanks both of those look helpful. I'll have to actually try making one of our prod apps use this to be really really sure I know what I'm looking for but certainly seems like that code is in the vicinity.

Is it worth leaving this open to have a page about that form of usage then, or not something planned?

**Comment by untitaker** [comment]
Sure, let's keep it open for me as reminder

**Comment by untitaker** [comment]
@Julian btw if you get around to trying this please make sure to share your experiences here

**Comment by Julian** [comment]
Yes, 100%! Hoping to get this scheduled for my team in the next week or two, and will def come back with what shakes out, appreciated!

**Comment by Julian** [comment]
@untitaker we gave this a shot with one of our prod apps and seemingly has gone swimmingly so far, so all good I think for now! Definitely will be on the lookout for doc changes but seems like we're not having any issues so far moving to this SDK.

Appreciated!

**Comment by untitaker** [comment]
That's great to hear!

**Comment by miracle2k** [comment]
So I am struggling with this, and in particular I have this sort of code, which I think is a standard Flask way of creating re-usable app objects:

```
def create_app(sentry_dsn):
    app = Flask(__name__)
    return app
```

I am not sure where I am supposed to be calling `sentry_sdk.init()`. It would be wrong inside `create_app()`, since I do not want to apply it globally.

To be fair, it is rare that I want to have to instances of the app in the same process reporting to different sentry servers, so I could do:

def create_app(sentry_dsn):
    app = Flask(__name__)
    app.config['SENTRY_DSN'] = sentry_dsn
    return app

def install_app_in_process(app):
    sentry_sdk.init(app.config['SENTRY_DSN'])
```

Then, I can add a call to `install_app_in_process` in  my `wsgi.py`. But I think I'd also have to patch the Flask `run` command to call the install function first, if I'd want to use it there.

Am I going in the wrong direction here?

**Comment by untitaker** [comment]
Hmm, I came up with this:

```python
from sentry_sdk import *
from sentry_sdk.integrations.flask import FlaskIntegration

integrations = [FlaskIntegration()]

app1 = create_app()
client1 = Client(app1.config["SENTRY_DSN"], integrations=integrations)
app2 = create_other_app()
client2 = Client(app1.config["SENTRY_DSN"], integrations=integrations)

init(integrations=integrations)

@app1.before_request
def set_sentry_client():
    Hub.current.bind_client(client1)

@app2.before_request
def set_sentry_client():
    Hub.current.bind_client(client2)
```

Admittedly this took a little thinking on my part, and I am not particularly happy about the solution either. But I think it's the simplest one.

**Comment by antonpirker** [comment]
The first issue reported in this Issue (no global state) was addressed and the OP was happy. The second issue (reporting to two different Sentry account in one file) was also solved and the OP never replied. 

So I think it is save to close this issue. 

If you come across this Issue and you want to help improve the docs on this, create a new Issue and link to this one. Also head over to the
