### ISSUE TITLE
Official way to manually indicate a crashed session

### ISSUE THREAD

**Issue by TheDuckCow** [getsentry/sentry-python#1462]
### Problem Statement

I would like to have a clean, intended interface to call for the current session to be turned into a crashed state (same use case could exist for marking abnormal too I suppose).

I am using completely manual instrumentation in my non-web python environment for various reasons. In this application, I set up a general purpose handler to capture otherwise unhandled error and surface a message to the user. Within this code which handles the exception, I call sentry to to perform the basic exception handling, but I also want to update the session at that time and have sentry treat it as though unhandled.

I would be happy to be told there is a better way of doing this 😁 

### Solution Brainstorm

Right now I have solved my problem using this code, but it doesn't feel great that I am accessing internals of the sentry sdk and I worry things could change in the future:

```python
def _set_session_crashed() -> None:
    """Force the session to appear as crashed.

    Had to pull this from lower level sources of the sentry lib to assign, see
    Hub.py's start_session function for partial reference, and session.py
    for updating aspects of the session variable itself.
    """
    hub = sentry_sdk.Hub.current
    client, scope = hub._stack[-1]
    session = scope._session
    session.update(status="crashed")
```

I then use `_set_session_crashed()` in my custom exception handling wrapper like so:

```python
except Exception as e:
    ...
    sentry_sdk.capture_exception(e)
    sentry_sdk.capture_message("unhandled_ops_error", "fatal")
    _set_session_crashed()
    ...
```

Perhaps also worth saying, I was somewhat hoping that assigning the capture_message as "fatal" would be recognized as a crash, but it just shows up as an error in sentry reporting.

**Comment by antonpirker** [comment]
The `capture_message` does just record a message, that will never change the state of the session. The `fatal` you set there will just set the level of the message, but not change the session.

If you capture an event with `capture_event()` that has one (or more) execptions set in `exception` property and one of the exceptions has set `handled` in the mechanism to `False` then the associated session will be set to `crashed`.

In the flask integration this is done like this: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/flask.py#L201-L219

This is the way almost all of our integrations do this, so it is kind of the unofficial official way to do this. :-)

Maybe you can recreate something like this for your own implementation?

Hope this helps,
Anton

**Comment by TheDuckCow** [comment]
Sorry for the delayed response - thanks for sharing that reference, good to know. I'm torn between the way I was doing it, whereas your suggestion ends up requiring me to essentially fork the entire `capture_exception` function which I also worry about getting outdated. But either way, I have what I need to resolve my problem, so will close this issue. Thanks for clarifying the way crash states and events work!
