### ISSUE TITLE
document in_app_include + in_app_exclude

### ISSUE THREAD

**Issue by danielcompton** [getsentry/sentry-python#148]
I took a look at the docs and API docs for the new Sentry python SDK and couldn't see a replacement for [`include_paths`](https://docs.sentry.io/clients/python/advanced/). Is this planned/available?

**Comment by untitaker** [comment]
Yes, this is called `in_app_include` now, as argument to `init`. We have to document this.

**Comment by untitaker** [comment]
https://github.com/getsentry/sentry-docs/pull/736

**Comment by untitaker** [comment]
Thanks for closing this, I forgot :)
