### ISSUE TITLE
SDK Name should include framework used

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-python#1497]
### Problem Statement

From many (most or all?) Sentry SDKs the sdk name in the event payload, query params, and auth headers follows a pattern of including the framework when being used. (like `sentry.ruby.rails` or `sentry.php.laravel`) The python SDK should follow the same pattern, this would make tracking usage per framework much easier.

### Solution Brainstorm

SDK name in the event body, header, query param, and auth header should all match, similar or same as other SDKs

### Where to include:

- [ ] event header [Dev docs headers](https://develop.sentry.dev/sdk/envelopes/#headers)
- [ ] event body [Develop docs Event payload Attributes](https://develop.sentry.dev/sdk/event-payloads/sdk/#attributes)
- [ ] auth header or query param: [Authentication dev docs](https://develop.sentry.dev/sdk/overview/#authentication)

**Comment by antonpirker** [comment]
Here is a list of all the integrations we have in Python and what name would this result in:

```
sentry.python.aiohttp
(sentry.python.argv)
sentry.python.asgi
(sentry.python.atexit)
sentry.python.aws_lambda
sentry.python.beam
(sentry.python.boto3)
sentry.python.bottle
(sentry.python.celery)
sentry.python.chalice
sentry.python.django
(sentry.python.dedupe)
(sentry.python.excepthook)
(sentry.python.executing)
sentry.python.falcon
sentry.python.fastapi
sentry.python.flask
sentry.python.gcp
sentry.python.gnu_backtrace
sentry.python.httpx
sentry.python.logging
(sentry.python.modules)
(sentry.python.pure_eval)
sentry.python.pyramid
sentry.python.quart
(sentry.python.redis)
(sentry.python.rq)
sentry.python.sanic
sentry.python.serverless
(sentry.python.sqlalchemy)
sentry.python.starlette
(sentry.python.stdlib)
(sentry.python.threading)
sentry.python.tornado
sentry.python.trytond
sentry.python.wsgi
```

Some of them are not framework integrations and therefore not worthy of a name on their own. (the ones in paranthesis)

So I guess he have to add a flag somewhere in the integration that defines if this integrations gets a name or not.
And what should happen if a user has the Django and the FastAPI integration enabled? There should be some precedence, right? Or just an "undefined" behavior, whichever integration is loaded last sets the name?

**Comment by antonpirker** [comment]
I guess the frameworks that have a guide in the documentation (right sidebar for example here: https://docs.sentry.io/platforms/python/guides/bottle/) should have a name on their own.
