### ISSUE TITLE
Split Python tests in unit, integration and e2e tests

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#1500]
### Problem Statement

So we can better track how many unit/integration/e2e tests we have. (hint: test pyramid)

Also it should be possible to only run unit/integration/e2e tests if desired.

Mark tests as unit/integration/e2e: 

 

or with this:

### Solution Brainstorm

Mark tests as unit/integration/e2e: 

 https://docs.pytest.org/en/6.2.x/example/markers.html

or with this:

https://pypi.org/project/pytest-integration-mark/

**Comment by vladanpaunovic** [comment]
Create an order of test types so we can fail faster.

**Comment by antonpirker** [comment]
Tests are ok now, so I am closing this for now.
