### ISSUE TITLE
Celery integration doesn't report uncaught exceptions when initialized as suggested

### ISSUE THREAD

**Issue by harto** [getsentry/sentry-python#1512]
### Core or SDK?

Platform/SDK

### Which part? Which one?

https://docs.sentry.io/platforms/python/guides/celery/

### Description

I tried to set up the Celery integration by following https://docs.sentry.io/platforms/python/guides/celery/. 

I tried to initialize Sentry in response to the `worker_process_init` signal as mentioned in this passage:

> There are many valid ways to do this like, for example, using a signal like [worker_process_init](https://docs.celeryq.dev/en/stable/userguide/signals.html#worker-process-init) […]

My code looked something like this:
```python
# myapp.celery

from os import environ
from celery import Celery, signals
import sentry_sdk

app = Celery(
    'myapp',
    broker='redis://localhost:6379',
    include=['myapp.tasks'],
)

def init_sentry():
    sentry_sdk.init(debug=True, dsn='…')

@signals.worker_process_init.connect
def init_worker(**_kwargs):
    init_sentry()
```

When set up this way, the Sentry initialization ran (I saw a bunch of Sentry debug output when the worker started) but uncaught exceptions in the worker were not reported to Sentry. For example, given the following task:

```python
# myapp.tasks

import sentry_sdk

from sentry_celery_test.celery import app

@app.task
def task():
    sentry_sdk.capture_message('should report this')
    raise Exception('should also report this')
```

Only the `capture_message` ended up appearing in Sentry.

If I changed `myapp.celery` like this:
```diff
--- /Users/stuart/src/sentry_celery_test/myapp/celery.py
+++ #<buffer celery.py>
@@ -14,7 +14,4 @@
 def init_sentry():
     sentry_sdk.init(debug=True, dsn=environ['SENTRY_DSN'])
 
-
-@signals.worker_process_init.connect
-def init_worker(**_kwargs):
-    init_sentry()
+init_sentry()
```

Then the uncaught exception was reported as expected.

Using the `celeryd_init` signal, as discussed in [this relevant issue](https://github.com/getsentry/sentry-docs/issues/3697) also seemed to work.

### Suggested Solution

Not sure :-)

**Comment by sl0thentr0py** [comment]
hey @harto thanks a lot for reporting this. I finally investigated this today.
You are right that `worker_process_init` will not work because we patch `build_tracer` and `worker_process_init` is called [here](https://github.com/celery/celery/blob/b96ab282a8a2ea3d97d034f862e9fd6aceb0a0b5/celery/concurrency/prefork.py#L73-L79) _after_ `build_tracer`.

Both `celeryd_init` and `worker_init` will however work so I will update the docs!
