### ISSUE TITLE
ClientDisconnect thrown from Starlette for FastApi Integration

### ISSUE THREAD

**Issue by biel-michael** [getsentry/sentry-python#1534]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.9.0

### Steps to Reproduce

1. Install the lib v1.9.0;
2. Configure the sentry initialization as described in the release documentation:

```python3
from fastapi import FastAPI
from sentry_sdk.integrations.starlette import StarletteIntegration
from sentry_sdk.integrations.fastapi import FastApiIntegration

sentry_sdk.init(
  dsn="...",
  integrations=[
        StarletteIntegration(), 
        FastApiIntegration()
  ],
)
app = FastAPI()
```

Originally my application (which is running on Rancher k8s, behind an nginx ingress controller) has a [SentryAsgiMiddleware](https://docs.sentry.io/platforms/python/guides/asgi/) instrumented and function normally. However, when I switch to use the new beta `FastApiIntegration()`, my application can start but would throw errors for all requests.

Strangely though, this setup would work locally when I am using localhost.

### Expected Result

My FastAPI server instance should function normally. Messages and errors should be captured and sent to my Sentry SAAS instance.

### Actual Result

The server hangs up on request to the server. An `ClientDisconnect` Error is thrown and received by Sentry.

![image](https://user-images.githubusercontent.com/74031047/182540249-67d0a352-1c83-4c7d-8e40-c3e8f57a4ec4.png)

**Comment by antonpirker** [comment]
Hello @biel-michael !
Thanks for reporting this. I guess this has already been fixed in this PR: https://github.com/getsentry/sentry-python/pull/1532

Could you by any chance use the branch from the PR to test if it is fixed in there?

**Comment by biel-michael** [comment]
Hello @antonpirker ,

Sure I can have a try. I would use the head of #1532 and see if that works then. Might be able to give you a feedback by the end of week or Monday.

**Comment by biel-michael** [comment]
We have tried to use #1532. It seems like the head of that branch has indeed fixed the issue! Here are some screenshots for the result:

![fastapi-sentry-branch](https://user-images.githubusercontent.com/74031047/183007402-91cbf68c-7ba7-4138-8b16-e53aa5044961.png)
![k8s-sentry](https://user-images.githubusercontent.com/74031047/183007404-64985382-3739-47c4-8604-3953cb2d0fda.png)
![sentry-branch](https://user-images.githubusercontent.com/74031047/183007403-502fd942-34d6-4b15-be5a-9fe7b6ff78da.png)

We have also double checked that the released v1.9.0 version of the library is not working, as we have previously depicted when we opened the issue.

**Comment by biel-michael** [comment]
When would that fix branch be released to production? It seems like it is nearly done and there is active development.

**Comment by biel-michael** [comment]
Sure @antonpirker , I will send you my shipping address (in Hong Kong) separately to your mail address. Good to know that your release is coming live soon! We would love to get that in for all our FastAPI projects.

It is alright if that gift doesn't get through after shipping. We are glad to be part of the process as well.

**Comment by biel-michael** [comment]
After a few trials, we settled with v1.9.3 and it is running live on production. We are still in the progress of instrumenting our frontend repository but everything is looking good on the Python side right now!
