### ISSUE TITLE
Disable sending Spans with attribute Sampled=False

### ISSUE THREAD

**Issue by andrewchernyh** [getsentry/sentry-python#1539]
### Problem Statement

Span attribute `sampled` is ignored and on `Transaction` finish all collected Spans inside `Transaction` will be send, if all transaction is Sampled.

I want to use feature-flags for disabling tracing of some parts of my code dynamically for reducing usage on production environment (for example when I've many fast request to another service). 

### Solution Brainstorm

Modify condition  https://github.com/getsentry/sentry-python/blob/b7c0dc412a1505fff382732f567952c8a9572b60/sentry_sdk/tracing.py#L646 to
`if span.timestamp is not None and (span.sampled == True or span.sampled is None)`

**Comment by sl0thentr0py** [comment]
@andrewchernyh how do you plan to use this even if we add this condition?

**Comment by andrewchernyh** [comment]
@sl0thentr0py 

I'm using tracing decorators, and can easy add something like this
```python
....
        def wrappee(*args, **kwargs):
            sampled = is_feature_enabled("tracing", context: { "op": decorator_self.op } )
            with start_span(decorator_self.op, decorator_self.description, sampled=sampled):
                return original_func(*args, **kwargs)

```

Another usage of unsampled spans is filtering them out on some condition, for example with duration less them 1ms

**Comment by sl0thentr0py** [comment]
Right now sampling as a concept only exists on the transaction level. Changing APIs like this needs to be discussed internally and synced across SDKs, so we won't be moving fast on this but I'll bring it up. But it's not clear to me that this is a good idea and fits into the rest of the performance UX.

---

Second, modifying
https://github.com/getsentry/sentry-python/blob/b7c0dc412a1505fff382732f567952c8a9572b60/sentry_sdk/tracing.py#L646
is after the span is recorded/instrumented already, so it doesn't really lower your overhead.

---

Third, if you already have that decorator, you could just move the sampling logic for spans to your decorator and do it yourself. This will probably unblock you sooner than waiting for us. For instance,
```python
        def wrappee(*args, **kwargs):
            sampled = is_feature_enabled("tracing", context: { "op": decorator_self.op } )
            if sampled:
                with start_span(decorator_self.op, decorator_self.description):
                    return original_func(*args, **kwargs)
            else:
                    return original_func(*args, *kwargs)
```
