### ISSUE TITLE
Transaction _data (after set_data) is ignored on sending to sentry server

### ISSUE THREAD

**Issue by andrewchernyh** [getsentry/sentry-python#1540]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.9

### Steps to Reproduce

Configure SENTRY_DSN env variable and run

```python
import sentry_sdk 

sentry_sdk.init(traces_sample_rate=1.0)

with sentry_sdk.start_transaction(None, op="Test Transaction", description = "My description", name = "My name") as tr:
    tr.set_data("mydata", "myvalue")

sentry_sdk.flush()
```

### Expected Result

Expected result is simulated with this code:
```python
with sentry_sdk.start_transaction(None, op="Test Transaction", description = "My description", name = "My name") as tr:
    with tr.start_child() as span:
        span.set_data("mydata", "myvalue")
```

<img width="323" alt="image" src="https://user-images.githubusercontent.com/22409414/182804306-377bab62-eec6-47f4-be1c-7303882e7011.png">

### Actual Result

<img width="264" alt="image" src="https://user-images.githubusercontent.com/22409414/182803969-e2bcf9d3-39d2-48f9-91b3-7947e9d1defe.png">

**Comment by sl0thentr0py** [comment]
hi @andrewchernyh, `set_data` is always supposed to be called on the `Span` object, so please use it like you did in your second example.

The `Transaction` API is a bit confusing because it inherits from `Span`. We want to clean this up eventually, but it'll be in a major with breaking changes at some point in the future.

**Comment by andrewchernyh** [comment]
Hi @sl0thentr0py. Thanks for clear response. Main reason of this issue is confusing behavior of Transaction, because it implements `Span`, but not working as not `Span`.

I'm using trick as I wrote on second example, and in short requests, that has no spans in deps, but can be cpu-intensive it looks in distributed trace like

Transaction (name=MyApiRequest)
 - Span (name=MyApiRequest)
    - Span Data

It confuses users, because they should tap on Span to see data.

And the second, when you have many small services it requires you to expose x2 (transaction+child span) spans  only for collecting 1 data field

**Comment by sl0thentr0py** [comment]
Yes I agree with you it's confusing and we'll clean up the Transaction API in the next major. 

Transactions are just containers of a Span tree so those semantics are correct and how we want them to be. This is a fairly general data structure so yes if you need just one span, you still have to make a transaction and nest a span within it.

I'm closing this issue, I've noted your feedback and we will make this less confusing in the future.
