### ISSUE TITLE
Incorrect attribute check

### ISSUE THREAD

**Issue by decaz** [getsentry/sentry-python#1561]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.9.4

### Steps to Reproduce

I guess it's incorrect attribute name is checking here:
https://github.com/getsentry/sentry-python/blob/8588dbeb023a124c6f8c35b66391a7d8caa8bf35/sentry_sdk/integrations/starlette.py#L149

### Expected Result

sta**t**us_code

### Actual Result

staus_code

**Comment by sl0thentr0py** [comment]
@decaz pls explain what you mean by 'incorrect'

**Comment by vasa-chi** [comment]
I presume he means the typo in `hasattr(exp, "staus_code")`, which should be `hasattr(exp, "status_code")`

**Comment by sl0thentr0py** [comment]
oh indeed, I cannot read, thank you! :)
