### ISSUE TITLE
Cant complete my Sentry Setup on AWS LAMBDA

### ISSUE THREAD

**Issue by bgreatfit** [getsentry/sentry-python#1572]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.9.5

### Steps to Reproduce

<img width="975" alt="image" src="https://user-images.githubusercontent.com/10434677/185252838-f7f05244-cd3b-4fa1-a2b4-06260df2df7a.png">

### Expected Result

Complete Sentry Setup for AWS Lambda Success

### Actual Result

Complete Sentry Setup for AWS Lambda Failed

**Comment by bgreatfit** [comment]
I followed this link https://docs.sentry.io/product/integrations/cloud-monitoring/aws-lambda/?_ga=2.104562944.1221919416.1660773054-43494044.1656590232&_gac=1.27710158.1660566721.Cj0KCQjw3eeXBhD7ARIsAHjssr98agr78-9oTLOrd6dBALug489_noht_14KTuI0tgBm-3r0BOemsysaAuYdEALw_wcB

**Comment by sl0thentr0py** [comment]
@bgreatfit I tried to find your errors in our Sentry, but wasn't able to. 
I'd need your organization slug for more investigation, but you can also open a support ticket if you don't want to disclose that here in public,

**Comment by bgreatfit** [comment]
@sl0thentr0py i guess this is what you mean "reoteyear "

**Comment by sl0thentr0py** [comment]
ok I see the actual error now, unfortunately this is a known limitation, your function + our layer's size is exceeding the allowed maximum AWS size.
```
InvalidParameterValueException

An error occurred (InvalidParameterValueException) when calling the UpdateFunctionConfiguration operation: Function code combined with layers exceeds the maximum allowed size of 262144000 bytes. The actual size is 275026992 bytes.
```

Do you have a lot of code in your function? Lambda functions are generally meant to be very small.

**Comment by bgreatfit** [comment]
the code in  functions are relatively small, for the layers not sure about this because we use thirdparty layers. is there another way of including sentry

**Comment by sl0thentr0py** [comment]
you can also just use it the traditional way by installing `sentry-sdk` and calling `init`
https://docs.sentry.io/platforms/python/guides/aws-lambda/

I'm closing this since this is a known limitation on the AWS side and there's not really much we can do except reducing our layer's size in the future (which is on the roadmap).
