### ISSUE TITLE
sentry-python Scope/Namespace limit

### ISSUE THREAD

**Issue by drummerboy2543** [getsentry/sentry-python#1577]
### Problem Statement

Hello, first off I want to say I really enjoy using sentry, it has made my life a lot easier to manage errors in other sw projects I have used.

I am working on a couple of python-pip packages that I would like to use sentry for any unhandled exceptions when it is used in the field.  That way if there are any edge cases I am missing that could cause exceptions will get reported directly to the sentry and have all the stack traces available.  That way I can make the system perform better.

However, this is a problem since it handles exceptions that occur globally from any python script using my pip package. This causes sentry to give me errors that are made via other people's code/development when using my package. Which makes it harder for me to determine issues involving my pip package specifically.

Currently, the only way I can think of stopping this from happening is to make a `before_send` function in the `init` and in that function get a stack trace and reverse engineer where the exception came from. The results of this are mixed and unwieldy since my package has a lot of files. 

### Solution Brainstorm

Ideally, it would be nice to have a way for the sentry-python SDK to have a scope or namespace feature, that can limit the scope of what it covers from an exception standpoint in the initialization. That way I can simply say only go to my pip package and not further. I imagine this can be good for modularity's sake as well. Since bigger teams can have different code bases and want to manage errors and exceptions/using sentry in different ways. Instead of having one sentry SDK have global scope.

If there is a tool or process to solve this, feel free to let me know! Looking at the github issues, and sentry docs/forums I could not find anything involving using sentry on specific sections of the codebase (in my case a python package)

Let me know if you have any questions and what I can clarify. 

Thanks again for looking I really appreciate it!

**Comment by sl0thentr0py** [comment]
hi @drummerboy2543, this is not a use case the SDK is principally designed for, but it comes up often. What we recommend is a [multi-hub setup](https://github.com/getsentry/sentry-python/discussions/1521), with your library using it's own `Hub/Client` pair. We can continue this thread on that discussion, closing this issue.
