### ISSUE TITLE
exiting `with push_scope()` fails if new client is bound

### ISSUE THREAD

**Issue by FelixLC** [getsentry/sentry-python#159]
Similarly to https://github.com/getsentry/sentry-python/issues/147, we started to get `popped wrong scope` assertion errors in a Falcon app sending jobs to `redis-queue` after updating to sentry-sdk from raven

Our `Python 3.5.2` stack:

```
rq==0.12.0
redis==2.10.6
sentry-sdk==0.5.2
```

The worker is initialized like this:

```python
    listen = [l.value for l in constants.QueueList]
    conn = redis.from_url(os.environ.get(
        'REDIS_WORKER', 'redis://redis_worker:6379'))

    sentry_sdk.init(sentry_key,
                    environment=environment,
                    release=release,
                    integrations=[RqIntegration()])
    with Connection(conn):
        worker = Worker(list(map(Queue, listen)))
        worker.work(logging_level='WARNING')
```

If it's the same kind of issue, would a change from:

```python
            with hub.push_scope() as scope:
                scope.add_event_processor(_make_event_processor(weakref.ref(job)))
                rv = old_perform_job(self, job, *args, **kwargs)
```

to

```python
            with Hub(hub) as hub:
                with hub.configure_scope() as scope:
                    scope.add_event_processor(_make_event_processor(weakref.ref(job)))
                    rv = old_perform_job(self, job, *args, **kwargs)
```

in https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/rq.py#L28 do the job ?

If not, I'd be happy to provide more info

**Comment by untitaker** [comment]
Hi, are you using the regular worker class? If yes I don't understand how this can happen conceptually, as each job runs in its own process as far as I understand. Could you give me example code that defines a job and executes it?

**Comment by untitaker** [comment]
Hi, are you using the regular worker class? If yes I don't understand how this can happen conceptually, as each job runs in its own process as far as I understand. Could you give me example code that defines a job and executes it?

**Comment by FelixLC** [comment]
@untitaker I am using the standard worker, yes:

`from rq import Connection, Queue, Worker`

And defining a job with the `job` decorator:

```python
from rq.decorators import job

@job(constants.CONTEXT,
     connection=redis.from_url(constants.REDIS_WORKER_URL))
def patch_page_count_content_string(meta: CommunicationRequestMeta):
    '''Perform actual patch on API'''
    page_count_patch = meta.add_page_count_extension()
    content_string_patch = meta.add_content_string()

    # async calls: might be that ?
    pool = ThreadPoolExecutor(2)
    futures = []
    if page_count_patch:
        futures.append(pool.submit(
            meta.doc_ref_target.patch, data=page_count_patch))
        meta.log.warning(
            'Patching page count {}'.format(
                meta.com_req_target.url))
    if content_string_patch:
        futures.append(pool.submit(
            meta.com_req_target.patch, data=content_string_patch))

    # wait for async calls to be executed
    wait(futures)
```

Then later:

```
patch_page_count_content_string.delay(meta)
```

**Comment by untitaker** [comment]
Yeah, probably the thread pool inside of your job does something. I'll test, thanks

**Comment by FelixLC** [comment]
@untitaker Update: I can confirm that all my calls are getting through with this small fix. I'll start a PR. We should add tests maybe ? I don't know exactly how we can simulate that

**Comment by untitaker** [comment]
@FelixLC if you claim it happens without threadpools (and generally without all the async stuff) then I am afraid we need to dig a little deeper here. We only used `Hub` in the sanic integration and the issue you linked directly because we understood what it fixed, but here it's completely unclear. We do have tests for RQ in general.

**Comment by untitaker** [comment]
@FelixLC can you reproduce this with an empty job or something trivial? I tried this with the following setup and I can't reproduce:

```python

import requests


def divide(x, y):
    return x / y


from redis import Redis
from rq import Queue

q = Queue(connection=Redis())

# the following in a shell:

while True:
    q.enqueue(divide, 1, 1)
```

I spawn my workers like this:

```rq worker -c settings```

**Comment by untitaker** [comment]
Also, could you clarify this part?

>we started to get popped wrong scope assertion errors in a Falcon app sending jobs 

Does:

1. Your job fail with the AssertionError
2. Your app fail with AssertionError (in that case the code of the app would be relevant, not sure how it's related to RQ)

**Comment by FelixLC** [comment]
Hello @untitaker !
I'll try and see if this happens to me with a divide job this afternoon.

For your second comment: The worker fails with an assertion error - which is initialized as an app with the same image as my base app, save for the entrypoint which is replaced by `python worker.py` (the content of which you can find just above). Note that 1/ the job actually get through from what I saw, and 2/ The error pops up in Sentry:

![image 2018-10-31 at 10 33 28 am](https://user-images.githubusercontent.com/4803830/47779090-94b9ba00-dcf8-11e8-831f-66503ae8d971.png)

I was in a rush with a production bug yesterday and seeing this small change fixed it I went for it and deployed it in production on a fork - all the job are getting through and I checked with a sample error it's getting to Sentry. But I feel your concerned and am happy to help with understanding why it fixes it.

**Comment by FelixLC** [comment]
@untitaker Ok I've done some tests. It seems to happen only when I use a `Worker` class and not the `rq worker` cli.

The following setup gives an error:

```python
# worker.py
import redis
import sentry_sdk
from rq import Connection, Queue, Worker
from sentry_sdk.integrations.rq import RqIntegration

listen = ['low', 'high']
conn = redis.from_url('redis://redis_worker:6379')

sentry_sdk.init(sentry_key, integrations=[RqIntegration()])

with Connection(conn):
    worker = Worker(list(map(Queue, listen)))
    worker.work(logging_level='WARNING')
                    integrations=[RqIntegration()])
    with Connection(conn):
        worker = Worker(list(map(Queue, listen)))
        worker.work(logging_level='WARNING')

# job.py
q = Queue('redis://redis_worker:6379')

def try_job(x, y):
    get_logger(__name__).warning('Trying job')
    return x/y

q.enqueue(try_job, 1, 1)
```

with docker-compose along the lines of:

```
yml
services:
  web:
    command: gunicorn app.py
  worker:
    command: python worker.py
```

when the following doesn't:

```python
# worker.py

import sentry_sdk
sentry_sdk.init(sentry_key, integrations=[RqIntegration()])

# job.py
q = Queue('redis://redis_worker:6379')

def try_job(x, y):
    get_logger(__name__).warning('Trying job')
    return x/y

q.enqueue(try_job, 1, 1) # or decorating try_job with rq's @job decorator and calling .delay
```

with docker-compose along the lines of:

```
yml
services:
  web:
    command: gunicorn app.py
  worker:
    command: rq worker --url redis://redis_worker:6379 -c worker
```

**Comment by untitaker** [comment]
I'm sorry, I can't reproduce this with your setup at all. I copypasted your code into a new folder, with the following modification: The way you instantiate `Queue` in `job.py` does not seem to work at all. I had to do `Queue(conn=connection)` where connection is the same `redis.from_url(..)` you did in worker.

Apart from that, the test does the same using fakeredis. We test both `SimpleWorker` and `Worker`.

It could be possible that you push a scope in your job without ever popping it, but then I am not sure how using `Hub` would even solve that, or why it happens with a job that simply divides two numbers. I'm not sure how that `get_logger` you use in the job looks like though. Perhaps it's doing something weird?

Could you patch the SDK to print `Hub.current._stack` before and after the job (i.e. in our monkeypatched version of `perform_job`, inside of the `with push_scope()`)?

**Comment by FelixLC** [comment]
@untitaker my bad, when simplifying my copy paste I messed up the queue initialisation, I was of course doing the same as you. I'll try to isolate everything in a new repo

**Comment by FelixLC** [comment]
@untitaker I tried starting from scratch with python script + redis and then with a docker compose and an app and a sibling worker linked to a redis_worker, and it works perfectly fine ... Even with thread pools. I am sorry something must doing some weird async stuff in my full fledged gunicorn app. `get_logger` is just a wrapper around python logging module. I'll try patching the SDK to get more informations. If we get nowhere we can close this issue. I'll fall back on using `rq worker` entrypoints although i would like to be able to preload some libs to speed up jobs

**Comment by untitaker** [comment]
Cool. Out of curiosity I'd be interested what exactly you do with gunicorn
in the worker that breaks it. Gevent monkeypatches?

**Comment by FelixLC** [comment]
Well gunicorn full fledged was just an expression to say that in my app I am using the same image for the worker (for simplicity - as I don't have to bother with ensuring that all the utils and stuff are available in the worker) and the app but it is not related with our issue. Some import somewhere in my app must be the culprit. If I ever find something I'll keep you posted but for now I'll close the issue

**Comment by FelixLC** [comment]
@untitaker => I finally found the culprit by peeling the layers one by one. Thought it might be useful as the error didn't point directly in that direction.

When unpickling the job, inside the worker runtime where `sentry-sdk` had already been inited, the call to get logger loaded my logging module where I happened to place the `sentry-sdk.init` used for the main app. I just had to move that part so it's not called twice.

You might want to add a line to prevent users from instanciating twice either in the code or juste a warning in the document [near the line](https://docs.sentry.io/platforms/python/rq/):

```Make sure that the code above is loaded on worker startup. E.g. put it in a settings.py and run the worker with rq worker -c settings.```

This line made me add a specific init for the worker. Anyway, thanks for your investigation.

**Comment by untitaker** [comment]
Amazing. I am sure we can do something that prevents this from being a problem

**Comment by untitaker** [comment]
Do you have a simple example app which exhibits the problem?

**Comment by untitaker** [comment]
Nvm I could reproduce.

@FelixLC I will add a warning to the debug logger of the SDK. I am not sure what I should adjust in the docs. Did that text imply to you that you should init the sdk twice?

**Comment by FelixLC** [comment]
Great ! I had prepared a small repo for you. Actually this line made me add an init in worker.py and I didn't give much thought to the other init hidden in the startup code. If you put a warning it's all right I think !

**Comment by untitaker** [comment]
Cool, I'll just release the bugfix then.
