### ISSUE TITLE
Transaction name not set for FastApi in sentry-python 1.9.7

### ISSUE THREAD

**Issue by sturaipo** [getsentry/sentry-python#1599]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.9.7

### Steps to Reproduce

Sample code to reproduce the issue:

```python
from datetime import datetime

import sentry_sdk
from fastapi import FastAPI
from sentry_sdk.integrations.asgi import SentryAsgiMiddleware

app = FastAPI()


SENTRY_DSN = "<redacted>"


sentry_sdk.init(
    dsn=SENTRY_DSN,
    environment="dev",
    traces_sample_rate=1,
    release=f"test-transaction-name:0.01",
)


@app.get("/{par}")
async def root(par: str | None):
    with sentry_sdk.configure_scope() as scope:
        scope.set_transaction_name(f"test sentry transaction {par}")
        return {"message": "Hello World", "time": str(datetime.utcnow())}


app = SentryAsgiMiddleware(app)

```

Then call the api with curl:

```
$ curl http://127.0.0.1:8000/test1                                                                                                                             [6:48:48]
{"message":"Hello World","time":"2022-09-05 10:53:08.987063"}%

$ curl http://127.0.0.1:8000/test1                                                                                                                             [6:53:08]
{"message":"Hello World","time":"2022-09-05 10:53:10.981846"}%

$ curl http://127.0.0.1:8000/test2                                                                                                                             [6:53:10]
{"message":"Hello World","time":"2022-09-05 10:53:12.449257"}%

```

### Expected Result

Transaction are stored in sentry with the expected transaction names:
- `test sentry transaction test1`
- `test sentry transaction test2`

### Actual Result

Sentry stores these transactions with the default name:

![image](https://user-images.githubusercontent.com/11156922/188433287-6ed97912-2d5c-44cc-964b-1564c5f08316.png)

The issue affects sentry-python 1.9.7
If I downgrade to sentry-python 1.9.5 the I get the expected behavior

**Comment by antonpirker** [comment]
Hello @sturaipo ! Could you try this with the newest SDK release (1.9.10) to see if it still does not work? Thanks!

**Comment by polina-popova** [comment]
Hi,
Looks like I have quite similar issue on sentry-sdk 1.10.1 (and on the 1.11.1):

I have manually instrumented traces_sampler counted on transaction name in sampling context. At some point with sentry-sdk version upgrade, it stopped work - there is always "generic ASGI request" in transaction name. But at the performance page, transaction has a proper name.

How we initiate sentry FastAPI integration:
```
sentry_sdk.init(
    dsn=SENTRY_DSN,
    environment="dev",
    traces_sampler=sentry_traces_sampler,
    integrations=[
        starlette.StarletteIntegration(transaction_style="endpoint"),
        fastapi.FastApiIntegration(transaction_style="endpoint"),`
    ]
)
```

The traces_sampler function:
```
def sentry_traces_sampler(sampling_context):
    transaction_sampling_mapper = {
        "app.api.api_v1.routers.users.some_name": 0.1,
        "app.api.api_v1.routers.messages.some_name_2": 0.5,
    }
    return transaction_sampling_mapper.get(
        sampling_context["transaction_context"]["name"], 1.0
    )
```

Should I make a separate issue for this, or it is ok to discuss it here?

**Comment by jswan106** [comment]
Hello,
Is there any update on this? 
I am having the same issue still, and I am currently on sentry-sdk release 1.14.0

**Comment by ripperdoc** [comment]
I have a related problem, that requests in FastAPI that get handled by a middleware, such as 404s or OPTIONS for CORS, are reported as "generic ASGI request" for transaction name. It seems like there should be an easy fix - all of these requests have enough information to name them at least a bit more specific, such as by the name of the middleware, the URI + method, or similar.

**Comment by antonpirker** [comment]
There are multiple issues now here:

a) hub.configure_scope() - scope.set_transaction_name() does not work. (has "generic ASGI request")
b) traces_sampler receives always "generic ASGI request" as transaction name.
c) FastAPI requests handled in middleware (ex 404, options for CORS) are always "generic ASGI request"

Will look at them one by one.

**Comment by antonpirker** [comment]
a) @sturaipo 

One thing that jumped into my eye was how you setup sentry in your app. It should be before you initialize your FastAPI app (and you do not need to set the SentryASGIMiddleware by hand, the FastAPI integration will do this under the hood. So it should look like this:

```python
from datetime import datetime

import sentry_sdk
from fastapi import FastAPI

SENTRY_DSN = "<redacted>"

sentry_sdk.init(
    dsn=SENTRY_DSN,
    environment="dev",
    traces_sample_rate=1,
    release=f"test-transaction-name:0.01",
)

app = FastAPI()

@app.get("/{par}")
async def root(par: str | None):
    with sentry_sdk.configure_scope() as scope:
        scope.set_transaction_name(f"test sentry transaction {par}")
        return {"message": "Hello World", "time": str(datetime.utcnow())}
```

See also the documentation: https://docs.sentry.io/platforms/python/guides/fastapi/
With this setup it works for me like expected. Can you update to the lastest Sentry SDK version and try again with this setup. 
Also keep in mind that it can take around 30 seconds for the new transaction show up in Sentry. (at least on the Saas version, not sure about self-hosted)

**Comment by antonpirker** [comment]
c) @ripperdoc 

Could you also please create a separate issue for this?

**Comment by antonpirker** [comment]
just a quick update, I will AFK until mid of next week, so this will wait until then.

**Comment by antonpirker** [comment]
Created some new issues for handling all the cases:
b) https://github.com/getsentry/sentry-python/issues/2262
c) https://github.com/getsentry/sentry-python/issues/2263

For a) I think this is due to wrong usage of the SDK, so I will close this issue.

**Comment by antonpirker** [comment]
@polina-popova I created a new issue for your problem: https://github.com/getsentry/sentry-python/issues/2262

You said above that it stopped working for you at some point, could you comment in the other issue in what SDK version it stopped working for you? Would be very helpful!
