### ISSUE TITLE
Tracing: expose HTTP response in `sampling_context`

### ISSUE THREAD

**Issue by guidoiaquinti** [getsentry/sentry-python#1615]
### Problem Statement

Afaik there's currently no way to [filter out transaction events](https://docs.sentry.io/platforms/python/configuration/filtering/) of HTTP requests by status code (e.g. HTTP 404) using the `traces_sampler` configuration option. `sampling_context` currently exposes the request but not the response context.

### Solution Brainstorm

There's a way to filter out transaction events by HTTP status code.

**Comment by antonpirker** [comment]
You can manually call `start_transaction` and set a `custom_sampling_context`.  (Like in our AWS Lambda integration: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/aws_lambda.py#L147-L153)

The `custom_sampling_context` is available to the `traces_sampler`. So if you put your status code (or the whole response) in the `custom_sampling_context` you can filter by it in `traces_sampler`.

Does this solve your issue?

**Comment by guidoiaquinti** [comment]
Hey @antonpirker thank you for the additional context! 🙌 

I can definitely make it work but I was wondering if this is something other users might benefit as well. If yes, we could probably make this context available as default instead of having to manually do the override. 

What do you think?

**Comment by sl0thentr0py** [comment]
hi @guidoiaquinti this is not really possible in a normal WSGI/ASGI integration due to lifecycle issues.
We start and sample a transaction at the beginning of the request flow and the response is available at the end after the sampling is already done.
