### ISSUE TITLE
Add tracePropagationTargets option

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-python#1621]
### Problem Statement

There is no mechanism to control where tracing is or is not propagated to. Leading to possibly sending useless tracing headers and contextual data to endpoints where it is not relevant. 

### Solution Brainstorm

Add the tracePropagationTargets option.

https://develop.sentry.dev/sdk/performance/#tracepropagationtargets

**Comment by sentrivana** [comment]
Added in https://github.com/getsentry/sentry-python/pull/1916
