### ISSUE TITLE
Python SDK incorrectly claims that environment is not set by default

### ISSUE THREAD

**Issue by lauredon** [getsentry/sentry-python#1625]
### Problem Statement

The [documentation](https://docs.sentry.io/platforms/python/configuration/options/#environment) claims that the `environment` is not set by default, but since [0.20.0](https://github.com/getsentry/sentry-python/releases/tag/0.20.0), the default value has been `production`.

### Solution Brainstorm

For the Python SDK and possibly other applicable platforms, change the statement from
```
This string is freeform and not set by default.
```

to:
```
This string is freeform and set to the value `production` by default.
```

**Comment by antonpirker** [comment]
Hey @lauredon 

Thanks for bringing this up! I will see If I can change the documentation this week.
