### ISSUE TITLE
Support usage of fastuuid

### ISSUE THREAD

**Issue by kasium** [getsentry/sentry-python#1629]
### Problem Statement

I work in an application where performance in critical. We found out, that we can improve the speed by using `fastuuid` instead of the stdlibs `uuid`. 
Sentry doesn't allow use easily to change that, so a monkeypatch is needed

```py
sentry_sdk.tracing.uuid = fastuuid
sentry_sdk.client.uuid = fastuuid
```

### Solution Brainstorm

1) Allow users to specify the uuid module/function somehow
2) Support fastuuid natively in sentry

**Comment by antonpirker** [comment]
This is also related to: https://github.com/getsentry/sentry-python/pull/784

**Comment by antonpirker** [comment]
We want to keep our dependencies at a minimum and we also support Python 3.6+ (and fastuuid only supports 3.7+) so we sill not implement this.
