### ISSUE TITLE
Django Signals integration breaks on partial objects for python <3.10

### ISSUE THREAD

**Issue by Agalin** [getsentry/sentry-python#1640]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.9.9

### Steps to Reproduce

1. Use python older than 3.10.
2. Register a partial function as a signal handler.

### Expected Result

Signal is traced correctly.

### Actual Result

Exception is raised from `_get_receiver_name` function as `partial` objects don't have `__module__` before python 3.10 (and even there it's undocumented from what I can see).

It fails in our tests where we don't even register any signals so either Django itself or some kind of integration (Sentry?) registers such signals by default.

The whole signals integration is missing a `capture_internal_exceptions` context too I believe.

**Comment by antonpirker** [comment]
Hello @Agalin !

Thanks for writing in!

I have now tried to reproduce this. 

I created a partial signal handler from my existing handler:
![Screenshot 2022-09-27 at 10 19 05](https://user-images.githubusercontent.com/202325/192473043-fe3929f4-c67a-4b01-8bd3-f676e3b21ae7.png)

Connected the signal like usually:
![Screenshot 2022-09-27 at 10 19 44](https://user-images.githubusercontent.com/202325/192473147-b82df8ba-b65e-49b7-9677-6d126de34363.png)

And then refreshed the page a couple of times and the partial signal handler is showing up in performance:
![Screenshot 2022-09-27 at 10 17 57](https://user-images.githubusercontent.com/202325/192473335-8db3b61b-e85d-4d86-9ce2-4916384dc6ce.png)

I tried this using Python 3.9.11, 3.8.13 and 3.7.12 and I never got an exception. 
Could you supply me with a mini project where I could reproduce this problem?

**Comment by Agalin** [comment]
Interesting. As said earlier - we don't use signals ourselves so I need to verify where does it come from to reproduce (possible candidate besides Sentry is pytest-django). Stacktrace seems to suggest Django's test client being at fault:

<details>
<summary>Stacktrace</summary>

```
/home/application/.local/lib/python3.7/site-packages/django/test/client.py:751: in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
/home/application/.local/lib/python3.7/site-packages/django/test/client.py:408: in post
    secure=secure, **extra)
/home/application/.local/lib/python3.7/site-packages/django/test/client.py:473: in generic
    return self.request(**r)
/home/application/.local/lib/python3.7/site-packages/django/test/client.py:714: in request
    response = self.handler(environ)
/home/application/.local/lib/python3.7/site-packages/django/test/client.py:145: in __call__
    response = self.get_response(request)
/home/application/.local/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py:409: in sentry_patched_get_response
    rv = old_get_response(self, request)
/home/application/.local/lib/python3.7/site-packages/django/core/handlers/base.py:136: in get_response
    request=request,
/home/application/.local/lib/python3.7/site-packages/django/utils/log.py:230: in log_response
    exc_info=exc_info,
/usr/local/lib/python3.7/logging/__init__.py:1407: in error
    self._log(ERROR, msg, args, **kwargs)
/usr/local/lib/python3.7/logging/__init__.py:1514: in _log
    self.handle(record)
/usr/local/lib/python3.7/logging/__init__.py:1524: in handle
    self.callHandlers(record)
/home/application/.local/lib/python3.7/site-packages/sentry_sdk/integrations/logging.py:96: in sentry_patched_callhandlers
    return old_callhandlers(self, record)
/usr/local/lib/python3.7/logging/__init__.py:1586: in callHandlers
    hdlr.handle(record)
/usr/local/lib/python3.7/logging/__init__.py:894: in handle
    self.emit(record)
/home/application/.local/lib/python3.7/site-packages/django/utils/log.py:120: in emit
    message = "%s\n\n%s" % (self.format(no_exc_record), reporter.get_traceback_text())
/home/application/.local/lib/python3.7/site-packages/django/views/debug.py:353: in get_traceback_text
    return t.render(c)
/home/application/.local/lib/python3.7/site-packages/django/template/base.py:170: in render
    return self._render(context)
/home/application/.local/lib/python3.7/site-packages/django/test/utils.py:99: in instrumented_test_render
    template_rendered.send(sender=self, template=self, context=context)
/home/application/.local/lib/python3.7/site-packages/django/dispatch/dispatcher.py:182: in send
    for receiver in self._live_receivers(sender)
/home/application/.local/lib/python3.7/site-packages/django/dispatch/dispatcher.py:182: in <listcomp>
    for receiver in self._live_receivers(sender)
/home/application/.local/lib/python3.7/site-packages/sentry_sdk/integrations/django/signals_handlers.py:40: in wrapper
    description=_get_receiver_name(receiver),
```
</details>

**Comment by Agalin** [comment]
Oh. Didn't mention that earlier: it's Django 3.2.15 with pytest-django 4.5.2 - it may be relevant.

**Comment by antonpirker** [comment]
Thanks for the update. I could now reproduce the error and have created a fix.

**Comment by antonpirker** [comment]
Finally, all the tests pass @sl0thentr0py could you please re-review? (The name generation function is now kind of complicated, but it generates nice names for python 2 and up and also for partials and normal functions)
