### ISSUE TITLE
Unified naming of span "op"s

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#1643]
### Problem Statement

For performance issues it is vital to have identical naming for span `op` parameter across SDKs. For this an audit was done and some of the span ops need to be renamed.

### Solution Brainstorm

Make sure the span `op`s are name like defined here: 
https://github.com/getsentry/develop/issues/693#issuecomment-1259423033

**Comment by AbhiPrasad** [comment]
Here is the list:
| SDK             | Old Operation                             | New Operation                                  | Link                                                                                                                                                                  | PR                                                         |
| --------------- | ----------------------------------------- | ---------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| Python          |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | serverless.function                       | faas.aws.lambda                                | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/aws_lambda.py#L143                                   |                                                            |
|                 | aws.request                               | http.client                                    | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/boto3.py#L65                                         |                                                            |
|                 | aws.request.stream                        | http.client.stream                             | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/boto3.py#L95                                         |                                                            |
|                 | celery.submit                             | queue.submit.celery                            | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/celery.py#L106                                       |                                                            |
|                 | celery.task                               | queue.task.celery                              | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/celery.py#L159                                       |                                                            |
|                 | http                                      | http.client                                    | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/httpx.py#L44                                         |                                                            |
|                 | redis                                     | db.redis                                       | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/redis.py#L32                                         |                                                            |
|                 | rq.task                                   | queue.task.rq                                  | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/rq.py#L64                                            |                                                            |
|                 | starlette.middleware                      | middleware.starlette                           | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/starlette.py#L94                                     |                                                            |
|                 | django.view                               | view.django                                    | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/django/asgi.py#L92                                   |                                                            |
|                 | django.middleware                         | middleware.django                              | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/django/middleware.py#L91                             |                                                            |
|                 | django.template.render                    | template.render                                | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/django/templates.py#L69                              |                                                            |

**Comment by antonpirker** [comment]
One item was missing:
| SDK             | Old Operation                             | New Operation                                  | Link                                                                                                                                                                  | PR                                                         |
| --------------- | ----------------------------------------- | ---------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| Python          |                                           |                                                |                                                                                                                                                                       |                                                            |
|                 | serverless.function                       | function.gcp                                | https://github.com/getsentry/sentry-python/blob/033b236e04a0a74b6d02fb955bed729aef9e2261/sentry_sdk/integrations/gcp.py#L85                                 |                                                            |
