### ISSUE TITLE
AWS Lambda with Python 3.9 not sending error

### ISSUE THREAD

**Issue by j-adamczyk** [getsentry/sentry-python#1645]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.9.9

### Steps to Reproduce

I deployed the following code to AWS Lambda to test the integration:
```python
import sentry_sdk
from sentry_sdk.integrations.aws_lambda import AwsLambdaIntegration

sentry_sdk.init(
    dsn=<MY DSN>,
    environment="dev",
    integrations=[AwsLambdaIntegration()],
    traces_sample_rate=1.0,
)

raise ValueError()
```

I am using Python 3.9. I allow all outbound TCP traffic.

### Expected Result

I expected Sentry to get the error.

### Actual Result

Sentry received nothing from Lambda, but I get logs in CloudWatch normally. It does work from my laptop though, with exactly the same code.

CloudWatch logs:
![Screenshot from 2022-09-28 16-14-04](https://user-images.githubusercontent.com/50807718/192803730-db0f26a1-381f-4e9f-8f20-2c3774b0b9a8.png)

CloudWatch logs with `debug=True`:
![Screenshot from 2022-09-28 16-18-50](https://user-images.githubusercontent.com/50807718/192803738-88700475-302e-40b9-a14b-fd14190fdeb3.png)

Setting `shutdown_timeout=20` (based on [this](https://github.com/getsentry/sentry-python/issues/549)) did not change anything. I also tried 300, and adding try/finally with long sleep, and none of it worked.

**Comment by sl0thentr0py** [comment]
@j-adamczyk not sure what is going on, the outgoing http request to your self-hosted sentry is there in the logs. There's some atexit problem but that looks unrelated. 

Maybe there's something wrong with the network setup between your AWS/sentry?

**Comment by j-adamczyk** [comment]
Yeah, it turned out it was the networking, VPC needs to have NAT Gateway or Internet Gateway in order for this to work, or Sentry has to be inside the VPC.
