### ISSUE TITLE
Django Integration: AttributeError: 'functools.partial' object has no attribute '__module__'

### ISSUE THREAD

**Issue by mpibpc-mroose** [getsentry/sentry-python#1648]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.9.9

### Steps to Reproduce

Pretty unsure what exactly is going on. I run my test suite, which itself does not fail at all. For one particular test I get an exception related to sentry_sdk- When downgrading to 1.9.8 the error goes away.

When looking into the source code the error is related to a newly added code in the latest release.

### Expected Result

No exception should be raised

### Actual Result

The exception raised is:
```
File "D:\Local_Development\microscopy_image_database\venv-mdb39\lib\site-packages\sentry_sdk\integrations\django\signals_handlers.py", line 40, in wrapper
    description=_get_receiver_name(receiver),
  File "D:\Local_Development\microscopy_image_database\venv-mdb39\lib\site-packages\sentry_sdk\integrations\django\signals_handlers.py", line 24, in _get_receiver_name
    name = receiver.__module__ + "."
AttributeError: 'functools.partial' object has no attribute '__module__'
```

**Comment by Orangensaft** [comment]
Got the same issue. Just updated from 1.9.8 to 1.9.9 and a bunch of tests for our django project failed the same way.
Downgrading fixed it aswell.
