### ISSUE TITLE
Set correct parent span in async environment

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#1664]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.9.10

### Steps to Reproduce

* Have a FastAPI app
* Have a FastAPI middleware like this one: https://github.com/getsentry/demo-app-django-react/blob/main/backend/fastapi/main.py#L80-L101
* Do something in this middleware that creates a span (like the redis call in the span
* Reload an endpoint that uses this middleware
* Go to the "Performance" section of sentry.io and look at the event
* You will see this:
    ![Screenshot 2022-10-05 at 08 55 07](https://user-images.githubusercontent.com/202325/194105827-d120df0f-cddf-4731-83a5-a2fe03f5a642.png)

### Expected Result

The redis span should be under the `CounterMiddleware`.

### Actual Result

The redis span is under the `AsyncExitStackMiddleware`

**Comment by antonpirker** [comment]
This is also related with this amazing issue: https://github.com/getsentry/sentry-python/issues/1187

**Comment by sl0thentr0py** [comment]
also https://github.com/getsentry/sentry-python/issues/772#issuecomment-1270020139
