### ISSUE TITLE
Cannot make Sentry work with Google Cloud Function (python 3.9)

### ISSUE THREAD

**Issue by NicolasMarlier** [getsentry/sentry-python#1666]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.9.10

### Steps to Reproduce

```
# main.py
import sentry_sdk
from sentry_sdk.integrations.gcp import GcpIntegration

sentry_sdk.init(
    dsn="https://***@***.ingest.sentry.io/***",
    integrations=[GcpIntegration()]
)

def main(request):
    return 1 / 0
```

```
# requirements.txt
sentry-sdk==1.9.10
```

```
# deploy.sh
gcloud functions deploy test_gcf_sentry \
--trigger-http \
--runtime=python39 \
--entry-point=main \
--memory=1GB \
--security-level=secure-always \
--region=europe-west1
```

### Expected Result

Exception should be ingested in Sentry interface

### Actual Result

Exception does not appear in Sentry interface

**Comment by NicolasMarlier** [comment]
link to stackoverflow: https://stackoverflow.com/questions/73970481/cannot-make-sentry-work-with-google-cloud-function-python-3-9

**Comment by NicolasMarlier** [comment]
(working fine with python 3.7)

**Comment by rushilsrivastava** [comment]
Sentry should work to some certain capacity in `3.9`. There is a [warning in the code](https://github.com/getsentry/sentry-python/blob/7569b5eca871a400405cffb5cba224a4fdf43bd2/sentry_sdk/integrations/gcp.py#L136-L138) that the `GcpIntegration` only supports `3.7` at the moment, although, it would be nice to have this constraint be more prominently listed on the [Sentry documentation](https://docs.sentry.io/platforms/python/guides/gcp-functions/). 

Additionally, it would also be useful to note why this limitation exists, and a timeline for when other versions will be supported.

**Comment by sentrivana** [comment]
Hey folks, as stated [in the docs](https://docs.sentry.io/platforms/python/integrations/gcp-functions/), we currently only support 3.7 for Google Cloud Functions. We have support for newer runtimes in our backlog and will track the progress in https://github.com/getsentry/sentry-python/issues/1667 once we get to it, but please note that this will take some time and we can't give you an estimate at the moment.

**Comment by rushilsrivastava** [comment]
> Hey folks, as stated [in the docs](https://docs.sentry.io/platforms/python/integrations/gcp-functions/), we currently only support 3.7 for Google Cloud Functions. We have support for newer runtimes in our backlog and will track the progress in #1667 once we get to it, but please note that this will take some time and we can't give you an estimate at the moment.

Python 3.7 has passed its end of life on June 27, 2023. Its quite unfortunate that this still doesn't have an appropriate workaround. From my suggestions previously, it would be great if:
- Sentry could explicitly warn this when running the integration on a version higher than 3.7
- There could be additional insight into why this limitation exists and what would be needed to fix it
- Any potential workarounds (one work around is just enabling the [`FlaskIntegration`](https://docs.sentry.io/platforms/python/integrations/flask/) for example).

**Comment by sentrivana** [comment]
Hey @rushilsrivastava, I'll [update the docs](https://github.com/getsentry/sentry-docs/pull/8486) with possible workarounds.

As for why the limitation exists, the integration as it's written now needs [`worker_v1`](https://github.com/getsentry/sentry-python/blob/44b0244156e1f332a8f173f337713dab99462609/sentry_sdk/integrations/gcp.py#L135), as long as that doesn't exist (as is the case for newer runtimes, apparently) the integration won't work. The integration itself was added a long time ago by a contributor in https://github.com/getsentry/sentry-python/pull/785. We need to find some time to look at it and investigate what's needed in order to support newer runtimes.
