### ISSUE TITLE
Don't trace OPTIONS and HEAD requests by default

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#1704]
We decided that OPTIONS requests shouldn't be traced by default since they eat into quota a lot for some users and don't add much value.

First implementation should not start transaction for `OPTIONS` and `HEAD` requests in Django, Flask and FastAPI integrations.

See https://github.com/getsentry/sentry-javascript/pull/5485

Also related to https://github.com/getsentry/sentry-ruby/issues/1864

**Comment by sentrivana** [comment]
Done, closing.
