### ISSUE TITLE
Add Starlette integration to Starlette third party packages documentation.

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#1705]
### Problem Statement

Sentry Starlette Integration is not references in Starlette docs

### Solution Brainstorm

Add PR to add Sentry Starlette Integration to the Starlette docs:
https://www.starlette.io/third-party-packages/ here.

See also dicscussion here: 
https://github.com/encode/starlette/discussions/1787#discussioncomment-3314878

**Comment by vagi8** [comment]
Hey I would like to take up this issue. I have written the following short description to add to the starlette docs. Need suggestions. 

> **Sentry** is a tool that finds and reports errors in software. The **Sentry Python SDK** is what makes it work with Python. It also gives actionable insights to resolve Python performance bottlenecks and errors. One can see the full picture of any Python exception so you can diagnose, fix, and optimize performance in the Python debugging process. Sentry has dedicated integration with Starlette for building web applications in Python. Sentry can help with Error tracking; performance insights; contextual information and Alerts and notifications.
> 
> Powered by **sentry.io** and **Starlette**.

**Comment by antonpirker** [comment]
Hey again @vagi8 !

Thanks for picking this up!

Looks great. The plan was to open a PR in the starlette website for this page: https://www.starlette.io/third-party-packages/
And then maybe add a header like "Plugin" but called "Services" or something like that (not sure what the starlette folks prefer. And then add your text and a link to Sentrys docs: https://docs.sentry.io/platforms/python/guides/starlette/

I guess the starlette guys will tell you if your text is ok or too long or whatever

**Comment by vagi8** [comment]
As Starlette does not have any documentation about the format for each plugin content, I will follow some of the previous ones given.

**Comment by vagi8** [comment]
Raised PR with starlette [starlette/pull#2279](https://github.com/encode/starlette/pull/2279)

**Comment by antonpirker** [comment]
Nice! Thanks @vagi8 for tackling this!
