### ISSUE TITLE
tracing.py is not included in https://getsentry.github.io/sentry-python/

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry-python#1708]
### Steps to Reproduce

1. Load https://getsentry.github.io/sentry-python/
2. Look for `set_status` ([link to code](https://github.com/getsentry/sentry-python/blob/c05bcf598c5455a6f35eabd18c840c4544c9392c/sentry_sdk/tracing.py#L417))

### Expected Result

Find documentation for `set_status`

### Actual Result

Cannot find any info about `set_status`

**Comment by sentrivana** [comment]
Closing in favor of https://github.com/getsentry/sentry-python/issues/2196
