### ISSUE TITLE
`extra` parameter is no longer respected

### ISSUE THREAD

**Issue by 2ps** [getsentry/sentry-python#171]
Parameters passed to sentry in the `extra` variable via the `LoggingIntegration` are no longer logged to sentry.  Steps to reproduce:

```python
    sentry_logging = LoggingIntegration(
        level=logging.INFO,  # Capture info and above as breadcrumbs
        event_level=logging.WARNING
    )
    sentry_sdk.init(
        dsn=dsn,
        integrations=[sentry_logging, CeleryIntegration()]
    )
    log = logging.getLogger(__name__)
    log.warning('Hello!', extra={
        'Sentry': 'sentry',
    })
```

The `Sentry` value in `extra` will not appear at getsentry.io.  Please let us know if you have any questions, and we're happy to help address.

**Comment by untitaker** [comment]
Hi, just tried that, works for me. Could you check which version of the SDK you have installed?

**Comment by untitaker** [comment]
Also could you clarify what you mean with "no longer"? Which SDK/version of SDK did you come from where this used to work?

**Comment by 2ps** [comment]
Pretty much every version of the legacy raven-python sdk.  This [is documented](https://docs.sentry.io/clients/python/integrations/logging/#usage).

**Comment by untitaker** [comment]
I know. I was trying to figure out whether you upgraded the new SDK and encountered this issue, or if you were switching from the old SDK.

I am sorry, I can't reproduce this. I tried your exact code example you posted with version 0.5.5 of `sentry-sdk`. There are some behavioral differences between `sentry-sdk` and `raven`. The `sentry-sdk` version is much simpler and does not allow setting of `user`, `culprit`, etc. Everything is just attached to `extra` (i.e. `setExtra`).

I think there's something fundamental missing from your example code that makes it behave diferently from your application. Could you link two events in the sentry UI and point out the difference you find problematic?

**Comment by 2ps** [comment]
@untitaker :  do the variables included in extra show up in the sentry UI for you?  they don't for us.
