### ISSUE TITLE
Add `pytest_asyncio` in test-requirements.txt

### ISSUE THREAD

**Issue by mgaligniana** [getsentry/sentry-python#1712]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.10.1

### Steps to Reproduce

I followed the steps defined in https://github.com/getsentry/sentry-python/blob/master/CONTRIBUTING.md#running-tests **WITHOUT USING** `tox`

1. Clone the repo
2. `cd sentry-python`
3. `python -m venv .env` (using python 3.7.13)
4. `source .env/bin/activate`
5. `pip install -e .`
6. `pip install -r test-requirements.txt`
7. `pytest tests/`

Note: The last week the `pytest_asyncio` import was added: https://github.com/getsentry/sentry-python/commit/973b2f6db7386aae50dd4279ffcead9a4c87d8c6#diff-eed9849977b164602f2509424aa79d672bfdf77cc7bcce9411a27fc8ad0dd3bfR5

### Expected Result

Test suite run successfully

### Actual Result

```
========================================================================================================================== ERRORS ==========================================================================================================================
_______________________________________________________________________________________________ ERROR collecting tests/integrations/asyncio/test_asyncio.py ________________________________________________________________________________________________
ImportError while importing test module '/.../sentry-python/tests/integrations/asyncio/test_asyncio.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.7.13/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/integrations/asyncio/test_asyncio.py:5: in <module>
    import pytest_asyncio
E   ModuleNotFoundError: No module named 'pytest_asyncio'
```

**Comment by antonpirker** [comment]
Will close. 
See comments in PR for details: https://github.com/getsentry/sentry-python/pull/1713
