### ISSUE TITLE
Baggage creation breaks external APIs

### ISSUE THREAD

**Issue by raphaelm** [getsentry/sentry-python#1717]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.10.1

### Steps to Reproduce

I just spent literal 5 hours debugging a very weird issue in our production system. A specific API call to an external system started to return an error code 400.

After a long search, I could pinpoint the change to our recent upgrade of sentry-sdk, and specifically to this pull request: https://github.com/getsentry/sentry-python/pull/1589

Starting from 1.9.8, Sentry will add a ``Baggage`` request to all external HTTP targets we call with ``requests.get()`` by default. I'm sure this is really helpful when calling internal systems that are also sentry-instrumented, but in our case we happen to call an external API that happens to break when it sees that header.

Our temporary solution is now to set ``propagate_traces=False``, which is sad, because it also breaks propagation to useful targets (such as celery). We'd very much appreciate a more detailed way to configure this.

### Expected Result

Sentry is not modifying requests to external APIs **by default**.

### Actual Result

Sentry is adding a ``Baggage`` header to requests to external APIs even though we never asked for it.

**Comment by sl0thentr0py** [comment]
hey @raphaelm apologies for that, we'll add a `trace_propagation_targets` config to enable control over which origins we add outgoing headers to.
It's interesting that `baggage` broke your setup because we also always added `sentry-trace` before by default.

**Comment by raphaelm** [comment]
> we'll add a trace_propagation_targets config to enable control over which origins we add outgoing headers to.

That'd be perfect!

>  It's interesting that baggage broke your setup because we also always added sentry-trace before by default.

Yeah… The target origin in our case is a German government entity, not sure what they're doing over there.

**Comment by antonpirker** [comment]
Related to this Issue https://github.com/getsentry/sentry-python/issues/1785

**Comment by antonpirker** [comment]
I will close this issue in favor of the Issue that adds the solution to this problem to the SDK:
https://github.com/getsentry/sentry-python/issues/1785

So @raphaelm please check the linked Issue for progress! Thanks!
