### ISSUE TITLE
get_integration raises "IndexError: list index out of range"

### ISSUE THREAD

**Issue by cpvandehey** [getsentry/sentry-python#1726]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.10.1

### Steps to Reproduce

Currently, I am seeing a race condition issue in the sentry client code. Our python apps are fairly straightforward, non-async gRPC applications (_still multi-threaded_). The only semi-unique aspect to our code structure is our custom logger that is bootstrapped at start up, but I see that as a stretch more than a reasonable clue for now. 

**Quick Details:**
* Out of the 8 apps of ours, I only see this issue in one app. It happens to be the app with by far the most requests per second.
* This issue does not occur immediately.
* This issue is fixed after rebooting a K8s pod that the app is running on.
* This issue does not occur on every K8s pod.
* Once the issue does occur, sentry does not recover and continues raising the same exception. 

**Our Implementation:**
We wrap all of our gRPC services with this sentry related code as a decorator:
```
def grpc_service_wrapper(self, func: Callable[..., Callable]) -> Callable[..., Optional[Callable]]:
  @functools.wraps(func)
  def _inner(self_obj, request, context):
        req_ctx = request_context.get_request_context() or {}
        with sentry.context(context=req_ctx):
            return func(self_obj, request, context)
  return _inner
```
`req_ctx` can be thought of our custom key values that we manage for our "context". Its nothing more than a collection.

`sentry.context` is another decorator that we use to manage scope. The full definition is below:

```
@contextlib.contextmanager
def context(
    context: Mapping[str, Any] = None, extra: Mapping[str, Any] = None, exc_handler: Callable = None, exc_type=Exception
):
    """A context manager that sets up Sentry context and records exceptions.
    Args:
      context: Additional Sentry context to set with set_context().
      extra: Additional Sentry context to set with set_extra().
      exc_handler: The function to call to handle the caught exception.
        If None then the exception will be re-thrown.
      exc_type: The exception type to listen for.
    """
    with sentry_sdk.push_scope() as scope:
        if context:
            for key, value in context.items():
                scope.set_context(key, value)
        if extra:
            for key, value in extra.items():
                scope.set_extra(key, value)

        try:
            yield
        except exc_type as exc:
            sentry_sdk.capture_exception()
            if callable(exc_handler):
                exc_handler(exc)
            else:
                raise
```

[Im not sure how helpful this will be, but I found this existing issue features a stack trace that is very similar to ours. It was closed due to an inactive status](https://github.com/getsentry/sentry-python/issues/172).

### Expected Result

My only expectation is that sentry functions as it normally would.

### Actual Result

`IndexError('list index out of range')`
```
  File "/venv/lib/python3.9/site-packages/our/custom/logging/keyword_logger.py", line 52, in _log
    logging.Logger._log(self, level, msg, args, exc_info=exc_info, extra=kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/venv/lib/python3.9/site-packages/sentry_sdk/integrations/logging.py", line 103, in sentry_patched_callhandlers
    integration = Hub.current.get_integration(LoggingIntegration)
  File "/venv/lib/python3.9/site-packages/sentry_sdk/hub.py", line 292, in get_integration
    client = self.client
  File "/venv/lib/python3.9/site-packages/sentry_sdk/hub.py", line 302, in client
    return self._stack[-1][0]
IndexError: list index out of range"
```

**Comment by sl0thentr0py** [comment]
@cpvandehey the only way I can see this happening is when the logging handlers are still patched from a previous run, and the rest of sentry_sdk.init + your application code is reloading somehow.

Does your reboot process do something like a lazy reload where it keeps the runtime of the previous run active?

**Comment by cpvandehey** [comment]
We've started to notice this in other high traffic python apps with the same pattern described above.

**Comment by sl0thentr0py** [comment]
@cpvandehey I need some kind of repro to help you.
* give me your full sentry.init setup
* are you doing any kind of scope management yourself? `push_scope/configure_scope`? If so, please provide relevant snippet
* what is `with sentry.context(context=req_ctx):` doing in the wrapper above? that seems to be something written by you as well

**Comment by cpvandehey** [comment]
Thanks for taking a look @sl0thentr0py 

> give me your full sentry_sdk.init setup
Heres what we pass to the `init` call
`{'before_send': <function custom_function.<locals>.handle_before_send at 0x4039ee4e50>, 'dsn': 'ourdsn', 'release': 'foobar', 'environment': 'foobar', 'integrations': [<sentry_sdk.integrations.redis.RedisIntegration object at 0x4038ec6191>]}`
`handle_before_send` is simply scanning the key/value data for any personal information, so we can scramble/remove it before sending it away to our Sentry instances. It does access our logging module to collect the "deny" list of attributes

> are you doing any kind of scope management yourself? push_scope/configure_scope? If so, please provide relevant snippet
We are doing scope management. Now that you mention that, I have some redactions to the original issue to include the full context. I have added the `sentry.context` decorator that we use to effectively `push_scope` for all of our uses.

> what is with sentry.context(context=req_ctx): doing in the wrapper above? that seems to be something written by you as well
You nailed it. This was my bad. Like I said, I made some edits to the original ticket now that should include the full story of our custom code.

**Comment by sl0thentr0py** [comment]
hmm thanks for the update but the scope stuff looks fine, weird.

The only other scenario I can think of is a race condition like
* one thread is initializing sentry and has just [patched the logging handlers](https://github.com/getsentry/sentry-python/blob/dd8bfe37d2ab369eaa481a93484d4140fd964842/sentry_sdk/integrations/logging.py#L107) but the client has [not been bound to the hub](https://github.com/getsentry/sentry-python/blob/dd8bfe37d2ab369eaa481a93484d4140fd964842/sentry_sdk/hub.py#L121) yet
* another thread logs something in between these two states

I will try some fix but I'm also wary of changing some of this code at this point.

**Comment by sl0thentr0py** [comment]
ok I checked and even if no client is bound, it should not throw `IndexError` so it's not the above problem

**Comment by sl0thentr0py** [comment]
can you turn on `debug=True` and see if you see any of these logger errors somewhere in the logs?
https://github.com/getsentry/sentry-python/blob/dd8bfe37d2ab369eaa481a93484d4140fd964842/sentry_sdk/hub.py#L181-L210
