### ISSUE TITLE
Custom instrumentation does not work in an ASGI (Django + Channels) environment

### ISSUE THREAD

**Issue by cjsoftuk** [getsentry/sentry-python#1727]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.10.1

### Steps to Reproduce

1. Set up a Django (2.2 in our case) + Channels (3.0.4 in our case) application
2. Attempt to set up custom instrumentation following the guide at https://docs.sentry.io/platforms/python/guides/django/performance/instrumentation/custom-instrumentation/
3. Assume (and this may be where I go wrong, but I don't think so) that Sentry has already started a transaction for me (as it's an HTTP request, and these are being instrumented & logged correctly).
4. Observe as the spans are actually created as transactions in Sentry.

For example, I have the following code (sanitised) within a django view:

```
def new_or_child_span(*args, **kwargs):
    return sentry_sdk.Hub.current.start_span(*args, **kwargs)

class MyApiView(View):
    def get(self, request, ....):
            with new_or_child_span(
                op="my-api", transaction="Custom Sorting"
            ) as span:
                if hasattr(self, "custom_sorting"):
                    objects = self.custom_sorting(request, objects)
```
There are similar span setups elsewhere in the code.

This fails to work, and leads to the results below.

I have traced this down to sentry_sdk.Hub.current.scope.span being None, always.  Even if I do a start_span, then *another* start_span within that, Hub.current.scope.span is still None, which means that either the docs are wrong about how to do this, or the sentry sdk has a bug in the specific environment I'm running it in.  I am not passing the spans down through the functions, because that seems totally wrong.  I am going to see if I can put together a minimalist example somewhere to demonstrate this behaviour.

### Expected Result

I'd expect this extra span to appear as a child span of the view.render span for the django View (which is logically the parent).

### Actual Result

Instead, I get the following at my top level Transactions view.

![Screenshot_2022-11-08_08-39-00](https://user-images.githubusercontent.com/2492472/200516924-07f41709-f5d9-4b90-ae45-f9d04a8f0f1d.png)

Note the transactions that have the descriptions I set in start_span, rather than these being nested inside the spans for the HTTP request paths - in this case the /api/shop/orders path.  The two I have masked are celery jobs that are running and are not relevant to this issue.

**Comment by cjsoftuk** [comment]
Some further notes on this (as I'm trying to figure out a short term solution while the SDK gets fixed):

- I think the cause is something to do with sendy_sdk.Hub.current being thread local (which makes sense)
- However, the Hub.current used when bootstrapping the Django integration will be the one on the main thread.
- Because of the way the patching is done, there's a reference to this being passed around, which means that the DB transactions are properly recorded, as are the template render calls, but custom instrumentation is happening on the sentry_sdk.Hub.current in another thread, leading to the spans showing up as a transaction .
- What I think probably needs to happen as at least a short term fix, is attach a Hub to the Django request object (which is passed about) and then we can call, for example, `request.sentry_hub.start_span(.....)` which would be more Django-friendly.
- Anywhere you have the request, you also then have the hub available, which means doing custom instrumentation should be fairly straight forward.

If I've understood this right (and I think I have), then I think I see a way to fix this using some Django middleware which sets up the thread local hub if not already set up (or attaches the Hub to the request - this may be better), and starts the transaction on that hub.  My only concern with this is that we'll end up with a situation where we then can't profile the DB spans and attach them to the Hub as I think those all happen on the main thread in Django (may have changed now - I've not looked into this for a while).

I'd welcome a developer's input as to whether I'm thinking in the right direction.

**Comment by antonpirker** [comment]
Hey!

If you add a `transaction` parameter to `start_span()` as you do in your example code, than a new transaction with that given name is started. See: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/hub.py#L478-L481 So removing this parameter should then create the span on the current transaction. 

For `Hub.current.scope.span` being None always and having multiple threads in Django. There is a Sentry threading integration: https://docs.sentry.io/platforms/python/configuration/integrations/default-integrations/#threading
This integration has a parameter `propagate_hub` that should clone the Hub for each new Thread. So maybe this is the way to go for you?

**Comment by cjsoftuk** [comment]
Ah, I will try these out and see if this solves the issues I was seeing!

**Comment by cjsoftuk** [comment]
Bingo, that's perfect.  Thanks @antonpirker and sorry for the noise.

For any future readers of this issue, If you run Django in a multi-threaded environment, you must use `ThreadingIntegration` and enable the hub propagation as noted in https://github.com/getsentry/sentry-python/issues/1727#issuecomment-1313739697

You should only then pass the "op" kwarg parameter to create_span, and lo and behold your custom instrumentation will work.
