### ISSUE TITLE
Catch all 4xxs with DjangoIntegration

### ISSUE THREAD

**Issue by iMerica** [getsentry/sentry-python#173]
Hi,

I'm using DRF with the new Sentry SDK for Python. Is there a built-in way to log all 4xxs in the new SDK? 

It would be nice to drop in a middleware and start logging all 4xx and 5xx implicitly.

**Comment by untitaker** [comment]
@iMerica I am not sure if that answered the question but I am going to go ahead and close this due to lack of activity.
