### ISSUE TITLE
Option to configure or disable tracing per route for FastAPI integration

### ISSUE THREAD

**Issue by davechallis** [getsentry/sentry-python#1744]
### Problem Statement

Using the FastAPI integration, I've got a couple of routes that are infrequently called, and ideally I'd like to capture 100% of transactions for those.

I've also got some very uninteresting routes that are called very frequently, that I'd like to avoid capturing any transactions for entirely (e.g. a route that just returns a constant string each time).

So would be nice to be able to set sample rates for Sentry per route, or just to disable transaction capture entirely for some routes.

### Solution Brainstorm

Since FastAPI routes are usually created with decorators, would be nice to configure Sentry on each route in the same way, e.g.:

```python
@sentry_sdk.fastapi.route(traces_sample_rate=0.0, sample_rate=0.1)
@app.get("/")
async def root():
    return {"message": "Hello World"}
```

**Comment by antonpirker** [comment]
Hello @davechallis !

We are currently at a feature called "Dynamic Sampling" here at Sentry. 
It is exactly what you are requesting here. With Dynamic Sampling it will be possible for you to configure the sample rate of different routes from your projects settings on Sentry.io.

It is not yet fully done, but we are getting there. 

Have a look at the documentation in the mean time:
https://docs.sentry.io/product/data-management-settings/dynamic-sampling/

**Comment by antonpirker** [comment]
In the mean time you can implement a `traces_sampler`. This is something you can do today, and will also have the desired effect. See the documentation here: https://docs.sentry.io/platforms/python/configuration/sampling/#setting-a-sampling-function

In the `sampling_context` there is a `transaction_context.name` that you can use to set the desired sample rates.

**Comment by davechallis** [comment]
@antonpirker thanks, I've got something working using this approach now 👍

**Comment by antonpirker** [comment]
Ok cool! Closing this.
