### ISSUE TITLE
AWS Lambda Python integration: fails to capture errors

### ISSUE THREAD

**Issue by Layvier** [getsentry/sentry-python#1745]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

-

### Steps to Reproduce

1. Create a new project on Sentry
2. Enable aws lambda integration
3. Enable the integration for a Python lambda (v3.9)
4. Trigger an error within this lambda

### Expected Result

I would expect the error to be captured by Sentry on the associated project

### Actual Result

Sentry fails send the events properly. No error will be captured by Sentry
```[WARNING]	2022-11-16T17:17:38.496Z	0962520f-3c93-4754-8de7-f1b8ce989649	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1787ad05b0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/{sentryId}/envelope/```

**Comment by antonpirker** [comment]
Please make sure, that your Lambda function is allowed to POST data to `https://sentry.io/api/{sentryId}/envelope/`.
