### ISSUE TITLE
sentry_sdk  can be used locally, but online is not acceptable.

### ISSUE THREAD

**Issue by jinji-hanbin** [getsentry/sentry-python#175]
[Tue Nov 20 14:33:21.226473 2018] [:error] [pid 2329] [client 127.0.0.1:56136]   File "/home/jinji/workspace/almond/settings.py", line 237, in <module>, referer: http://almond.dev.attackt.com/admin/flush/test/log/
[Tue Nov 20 14:33:21.226558 2018] [:error] [pid 2329] [client 127.0.0.1:56136]     integrations=[DjangoIntegration()], referer: http://almond.dev.attackt.com/admin/flush/test/log/
[Tue Nov 20 14:33:21.226599 2018] [:error] [pid 2329] [client 127.0.0.1:56136]   File "/home/jinji/envs/almond/lib/python2.7/site-packages/sentry_sdk/hub.py", line 49, in init, referer: http://almond.dev.attackt.com/admin/flush/test/log/
[Tue Nov 20 14:33:21.226695 2018] [:error] [pid 2329] [client 127.0.0.1:56136]     client = Client(*args, **kwargs), referer: http://almond.dev.attackt.com/admin/flush/test/log/
[Tue Nov 20 14:33:21.226722 2018] [:error] [pid 2329] [client 127.0.0.1:56136]   File "/home/jinji/envs/almond/lib/python2.7/site-packages/sentry_sdk/client.py", line 61, in __init__, referer: http://almond.dev.attackt.com/admin/flush/test/log/
[Tue Nov 20 14:33:21.226796 2018] [:error] [pid 2329] [client 127.0.0.1:56136]     self.transport = make_transport(options), referer: http://almond.dev.attackt.com/admin/flush/test/log/
[Tue Nov 20 14:33:21.226815 2018] [:error] [pid 2329] [client 127.0.0.1:56136]   File "/home/jinji/envs/almond/lib/python2.7/site-packages/sentry_sdk/transport.py", line 207, in make_transport, referer: http://almond.dev.attackt.com/admin/flush/test/log/
[Tue Nov 20 14:33:21.226881 2018] [:error] [pid 2329] [client 127.0.0.1:56136]     return transport_cls(options), referer: http://almond.dev.attackt.com/admin/flush/test/log/
[Tue Nov 20 14:33:21.226899 2018] [:error] [pid 2329] [client 127.0.0.1:56136]   File "/home/jinji/envs/almond/lib/python2.7/site-packages/sentry_sdk/transport.py", line 99, in __init__, referer: http://almond.dev.attackt.com/admin/flush/test/log/
[Tue Nov 20 14:33:21.226913 2018] [:error] [pid 2329] [client 127.0.0.1:56136]     self._retry = urllib3.util.Retry(), referer: http://almond.dev.attackt.com/admin/flush/test/log/
[Tue Nov 20 14:33:21.226943 2018] [:error] [pid 2329] [client 127.0.0.1:56136] AttributeError: 'module' object has no attribute 'Retry', referer: http://almond.dev.attackt.com/admin/flush/test/log/
![image](https://user-images.githubusercontent.com/18417846/48756153-ea1f3080-ecd2-11e8-9e9c-4123bc137a00.png)
I reference 
![image](https://user-images.githubusercontent.com/18417846/48756205-22267380-ecd3-11e8-81b1-157a9958f006.png)
sentry_sdk 0.5.5 Django  1.9 python 2.7.6

**Comment by untitaker** [comment]
Could you tell me the version of urllib3 you use on the server?

**Comment by jinji-hanbin** [comment]
urllib3 1.24.1

**Comment by untitaker** [comment]
I'm sorry, I think you have a broken deployment setup on your server. Perhaps a systemwide urllib3 conflicting with the one in your virtualenv, or the other way around. In any case `urllib3.util.Retry` definetly exists in that version of urllib3 so I don't think this issue is appropriate here.

**Comment by jinji-hanbin** [comment]
system 1.7.1   
virtualenv 1.24.1

**Comment by champ** [comment]
I'm having the same problem migrating to python sentry SDK from raven on an old Ubuntu server (14.04) having `urllib3` 1.7.1 installed.
Pin-pointing requirement versions is a best practice: the retry logic in `urllib3` was implemented in version 1.9  as seen [here in the changelog](https://github.com/urllib3/urllib3/blob/master/CHANGES.rst#19-2014-07-04). Please consider pin-pointing this version in  `install_requires` in `setup.py`.

**Comment by untitaker** [comment]
Ah, sure, will do. 1.9 is still from 2014 though :)
