### ISSUE TITLE
Expose WSGI middleware

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#177]
It would be nice to expose a WSGI middleware that does error handling for you. We currently have a helper function here: https://github.com/getsentry/sentry-python/blob/58ec2e4d3f14f950a0be81ca34160b16cb970935/sentry_sdk/integrations/_wsgi.py#L158 

make the API nicer, document it

**Comment by sboisson** [comment]
Regarding the run_wsgi_ap, why is the _ScopePoppingResponse used and not a context manager?
_ScopePoppingResponse seems to generate HTTP responses that choke NodeJS HTTP parser ("Error: Parse Error" with code 'HPE_INVALID_CONSTANT')

**Comment by untitaker** [comment]
`ScopePoppingResponse` does not generate HTTP responses. We need to exit the scope when the request is done streaming, otherwise we will not have a request attached to exceptions happening during streaming

**Comment by sboisson** [comment]
> `ScopePoppingResponse` does not generate HTTP responses. We need to exit the scope when the request is done streaming, otherwise we will not have a request attached to exceptions happening during streaming

Well, I don't know why, but when I returned the non wrapped response it could not reproduce the issue anymore..

I was curious why the following code would not work:
 
```
       def patched_wsgi_app(environ, start_response):
            hub = Hub.current
            with hub.push_scope() as scope:
                try:
                    return old_app(environ, start_response)
                except:
                    einfo = _capture_exception(hub)
                    reraise(*einfo)
```

**Comment by untitaker** [comment]
@sboisson I don't know how to answer that. I don't have any context on your issue. Either way I don't think it's great to have this conversation on an unrelated thread.
