### ISSUE TITLE
"trace" header missing in envelope when trace is started on Python project

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#1776]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.11.0

### Steps to Reproduce

The `trace` object is missing in the envelope header in the main `sentry` project for these transactions:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/202325/205591959-767cc930-dab3-4148-a936-07193aabfbef.png">

`propagate_tracestate` is not set, ergo `False`.

Reproduce this locally: Simply start `sentry devserver --workers` and put some code into capture_envelope ([here](https://github.com/getsentry/sentry/blob/d92c8f42227ab9ff4e834b1e063bdabdce28e8b4/src/sentry/utils/sdk.py#L324)) to log what's in the envelope.

### Expected Result

There should be a `trace` header in the envelope containing the dynamic sampling context.

### Actual Result

The complete `trace` object in the envelope header is missing.

**Comment by sl0thentr0py** [comment]
== investigate broken DSC ==

* /api/0/projects/{organization_slug}/{project_slug}/files/dsyms/
  * incoming `sentry-trace` from symbolicator without `baggage`, so empty/frozen DSC
  * https://sentry.io/organizations/sentry/performance/sentry:f30ea9abfa6948e78e66f400ff9b0a58/?project=1&query=&referrer=performance-transaction-summary&statsPeriod=24h&transaction=%2Fapi%2F0%2Fprojects%2F%7Borganization_slug%7D%2F%7Bproject_slug%7D%2Ffiles%2Fdsyms%2F&unselectedSeries=p100%28%29


* sentry.tasks.post_process.post_process_group


* sentry.profiles.task.process_profile

* /api/0/organizations/{organization_slug}/events/
  * no clue, can't find an event without incoming headers/DSC

* sentry.tasks.app_store_connect.dsym_download

* /
  * https://sentry.io/organizations/sentry/performance/sentry:9b251324808847a0972eada849ee3284/?project=1&query=http.method%3AGET&referrer=performance-transaction-summary&statsPeriod=24h&transaction=%2F&unselectedSeries=p100%28%29
  * again incoming `sentry-trace` without `baggage`
  * likely coming from crawlers/spiders using sentry SDK as well

* sentry.tasks.send_process_resource_change_webhook

* sentry.tasks.process_resource_change_bound

* sentry.tasks.process_commit_context

* /auth/login/{organization_slug}/
