### ISSUE TITLE
Google Cloud Functions SDK

### ISSUE THREAD

**Issue by xarg** [getsentry/sentry-python#181]
There is an AWS Lambda integration, but there is no Google Cloud Functions SDK. 

Here's their python environment description: https://cloud.google.com/functions/docs/concepts/python-runtime

**Comment by untitaker** [comment]
It's on our radar but so far there haven't been too many requests for it. I suppose the best way to go about this is to vote with :+1: on the OP (please no comments!) because that's what I can sort issues by.

**Comment by davegaeddert** [comment]
In the meantime is there a suggestion for a basic way to configure and use Sentry within a python Google Cloud Function?

Thanks!

**Comment by untitaker** [comment]
@davegaeddert just calling `sentry_sdk.init()` without integrations should be fine, as per https://docs.sentry.io/quickstart/?platform=python

You might encounter issues where Google suspends your process before events are sent, because we don't have a synchronous transport... in master we have a new function `Client.flush()` which you can call to wait for all events to be sent out.

**Comment by untitaker** [comment]
Example:

```python

def sentry_cloud_function(f):
    def inner(*a, **kw):
        try:
            return f(*a, **kw)
        except Exception:
            capture_exception()
            raise
        finally:
            Hub.current.client.flush()
    return inner

@sentry_cloud_function
def hello_http(...): # see google cloud function docs
    pass
```

**Comment by untitaker** [comment]
This decorator is now shipped with the SDK: https://docs.sentry.io/platforms/python/serverless/

**Comment by davegaeddert** [comment]
Awesome, thanks @untitaker!

**Comment by antonpirker** [comment]
Sentry does now support Google Cloud Functions. See: https://docs.sentry.io/platforms/node/guides/gcp-functions/

So I think it is save to close this issue.
