### ISSUE TITLE
Support for Sanic 22.12.0

### ISSUE THREAD

**Issue by robd003** [getsentry/sentry-python#1814]
### Problem Statement

We'd like to upgrade from prior LTS release of sanic (21.12.2) to the new LTS release and just want to make sure everything will work reliably.

Could you please verify that sentry-python works with the latest LTS release of sanic?

### Solution Brainstorm

Just want clarification

**Comment by sl0thentr0py** [comment]
@robd003 added it to test matrix, seems to work, feel free to upgrade :)
