### ISSUE TITLE
FastAPI integration ROOT_PATH problem

### ISSUE THREAD

**Issue by sector119** [getsentry/sentry-python#1832]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.12.0

### Steps to Reproduce

I have FastAPI app with nginx as proxy with following config. I host my api service on "/api/xmlrpc/v1" location and I rewrite it to send to my app on "/" location.

```
location /api/xmlrpc/v1 {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_pass http://xmlrpc_api_service_upstream;
    rewrite ^/api/xmlrpc/v1/(.*)$ /$1 break;
}
```

To get FastAPI docs to work I must set FastAPI root_path argument to "/api/xmlrpc/v1" when I create app.

Here is request scope example 
`{'type': 'http', 'scheme': 'https', **'root_path': '/api/xmlrpc/v1'**,  **'path': '/api/xmlrpc/v1'**}`

### Expected Result

What can I do to get url tag and curl example urls look as expected (https://api.my.site/api/xmlrpc/v1) ?

### Actual Result

I get url tag like https://api.my.site/api/xmlrpc/v1/api/xmlrpc/v1 not https://api.my.site/api/xmlrpc/v1 as it has to be, as well as curl example.

![api](https://user-images.githubusercontent.com/5519953/211917057-34abc631-14a2-40f6-9e52-1d55f61da69e.jpg)

That's happened because of asgi.py integration's _get_url() function where url path is 
`scope.get("root_path", "") + scope.get("path", "")` that is why it got duplicated.

I can workaround it by setting FastAPI root_path=None and openapi_url='/api/xmlrpc/v1/openapi.json' and don't rewrite location for '/api/xmlrpc/v1/openapi.json' location while sending request to app from nginx, but it looks like a dirty hack.

Thank You

**Comment by smeubank** [comment]
I understand then that the problem is nginx is kindof duplicating the api route, and you're wondering if we have a better work around to get the original FastAPI route?

**Comment by sector119** [comment]
> I understand then that the problem is nginx is kindof duplicating the api route, and you're wondering if we have a better work around to get the original FastAPI route?

Nginx doesn't duplicate it just rewrite url from "/api/xmlrpc/v1" to "/" while proxying request to upstream backend, but backend also get original url "/api/xmlrpc/v1" at scope["path"], but also FastAPI makes me set root_path to that original url "/api/xmlrpc/v1" to serve it's docs properly. And here we get duplicated path.

It's not a problem with nginx, but with asgi integration and _get_url() function IMO. It shouldn't concat root_path and path, or we have redefine it by subclassing, I don't know..

**Comment by antonpirker** [comment]
Hey @sector119 

Now I get it. We need to support the FastAPI option `root_path` properly.
Note so self: Look here: https://fastapi.tiangolo.com/advanced/behind-a-proxy/?h=root_path

**Comment by sector119** [comment]
> Hey @sector119
> 
> Now I get it. We need to support the FastAPI option `root_path` properly. Note so self: Look here: https://fastapi.tiangolo.com/advanced/behind-a-proxy/?h=root_path

Yes, for sure !

**Comment by antonpirker** [comment]
Hey @sector119 !

I finally had time to test this. I tried to reproduce this with this sample project: https://github.com/antonpirker/test-fastapi-root-path

But there is no path duplication happening for me. Can you have a look at the demo repo I linked and tell me how your setup is different to mine?

Thanks!
