### ISSUE TITLE
Improve documentation for configure_scope()

### ISSUE THREAD

**Issue by beaugunderson** [getsentry/sentry-python#184]
The current documentation does not make it clear whether this code is permanent or if it is reverted as soon as the `with` block is exited:

```python
from sentry_sdk import configure_scope

with configure_scope() as scope:
    scope.set_tag("my-tag", "my value")
    scope.user = {'id': 42, 'email': 'john.doe@example.com'}
```

I assume it is permanent, because if it is not then there would be no difference from `push_scope`, but it should be made explicit with an example (the opposite of the example given for `push_scope` would make it clear).

**Comment by untitaker** [comment]
You're talking about this page, right? https://docs.sentry.io/enriching-error-data/context/?platform=python#capturing-the-user

**Comment by beaugunderson** [comment]
This is the one that contains the counter-example:

https://docs.sentry.io/enriching-error-data/scopes/?platform=python

```python
from sentry_sdk import push_scope, capture_exception

with push_scope() as scope:
    scope.set_tag("my-tag", "my value")
    scope.level = 'warning'
    # will be tagged with my-tag="my value"
    capture_exception(Exception("my error"))

# will not be tagged with my-tag
capture_exception(Exception("my other error"))
```

Inverting that example would give something like this:

```
from sentry_sdk import configure_scope, capture_exception

with configure_scope() as scope:
    scope.set_tag("my-tag", "my value")
    scope.level = 'warning'
    # will be tagged with my-tag="my value"
    capture_exception(Exception("my error"))

# will also be tagged with my-tag
capture_exception(Exception("my other error"))
```

**Comment by cancan101** [comment]
Is there any way to provide a function rather than a dict that gets run at exception time? I think js does this.

**Comment by aviv-ebates** [comment]
If this:
```
with configure_scope() as scope:
    scope.set_tag("my-tag", "my value")
    scope.level = 'warning'
    # will be tagged with my-tag="my value"
    capture_exception(Exception("my error"))

# will also be tagged with my-tag
capture_exception(Exception("my other error"))
```

then why is `configure_scope()` a context manager? What does it do in its `__exit__` method?

**Comment by untitaker** [comment]
@aviv-ebates nothing. it will be gone or at least superseded soon. configure_scope is a concept that didn't translate well to python from other languages

**Comment by untitaker** [comment]
@cancan101 you can use before_send in either: https://docs.sentry.io/error-reporting/configuration/filtering/?platform=python#before-send

**Comment by roksys** [comment]
Can I use `before_send` for setting custom tag? I have the following code and it doesn't set the tag, or at least it is not visible in the issue. Am I missing something?

```
sentry_sdk.init(
     dsn=app.config['SENTRY_DSN'],
     in_app_exclude=logging_exclusions,
     integrations=[FlaskIntegration()],
     before_send=self.add_request_id_sentry_python)    

def add_request_id_sentry_python(self, event, hint):
        from sentry_sdk import push_scope
        with push_scope() as scope:
            scope.set_tag('request_id', '214')
        return event
```

**Comment by untitaker** [comment]
if you want to set a tag in `before_send`, scopes cannot be used.

I suggest doing this in your request handler:

```
with configure_scope() as scope:
    scope.set_tag("request_id", 214)
```

**Comment by pietrodn** [comment]
The `configure_scope()` call shouldn't offer the context manager interface, as it's misleading (IMHO). Plain function calls to set scope parameters "from now on" should be sufficient and clearer.

**Comment by untitaker** [comment]
We're revamping the documentation right now, and while there will be shortcuts to setting tags, the context manager will stay.

**Comment by MaximeLaurenty** [comment]
I'm not sure if the behaviour of configure_scope has changed since the above discussion, but since I'm stumbling upon it today, here's how configure_scope behaves today and isn't clear to me from the doc: 
- configure_scope creates a scope which doesn't inherit the scope defined beforehand (difference with push_scope)
- configure_scope doesn't impact the global scope (like push_scope)

example:
```
import sentry_sdk
sentry_sdk.set_tag("outer", 'tag')

with sentry_sdk.push_scope() as scope:
     scope.set_tag('push_scope', 'yes')
     print(scope._tags) # prints {'outer': 'tag', 'push_scope': 'yes'}

with sentry_sdk.configure_scope() as scope:
     scope.set_tag('conf_scope', 'yes')
     print(scope._tags) # prints {'conf_scope': 'yes'}
     
 print(sentry_sdk.Hub.current.scope._tags) # prints {'outer': 'tag'}
```
