### ISSUE TITLE
Disable auto-instrumentation of server functions

### ISSUE THREAD

**Issue by NakulK48** [getsentry/sentry-python#1848]
### Problem Statement

I've been evaluating the free tier of Sentry, but my entire month's allowance of performance instrumentation went on this uninteresting span, created when the AWS load balancer runs a health check (every 10 seconds or so):

<img width="720" alt="image" src="https://user-images.githubusercontent.com/6199511/213202261-03939b5c-43a3-4cb9-a054-ef4e5bb461b1.png">

I would like to be able to disable this integration entirely (either just Tornado, or all auto-instrumentation), and only report performance for explicitly generated spans.

I can't even filter these out with inbound filters, because those are only available in Business and above.

### Solution Brainstorm

The NextJs implementation seems to support this behaviour https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#disable-api-route-middleware-and-data-fetching-auto-instrumentation-entirely

**Comment by antonpirker** [comment]
Hey @NakulK48 !

Thanks for writing in. 
We plan to release a new feature called `before_send_transaction` on coming Monday. With this you can specify a function that is called for every performance event before it is send and you can drop the event if it is the AWS load balancer. With this you then have full control of what performance events are sent and which are dropped. 

So please stay tuned.

**Comment by antonpirker** [comment]
The documentation for the feature is already there:
https://docs.sentry.io/platforms/python/configuration/filtering/#filtering-transaction-events

The feature itself will be released on Monday.

**Comment by NakulK48** [comment]
Thanks!

**Comment by antonpirker** [comment]
`before_send_transaction` has been released: https://github.com/getsentry/sentry-python/blob/master/CHANGELOG.md

**Comment by NakulK48** [comment]
Excellent! Is there some kind of typing/schema that indicates the format of `event`?

**Comment by antonpirker** [comment]
You can have a look here: https://develop.sentry.dev/sdk/event-payloads/transaction/
