### ISSUE TITLE
opentelemetry-distro dependency version has typo

### ISSUE THREAD

**Issue by heartcored98** [getsentry/sentry-python#1857]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.13.0

### Steps to Reproduce

When I try to install opentelemetry-distro and sentry-sdk with opentelemetry integration, I specified the version as below.

```
opentelemetry-distro>=0.35b0
sentry-sdk[starlette,opentelemetry]==1.13.0
```

However, the following error raised when run `pip install -r requirements.txt`.

```
The conflict is caused by:
The user requested opentelemetry-distro>=0.35b0
sentry-sdk[opentelemetry,starlette] 1.13.0 depends on opentelemetry-distro>=0.350b0; extra == "opentelemetry"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

It turned out the sentry requires `opentelemetry-distro>=0.350b0` dependency but there is no `0.350b0` version. 
The dependency should be fixed to `opentelemetry-distro>=0.35b0` 

### Expected Result

sentry-sdk should be install with `opentelemetry-distro>=0.35b0` version

### Actual Result

sentry-sdk seeking for `opentelemetry-distro>=0.350b0` (which does not exists)

**Comment by AbhiPrasad** [comment]
Hey @heartcored98 thanks for writing in! I'm going to submit a PR to fix this!

**Comment by antonpirker** [comment]
This has been fixed: https://github.com/getsentry/sentry-python/blob/master/setup.py#L68
