### ISSUE TITLE
Discarded invalid parameter '_meta'

### ISSUE THREAD

**Issue by tonal** [getsentry/sentry-python#186]
Sentry 9.0.0
sentry.python 0.5.5
```
Discarded invalid parameter '_meta' 
```

How to correct it?

**Comment by untitaker** [comment]
Hi @tonal, this is fixed on the master branch of sentry. We realize that we should push out a new release of sentry but there are a few other blockers there. I would recommend installing sentry from the master branch.

**Comment by pavelpatrin** [comment]
@untitaker does you mean that it is a Sentry bug, not a python client bug?

**Comment by pavelpatrin** [comment]
My project send to Sentry event with this JSON

```
{
  // Many different fields...

  "breadcrumbs": [
    {
      "category": "query",
      "timestamp": "2019-01-17T16:54:28Z",
      "message": "SELECT ... part of big query ...",
      "type": "default"
    }
    // Many other queries...
  ],
  "_meta": {
    "breadcrumbs": {
      "0": {
        "message": {
          "": {
            "len": 710823,
            "rem": [["!limit", "x", 816, 819]]
          }
        }
      }
      // Many other queries...
    }
  }
}
```

and Sentry shows a message "Discarded invalid parameter '_meta' ".

Is my situation fixed in Sentry from master?

**Comment by untitaker** [comment]
Yes, it's a new parameter in the event payload. It should not be a problem for older sentry installations though, except for that error message
