### ISSUE TITLE
Patched task factory in AsyncioIntegration loses task result.

### ISSUE THREAD

**Issue by tkukushkin** [getsentry/sentry-python#1881]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.14.0

### Steps to Reproduce

```python
import asyncio
import sentry_sdk
from sentry_sdk.integrations.asyncio import AsyncioIntegration

async def add(a, b):
    return a + b

async def main():
    sentry_sdk.init('dsn', integrations=[AsyncioIntegration()])
    result = await asyncio.create_task(add(1, 2))
    assert result == 3, result

asyncio.run(main())
```

### Expected Result

No `AssertionError`.

### Actual Result

```python
    assert result == 3, result
AssertionError: None
```

Patched task factory always loses task result.

**Comment by dvdblk** [comment]
Pretty sure my problem is related or there is something wrong with the `AsyncioIntegration` patch. Came accross your issue while trying to add Sentry to a project with some `aiohttp` requests. Here is some reproducible  sample code:

```python
import asyncio

import aiohttp
import sentry_sdk
from sentry_sdk.integrations.asyncio import AsyncioIntegration


async def main():
    sentry_sdk.init(
        dsn="<dsn>",
        integrations=[AsyncioIntegration()],
    )

    async with aiohttp.ClientSession() as client:
        await client.get("https://google.com")

asyncio.run(main())
```

The above code results in `TypeError: 'NoneType' object is not iterable` coming from the aiohttp library. When the `AsyncioIntegration()` is omitted, it works fine.

**Comment by antonpirker** [comment]
Hey @tkukushkin  and @dvdblk for the great issue and the example projects for reproducing this. I am having a look at it.
