### ISSUE TITLE
Request to reduce `urllib3` requirement to `urllib3<=1.24.3` to align with Google Colab

### ISSUE THREAD

**Issue by glenn-jocher** [getsentry/sentry-python#1891]
### Problem Statement

We recently adopted sentry-sdk for our popular `ultralytics` [YOLOv8](https://github.com/ultralytics/ultralytics) pip package, where a dominant use case is quick Google Colab demos for our users, i.e. https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb

Colab already includes an install of `urllib3==1.24.3`, which is uninstalled and then replaced with a later version when `sentry_sdk` is installed. Relaxing the requirement would eliminate this additional uninstall and install step for all Colab users, which will provide faster installs and faster demos for us.

```ipython
!pip install sentry_sdk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting sentry-sdk
  Downloading sentry_sdk-1.15.0-py2.py3-none-any.whl (181 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.3/181.3 KB 4.7 MB/s eta 0:00:00
Collecting urllib3>=1.26.11
  Downloading urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 KB 3.3 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/local/lib/python3.8/dist-packages (from sentry-sdk) (2022.12.7)
Installing collected packages: urllib3, sentry-sdk
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
Successfully installed sentry-sdk-1.15.0 urllib3-1.26.14
```

### Solution Brainstorm

Relax urllib3 requirement to `urllib3<=1.24.3`

**Comment by sl0thentr0py** [comment]
we bumped the min urllib3 version because some other user wanted the security patches in newer versions enforced.
The answer to this is to get everyone in the ecosystem to upgrade their versions gradually, not for us to go lower.
Sorry, closing!
