### ISSUE TITLE
Notes for Django

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-python#19]
- Probably should try to find an earlier entry point other than settings.py (but I'm out of touch w/ Django's load process)
- sentry_sdk.init is better than init on our suggest import process

Test Plan:

- [ ] catches wsgi error?
- [ ] catches manage.py error?
- [x] catches sys.except_hook (non manage.py) error?
- [x] catches middleware error?
- [x] catches view error?

**Comment by dcramer** [comment]
Also a note that it 100% doesnt work with native graphene integration (as they hijack error handling in a not-so-great kind of way).

**Comment by untitaker** [comment]
manage.py is not handled by excepthook, django catches exceptions. Need to patch django again

**Comment by untitaker** [comment]
raw wsgi errors are not caught at all. I think this needs more thought, especially wrt how to deduplicate code between Flask and Django. I'd like to attach parts of the environ but then I duplicate already existing functionality that operates on request objects.

In the long term I suspect we will have to convert everything to a WSGI middleware and do our own request parsing.

**Comment by untitaker** [comment]
Follow-up issues have been created
