### ISSUE TITLE
AWS Flask / Lambda Integration - AssertionError: popped wrong scope

### ISSUE THREAD

**Issue by iteratelance** [getsentry/sentry-python#190]
When upgrading to 0.6.0 from 0.5.5 I started receiving this error:

```
[1543928085886] [INFO] 2018-12-04T12:54:45.869Z c6a7f732-f7c3-11e8-8354-13e650ef3e7e 104.63.241.241 - - [04/Dec/2018:12:54:45 +0000] "GET / HTTP/1.1" 200 56 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36" 0/1.58
[1543928085886] popped wrong scope: AssertionError
Traceback (most recent call last):
  File "/var/task/sentry_sdk/integrations/aws_lambda.py", line 37, in sentry_handler
  reraise(*exc_info)
  File "/var/task/sentry_sdk/hub.py", line 94, in __exit__
  assert layer[1] == self._layer[1], "popped wrong scope"
AssertionError: popped wrong scope
```
I upgraded to 0.6.1 and still receive the same error message.  

The error results in API Gateway throwing a 502 error for every request regardless if the application throws an exception or not. 

API Gateway response for every request result in.
```json
{"message": "Internal server error"}
```

We are initiating the SDK as follows and using Lambda runtime Python 3.6
```python
sentry_sdk.init(
    dsn=os.environ.get('SENTRY_DSN'),
    environment=os.environ.get('FLASK_ENV', 'development'),
    integrations=[FlaskIntegration(transaction_style='url'), AwsLambdaIntegration()]
)
```

Downgrading to 0.5.5 resolves the issue.

**Comment by untitaker** [comment]
Hi, is this reproducible with all lambda functions you have? Is there one that doesn't use flask or zappa that exhibits this error? Do you receive the same error in the Python 3.7 runtime?

**Comment by untitaker** [comment]
I suspect that reverting https://github.com/getsentry/sentry-python/pull/174 will fix this but I would like to know why.

**Comment by wangsha** [comment]
Having same issue with lambda + zappa + flask, python 2.7

**Comment by wangsha** [comment]
@untitaker sorry, we don't have any other use cases. All our lambdas are running with the same configuration and all exhibit this error. Reverting to earlier version fixed this issue.

**Comment by untitaker** [comment]
Hi, this is a bug in Zappa. See here: https://github.com/Miserlou/Zappa/issues/1723

I will release a fix for the Python SDK to be less strict about the assertion, but that's all I can do.

**Comment by untitaker** [comment]
https://github.com/getsentry/sentry-python/pull/194 should fix this error.

**Comment by untitaker** [comment]
0.6.2 has been released, but the underlying Zappa issue is more severe.

**Comment by iteratelance** [comment]
> Hi, is this reproducible with all lambda functions you have? Is there one that doesn't use flask or zappa that exhibits this error? Do you receive the same error in the Python 3.7 runtime?
@untitaker sorry for the late reply, yes it's reproducible in all Lambda functions.

**Comment by untitaker** [comment]
@iteratelance @wangsha please test if 0.6.2 fixes your problems

**Comment by wangsha** [comment]
@untitaker confirm it's fixed for my use case. thanks for highlighting zappa issue.

**Comment by iteratelance** [comment]
@untitaker it appears to solve are issues as well.  Thanks for the quick patch.

**Comment by iteratelance** [comment]
@untitaker seems to be working however the tags for `url` and `transaction` seem to be inaccurate.  I suppose this might be because Zappa isn't closing the response per your earlier comment.  The `transaction` tag is actually being named the name of our Lambda function and the `url` is another route in our application.  This might be something that Zappa has to deal with but I wanted to point it out.

**Comment by untitaker** [comment]
@iteratelance This seems like an entirely unrelated issue. Does rolling back to 0.5.5 fix this, does applying the patch to Zappa, ...? In any case pls open a new issue here
