### ISSUE TITLE
raise_send_errors support (or equivalent)

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#191]
This is about reimplementing Raven's `raise_send_errors` in sentry-sdk.

Please vote with 👍 here if you somehow need this. However, I currently don't understand what people use this for. Are you using the SDK like a library? Why?

**Comment by charlax** [comment]
I'm debugging why my Zappa-AWS installation does not send exceptions to Sentry and `debug=True` does not let me know why exceptions are not being sent...

**Comment by untitaker** [comment]
Sorry but this is entirely unrelated to this issue.

**Comment by untitaker** [comment]
@charlax if you set `debug=True` it prints out all exceptions to `log` that it catches, really all of them. So there is no way you would get new information by raising those errors.

**Comment by charlax** [comment]
You're right. I'd need a sync transport to see transport error anyway... (#125).

**Comment by untitaker** [comment]
@charlax `debug=True` should print out the errors from the transport as well. Enabling the AWS Lambda integration is important and should fix your issues.

**Comment by charlax** [comment]
Let me open another issue so that I don't pollute this thread. See #227.

**Comment by antonpirker** [comment]
As this issue is resolved and a follow up issue #227 was created I will close this issue.
