### ISSUE TITLE
Re-raise exceptions

### ISSUE THREAD

**Issue by 0x5e5e** [getsentry/sentry-python#192]
Currently, sentry-python out of the box, e.g.

`
import sentry_sdk
sentry_sdk.init("https://<key>@sentry.io/<project>")
`

automatically catches and handles exceptions.   How can I configure the sdk to re-raise exceptions after pushing the requisite event out?   My use case is such that any exceptions caught should crash the program as continuing to run would result in unwanted and/or unexpected program behavior, however, I still want the exception to be logged.  Am I misunderstanding something about how sentry works?

**Comment by untitaker** [comment]
sentry-sdk should reraise exceptions in all situations where it automatically catches them. Do you have an example where this is not the case?
