### ISSUE TITLE
Sentry ignores traces_sample_rate

### ISSUE THREAD

**Issue by PAKalucki** [getsentry/sentry-python#1921]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.9.10

### Steps to Reproduce

With following sentry configuration:
```
    SentryClient.client.init(
        dsn=settings["sentry_dsn"],
        integrations=[
            PyramidIntegration(),
        ],
        traces_sample_rate=float(settings["sentry_sample_rate"]),
        send_default_pii=True,
    )
```

Regardless of what value we put in traces_sample_rate in range from 0.0 to 1.0, we still get the same amount of transactions in our self-hosted Sentry instance.

### Expected Result

The number of transactions to drop

### Actual Result

The number of transactions doesn't change

**Comment by antonpirker** [comment]
Hey @PAKalucki 
Thanks for reporting this!
Could you tests if this is also happening if you upgrade to the newest version of the Sentry SDK?
