### ISSUE TITLE
Add measurement for number of DB queries

### ISSUE THREAD

**Issue by blueyed** [getsentry/sentry-python#1930]
### Problem Statement

I think it would be useful to have a measurement about the number of database queries that a Django app did for a transaction.

### Solution Brainstorm

This could be achieved by adding a counter to the logging/handling of queries in https://github.com/getsentry/sentry-python/blob/ff60906fcb9af3db9cda245288f2e49f70ee432f/sentry_sdk/tracing_utils.py#L134-L174, and then adding it as a measurement to the transaction in the end (https://docs.sentry.io/platforms/python/performance/instrumentation/performance-metrics/).

**Comment by sl0thentr0py** [comment]
hey @blueyed thanks for the proposal, I had a quick chat with the product folks and we don't think this is generally useful to all users, sorry!

We exposed `set_measurement` in the top-level api now with 1.16.0 so you can simply do 
```python
from sentry_sdk import set_measurement

set_measurement('num_queries', 42)
```
somewhere in your application code.

**Comment by sl0thentr0py** [comment]
to add,
we already have this info from the `db` spans server-side, so we could already expose this info in the product already if valuable. So having it is a special custom measurement doesn't really make sense as well.
