### ISSUE TITLE
Add support for Sentry Crons to Celery Beat

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#1932]
Add a decorator for celery beat tasks (or something like) where you related a sentry `monitor_id` with the task.

In the task submit this events to sentry:

When the task starts:
```
{
    "event_id":"6650bef0d8ba4a70be1d9a5ed6ee5dff",
    "sent_at":"2023-03-01T14:08:34Z",
    "dsn":"xxx",
    "sdk":{
        "name":"sentry.python.celery",
        "version":"1.16.0"
    }
}
{"type":"check_in","content_type":"application\/json"}
{
    "check_in_id":"39588134018140db8b7eb6628bccb636",
    "monitor_id":"4dc8556e-0392-45c7-bd56-9f8cf513ea42",
    "status":"in_progress",
    "duration":null
}
```

When the task finishes (or errors, the the status needs to be "error"):
```
{
    "event_id":"ff8bd082278e48d9b6632f88d642cdba",
    "sent_at":"2023-03-01T14:08:34Z",
    "dsn":"xxx",
    "sdk":{
        "name":"sentry.python.celery",
        "version":"1.16.0"
    }
}
{"type":"check_in","content_type":"application\/json"}
{
    "check_in_id":"39588134018140db8b7eb6628bccb636",
    "monitor_id":"4dc8556e-0392-45c7-bd56-9f8cf513ea42",
    "status":"ok",
    "duration":null
}
```

**Comment by evanpurkhiser** [comment]
The ideal for this will be that the user does nothing other than

> Enable Sentry Crons for all of my celery beat tasks

We have (are currently) added upsert support to checkins with user defined slugs. This means you can simply to a

```
POST https://sentry.io/api/0/monitors/<slugified-celery-task-name>/checkins/
```

which will automatically create the monitor with that name. Still TBD what passing the schedule with the checkin will look like (we'll want to translate the celery schedule to match what sentry expects), but doing this essentially means there should be practically zero configuration needed to start monitoring celery tasks.

**Comment by antonpirker** [comment]
Thanks for the update @evanpurkhiser 
"Enable Sentry for all celery beat tasks" seems cool (and not that hard to do. We create a CeleryCronsIntegration and when loaded it slaps the decorator on all tasks.)

Celery beat tasks can have multiple things as a schedule:
a) a int number of seconds (specifying and interval) 
b) a timedelta (specifying an interval)
c) a crontab
d) a solar scheduling (where you say: at "sunset" at geo location lat,lon)

What I understand from the UI of crons in the backend c) will be easy, and also a), and b) are easy. 
The solar one d) (or other custom scheduling that people implemented) will be not working right now. But I guess it is OK if we do not suppport everything under the sun at the beginning.

**Comment by evanpurkhiser** [comment]
Yes exactly. And yeah I don’t think we’ll need to support everything under the sun. I can imagine we produce some logging in the SDK that says “NOTICE: Unable to enable auto cron monitor instrumentation for xyz”

cc @dcramer to make sure this all aligns with his vision of this integration
