### ISSUE TITLE
SQLAlchemy integration fails to parse version `2.0.5.post1`

### ISSUE THREAD

**Issue by jamadden** [getsentry/sentry-python#1941]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.16.0

### Steps to Reproduce

Call `sentry_sdk.init()` with SQLAlchemy integration and install `SQLAlchemy==2.0.5.post1`.

### Expected Result

Success.

### Actual Result

```
  File "///src/.../__init__.py", line 150, in <module>
    sentry_sdk.init(
  File "///.tox/py/lib/python3.10/site-packages/sentry_sdk/hub.py", line 121, in _init
    client = Client(*args, **kwargs)  # type: ignore
  File "///.tox/py/lib/python3.10/site-packages/sentry_sdk/client.py", line 117, in __init__
    self._init_impl()
  File "///.tox/py/lib/python3.10/site-packages/sentry_sdk/client.py", line 151, in _init_impl
    self.integrations = setup_integrations(
  File "///.tox/py/lib/python3.10/site-packages/sentry_sdk/integrations/__init__.py", line 124, in setup_integrations
    type(integration).setup_once()
  File "///.tox/py/lib/python3.10/site-packages/sentry_sdk/integrations/sqlalchemy.py", line 37, in setup_once
    raise DidNotEnable(
sentry_sdk.integrations.DidNotEnable: Unparsable SQLAlchemy version: 2.0.5.post1
```

This is very similar to https://github.com/getsentry/sentry-python/issues/1811, which was fixed in #1812 but that doesn't handle all the possible [PEP440](https://peps.python.org/pep-0440/#version-scheme) variations, `[N!]N(.N)*[{a|b|rc}N][.postN][.devN]`

**Comment by razzeee** [comment]
We're seeing this with the cloud version too. Which isn't surprising I guess.

**Comment by RazerM** [comment]
The version parsing in the other integrations is equally brittle in relation to PEP 440. It's probably best to use the [regular expression provided in the PEP](https://peps.python.org/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions) and parse the `release` group:

```python
VERSION_PATTERN = r"""
    v?
    (?:
        (?:(?P<epoch>[0-9]+)!)?                           # epoch
        (?P<release>[0-9]+(?:\.[0-9]+)*)                  # release segment
        (?P<pre>                                          # pre-release
            [-_\.]?
            (?P<pre_l>(a|b|c|rc|alpha|beta|pre|preview))
            [-_\.]?
            (?P<pre_n>[0-9]+)?
        )?
        (?P<post>                                         # post release
            (?:-(?P<post_n1>[0-9]+))
            |
            (?:
                [-_\.]?
                (?P<post_l>post|rev|r)
                [-_\.]?
                (?P<post_n2>[0-9]+)?
            )
        )?
        (?P<dev>                                          # dev release
            [-_\.]?
            (?P<dev_l>dev)
            [-_\.]?
            (?P<dev_n>[0-9]+)?
        )?
    )
    (?:\+(?P<local>[a-z0-9]+(?:[-_\.][a-z0-9]+)*))?       # local version
"""

_regex = re.compile(
    r"^\s*" + VERSION_PATTERN + r"\s*$",
    re.VERBOSE | re.IGNORECASE,
)
```

Alternatively [`packaging.version`](https://pypi.org/project/packaging/) or [`parver`](https://pypi.org/project/parver/) would work (probably not worth adding a dependency here).

**Comment by sl0thentr0py** [comment]
I actually don't know historically why we have our own ad-hoc parsers in the first place. One reason might be the python2/python3 mess. 

Using something standardized given it does not add unnecessary overhead makes total sense to me.

**Comment by erdnaxeli** [comment]
I wonder why sentry should crash on this case. Should not it just not enable the integration?

**Comment by hynek** [comment]
I extremely prefer a crash over a silently disabled error reporting.

**Comment by erdnaxeli** [comment]
I don't expect my monitoring tool to crash my app.

**Comment by jace** [comment]
Folks, is there any ETA on getting this fixed? I have a pin on the SQLAlchemy version now that I'd like to remove.

**Comment by d0ugal** [comment]
You can upgrade to 2.0.6 and remove the pin

**Comment by d0ugal** [comment]
> I don't expect my monitoring tool to crash my app.

You could catch and suppress the errors from Sentry. If sentry did this for you then you wouldn't have the option of knowing or not.

**Comment by erdnaxeli** [comment]
> > I don't expect my monitoring tool to crash my app.
> 
> You could catch and suppress the errors from Sentry. If sentry did this for you then you wouldn't have the option of knowing or not.

I can catch it but I would still not have the option to know, because my alerting tool is… Sentry. I would have to use another monitoring tool to monitore that Sentry had failed, it's endless.

**Comment by hynek** [comment]
The real question is why you don’t set up Sentry in your tests. If you don’t provide a token, it will set up but not report. That’s how I found out about it.

**Comment by erdnaxeli** [comment]
> The real question is why you don’t set up Sentry in your tests. If you don’t provide a token, it will set up but not report. That’s how I found out about it.

because I didn't knew about that! thanks ^^

**Comment by hynek** [comment]
I mean unless you've fixed it, this will break the moment SQLAlchemy (or probably any other dependency like that?) releases version with a tag?
