### ISSUE TITLE
sentry-sdk stopped working with falcon 3+ asgi app

### ISSUE THREAD

**Issue by detoyz** [getsentry/sentry-python#1946]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.16.0

### Steps to Reproduce

I created a test repo where the bug can be reproduced -> https://github.com/detoyz/sentry_falcon_asgi_bug . There are also details on how to setup project & reproduce the error.

However a small summary here:
1. Install sentry-sdk 1.16.0
2. Install falcon
3. Init `falcon.asgi.App()` and try to use it via [falcon-inspect-app](https://falcon.readthedocs.io/en/stable/api/inspect.html)
4. **See error from sentry's falcon patching middleware**
5. Downgrade sentry sdk to 1.15.0
6. Your `falcon.asgi.App()` and `falcon-inspect-app` are working as expected

### Expected Result

By using sentry-sdk anywhere in the code it should not break during runtime because of any `falcon.asgi.App()` isntances

### Actual Result

Runtime errors while using `falcon.asgi.App()` isntances with sentry-sdk client
```
TypeError: _patch_prepare_middleware.<locals>.sentry_patched_prepare_middleware() takes from 0 to 2 positional arguments but 3 were given
```

**Comment by antonpirker** [comment]
Thanks for reporting this @detoyz !
I put it in our backlog, but we have a lot on our plate right now, so this will take some time.

But we are always happy about pull requests if you want to give it a shot!
