### ISSUE TITLE
Support Huey Task Queue

### ISSUE THREAD

**Issue by sloweclair** [getsentry/sentry-python#195]
Would be great to have support for https://github.com/coleifer/huey since it supports both Django and regular python scripts.

Right now when exception occurs it has 90+ breadcrumbs because it saves them from the previous jobs

**Comment by untitaker** [comment]
For the breadcrumb issue you can use this decorator for tasks:

```
def scoped(f):
    def inner(*args, **kwargs):
        with push_scope():
            return f(*args, **kwargs)
    return inner

@huey.task(..)
@scoped
def mytask(..):
    ...
```

**Comment by viperfx** [comment]
Hi there, 

Is there any support for this? I have not been able to get sentry to catch the errors from Huey.

**Comment by nerdbaggy** [comment]
I am also looking for some help with this issue. 

Even doing the following code before I still get the previous breadcrumbs. Do I need to like clear the beadcrumbs or something? 
```
with push_scope() as scope:
   do_stuff()
```

**Comment by untitaker** [comment]
Sorry, yes. This information is out of date. The new code is:

```
with push_scope() as scope:
    scope.clear_breadcrumbs()
    do_stuff()
```

**Comment by simkimsia** [comment]
I'm now subscribing to this as I am in the midst of moving away from celery

**Comment by ulgens** [comment]
I think this can be marked as done.
