### ISSUE TITLE
Officially support Python 3.11

### ISSUE THREAD

**Issue by sk-** [getsentry/sentry-python#1950]
### Problem Statement

We want to be able to use the sentry sdk in Python 3.11, knowing that we are going to get official support from Sentry.

### Solution Brainstorm

The only steps required would be to add Python 3.11 to the [classiffiers](https://github.com/getsentry/sentry-python/blob/2c8d27788c7e78a2e24e264d0e2d2f221e157658/setup.py#L87), as testing support for Python 3.11 was already added in PR #1871.

**Comment by antonpirker** [comment]
Hey @sk- 

Thanks for bringing this up! I will check next week all the stuff we need to support 3.11 officially. (maybe some docs update or so)

**Comment by sk-** [comment]
@antonpirker could you mark this as Status: Backlog ?

**Comment by danpaulson** [comment]
https://blog.sentry.io/2022/11/08/python-3-11-release-top-5-things-to-know/ - am I to understand your blog is promoting the benefits of Python 3.11 and your sdk doesn't support it? :D

**Comment by asmoker** [comment]
Is there any progress? 🤨
