### ISSUE TITLE
Span description being truncated due to Django db query being too long

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry-python#1953]
### Problem Statement

DB Queries for Django are long which makes Sentry spans truncate the description. 
<img width="1113" alt="Screenshot 2023-03-06 at 16 04 18" src="https://user-images.githubusercontent.com/25929053/223148645-f6601277-9bfd-48f3-be53-f8e59d5eea24.png">

This happens more often for Django projects, which is why we need to be able to get the full description somehow

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1765) by [Unito](https://www.unito.io)

**Comment by antonpirker** [comment]
Checked with ingest folks: If events are larger than the 1MB limit, relay just drops it.

**Comment by gggritso** [comment]
> not documented and is False by default, so it is never executed

Gotcha, thanks!

> it is totally save to just never truncate span descriptions to 1024 but keep them as they are

> big enough for almost everything

Roger that!

@antonpirker what's your feeling about this issue, overall? Is turning truncation fully off and/or making the truncation length configurable something that might happen soon? The Performance team might be able to pitch in here, if that's helpful!

**Comment by antonpirker** [comment]
With version 1.19.0 this is fixed: https://github.com/getsentry/sentry-python/releases/tag/1.19.0

So the span description is not truncated anymore. Please give it a try @gggritso if this works for you. 

One thing: we did not disable all truncation, if you have a lot of spans, they still will be truncated. But for the spans that remain, the description will not be truncated. (we will deal with the number of spans in another issue)

**Comment by antonpirker** [comment]
That was the related issue where were the PR was attached: https://github.com/getsentry/sentry-python/issues/1974

**Comment by gggritso** [comment]
@antonpirker awesome, thank you!

**Comment by karambaq** [comment]
How can I increase the size of the transaction event more than 1mb? It doesn't even show any errors, event just didn't show up on sentry.

**Comment by gggritso** [comment]
@karambaq unfortunately, you cannot increase the maximum transaction event size in Sentry, sorry! Self-hosted users can configure this in Relay.

As for the events that don't show up, you should be able to see events that were dropped from ingestion on your organization's Stats page
