### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'f_back' in profiler thread

### ISSUE THREAD

**Issue by adamchainz** [getsentry/sentry-python#1958]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.16.0

### Steps to Reproduce

Run sentry SDK with profiling on, Python 3.11

### Expected Result

The thread runs fine without crashing.

### Actual Result

The profiler thread (`<Thread(sentry.profiler.ThreadScheduler, started daemon 140454125577984)>`) fails this stack trace:

```
AttributeError: 'dict' object has no attribute 'f_back'
  File "threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
```

Unfortunately there is no more information. It looks like the full stack trace is not captured / lost, perhaps because this is an exception within a thread?

Full screenshot from Sentry UI:

<img width="1134" alt="Xnapper-2023-03-15-14 21 38" src="https://user-images.githubusercontent.com/857609/225338517-a1d7cfb3-20f6-45b1-a0e6-69cfa77d7e1e.png">

It's not clear from a quick glance at the source how a `dict` could be ending up in the profiler thread's queue.

**Comment by antonpirker** [comment]
Hey @adamchainz !

Thanks for reporting this. We will see if we can reproduce this!

**Comment by Zylphrex** [comment]
Hey @adamchainz, are you able to share the following?
- What frameworks do you use to run your application?
- How do you run it?
- How does your `sentry_sdk.init` look like?
- Do you do any monkey patching in your application? Or is there some monkey patching happening from a package you use?

**Comment by LiveNL** [comment]
Not sure if helpful, but we've had the same issue also using `gunicorn` but instead of Django we use Flask (with python 3.11).

Our init looks like:
```
sentry_sdk.init(
    integrations=[FlaskIntegration()],
    attach_stacktrace=True,
    traces_sample_rate=1.0,
    _experiments={
        "profiles_sample_rate": 1.0,
    },
    environment=Config.APP_ENV,
)
```

We went back to 1.15.0, which resolved the issues for us.

**Comment by Zylphrex** [comment]
@LiveNL @adamchainz One follow-up question for the two of you. Is this error preventing you from collecting profiles completely? Or is it happening occasionally and you are still able to collect some profiles?

**Comment by LiveNL** [comment]
The latter for us. 

Btw. the error presented itself in a few different shapes besides `'dict' object ...`:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/5443727/226431647-40f88abb-0458-4599-87a7-f2afd1a7fcc5.png">

**Comment by Zylphrex** [comment]
Yeah, I noticed that in another report. It's not clear to me how this can be happening as I cannot reproduce it. The only thing in common from all the reports so far is that they're all from Python 3.11 which may have some edge case where the API is not returning what is expected. I have #1965 to handle these errors as there's not really anything to be done when the data being returned is bad.

**Comment by adamchainz** [comment]
> @LiveNL @adamchainz One follow-up question for the two of you. Is this error preventing you from collecting profiles completely? Or is it happening occasionally and you are still able to collect some profiles?

Same here, only happening occassionally. The profiling dash has thousands of transactions but this error has occurred 33 times.

Also from the breadcrumbs I can tell it normally occurs a while from the server process startup, sometimes many hours.

It may be related to Python's shutdown procedure, where threads may still be running whilst objects and classes start getting cleaned up, which could lead to attributes seeming gone or types changed?

**Comment by Zylphrex** [comment]
Yeah, that's possible. In either case, it should be safe to handle these errors and ignore these samples like in the PR I linked.
