### ISSUE TITLE
Is ini logging configuration supported?

### ISSUE THREAD

**Issue by gforcada** [getsentry/sentry-python#196]
On raven-python this configuration was working fine and smooth:
```
[handler_sentry]
class = raven.handlers.logging.SentryHandler
formatter = generic
level = ERROR
args = ('DSN',)
```
On this new sentry-python one, as it does not have a custom ``__init__`` method to set up the DSN and so on, it fails with a traceback complaining that the DSN is not a valid level (that's what the default logging.Handler expects to be the first argument).

As the new documentation does not mention this configuration style, is that considered to be deprecated? :thinking: 

We are using this to get error reports from gunicorn, how are we supposed to configure it now?

**Comment by untitaker** [comment]
The new SDK grabs all errors from all loggers by default, so all it takes to get errors from gunicorn is to call `init()`.


You can use the [Handler](https://docs.sentry.io/platforms/python/logging/#handler-classes) directly as well but that one does not take a DSN. You still have to provide that one to `init`. The handler will take whatever client you have set up using `init` and log its data there.

**Comment by gforcada** [comment]
So in short, *ini-only* configurations are no longer supported.

**Comment by untitaker** [comment]
It is no longer possible to initialize the entire SDK via `.ini` but you can absolutely call `init()` in your code and use `ini` to wire up the logging handler I linked.
