### ISSUE TITLE
Change how the relay application AWS Lambda layers logs its own activities.

### ISSUE THREAD

**Issue by DM1145** [getsentry/sentry-python#1961]
### Problem Statement

The provided AWS Lambda layer uses a relay extension to catch and distribute data to Sentry.

This relay extension writes a significant number of entries to Cloudwatch upon start and termination, which clutters logs with unneeded entries.

The requested functionality duplicates that requested in the Sentry-Javascript ticket [6921](https://github.com/getsentry/sentry-javascript/issues/6921).

### Solution Brainstorm

Please change the default behavior of the relay process to only write cloudwatch logs on unexpected behavior.

**Comment by micah-redwood** [comment]
+1 to this! We're hoping to get our team to adopt Sentry and this is a major pain point. When log level is set to debug, CloudWatch is pretty much unusable.

**Comment by antonpirker** [comment]
We are currently working on removing relay from the lambda layers: https://github.com/getsentry/sentry-python/pull/2068

It did not bring the benefits we where hoping for, so with the next release of the lambda layers, the logs should be clean again.

**Comment by antonpirker** [comment]
With our new Lambda layers we do not run `relay` in the layer anymore, so all the log messages are gone. If you upgrade to the newest lambda layer @DM1145  and @micah-redwood and your logs are only yours and nothing from relay will be in there!

**Comment by micah-redwood** [comment]
Thanks @antonpirker !
