### ISSUE TITLE
the `is_valid_sample_rate` is refactored (moved and changed signature) from `tracing_utils` to `utils` in 1.17.0

### ISSUE THREAD

**Issue by jberends** [getsentry/sentry-python#1968]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.17.0

### Steps to Reproduce

- We use `is_valid_sample_rate` to validate if a provided sample rate is correct in our own `SentryTraceSampler` custom class. This class supports can set a sample rate according to a certain context. As indicated in https://docs.sentry.io/platforms/python/configuration/sampling/#sampling-context-data
- We found out that this function is moved from `tracing_utils` to `utils` starting in 1.17.0.
- We found out that this function uses a required additional argument `source` (string) that is used for providing more contextual information when raising an exception from that function.
- This is not documented in the CHANGELOG.md as such (or i did not capture as such).

### Expected Result

- A Changelog item with deprecation and or change of signature of this function.
- Or some documentation or code hints in the source that this is_valid_sample_rate is supposed to be an internal function and not for external developers usage.

### Actual Result

An `ImportError` trown like

```
  ...
  File "###/config/settings/production.py", line 242, in <module>
    from ###.utils.sentry import setup_sentry_tracing_settings
  File "###/utils/sentry.py", line 4, in <module>
    from sentry_sdk.tracing_utils import is_valid_sample_rate
ImportError: cannot import name 'is_valid_sample_rate' from 'sentry_sdk.tracing_utils' (###/_venv/
lib/python3.8/site-packages/sentry_sdk/tracing_utils.py)
```
`###` is masking a path to the modules in our codebase.

**Comment by antonpirker** [comment]
Hey @jberends 

Thanks for reporting this!

You are right, we moved the functions and did not make sure it is a non breaking change (and not even mention it in the changelog.)

That's our fault. We will try to be better in the future.

I hope you did not have to much hassle because of this?

**Comment by jberends** [comment]
Hi @antonpirker. Thanks for this information. We are doing fine; thanks. We just wanted you to know in order to be able to inform others. We changed our codebase and refrained from deep importing utility code from sentry-sdk in our codebase and took measures to ensure that the function actually returns a proper sample-rate.
