### ISSUE TITLE
Cannot use `with sentry_sdk.start_transaction` with async code

### ISSUE THREAD

**Issue by Bi0max** [getsentry/sentry-python#1969]
### Problem Statement

I want to use Sentry in my async worker, but there seem to be no `async with` alternative to `with sentry_sdk.start_transaction` context manager.
Is it possible to use Sentry in an async setting?

### Solution Brainstorm

Add `async with sentry_sdk.start_transaction`

**Comment by antonpirker** [comment]
Hey @Bi0max !

Thanks for writting in!

Indeed, we do not have a `async with start_transaction`.

You could create a transaction without using the with context manager, like we do internally here:
https://github.com/getsentry/sentry-python/blob/dc730ed953ffe00ad72e0a1c29e11b2caf4afe7f/sentry_sdk/integrations/opentelemetry/span_processor.py#L134-L142

If you do this, you have to make sure that you finish the transaction later:
https://github.com/getsentry/sentry-python/blob/dc730ed9

This way you can create transactions in a async context.
Does this help?

As for the `async with`: If you want to give it a go and try to implement it, we are always happy to accept pull requests!

**Comment by Bi0max** [comment]
Hi @antonpirker , thanks for reply!
I will give it a try! The only thing: the second link does not work (i get 404), could you pls send it again?

If it works and I implement `async with` internally, then I'll try to submit a pull request.

**Comment by antonpirker** [comment]
Oh, this is the correct link: https://github.com/getsentry/sentry-python/blob/dc730ed953ffe00ad72e0a1c29e11b2caf4afe7f/sentry_sdk/integrations/opentelemetry/span_processor.py#L174-L176
