### ISSUE TITLE
Make ``EventScrubber`` also scrub ``exception`` entries

### ISSUE THREAD

**Issue by DanielNoord** [getsentry/sentry-python#1986]
### Problem Statement

I'd like to use ``EventScrubber`` (added in https://github.com/getsentry/sentry-python/pull/1943) to scrub the events we send to Sentry. However, our own current scrubbing implementation also scrubs `event["exception"]` based on whether `exc_info` is in the `hint` supplied to the `before_send` hook.

Not scrubbing the exception is a blocker to adoption of `EventScrubber` for us and I think it would be nice to add this functionality.

### Solution Brainstorm

/

**Comment by sl0thentr0py** [comment]
@DanielNoord DanielNoord `event["exception"]` is an entire interface, which field in the exception do you want to scrub?
Note that the scrubber is for _stripping_ sensitive data like PII/security credentials and not for _filtering_ events you don't want to send.

**Comment by sl0thentr0py** [comment]
thanks for the snippet!

So basically the only actual container of data you're stripping is `frame["vars"]` which should be handled by this block here.
https://github.com/getsentry/sentry-python/blob/c4d03846cb3f1b157cc35d20ef73c7671839796a/sentry_sdk/scrubber.py#L108-L113
`iter_event_frames` goes through frames/stacktraces in both the `threads` and `exception` interfaces.

**Comment by sl0thentr0py** [comment]
ah sorry are you requesting `hint` based conditional scrubbing?

**Comment by sl0thentr0py** [comment]
> Just to confirm the snippet you provide is basically the same as:

yes, `iter_event_frames` will iterate through both of those fields. You're just using `hint["exc_info"]` to just check if there's an exception in there, so I think that is also no longer necessary with the scrubber. It should just work.

**Comment by DanielNoord** [comment]
Thanks! I'll start our bump then. If we do find issues I'll open a new one. Thanks for the speedy responses!
