### ISSUE TITLE
Sentry Lambda Layer Files to Execute (version 53)

### ISSUE THREAD

**Issue by DM1145** [getsentry/sentry-python#1987]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

arn:aws:lambda:us-west-2:943013980633:layer:SentryPythonServerlessSDK:53

### Steps to Reproduce

Create a new Lambda function using Python 3.9 and x86_64 architecture.
Reference the Sentry-provided layer above (see version)

Add an import reference to sentry_sdk and initialize sentry.

import sentry_sdk

sentry_sdk.init(
    dsn="https://-----------------------@-------.ingest.sentry.io/-----------------"
)

Call the lambda function.

### Expected Result

The lambda function should execute as normal, writing events to Sentry.

### Actual Result

Function does not run, throwing this error:

/opt/extensions/sentry-lambda-extension: line 3: SENTRY_DSN: unbound variable
EXTENSION	Name: sentry-lambda-extension	State: Started	Events: []
START RequestId: bdcc72e2-1f80-4c55-8217-0da2588b8db3 Version: $LATEST
RequestId: bdcc72e2-1f80-4c55-8217-0da2588b8db3 Error: exit status 1 Extension.Crash
END RequestId: bdcc72e2-1f80-4c55-8217-0da2588b8db3

**Comment by antonpirker** [comment]
You need to set an env variable called `SENTRY_DSN` and put your DSN in there. This is for the layer, so it also knows your DSN.

**Comment by DM1145** [comment]
I have to set an environment variable in the Lambda function config instead of setting the DSN on initialization, as for previous releases?
