### ISSUE TITLE
FlaskIntegration / AwsLambdaIntegration  version 0.6.2 has incorrect url and transaction tags

### ISSUE THREAD

**Issue by iteratelance** [getsentry/sentry-python#200]
_Originally posted by @untitaker in https://github.com/getsentry/sentry-python/issues/190#issuecomment-446722477_

After upgrading to 0.6.2 tags in our event stream are not accurate.  Specifically the url and transaction tag.

For example if an exception occurs at http://www.example.com/path/1234 the url tag in our stream is showing as http://www.example.com.  Furthermore the transaction tag, which we expect to be /path/1234 is registering as the name of our AWS lambda function.

We instantiate the SDK as follows:
```python
sentry_sdk.init(
    dsn=os.environ.get('SENTRY_DSN'),
    environment=os.environ.get('FLASK_ENV', 'development'),
    integrations=[FlaskIntegration(transaction_style='url'), AwsLambdaIntegration()]
)
```
Reverting to 0.5.5 solves the issue, I have not tried to apply the Zappa patch https://github.com/Miserlou/Zappa/issues/1723

It might be worth mentioning that we initialize the SDK in a common` __init__.py` file and import the sentry_sdk file in files that require it. Perhaps when sentry is initially created it is yet to know about the flask app?

`__init__.py`
```python
sentry_sdk.init(
    dsn=os.environ.get('SENTRY_DSN'),
    environment=os.environ.get('FLASK_ENV', 'development'),
    integrations=[FlaskIntegration(transaction_style='url'), AwsLambdaIntegration()]
)

def create_app(name, config=None):
    pass
```

`someapp.py`
```python
from apps import create_app
import sentry_sdk

app = create_app(__name__)

def exception_handler(e, event, context):
    sentry_sdk.capture_exception()
```

**Comment by untitaker** [comment]
Thanks! I believe I know what the cause of this issue is. Should be straightforward to fix.

**Comment by untitaker** [comment]
Actually not straightforward to fix but I am certain about the cause. It's an issue about how/in which order the event is modified. Right now the Flask integration will not set request data because there is already a request set on the event. It does this because the user might have set the request explicitly and the code can't tell whether that actually came from the user or another integration.

**Comment by untitaker** [comment]
Not sure about why this only surfaced in 0.6.2 but I assume that the old AWS lambda integration was not able to hook into the request handler because it patched less aggressively than the current one.

**Comment by untitaker** [comment]
@iteratelance can you still reproduce this with 0.6.4? A few things changed since then.

**Comment by iteratelance** [comment]
@untitaker I'll give it a try and report back

**Comment by iteratelance** [comment]
@untitaker, yes release 0.6.4 seems to resolve issues for us.  Thanks

**Comment by iteratelance** [comment]
@untitaker I spoke too soon.  The url is now correct however the transaction tag is not.

For example if an exception occurs at http://www.example.com/path/1234 the url tag in our stream is showing as http://www.example.com/path/1234 as expected however, the transaction tag, which we expect to be /path/1234 is registering as the name of our AWS lambda function. `myfunction-dev`

**Comment by untitaker** [comment]
@iteratelance could you check how #225 works for you?

**Comment by iteratelance** [comment]
@untitaker the transaction tag appears to be correct except for 404 errors.  This might be by design, but if I go to http://www.example.com/not/found  I will see a transaction = `lamda_function-dev` rather than `/not/found` as expected.

**Comment by untitaker** [comment]
@iteratelance yes I believe that setting the transaction to random user input is not great (and since this is a 404 the raw URL would be truly arbitrary).
