### ISSUE TITLE
Auto monitor celery tasks with environment support

### ISSUE THREAD

**Issue by aemr3** [getsentry/sentry-python#2000]
### Problem Statement

Currently monitor names are key names from celery beat schedule. Is it possible to append or prepend environment name so that we can differentiate tasks according to environment?

### Solution Brainstorm

We can append or prepend environment name to monitor_name variable inside _patch_celery_beat_tasks function.

**Comment by antonpirker** [comment]
Hey @aemr3 !

Thanks for bringing this up.

Monitor check ins add the `environment` of your Sentry setup automatically to the check in. 
But I just tried it and for me it was also not possible to filter the list of Cron Monitors by environment and see the check in from a environment that is not the default one (default is production)

I have asked the persons in the product team why this is happening. I will keep you posted If I hear from them!

**Comment by antonpirker** [comment]
I heard back from the API persons. This is a bug in ingesting the checkins. They will have a fix out later this week! (fyi @aemr3 )

**Comment by aemr3** [comment]
Hey @antonpirker, thank you for looking into this.

**Comment by antonpirker** [comment]
This is fixed now.
