### ISSUE TITLE
Make possible to create multiple Sentry clients

### ISSUE THREAD

**Issue by ab-budaev** [getsentry/sentry-python#2012]
### Problem Statement

**Context**
Inside my team we have a need to create multiple Sentry clients for a project (not usually, but in some specific cases). 
I've tried to figure it out if it is something we can do using sentry sdk for Python and it looked like it's impossible at the moment. 

**What I did**: 
- Tried to manually create Client, Scope and saturate their options and properties using the given public methods
- Tried to manually create Hub and do the same
- Experimented a lot with these manual actions

**Problem**
During experiments I've figured out that everything is working around the thing that is called `Hub.current` and there are some hardcoded places that are using it to get the client and the scope. 
It looks like that I need to setup current hub somewhere at the init myself, otherwise SDK will create it itself even if I have my own hub or client. 

**Thoughts**
it might be handy to make it possible to manually create Sentry clients without using `sentry_sdk.init()` function or its internals. And it could help to document if my feature request is something possible. 
Probably, something like having multiple dsn could solve my problem, but not at all - it might be needed to set up different listen levels for different dsn's. 

### Solution Brainstorm

1. Separate different SDK modules from Hub.current usage - make it possible to set up own Client, Scope and use it
2. Document how to deal if multiple Sentry setups are needed

**Comment by antonpirker** [comment]
Hey @abennett87 !

Thanks for writing in. Currently we do not support having multiple Sentry instances in one project (as you said, because we use `Hub.current` a lot.)

What is your use case? Why do you need multiple instances of Sentry in you project? Please let us understand your requirements or setup. Thanks!

**Comment by sl0thentr0py** [comment]
we've rejected this multiple times in the past as a feature but we can help you debug your setup.
There's a dedicated discussion for this here - https://github.com/getsentry/sentry-python/discussions/1521
Please move this there, closing this issue.
