### ISSUE TITLE
Add `include_source_context` option

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#2017]
### Problem Statement

Some users do not like the source context to be there and want to disable it.

### Solution Brainstorm

For this we need to add a SDK option `include_source_context` that defaults to `True`.
If set to false, the source context should not be included.

Here is probably the place where to decide whether to add the source context or not: 
https://github.com/getsentry/sentry-python/blob/antonpirker/celery-beat-wo-restart/sentry_sdk/utils.py#L614-L625

**Comment by sentrivana** [comment]
Reopening since there's a bit missing in order to finish the implementation fully.

**Comment by antonpirker** [comment]
Documentation for this option is still missing, but the option itself is already release in version `1.23.0`
