### ISSUE TITLE
AttributeError: 'NoOpSpan' object has no attribute 'set_measurement'

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry-python#2019]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.19.1

### Steps to Reproduce

1. in this PR https://github.com/getsentry/sentry/pull/47486 i am attempting to set a custom measurment

I get this type error when I run tests https://github.com/getsentry/sentry/pull/47486/commits/89b400dd7fee61e603a6c554ddb981214a0cbeb2

### Expected Result

i shouldn't get an error if the transaction isn't sampled

### Actual Result

My usage of the python SDK causes the backend to throw with this type error here.

**Comment by antonpirker** [comment]
@Majsvaffla are you using the OTel instrumenter?

**Comment by antonpirker** [comment]
@JoshFerge as the `NoOpSpan` should only be retruned if the OTel instrumenter is used this feels strange. You are not using the Otel instrumenter, right?

**Comment by JoshFerge** [comment]
this was in Sentry -- you can replicate by looking at the PR I linked and checking out the commit before I removed the `set_measurement` call

**Comment by Majsvaffla** [comment]
Hmm @antonpirker I don't think so. I'm doing `import sentry_sdk` and then `with sentry_sdk.start_transaction: ...`.

**Comment by JoshFerge** [comment]
@antonpirker any updates on this?

**Comment by JoshFerge** [comment]
@antonpirker any updates here?

**Comment by antonpirker** [comment]
Sorry this one kind of fell through the cracks. I have put this now on our board, so it should be handled soonish.

**Comment by antonpirker** [comment]
@joshuarli sorry for it taking so long, but this has been merged, and will be released soon. (probably this week)

**Comment by shikharvaish28** [comment]
@antonpirker in which version of package will this be release?
