### ISSUE TITLE
Allow setting a custom span name when tracing with `sentry_sdk.trace`

### ISSUE THREAD

**Issue by nambrosini-codes** [getsentry/sentry-python#2021]
### Problem Statement

Decorating functions with `sentry_sdk.trace` forces the name to be the function decorated. This is convenient for almost all cases except when decorating decorators that are used for many functions.

For example i have a function that decorates every db call. I would like to `sentry_sdk.trace` it but all spans have the same name. 

### Solution Brainstorm

I copy pasted `sentry_sdk.start_child_span_decorator` and put it inside a "decorator factory" so it accepts a span name, and then returns the bultin sentry trace decorator. 

The problem with this solution is that i have to repeat the error handling on the span not existing and any change other sentry code that might be added in the future.

This is my current code
```diff
+def trace_with_name(name):

    def start_child_span_decorator(func):
        if inspect.iscoroutinefunction(func):

            @wraps(func)
            async def func_with_tracing(*args, **kwargs):
                # type: (*Any, **Any) -> Any

                span = get_current_span(sentry_sdk.Hub.current)

                if span is None:
                    logger.warning(
                        "Can not create a child span for %s. "
                        "Please start a Sentry transaction before calling this function.",
                        qualname_from_function(func),
                    )
                    return await func(*args, **kwargs)

                with span.start_child(
                    op=OP.FUNCTION,
-                    description=qualname_from_function(func),
+                    description=name,
                ):
                    return await func(*args, **kwargs)

        # omitted sync case for brevity

+    return start_child_span_decorator
```

The intended usage would be
```python
@trace_with_name('custom')
def my_function():
    pass

# or even
decorated_func_with_custom_span_name = trace_with_name(name='users query')(func)('select users;')`
```

Of course the api can be refined, but the main idea would be more control over the created span name.

Thanks in advance for considering it!

**Comment by antonpirker** [comment]
Hey @nambrosini-codes 

That's a really nice idea. 
Currently we have a lot on our plates, so this will not be implemented very soon.
But we always are happy about pull requests if you (or anyone else) wants to give it a go)

**Comment by nambrosini-codes** [comment]
Hey, i'd be honored to contribute. Do you have a preferred name for such a decorator? I will prepare a PR for it

**Comment by antonpirker** [comment]
The best thing would be to enhance the existing `trace` and `start_child_span_decorator` decorators to just be able to take a `description` parameter to set the spans descriptions. So that from the developer experience you can do this:

```python
import sentry_sdk

@sentry_sdk.trace
def my_function():
    ...

@sentry_sdk.trace("customer description")
def my_function2():
    ...

@sentry_sdk.trace(description="some other thingy describing it")
def my_function3():
    ...
```

As for the decorator names: they should always have just a name that is describing what they do. As long as it is not user facing code it is not that critical. Just the existing `trace` name needs to stay the same.

**Comment by antonpirker** [comment]
After internal discussions we decided to not implement this for now.

If there is a strong urge by the community someone cal always create a new issue and PR and link to this.
