### ISSUE TITLE
AttributeError:  'function' object has no attribute 'co_filename'

### ISSUE THREAD

**Issue by amureki** [getsentry/sentry-python#2022]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.20.0

### Steps to Reproduce

- Run sentry SDK with profiling on
- Python 3.11.3
- Django 4.1

```python
sentry_sdk.init(
    dsn=SENTRY_DSN,
    release=os.getenv("HEROKU_RELEASE_VERSION"),
    server_name=os.getenv("HEROKU_DYNO_ID"),
    integrations=[DjangoIntegration(), sentry_logging, RedisIntegration()],
    send_default_pii=True,
    debug=os.getenv("SENTRY_DEBUG") in TRUE_VALUES,
    traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
    _experiments={
        "profiles_sample_rate": 1.0,
    },
)
```

### Expected Result

No errors here

### Actual Result

```
AttributeError: 'function' object has no attribute 'co_filename'
  File "threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
```

**Comment by amureki** [comment]
I guess, it is similar to #1958

**Comment by amureki** [comment]
I do not think the server is crashed, at least I do not see any traces of it in the logs.
I honestly did not test it without profiling, but it seems to be connected to the previous issue, so do we need to test it without it? I do not want to change configuration for now.

Also, I don't know if this is easily reproducible, but if I'd be able to - will provide further feedback!

**Comment by Zylphrex** [comment]
> I do not think the server is crashed, at least I do not see any traces of it in the logs.
> I honestly did not test it without profiling, but it seems to be connected to the previous issue, so do we need to test it without it? I do not want to change configuration for now.
> 
> Also, I don't know if this is easily reproducible, but if I'd be able to - will provide further feedback!

I don't think you need to change anything for now. As far as I can tell, it only crashes the profiler without affecting your application. So the main impact is that you won't get any profiles.

We'll have this fixed up soon 👍
