### ISSUE TITLE
"Sentry is attempting to send x pending error messages" showing up despite no error occurred

### ISSUE THREAD

**Issue by fguy** [getsentry/sentry-python#2027]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.19

### Steps to Reproduce

1. Ran a process integrating with Sentry performance
2. Finished without error
3. This shows up:
```
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

### Expected Result

Sentry is attempting to send 2 pending ~~error messages~~ -> events
Waiting up to 2 seconds
Press Ctrl-C to quit

### Actual Result

<img width="389" alt="image" src="https://user-images.githubusercontent.com/1557628/233728484-7d9e6574-96c6-49ad-bef0-892f484bb1bf.png">

It seems like sentry-python handles errors and traces in the same way in atexit callback. Please update the message from "error messages" to "events" if so.

**Comment by antonpirker** [comment]
Hey! Thanks for bringing this up.
Currently we are a bit swamped, so we have no resources to fix this.
But I added the "good first issue" label. So maybe someone picks it up!

If you want to give it a go yourself, PRs are always welcome!
