### ISSUE TITLE
Add `cache.hit` data to Django spans

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#2043]
### Problem Statement

We want to add information on if a configured cache was hit or missed in Django. 

See also https://github.com/getsentry/team-webplatform-meta/issues/60

### Solution Brainstorm

There are multiple ways to cache data in Django, we probably have to monkey patch Django in various places:
- per-site cache (middlewares) https://docs.djangoproject.com/en/4.2/topics/cache/#the-per-site-cache
- per-view cache (decorator) https://docs.djangoproject.com/en/4.2/topics/cache/#the-per-view-cache
- Template fragment caching (template tag) https://docs.djangoproject.com/en/4.2/topics/cache/#template-fragment-caching
- low level cache api https://docs.djangoproject.com/en/4.2/topics/cache/#the-low-level-cache-api
- async flavor of low level cache api https://docs.djangoproject.com/en/4.2/topics/cache/#asynchronous-support

Maybe just patching the low level cache api will handle all the cases.

**Comment by AbhiPrasad** [comment]
@antonpirker mind linking some example transactions that has these values? Screenshots are cool as well 😄
