### ISSUE TITLE
Duplicate crons created by django-celery-beat

### ISSUE THREAD

**Issue by joshuata** [getsentry/sentry-python#2046]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.20.0

### Steps to Reproduce

1. Set up project using celery and [django-celery-beat](https://github.com/celery/django-celery-beat)
2. Initialize sentry SDK using `CeleryIntegration(monitor_beat_tasks=True)`
3. Create a periodic task using the admin interface to execute once every 15 minutes
4. Check cron tab after the periodic task has executed

### Expected Result

A single check-in for the task every 15 minutes

### Actual Result

One successful cron and missed cron for each task execution.

I have tried editing the time until missed in the cron settings, but it seems to be reset each time it updates.

![Cron history](https://user-images.githubusercontent.com/3958801/234436606-4fb4dda4-7c91-4cca-8e96-7c9cd2cda465.png)

**Comment by antonpirker** [comment]
Hey @joshuata !
Thanks for reporting this. We will have a look!

**Comment by joshuata** [comment]
Disregard the last comment. The problem regressed shortly after I commented that.

At this point my best bets for the bug cause are:
- Interaction with django-celery-results causing the registration method to be called multiple times
- Interaction with django-celery-beat causing the registration method to be called multiple times
- Our CI setup deploys several times a day - the missed checkins may be from a version that are no longer running

**Comment by joshuata** [comment]
This problem seems to have resolved itself with recent updates to the sdk
