### ISSUE TITLE
Import of deprecated flask.Markup

### ISSUE THREAD

**Issue by kasium** [getsentry/sentry-python#2056]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.21.0

### Steps to Reproduce

https://github.com/getsentry/sentry-python/blob/2c3e8b2b000427d70cc41a5b1c5a1483f7202ddb/sentry_sdk/integrations/flask.py#L29

The import of flask.Markup is deprecated with flask 2.3

### Expected Result

Import is adjusted to avoid a deprecation warning and to be future proof

### Actual Result

Deprecation warning

**Comment by ala-ableton** [comment]
This is fixed in https://github.com/getsentry/sentry-python/pull/2047

**Comment by kasium** [comment]
Thanks
