### ISSUE TITLE
Sampling rates not working as expected?

### ISSUE THREAD

**Issue by ashleyxue529** [getsentry/sentry-python#2063]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.20.0

## Before (everything is logged to sentry)
```
sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN", None),
    integrations=[
        DjangoIntegration(),
    ],
    profiles_sample_rate=1.0,
    send_default_pii=True,
)
```
## After (an abnormally small percentage is logged to sentry, almost no transactions going through)
```
sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN", None),
    integrations=[
        DjangoIntegration(),
    ],
    traces_sample_rate=0.5, <-- added
    profiles_sample_rate=1.0,
    send_default_pii=True,
)
```

### Expected Result

Roughly 0.5 of our profiling/performance logs will come through and all errors will still come through.

### Actual Result

Not even 10% of the original volume is coming through. The dropoff in the image below is when the 'traces_sample_rate=0.5' value was added to sentry init. Am currently unsure if all of our errors are still coming through. Is our setup incorrect? Our goal is to have:
- ALL errors logged AND
- Performance/Profiling transactions sampled AND
- Certain endpoints to be unsampled

![image](https://user-images.githubusercontent.com/8787344/235740214-7db3acb1-e6a5-48e7-b4e8-08108eba38b7.png)

## Remaining Questions
- Would this setup do the trick?
```
def traces_sampler(sampling_context):
    # If there's already a sampling decision, just use that
    if sampling_context["parent_sampled"] is not None:
        return sampling_context["parent_sampled"]

    # 100% endpoint sample overrides
    if "wsgi_environ" in sampling_context:
        try:
            path = sampling_context["wsgi_environ"].get("PATH_INFO", None)
            if path and path in os.environ.get("SENTRY_FULL_SAMPLE_RATE_PATHS", []):
                return 1.0
        except Exception:
            pass

    return os.environ.get("SENTRY_TRACES_SAMPLE_RATE", 0.5)

sentry_sdk.init(
      dsn=os.environ.get("SENTRY_DSN", None),
      integrations=[
          DjangoIntegration(),
      ],
      traces_sampler=traces_sampler,
      profiles_sample_rate=1.0,
      send_default_pii=True,
  )
```

- I saw `profiles_sample_rate` is relative to the `traces_sample_rate`, does that mean if `traces_sample_rate=0.5` and `profiles_sample_rate=1.0`, only roughly `0.5` of potential profiles will be logged?
- Does setting `traces_sampling_rate` affect the error sampling rate? If I want all errors logged, will setting a value here prevent that?

Thank you! Apologies if this is the wrong place to ask these.

**Comment by sl0thentr0py** [comment]
hi @ashleyxue529, can you contact support for this? There can be many reasons for this (rate limits, dynamic sampling, quota) and they can help you debug the correct reason.

**Comment by cleptric** [comment]
> I saw profiles_sample_rate is relative to the traces_sample_rate, does that mean if traces_sample_rate=0.5 and profiles_sample_rate=1.0, only roughly 0.5 of potential profiles will be logged?

This is correct.

> Does setting traces_sampling_rate affect the error sampling rate? If I want all errors logged, will setting a value here prevent that?

No, the amount of errors sent is controlled by `sample_rate`, which defaults to `1.0`.
The `traces_sampling_rate` only affects transactions and profiles to some extent.
