### ISSUE TITLE
capture_message not working inside scheduled celery tasks

### ISSUE THREAD

**Issue by kid-alan** [getsentry/sentry-python#2066]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.20.0

### Steps to Reproduce

1. Make a periodic task
2. Add a `sentry_sdk.capture_message("Hello!")` to it.
3. Observe that the task is executed successfully, but the message does not appear in Sentry.

Example task:
```
import sentry_sdk
from celery import shared_task

@shared_task
def notify_something():
    results = do_something()
    sentry_sdk.capture_message('Results: %s' % results, level='fatal')
```

### Expected Result

Expected the message to be sent to Sentry.

### Actual Result

Message is not being sent, despite the task being executed properly.
Task results are saved to TaskResults model, and there they are with a proper complete dates and a SUCCESS status.

At version 1.15.0 we had this task running every hour and got the message in the Sentry.
After upgrading to 1.20.0 we noticed that the message flow have stopped.
Downgrading back to 1.15 fixed the problem.

Another interesting thing. If you go directly to the django server, drop into interactive session and do:
* Execute the task directly: `notify_something()` — message is being properly sent.
* Execute the task async: `notify_something.delay()` — message is being properly sent.

It is only when it is executed by celerybeat schedule it is not being sent properly.

**Comment by antonpirker** [comment]
Hey @kid-alan !
Better late then never. I have just tried this with Sentry SDK 1.35.0, Python 3.9.15:

```python
# tasks.py
import os 
from celery import Celery
from celery.schedules import crontab
from celery import shared_task

import sentry_sdk
sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN"),
    enable_tracing=True,
    debug=True,
    send_default_pii=True,
)

app = Celery("tasks", broker='redis://localhost:6379/0')
app.conf.beat_schedule = {
    'my_task_from_beat': {
        'task': 'tasks.my_task',
        'schedule': crontab(minute='*/1'),
        'args': ('BEAT',),
    },
}

@shared_task
def my_task(msg=""):
    sentry_sdk.capture_message('Results!', level='fatal')
```

This is how I start celery:
```
celery -A tasks.app worker \
    --loglevel=INFO \
    -c 1
```

And this how I start celery beat:
```
celery -A tasks.app beat \
    --loglevel=INFO
```

Everything works like advertised, the message ends up in Sentry. Can you try again with updated Sentry SDK and make sure that beat really executes the task?

**Comment by kid-alan** [comment]
Hello, @antonpirker ! I am a bit late to the party too. :) Thanks for taking a time to look into issue. I guess a few updates later that issue was somehow resolved. We don’t notice this problem anymore.

Thanks again. Have a good one!

**Comment by antonpirker** [comment]
Nice to here @kid-alan!
