### ISSUE TITLE
Breadcrumbs from previous requests or from bootup

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#207]
Continuation of https://github.com/getsentry/sentry-python/pull/206, cc @dimrozakis

**Comment by untitaker** [comment]
>In my scenario, I have uwsgi processes running django and a number of celery workers. During startup they all log several messages that end up in breadcrumbs. Any event that occurs during the handling of a django request or celery task will carry all the initial breadcrumbs which can at times be more than 40.

Yes we run into this thing ourselves at Sentry when using our own SDK.

I think we should just have a public stable method to clear breadcrumbs on the scope and that'd be it.

**Comment by dimrozakis** [comment]
Do you think that in addition to having a public stable method to clear breadcrumbs on the scope, it'd also make sense to call this method in cases like the wsgi and celery integrations (perhaps depending on a configurable flag)? It could be done on the application side with the use of extra middlewares etc, but I think it'd be really helpful to get it from the sdk.

**Comment by untitaker** [comment]
Oh yeah that's what I meant, basically. I don't think there's a need to make it configurable.

**Comment by dimrozakis** [comment]
Thanks for clarifying, glad we're on the same page. Should I go ahead with another PR or do you prefer for this to be handled by the sentry team?

**Comment by untitaker** [comment]
@dimrozakis I have no objections to you implementing it or being part of this conversation but basically @HazAT needs to know and agree to this approach.

**Comment by jrideout** [comment]
I have the same issue with the awslambda integration. I see breadcrumbs from prior lambda invocations that are irrelevant to the current invocation.

**Comment by untitaker** [comment]
I think another issue that breadcrumbs are already partially cleared because we create new hubs for each WSGI request, for example. So it's not even consistent across integrations within the Python SDK.

At least in recent versions of the SDK this issue should no longer occur for Flask and Django, but is stil present for Celery.

**Comment by rouge8** [comment]
I also see this issue with Pyramid + gunicorn with gevent workers.

![Screen Shot 2019-03-14 at 09 50 10](https://user-images.githubusercontent.com/237005/54375575-8385a000-463e-11e9-86ed-d65fef93143a.png)

**Comment by untitaker** [comment]
Just as an update: We decided that a `Scope.clear_breadcrumbs` method + using it in integrations is the way to go. It just needs to be implemented.

**Comment by untitaker** [comment]
This should be fixed in the next release. It recently became clear how inconveniencing this issue is for reading events. Apologies for the wait.

btw I believe there's the chance that a few of you encounter concurrency issues entirely unrelated to this issue. A common problem is that [`gevent.monkey`](http://www.gevent.org/api/gevent.monkey.html) is currently needed to avoid request data "leaking" between events. If your issue is still not fixed in the next release please open a separate issue.
