### ISSUE TITLE
do not recursively create events while processing events

### ISSUE THREAD

**Issue by mmerickel** [getsentry/sentry-python#208]
1. Configure LoggingIntegration and PyramidIntegration.
1. Put `log.error` statements in authentication policy's `authenticated_userid` function.
1. Trigger some unrelated error during a request.
1. Observe infinite recursion as the event processor in PyramidIntegration invokes `request.authenticated_userid` which triggers creation of new events, until the process crashes.

It seems that `capture_internal_exceptions` should also temporarily disable the creation of new events by the hub.

**Comment by mmerickel** [comment]
I'm not sure exactly how to approach it right now. My initial impression is to add a flag to the scope and check for it in `client._should_capture`. I'd then modify `capture_internal_exceptions` to set that flag but turn it off before invoking the `debug_hub` so that `capture_internal_exceptions` can still catch / create events.

Another, possibly better, way to look at it is to have `client._prepare_event` manage a flag on the scope around the processors. This would prevent any events from being emitted while processing an event, but that might prevent `capture_internal_exceptions` from emitting errors it catches unless I work around that somehow.

**Comment by untitaker** [comment]
I would attach this to capture_internal_exceptions.
