### ISSUE TITLE
DjangoCache `IndexError` raised when using keywords approach

### ISSUE THREAD

**Issue by sshishov** [getsentry/sentry-python#2085]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.22.1

### Steps to Reproduce

1. Install the latest version
2. Run the code with django cache and get the key using keyword approach
3. Observe `IndexError` issue

Snippet:
```python
from djang.core.cache import cache

cache.get(key="my_key")  #  <-- `IndexError` as there will no `args[0]` which is used for spans
```

### Expected Result

No exception raised and value retrieved

### Actual Result
`IndexError` raised:
```python
IndexError
tuple index out of range
```

**Comment by antonpirker** [comment]
Thanks for reporting this @sshishov !
I will fix this.
