### ISSUE TITLE
Django WSGI integration logs exceptions with odd titles

### ISSUE THREAD

**Issue by beaugunderson** [getsentry/sentry-python#209]
For example:

![screen shot 2018-12-14 at 10 57 00](https://user-images.githubusercontent.com/61791/50021931-700b6000-ff8f-11e8-9271-60e2ee55920f.png)

We have hundreds of these, ~and they don't seem to group correctly either~. They do group correctly, as shown in the screenshot below. It's just confusing because they all start with the same string.

In this specific case the root cause seems to be WSGI returning a 403 response because someone made a request to an endpoint that requires authorization without being logged in...

The other confounding factor here is that the view in question is a Django Rest Framework `APIView`.

~I had a little bit of trouble tracking this down because it doesn't seem to happen when using Django's `runserver` but it does underneath `uwsgi`.~ Still tracking down what causes this to happen in production but locally...

**Comment by beaugunderson** [comment]
These are all either a 403 or a 400:

![screenshot](https://i.imgur.com/ImDE2Hw.png)

**Comment by untitaker** [comment]
@beaugunderson could you post a screenshot of the issue detail page of one of them? There is some information on there on which hook recorded the event. I suspect some stray logger from whichever WSGI server you are using.

**Comment by beaugunderson** [comment]
@untitaker i see this for the logger:

![screenshot](https://i.imgur.com/cSNrnqx.png)

**Comment by beaugunderson** [comment]
![screenshot](https://i.imgur.com/PkORujE.png)

![screenshot](https://i.imgur.com/quw6ZWy.png)

**Comment by untitaker** [comment]
The relevant value should be as tags in the event and there should also be a section called "mechansim"

**Comment by untitaker** [comment]
I think this should fix your problem anyway:

```python
from sentry_sdk.integrations.logging import ignore_logger

ignore_logger("django.request")
```

**Comment by beaugunderson** [comment]
ah, i see `django.server` is already ignored there 👍

is the idea that anything logged with `logger.error(...)` goes to Sentry automatically?

**Comment by untitaker** [comment]
You're spot on. Maybe I misremembered the mechanism stuff, probably logging is a case where it's just not there.

**Comment by untitaker** [comment]
Ah mechanism only exists for exceptions, lol

**Comment by untitaker** [comment]
Yes I will release a fix but it will take a while. I think you can use the snippet above to work around it for now though

**Comment by beaugunderson** [comment]
@untitaker gotcha--i was unsure if `ignore_logger` needed to be called at a certain point in sentry-sdk's initialization; will try and report back 👍

**Comment by untitaker** [comment]
You can call it wherever. Wouldn't call it in a request handler though
