### ISSUE TITLE
AttributeError: 'async_generator_athrow' object has no attribute '__qualname__'

### ISSUE THREAD

**Issue by knkski** [getsentry/sentry-python#2093]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.19.1

### Steps to Reproduce

I'm trying to use the `asyncio` integration like this:

```python
sentry_sdk.init(dsn=os.environ.get("SENTRY_DSN"), traces_sample_rate=0.1, integrations=[AsyncioIntegration()])
```

I keep on getting a traceback that seems to be a Sentry-specific issue.

### Expected Result

No tracebacks repeatedly occur

### Actual Result

I see this traceback repeatedly printed in the logs:

```python
Task exception was never retrieved
future: <Task finished name='Task-1512' coro=<patch_asyncio.<locals>._sentry_task_factory.<locals>._coro_creating_hub_and_span() done, defined at /usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asyncio.py:34> exception=AttributeError("'async_generator_athrow' object has no attribute '__qualname__'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/asyncio.py", line 40, in _coro_creating_hub_and_span
    with hub.start_span(op=OP.FUNCTION, description=coro.__qualname__):
AttributeError: 'async_generator_athrow' object has no attribute '__qualname__'
```

**Comment by sl0thentr0py** [comment]
@knkski can you give an example of what your task looks like? for some reason it doesn't have `__qualname__`.

**Comment by sl0thentr0py** [comment]
ok I found this note in `cpython`
https://github.com/python/cpython/blob/438b811761da124b949265d233f9fd9a74d7dd3f/Lib/asyncio/coroutines.py#L51-L63
