### ISSUE TITLE
Django patch breaks cache

### ISSUE THREAD

**Issue by nicootto** [getsentry/sentry-python#2094]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.22.2

### Steps to Reproduce

```python
# Sentry instrumentation here

class NoBool:
    def __bool__(self):
        raise NotImplementedError

from django.core.cache import cache
cache.set(1, NoBool())
cache.get(1)
```

### Expected Result

The instance of `NoBool` saved

### Actual Result

`NotImplementedError`

This is the PR that introduced the bug https://github.com/getsentry/sentry-python/pull/2057 , I commented over there what you should be doing instead :)

**Comment by oizik** [comment]
Hit this one last night was going to put in a bug request this morning you beat me to it :)

We cache `DataFrame`s and PR for [#2507](https://github.com/getsentry/sentry-python/pull/2057) breaks the caching with error:

```
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()  
```

The work around is either to pin sentry-sdk to v1.21.1, or disable cache spans as described in the [docs](https://github.com/getsentry/sentry-python/blob/master/CHANGELOG.md#1220) with 

```
 DjangoIntegration(cache_spans=False),
```

The error is raised from line 51 of [`caching.py`](https://github.com/getsentry/sentry-python/blob/8a2b74f58e97205233717c379b0d78f85d697365/sentry_sdk/integrations/django/caching.py#L51)

**Comment by oizik** [comment]
Here is a basic test that reproduces the issue: https://github.com/oizik/sentry-python/commit/785e800d14dc78f22fb8289d922c2ca0522897af

**Comment by oizik** [comment]
I have added a fix for this https://github.com/getsentry/sentry-python/compare/master...oizik:sentry-python:django_caching_spans_issue_2094

Let me know if it's worthy of a PR?

**Comment by antonpirker** [comment]
Hey! 
Thanks @nicootto  for reporting this and @oizik for the fix. 
Could you please create a PR? Definitely worth it!

**Comment by oizik** [comment]
@antonpirker I have created the pull request: https://github.com/getsentry/sentry-python/pull/2098 

On a side note as I was going though the code, I noticed [this line in `caches.py`](https://github.com/getsentry/sentry-python/blob/e0209db8076aaf4d2f90d83fe5379f8591c5d8ee/sentry_sdk/integrations/django/caching.py#L54)

```python
size = len(text_type(value).encode("utf-8"))
```

The `value` from what I understand is the value retrieved from the cache. 

The line takes a `str`ing representation of the value and calculates the number of characters in the resulting string. Is that the intended behavior?

**Comment by whyscream** [comment]
In https://github.com/getsentry/sentry-python/pull/2120, Django cache spans are disabled by default. So unless Sentry enables them again, users bitten by this issue should be safe to upgrade Sentry to the latest version, right?

**Comment by antonpirker** [comment]
> In #2120, Django cache spans are disabled by default. So unless Sentry enables them again, users bitten by this issue should be safe to upgrade Sentry to the latest version, right?

Yes, correct. Users can upgrade and disable Django Cache spans with the `cache_spans` option described here: https://docs.sentry.io/platforms/python/guides/django/#options
