### ISSUE TITLE
`http.response.status_code` normalization for Metrics & Alerts

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-python#2099]
Background:
http.status is set in different places in different SDKs which creates some problems in processing for metrics extraction and then

https://www.notion.so/sentry/Expand-Metrics-for-Alerts-cdfa32d7624e498b8246c3f131f753f1#17480955e2fb4407b619b9236bc2723a

**Requirements:**
Need status code number (standard HTTP status code 2xx, 4xx, 5xx, etc)
The SDK should never on it's own set this as a tag - as this adds expense due to indexing being based on tags
the location of storage needs to be in a standard location based on span schema
follow existing standard in [develop docs](https://develop.sentry.dev/sdk/performance/span-operations/)
Starfish has a workstream to standardize span schema https://github.com/getsentry/rfcs/pull/89

**Comment by antonpirker** [comment]
UPDATE: The span data fields should be called `http.response.status_code`. See: https://develop.sentry.dev/sdk/performance/span-data-conventions/#http
