### ISSUE TITLE
Cron checkins are not sent for celery beat tasks

### ISSUE THREAD

**Issue by strokirk** [getsentry/sentry-python#2104]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.22.2

### Steps to Reproduce

Using these versions:
```
sentry-sdk==1.22.2
celery==4.4.7
```

And the default configuration with automatic cron monitoring for Celery Beat enabled:
```
CeleryIntegration(monitor_beat_tasks=True)
```

### Expected Result

- Cron Monitors should be set up
- Checkins should be done automatically

### Actual Result

- Cron Monitors are set up for all Beat schedule items ✅ 
- No checkins occur 💥

**Comment by antonpirker** [comment]
Hey @strokirk 
Thanks for reporting this! Yes, I have also noticed this and I am working on a fix right now.
