### ISSUE TITLE
Native asyncio Transport

### ISSUE THREAD

**Issue by dimaqq** [getsentry/sentry-python#2118]
### Problem Statement

Some of my programs (typically web server nodes) are purely asyncio (no thread pools, no blocking calls).

A program like this has some advantages (deployment, containerisation, debugging) that I would like to keep.

I'd like to be able to use Sentry too, but it only gives me one option, `urllib3` and the `Transport._send_request` has logic (dropped records) intermingled with blocking calls (self._pool.request), which makes writing own chimera transport kinda hard.

### Solution Brainstorm

So, like bring back the raven days, but with a modern transport.

**Comment by antonpirker** [comment]
Hey @dimaqq !

I guess the solution would be to write a pure ayncio Transport as replacement for `HttpTransport` based on `aiohttp` or something.

Wanna give it a go?

**Comment by sl0thentr0py** [comment]
tbh I don't know if we will support this ootb, but if you manage to get something running, we should add it to the examples in https://github.com/getsentry/sentry-python/discussions/1484.

> Transport._send_request has logic (dropped records) intermingled with blocking calls (self._pool.request)

to understand your use case, would you like to just implement the actual `pool.request` yourself and keep the surrounding logic the same? You can in principle just ignore the `record_loss` stuff, that just adds some statistics called [`Client Reports`](https://develop.sentry.dev/sdk/client-reports/) that are used to count drops on the client side.
