### ISSUE TITLE
Django cache_spans cause excessive overhead

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-python#2122]
We noticed a drastic uptick in latency for a few key endpoints that utilize the cache (redis) starting on May 8th. After looking through what we deployed we noticed an update to `sentry-sdk` from `1.21.1` to `1.22.1`. After looking at the change log the "add some overhead to your server" comment stood out and so we reverted this upgrade yesterday and the endpoint normalized.  ![Here is a screenshot of the endpoint's latency](https://github.com/getsentry/sentry-python/assets/5312952/07a46f9c-a1e8-4651-bfcb-be9c5cd1f19f)

This is our sentry init if it helps:

```
sentry.init(
        before_send=event_filter,
        dsn=settings.SENTRY_DSN if get_environment() in ['production', 'staging'] else '',
        environment=get_environment(),
        integrations=[CeleryIntegration(), DjangoIntegration(), RedisIntegration(), SqlalchemyIntegration()],
        release=get_release(),
        send_default_pii=True,
    )
```

_Originally posted by @dvprz in https://github.com/getsentry/sentry-python/issues/2116#issuecomment-1550101647_

**Comment by jarekwg** [comment]
This knocked out our servers, causing a severe outage across many customers.
We had to roll back our latest release as it took a while to diagnose that the CPU shredding was a result of bumping sentry.
The irony of having an error monitoring framework causing a major outage....
Would it be possible to mark releases as beta or something when they're introducing this level of risk?

**Comment by HazAT** [comment]
@jarekwg you are entirely correct, and we apologize that this happened.
We already had an internal conversation about making sure we roll out changes similar to this with more care.

**Comment by antonpirker** [comment]
We added a parameter `cache_spans` to `init()` that defaults to `False`. See the [documentation](https://docs.sentry.io/platforms/python/integrations/django/#options). This resolves this issue.
