### ISSUE TITLE
Distributed Tracing in Python with FastAPI and Requests

### ISSUE THREAD

**Issue by joelhess** [getsentry/sentry-python#2127]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.23

### Steps to Reproduce

I'm trying to get distributed tracing working between two FastAPI Python Projects. I'm using an http client between them that is an overloaded version of Requests, and I'm not seeing the headers pass between the two automatically. 

As a test, I also just tried to add the `sentry-trace` and `trace-id` headers to the request. 

```
span = sentry_sdk.get_current_span()
headers["trace-id"] = span.trace_id
headers["sentry-trace = "1" if span.sampled else "0"
```
I see sampled events for both services in the dashboard, but they're under separate traces. 

### Expected Result

Headers attaching magically as described in the docs, or at least everything tied together when I set the headers on the request myself. 

### Actual Result

Separate traces/spans between services

**Comment by antonpirker** [comment]
Hey @joelhess 

Thanks for writing in! Can you turn on `debug=True` on your project that sends the request to the second project and see if you have any log statements starting with `[Tracing] Adding ` in your console output?

Could you post the output here?

Sentry patches `http.client.HTTPConnection.putrequest` that is used by `requests`. So if your overloaded version of requests also uses this, it should work in theory.

**Comment by joelhess** [comment]
I do see the trace logs suggesting that they're adding the headers on now. So it seems like the SDK is working as intended. I think I was looking at the wrong spot in the web console. Thanks for the insight on the logs and apologies for not digging deeper.
