### ISSUE TITLE
Make `MAX_PROFILE_DURATION_NS` a parameter of `sentry_sdk.init()`

### ISSUE THREAD

**Issue by evroon** [getsentry/sentry-python#2129]
### Problem Statement

`MAX_PROFILE_DURATION_NS` is defined as a constant here:

https://github.com/getsentry/sentry-python/blob/565567f9c440d9f9e0e20396a91571961a4337c5/sentry_sdk/profiler.py#L391

For our application, we have transactions that last much longer than 30 seconds. We would like to view the full profiles of those transactions. I couldn't find such a cutoff constant/variable in https://github.com/getsentry/sentry, so I assume it's something that's only defined on the client side?

I was also wondering whether setting the cutoff higher than 30 seconds (let's say 30 minutes instead) has noticeable disadvantages?

### Solution Brainstorm

My proposal is to transform this value from a constant to a parameter of `sentry_sdk.init()`. This way, the user can determine the cutoff of profile durations.

**Comment by Zylphrex** [comment]
Hey @evroon, at this time, profiles are only sent at the end of the transaction. This means that the entire payload is sent at once. If you were to buffer a 30-minute profile in the SDK, it can easily cause your application to run out of memory as it has to hold all that data for the entire 30 minutes.

We have thought about this but this isn't something on our roadmap at this time. For more information, you can follow getsentry/sentry#48931

**Comment by evroon** [comment]
Thanks for your reply @Zylphrex. The memory issue makes sense, I will subscribe myself to that issue for updates, thanks

**Comment by realkosty** [comment]
Beta is available for iOS, Node.js, and Python:

https://sentry.io/changelog/continuous-profiling-available-for-early-adopters/
