### ISSUE TITLE
Custom local variable exclusions

### ISSUE THREAD

**Issue by huntfx** [getsentry/sentry-python#2140]
### Problem Statement

Could we have a way to exclude certain variable types from the stack trace?

---------------

The "local variable" feature of Sentry was hammering an external API we use, because their objects are dict-like, and Sentry was [serialising each one as a dict](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/serializer.py#L329), causing a separate database call for each value. The sheer number of calls was causing the whole API to start throwing out 502 errors.

Setting `include_local_variables=False` has alleviated the issue, but it would be nice to keep that as `True` and just target specific variable types only.

I'd attempted using `before_send`, but that [runs _after_ all the serialisation](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/client.py#L322-L325), so wasn't helpful in this case. 
```python
def before_send(event, hint):
    for value in event['threads']['values']:
        for frame in value['stacktrace']['frames']:
            for k, v in dict(frame['vars'].items()):
                if isinstance(v, invalid_class):
                    del frame['vars'][k]
    return event
```

### Solution Brainstorm

Perhaps something around the lines of a `local_variable_exclude` option similar to this?

```python
sentry_sdk.init(
    local_variable_exclude=lambda name, var: name == 'ignore' or isinstance(var, MyType)
)
```

Then for the `_Client._prepare_event` method:

```python
local_variable_exclude = self.options['local_variable_exclude']
if callable(local_variable_exclude):
    for value in event['threads']['values']:
        for frame in value['stacktrace']['frames']:
            for k, v in dict(frame['vars'].items()):
                if local_variable_exclude(k, v):
                    del frame['vars'][k]
```

**Comment by sentrivana** [comment]
Hey @huntfx, thanks for this suggestion. This sounds like something that could also be achieved by using a custom [EventScrubber](https://docs.sentry.io/platforms/python/guides/logging/data-management/sensitive-data/#scrubbing-data). We [run the event through the provided scrubber before serializing](https://github.com/getsentry/sentry-python/blob/396cc668d0a7b80d43aa1f97733fb4430aff6986/sentry_sdk/client.py#LL315C1-L323C6). Let me know if this works dor you.

**Comment by huntfx** [comment]
Thanks, that's worked great:

```python
class CustomScrubber(EventScrubber):
    def scrub_event(self, event):
        for frame in sentry_sdk.utils.iter_event_frames(event):
            if 'vars' in frame:
                for k, v in dict(frame['vars'].items()):
                    if isinstance(v, SomeType):
                        del frame['vars'][k]
        return super(CustomScrubber, self).scrub_event(event)
```

My only thought was that it's a shame `scrub_frames` exists but provides no hook to do custom things per frame. For example if it called `scrub_frame` as an intermediate method before `scrub_dict`, then it'd be a bit nicer to subclass.

But again this is quite a niche use case I've got here, so I'm happy for you to close this if you like.

**Comment by sentrivana** [comment]
Nice! Yeah, the way it is now you need to manually iterate through the frames in the subclass if you want to do something extra there. We could consider adding hooks for doing stuff per frame, per breadcrumb and per span to make subclassing a bit more comfy. The scrubber is fairly new and purposefully simple since we wanted to see how folks would use it and what features would be useful for them, so this is definitely valuable input. It goes a bit in the direction of making the scrubber a more generic tool, not just for scrubbing sensitive data, so we'll have to consider if that's something we want. But I do see the benefit.

Will close this now since the original issue is fixed, but I'll keep the hooks idea in mind. (But feel free to submit a new issue for it if you like.)
