### ISSUE TITLE
Stack locals missing from gevent greenlets

### ISSUE THREAD

**Issue by ghost** [getsentry/sentry-python#215]
We are using `sentry-sdk[flask]==0.5.3` and spawn Greenlets (`gevent==1.3.4`) to parallelize various I/O requests. Unfortunately Sentry only captures the stacktrace but not the local variables from the spawned thread. They do appear in the stacktrace right until the thread is spawned.

**Comment by untitaker** [comment]
I assume the reason for this is that gevent fakes the stacktrace but not the locals. I suspect there is not much we can do about this but I would be happy if somebody could investigate if those assumptions are true.
