### ISSUE TITLE
Clickhouse Integration

### ISSUE THREAD

**Issue by mimre25** [getsentry/sentry-python#2154]
### Problem Statement

I would love to see a clickhouse integration similar to the SQL integration to get traces/error reports from I/O with clickhouse.

This is the [clickhouse-driver](https://github.com/mymarilyn/clickhouse-driver) that I'm using - any chance this could be implemented?

### Solution Brainstorm

Is there a guide on how to implement integrations myself? 
If so, I might find some time to contribute myself :slightly_smiling_face:

**Comment by mimre25** [comment]
I started working a bit on this and realized that neither `clickhouse-driver`, nor any other clickhouse implementation for python is really mature yet. 

I was wondering whether it would even make sense/be accepted to create such integrations?

**Comment by mimre25** [comment]
FWIW: I've implemented it - see [here](https://github.com/getsentry/sentry-python/commit/884351f166ebceaaad7e99d246ca8e9f251d76f1), but I'm waiting for confirmation of whether it makes sense to add this before creating a pull request. (I would add documentation in such a case).

In case you don't want this to be added to sentry-python, that's fine for me as well :slightly_smiling_face:

**Comment by sentrivana** [comment]
@mimre25 Sentry itself [uses ClickHouse in the background](https://blog.sentry.io/introducing-snuba-sentrys-new-search-infrastructure/) so we're ClickHouse fans over here. :) It'd be nice to have direct support for it in the SDK, so feel free to open a PR anytime -- and thanks a lot for working on this!

**Comment by mimre25** [comment]
Alright, here it is:

PR for code https://github.com/getsentry/sentry-python/pull/2167
PR for docs https://github.com/getsentry/sentry-docs/pull/7129
