### ISSUE TITLE
Sub minute intervals for Celery Cron integrations

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#2168]
We do NOT support sub minute intervals in Sentry Crons. There when where would be "interval" type schedule that is sub minute, we should print a warning and return an empty monitor config:

See code here:
[[_get_monitor_confi](https://github.com/getsentry/sentry-python/blob/a1c27600625d20803fc58a008172dcc11d053a01/sentry_sdk/integrations/celery.py#L396-L407)](https://github.com/getsentry/sentry-python/blob/a1c27600625d20803fc58a008172dcc11d053a01/sentry_sdk/integrations/celery.py#L396-L407)

In the `elif` there should be warning and a return {} like in the `else` below in case the interval is under a minute.

**Comment by rjo100** [comment]
Yeah specifically change this return line here:
https://github.com/getsentry/sentry-python/blob/a1c27600625d20803fc58a008172dcc11d053a01/sentry_sdk/integrations/celery.py#L377

**Comment by antonpirker** [comment]
@rjo100  I have now implemented, that when there is a interval short than a minute, we will not send check-ins at all. (also when other not supported schedule types are used (like based on sunraise/sunset)

I guess this is the best solution for this. In case of non supported schedule types, no monitors will be created and warning messages are print.
