### ISSUE TITLE
Allow filtering/custom handling of `with_locals` values

### ISSUE THREAD

**Issue by alvinlindstam** [getsentry/sentry-python#217]
Including locals in the stacktrace for errors can be very useful, but we've found that we'd like some more control of those values.

Example: 
Calling `repr` on a django queryset will evaluate the query if it's not cached, which might both slow the error reporting down and even affect the database performance (if it's a costly query).

It could also be used to control which locals to include, in case we'd like to scrub some out.

The data scrubbing could be done in `before_send` I guess, but all values would have been evaluated already so it would not help us with expensive `repr` calls. And it would require us to dive into the nested(?) stacktrace data. How about having some option, similar to `before_send` or `before_breadcrumb` but for `before_locals` that could receive the locals and should returned some new dict as the locals?

Or is there any ideas on other way's to prevent lazy queryset evaluation in sentry, other than disabling all locals with `with_locals=False`?

**Comment by untitaker** [comment]
I agree that something needs to be done here. My preferred solution would be to delay the call to `repr()` such that `before_send` still sees the raw local. It can then filter it out or use an alternative repr.

**Comment by untitaker** [comment]
On reading the OP again, I don't understand the argument that this would affect the DB performance. Why do you have the queryset around if evaluating would hit the DB too hard?

**Comment by alvinlindstam** [comment]
In our case, it was a queryset of a moderately large table and some select_related (causing joins) and _a sort_by on a non-indexed column_. It was executed without filters as it was in a local variable in the stack of an error handled by `sentry-sdk`. Because it was sorted by the unindexed column, the db still had to read the full table and sort it.

The same thing would of course happen if we executed that queryset, but the application code would not evaluate the queryset as it was. It would use that queryset and apply some `.filter(...)`-calls which would reduce the number of items to be sorted to a manageable state.

I'm not sure if that should be considered bad practice, but I think it's fairly common in the django ecosystem to construct querysets in multiple steps, and not considering the safety in executing the queryset as it is at every stage but just rather when it's used by the application code.

More generally, I can think of these risks in calling repr on all querysets in the stack trace's locals:

1. querysets that have an ordering, if not on an indexed column (as above)
2. the number of queries (even if each is quite quick):
  1. it's possible the stack contains a bunch of querysets (multiple frames, multiple locals), I don't think that 10-20 queryset's would be uncommon for a django app's stack trace(?)
  2. the `repr` call on each object in the queryset could perform queries, if it uses any related object from it's `__repr__` method (though that would surely be bad practice). But then we could get 21 queries just form a single repr on a queryset.
3. Lock contention. The sentry handler could be called within a transaction, where locks are held or where the query has to wait for other locks. That could result in significant delays for the query itself or for other queries, or cause deadlocks.
4. Querysets with `select_for_update`, which would lock the selected item's.

I'm not sure how often people would use select_for_update without applying the valid filter's at the same time, but I don't think that I would raise my eyebrows for code such as (written to create or update a user in an atomic manner):

```python
obj, created = User.objects.select_for_update().update_or_create(
    id=42,
    defaults={'first_name': 'Bob'},
)
```

But if an error is raised within that call, such as in a signal or in the save method, the frame for `update_or_create` will contain the local `self` which is an unevaluated queryset that if `repr`ed will lock 21 users for the duration of the transaction.

**Comment by alvinlindstam** [comment]
Or consider

```python
qs1 = User.objects.filter(id__in=request.session['friends']).order_by('last_post')
qs2 = User.objects.order_by('last_post').filter(id__in=request.session['friends'])
```

I would consider them functionally equivalent, but if the second would raise an exception in the filter call (the session not having the data, or it being the wrong type for the filtering etc) it would have a local (`self` in the filter frame) that is the full queryset with a sort, which could be very expensive.

Upon thinking about it, I find it quite scary to call `repr` on any django queryset in sentry.

For reference, I found this ticket interesting (about django's querysets calling the db on repr): https://code.djangoproject.com/ticket/20393

**Comment by alvinlindstam** [comment]
What solution would you have in mind, @untitaker? Delaying the repr-call until after the before_send and make make it possible to filter them out? My initial idea of `before_locals`? Some modification to the django integration to stop calling `repr` on querysets?

**Comment by untitaker** [comment]
I think this is very related to https://github.com/getsentry/sentry-python/pull/229 and I have the feeling that there exists a solution that satisfies both. I am no longer sure what I want to have implemented.

**Comment by bucko909** [comment]
Oh heh, I didn't even look for an open bug. :)

**Comment by bucko909** [comment]
Reading up, I'm a bit horrified that `repr` would ever cause a query to happen -- I realise it's beyond your control, and the Sentry API should work despite it, but ugh (my expectation would be that it summarised data it had available at the time but didn't pull in any extra data except possibly by recursive `repr` calls).

My suspicion is that this would be better served by creating a type adapter layer which understood how to encode these values rather than overriding the encoder itself (else you're forced to duplicate much of the encoder's behaviour). It's an approach used in some JSON encoding modules and psycopg2, I think.

If you're having problems in the field, you might consider monkey-patching `__repr__` on the `ResultSet` object to do something less awful until you can find a better fix.

**Comment by bucko909** [comment]
Thinking harder, I could replace the `CapturePicker` with a `CaptureGenerator` which could have a (recursively called) `to_json_obj()` which @alvinlindstam could override. My `OneTimeCapturePicker` would simply override `get_locals()` (or something) to return `None` mostly. It probably results in a positive refactoring of that code, too. It's a bit strange to have a persistent object for generating captures (it must be thread-safe, for instance), but perhaps I could pass a class with a static traceback field.

**Comment by bucko909** [comment]
And looking closer at @alvinlindstam's suggestion (presumably replacing `locals` with `raw_locals` in the event dictionary until after `before_send`) I think that'd work for both of us, too, though it'd still have to do work enumerating the locals of the full stack even if it didn't format them. I seem to recall when I did the profiling of our death loop almost all of the cost was in stringification, so I suspect that's relatively cheap.

**Comment by alvinlindstam** [comment]
It would be an option to pass some object instead of just a bool for `with_locals`, as is suggested in https://github.com/getsentry/sentry-python/pull/229/ with methods for if and how to capture locals. However, it would also be nice to be able to control this from integrations. I think that it would be nice to have the DjangoIntegration take some boolean parameter on wether or not to call repr on Django querysets and managers.

But if integrations are to be able to control the handling of this, I guess we would have to support multiple integrations doing so and then we can't rely on a single with_locals-object?

I wouldn't mind some solution similar to the `add_(global_)?event_processor` or `add_(global_)?error_processor` that would process an object of locals and support chaining. So basically applying `extract_locals` some of `object_to_json` (everything but the stringification) first, then the chain of processors, and finally a stringification processor using the current `safe_repr` function. 

Thoughts?

Also, all of this applies if `attach_stacktrace` is True, not just `with_locals`.

**Comment by vinayinvicible** [comment]
In raven this was very easy to achieve with the following.
```python
@raven_serializer.register
class QuerySetSerializer(raven_serializer.Serializer):
    types = (models.QuerySet,)

    def can(self, value):
        # Only mask unevaluated queryset
        return super(QuerySetSerializer, self).can(value) and not bool(
            value._result_cache
        )

    def serialize(self, value, **kwargs):
        return "<%s from %s at 0x%x>" % (
            value.__class__.__name__,
            value.__module__,
            id(value),
        )
```
I feel that the serializer implementation should be ported from raven to allow for this kind of customization.

**Comment by untitaker** [comment]
Is this still an issue for querysets in particular? we recently fixed an issue where any instance of `Sequence` was iterated over. We now restrict that to primitive types.

@bucko909's issue would not be solved by raven's solution if I understand correctly. It depends on a few things, e.g. which part of capturing locals is too expensive (yeah it's probably the repr) and by which criteria one generally wants to disable locals capturing

**Comment by vinayinvicible** [comment]
@untitaker iteration fixed the issue of queryset getting evaluated and fetching all of the records.
but the repr call stills evaluates the queryset with limit 21.

**Comment by vinayinvicible** [comment]
to ensure that the hook is triggered only when integration is enabled, `add_global_repr_processor` can be a part of `setup_once`.

**Comment by untitaker** [comment]
I forgot to update this issue, please check out #247. We encountered a need for this feature in JS, so it's higher priority now

**Comment by untitaker** [comment]
This is completed in #247. You will be able to filter out local vars by type and value. Right now it's not possible to filter by key.

Please don't use this for PII stripping! If this seems like an attractive hook for stripping PII we'd love to know how we can improve `before_send`.

**Comment by alvinlindstam** [comment]
That's seems awesome, haven't gotten to look into the solution in detail or test it yet but it seems that it will do what it says :)
