### ISSUE TITLE
Profiling for eventlet

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-python#2170]
### Problem Statement

The flamegraph looks very incomplete if eventlet is used. User turns off eventlet, then finds the flamegraph has a lot more information.

The problem may be:

Due to the async nature of the eventlet, frames do not usually stay on the stack for long. Combined with some biases in when the profiler samples, the profiles can look like that screenshot where it's only able to capture the frames related to eventlet.

### Solution Brainstorm

Support for Eventlet.

**Comment by sl0thentr0py** [comment]
yea we're aware of the shortcomings here, but this is basically uncharted territory and I think @Zylphrex has already given some thought into making the async user story better here.

**Comment by sentrivana** [comment]
Closing in favor of https://github.com/getsentry/sentry-python/issues/1949
