### ISSUE TITLE
CI doesn't support 2.7 anymore

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#2178]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

--

### Steps to Reproduce

Open a PR and see that the 2.7 tests fail with
```
  Warning: The support for python 2.7 will be removed on June 19. Related issue: https://github.com/actions/setup-python/issues/672
  Version 2.7 was not found in the local cache
  Error: The version '2.7' with architecture 'x64' was not found for Ubuntu 20.04.
```
E.g. here: https://github.com/getsentry/sentry-python/actions/runs/5311404601/jobs/9614596733?pr=2177

Reason (and possible workarounds): https://github.com/actions/setup-python/issues/672

**TODO**

- see if we can simply use an older Ubuntu version
- if not, we can [try running all 2.7 suites in a container](https://github.com/actions/setup-python/issues/672#issuecomment-1589120020)

### Expected Result

CI for 2.7 still works.

### Actual Result

CI for 2.7 doesn't work.

**Comment by antonpirker** [comment]
We probably can just select another Ubuntu version in the test matrix: https://github.com/getsentry/sentry-python/blob/master/.github/workflows/test-integration-django.yml#L33-L39
