### ISSUE TITLE
Don't record spans for internal SDK requests to the DSN

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-python#2185]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.25.1

### Steps to Reproduce

```python
import sentry_sdk

sentry_sdk.init(traces_sample_rate=1.0, debug=True)

# for i in range(1000):
with sentry_sdk.start_transaction(name='parent transaction'):
    with sentry_sdk.start_span(op='span wrapper', description='foobar'):
        for i in range(100):
            with sentry_sdk.start_transaction(name='child transaction'):
                for i in range(1050):
                    with sentry_sdk.start_span(op='sleep', description='zzz'):
                        2**10

sentry_sdk.flush(10)
```

### Expected Result

no internal http spans

### Actual Result

![image](https://github.com/getsentry/sentry-python/assets/6536764/18fc5a0b-a345-4806-b3ad-1aaa22a6002f)

**Comment by sentrivana** [comment]
How GO does this, for inspiration: https://github.com/getsentry/sentry-go/blob/master/otel/internal/utils/sentryrequest.go#L27-L47
