### ISSUE TITLE
FastAPI's `HTTPException`s do not get sent with the error message as subtitle

### ISSUE THREAD

**Issue by nicolassanmar** [getsentry/sentry-python#2192]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.25.1

### Steps to Reproduce

1. Create 2 simple FastAPI routes that raise exceptions like this:
``` py
@router.get("/http-exception")
async def trigger_http_exception():
    raise HTTPException(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        detail="Intentional HTTPException, please ignore",
    )

class MyHTTPException(HTTPException):
    """This class should be used to throw our custom HTTPExceptions,
    as the base class does not provide the error message to Sentry"""

    def __init__(self, status_code: int, message: str):
        super().__init__(
            status_code=status_code,
            detail=message,
        )
        self.message = message  # required to make Sentry display subtitles on issues


@router.get("/http-exception-cause")
async def trigger_http_exception_with_cause():
    raise MyHTTPException(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        message="Intentional HTTPExceptionWithCause, please ignore",
    )

```
2. Call the endpoint at `/http-exception`
3. Call the endpoint at `/http-exception-cause`
4. Go to Sentry's issue page, and confirm that only the `MyHTTPException` provides a subtitle for the issue with the error message, and the `HTTPException` does not.

I also contacted Sentry support and they also confirmed this is a bug.

### Expected Result

Both exceptions should show the error message as the subtitle in the issue. On FastAPI `HTTPException`s this is called `detail`.

### Actual Result

Only the custom `MyHTTPException` has the subtitle in Sentry issues.
![image](https://github.com/getsentry/sentry-python/assets/57573579/305c861b-b445-40bb-b343-16482059bdcd)

I debugged printing the `event` on the `before_send` function and the `event.exception.values[0].value` as an empty string for `HTTPException`s:

![image(1)](https://github.com/getsentry/sentry-python/assets/57573579/67b12d24-988d-4ef8-85e1-8c6012b26463)

This is not the case with our custom exceptions, that as a workaround set the `message` field.

**Comment by sentrivana** [comment]
Hey @nicolassanmar, thanks for opening this, it'd definitely be nice to have the `detail` treated the same way we do `message`s. PRs are always welcome if you or anyone reading this feel like giving it a shot! We could either fix this in the Starlette integration, or more generally whenever we format the exception value and there's no `message`, but there is a `detail`.

**Comment by goharShoukat** [comment]
This is an excellent Issue raised! I have also encountered the same issue and am working around it with using Python's Exception class for now. But this really does need to be solved.

**Comment by sentrivana** [comment]
Status update: there's an open pull request for this, but it needs some changes and the original contributor hasn't had time -- we'll take a look at it and finish it when time permits.
