### ISSUE TITLE
Improve API docs

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#2196]
### Problem Statement

Our [API docs](https://getsentry.github.io/sentry-python/) are in desperate need of some love, e.g.:

- some stuff is not documented at all
    - no docs for the tracing module (spans, transactions)
    - [only Logging under Integrations](https://getsentry.github.io/sentry-python/integrations.html), no other integrations
- some of the top level API docs only mention `**kwargs` without any further explanation, so people have to dive into the code themselves (https://github.com/getsentry/sentry-python/issues/2199) https://github.com/getsentry/sentry-python/pull/2213
- there's some annoying overlapping happening at times:
![Screenshot 2023-06-26 at 11 24 44](https://github.com/getsentry/sentry-python/assets/131587164/8eef949d-a180-473a-8a65-7956b195cd60)

### Solution Brainstorm

* See what relevant parts are undocumented and add them.
* Find an alternative theme where things don't overlap. https://github.com/getsentry/sentry-python/pull/2210
* Make a general effort to improve existing docstrings.
* Add more docstrings where it makes sense.

See also:
* https://github.com/getsentry/sentry-python/issues/1086
* https://github.com/getsentry/sentry-python/issues/1708
* https://github.com/getsentry/sentry-python/issues/2199

**Comment by untitaker** [comment]
ways in which sdk api docs differ from [arroyo](https://getsentry.github.io/arroyo/) off the top of my head:

1. [different theme](https://github.com/lepture/shibuya)
2. get rid of sphinx-autodoc-typehints, use sphinx builtin way to render typehints (unclear if it works with type hint comments though)

about the `**kwargs` situation, we have a glorious hack in the sdk to share kwargs definitions between `sentry_sdk.init`, `sentry_sdk.Client` and `sentry_sdk.get_options`, just gotta reuse that. also works for IDEs

**Comment by untitaker** [comment]
> but then it shows up in the docs as a class (much surprise)

ah yeah. i forgot about that. i think i might have just lived with it back then for get_options. I think it might be possible to re-bind `__init__` like so, but that's just a random idea, haven't tried it out:

```
class capture_event(CaptureEventArgs):
    pass

capture_event = capture_event.__init__
```

even if sphinx picks that up as a function to document, now the return type will be wrong :(

**Comment by sentrivana** [comment]
`capture_event = capture_event.__init__` works 🙈 

Dunno if we can make the return type work. You _can_ just add `# type: (...) -> Optional[str]` to the fake class `__init__` which tricks vscode into suggesting the correct return type, but don't think there's a way to get this past mypy. Will play with it a bit more.

**Comment by sentrivana** [comment]
Nevermind, TIL `@typing.no_type_check`

**Comment by untitaker** [comment]
I believe you can do this:

```
if TYPE_CHECKING:
    BogusBaseclass = TypeVar("T")
else:
    BogusBaseclass = object

class CaptureEventArgs(Generic[BogusBaseclass]):
    def __init__(self, ...) -> BogusBaseclass: ...

class capture_event(CaptureEventArgs[Optional[str]]):
    pass

capture_event = capture_event.__init__
```

**Comment by untitaker** [comment]
Updated above example to be self-contained -- you also have to make `__init__` no longer take `self` to make it work. Maybe it is not a good idea!

**Comment by untitaker** [comment]
Actually I think it might be good enough to re-bind `Hub.capture_event` into global scope to copy its args, like this:

```
class Hub:
    def capture_event(self, event, hints=None) -> Optional[str]:
        ...


if TYPE_CHECKING:
    capture_event = Hub().capture_event

else:
    def capture_event(*args, **kwargs): ...
```
