### ISSUE TITLE
GraphQL Connected Services

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-python#2198]
### Background
We want to provide better GraphQL support with Sentry SDKs, frontend to backend. Work has already begun on some mobile platforms. There is also already some implementations for GraphQL server and client side. With the current work we want to ensure that the strategy to ensure proper connected errors and grouping works from backend to frontend. Java already has an [integration for GraphQL](https://docs.sentry.io/platforms/java/configuration/integrations/graphql/).

### Proposal

Python SDK should set context for GraphQL on errors same as what is done for Mobile SDK to ensure the value add from Frontend to Backend

Definition of Done TBC:

- [ ] GraphQL Context
- [ ] Propagating Trace

Further context:

https://github.com/getsentry/sentry/issues/50230
- https://github.com/getsentry/sentry/pull/50764

**Comment by sentrivana** [comment]
Reopening this since the implementation will have to be reworked.
