### ISSUE TITLE
AIOHTTP: Attach request body

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#220]
Methods for reading the request body are async in AIOHTTP, but event processors are not. So right now we can't attach any request bodies to the event without severely affecting perf.

**Comment by untitaker** [comment]
Everybody who voted with 👍 , please suggest how to read the body in a sync function. I don't really understand why aiohttp works the way it does. Other async frameworks don't make me await on something that is just `json.parse`

**Comment by sivakov512** [comment]
Any solutions here?

**Comment by untitaker** [comment]
@sivakov512 no, I would prefer if the community investigated how other code deals with aiohttp for reading bodies twice

**Comment by EasyLovv** [comment]
@untitaker 
The aiohttp does a cache of the body in bytes on the first read call. [BaseRequest.read()](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_request.py#L558-L573)

**Comment by EasyLovv** [comment]
@untitaker 
I could be out of the concept, by from the processor you could get a loop and create async task which will get the body and send it to sentry. something like this:
`from aiohttp import web
    import asyncio

    loop = asyncio.get_event_loop()

    async def async_task(request: web.Request):
        body = await request.read()
        # send to sentry

    def processor():
        loop = asyncio.get_event_loop()
        request: web.Request = None
        loop.create_task(async_task(request))


    async def async_func():
        processor()

    loop.run_until_complete(async_func())`

**Comment by untitaker** [comment]
@EasyLovv that sounds a bit dangerous. I wonder if we should just grab `request._post` and `request._read_bytes` if it's already there, and just do nothing if it isn't.

**Comment by EasyLovv** [comment]
@untitaker it is also an option, would be great to have at least that. But in my view, I can't see anything dangerous, we are just reading the request body, any unsupported behavior or type could be covered by try-catch and posted to sentry with some additional "Unsupported body" tag etc.

**Comment by untitaker** [comment]
@EasyLovv my issue is that I need the request body as string in the processor. I can't just spawn a task and return. So I block for `async_task` in `processor`, which ends up behaving like a blocking sync operation in `async_func`. Not cool for performance.

**Comment by untitaker** [comment]
@EasyLovv do you want to make a PR for this so people can try it out?

**Comment by samuelcolvin** [comment]
In case it's of any interest or help to anyone else, I have a fulling working aiohttp-sentry integration implemented as middleware, see [here](https://github.com/samuelcolvin/aiohttp-toolbox/blob/02ab51105e59463cde9889db55db53f034f6e5fe/atoolbox/middleware.py#L35-L142).

Also https://github.com/aio-libs/aiohttp/pull/3557 and https://github.com/aio-libs/aiohttp/pull/3767  mean that with aiohttp 4 all error logging will possible in access loggers without adding middleware or messing with the nuts and bolts of running servers.

**Comment by untitaker** [comment]
The integration takes extra precautions to not make scope data leak across request boundaries. Your middleware avoids this issue by assembling the entire event payload before calling `capture_event`, but this means that custom calls to `capture_*` will not have request data.

I would really like the work for request bodies to land in the SDK, but possibly hidden behind an option (kwarg to the integration object).
