### ISSUE TITLE
[TwP] Fallback to propagation context if span is None

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry-python#2201]
https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/scope.py#L608-L612

Instead of checking for `has_tracing_enabled`, I suggest we only check for an existing span on the scope, with a fallback on using the Propagation Context.

PHP for inspiration https://github.com/getsentry/sentry-php/blob/master/src/State/Scope.php#L382-L398

**Comment by antonpirker** [comment]
Fixed in the linked issue.
