### ISSUE TITLE
Tornado integration does not capture formdata

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#221]
There is no obvious way to get just formdata from Tornado's request object (not mixed with other request params), but I haven't done a lot of research on that.

**Comment by nickbaum** [comment]
I think this is the function you want:

https://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.get_body_arguments

**Comment by untitaker** [comment]
@nickbaum amazing. I thought this would parse JSON as well.

**Comment by nickbaum** [comment]
🙌🏻 Thanks!
