### ISSUE TITLE
Sentry asyncio integration does not support Python 3.11

### ISSUE THREAD

**Issue by cookiesowns** [getsentry/sentry-python#2212]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.26.0

### Steps to Reproduce

1. Use Python 3.11.x
2. Install Sentry 1.26.0
3. Init sentry asyncio integration
4. Expect to see app running

### Expected Result

App runs

### Actual Result

File "uvloop/loop.pyx", line 1431, in uvloop.loop.Loop.create_task
TypeError: patch_asyncio.<locals>._sentry_task_factory() got an unexpected keyword argument 'context'

https://github.com/MagicStack/uvloop/blob/master/uvloop/loop.pyx#L1431

**Comment by sentrivana** [comment]
Hey @cookiesowns, thanks for reporting this. We already have [an older issue for this](https://github.com/getsentry/sentry-python/issues/1993) that we didn't get around to yet, so I'll close this one.
