### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by mantrabikash** [getsentry/sentry-python#2221]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

Layer version is 66 in aws lambda function

### Steps to Reproduce

Steps 
1. Created a project for Python Lambda Node sentry.
2. Created a Lambda function with python 3.7 in aws lambda.
3. Go to settings in sentry click on integration.
4. Select aws lambda and create a cloudformation.
5. After that give your account id and region.
6. Select the lambda function .
7. Enable the integration.

### Expected Result

When testing my lambda function i wanted the error to be stored in the project in sentry.

### Actual Result

" {
  "errorMessage": "Unable to import module 'sentry_sdk.integrations.init_serverless_sdk': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
} "

**Comment by antonpirker** [comment]
Hey @mantrabikash !

It has todo with AWS not supporting urllib2 v2.0 see this comment on how to fix it: https://github.com/urllib3/urllib3/issues/2168#issuecomment-1607906183

**Comment by sentrivana** [comment]
I'd try pinning `urllib3<2.0.0` or `sentry-sdk==1.24.0` (which pins it transitively) if that's an option for you @mantrabikash.

**Comment by mantrabikash** [comment]
okay thanks @sentrivana let me try this.!
