### ISSUE TITLE
Serializer trimming improvements

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#2223]
### Problem Statement

It's been coming up a lot in recent years that people are unhappy with the way our serializer auto-trims their events. The most common issues are that there is no indication in the UI that some part of the event was trimmed and that parts of objects important for debugging go missing.

As far as we know `sentry-python` is also the only SDK that actively trims events before sending.

[Ingest will drop an event if it is too large](https://github.com/getsentry/relay/blob/5e161d17f9b5af3468b1b044cf60a356cad63ab2/relay-config/src/config.rs#L574C23-L574C23), (see also https://github.com/getsentry/sentry-python/issues/2223#issuecomment-1621228685) which should be made transparent to users (e.g. [client reports](https://develop.sentry.dev/sdk/client-reports/)) if it happens.

We've recently [updated an option to skip trimming request bodies](https://github.com/getsentry/sentry-python/pull/2092). This issue considers going one step further and removing the limits altogether, either optionally or in all cases.

#### Related Issues
* https://github.com/getsentry/sentry-python/issues/377
* https://github.com/getsentry/sentry/issues/68426
* https://github.com/getsentry/sentry-python/issues/1259
* https://github.com/getsentry/sentry-python/issues/344
* https://github.com/getsentry/sentry-python/issues/335
* https://github.com/getsentry/sentry-python/issues/2121
* https://github.com/getsentry/sentry/issues/51998

### Solution Brainstorm

* (add a client option to) disable trimming altogether
* consider if we need the serializer
* make sure that it's transparent to the user if ingest drops an event due to it being too large
* add a visual indicator to the UI that something was trimmed (if we keep the trimming)

**Comment by antonpirker** [comment]
I just talked to ingest at breakfast. What happens with big payloads:
- There is something in nginx that drops REALLY big payload. They where not sure if there will be an outcome for that.
- Then the envelope arrives at relay and a size check is done. Eventually dropping if too big (with outcome)
- There there is also an envelope item limit, eventually dropping the item.
- Then relay does some truncation.
- Then the rest of the processing
