### ISSUE TITLE
Start using `types-WebOb`

### ISSUE THREAD

**Issue by Daverball** [getsentry/sentry-python#2226]
### Problem Statement

I've recently contributed type stubs for WebOb on typeshed, which have been merged and are now available to the public. Some of the Integrations refer to types defined in WebOb (e.g. `PyramidIntegration`), but don't yet make use of `types-WebOb` and as such are really operating on `Any`.

### Solution Brainstorm

Install `types-WebOb` and fix any uncovered typing issues.

As a side note, I've noticed that sometimes you use `dict[str, str]` as the type annotation for `environ`, even though that is inaccurate. You should use `_typeshed.wsgi.WSGIEnvironment` which is currently an alias for `dict[str, Any]` but will ensure that your type hints for `environ` will remain consistent with the stdlib and any third party stubs managed through typeshed in the future.

The same goes for `WSGIApplication` and `StartResponse` defined within that module.

**Comment by antonpirker** [comment]
Hey @Daverball 

Thanks for writing in, sounds like a good think. (In general for our typing there is still lots of room for improvement.)
I put this on our backlog but not at a high priority, because we have lots of other things we want to do before.
