### ISSUE TITLE
Should sentry-sdk depend on urrllib3[secure]?

### ISSUE THREAD

**Issue by dimaqq** [getsentry/sentry-python#2242]
### Problem Statement

I've added `sentry-sdk` to a project that I'm moving from `requirements.txt` to `poetry`.

I've got these versions:

```
sentry-sdk 1.28.0 Python client for Sentry (https://sentry.io)
├── certifi *
└── urllib3 >=1.26.11
```

However, this did not add `cryptography` which the earlier, manual setup had.

I wonder if that's all right.

Poetry lock shows these possible options to `urllib3`, options are not installed in my case:
```
[[package]]                                                                             
name = "urllib3"                                                                        
version = "2.0.3"                                                                       
...                                                                                     
                                                                                        
[package.extras]                                                                        
brotli = ["brotli (>=1.0.9)", "brotlicffi (>=0.8.0)"]                                   
secure = ["certifi", "cryptography (>=1.9)", "idna (>=2.0.0)", "pyopenssl (>=17.1.0)", "urllib3-secure-extra"]
socks = ["pysocks (>=1.5.6,!=1.5.7,<2.0)"]                                              
zstd = ["zstandard (>=0.18.0)"]    
```

### Solution Brainstorm

If current dependency is correct, let's leave this ticket for others to find.

If cyrptography or pyopenssl is actually required to send errors to Sentry securely, maybe the dependency should be updated to `urllib3[secure]`

**Comment by antonpirker** [comment]
Hey @dimaqq !

The Sentry SDK does not need `cryptography` to send data to Sentry. 
The only dependencies needed are `certifi` and `urllib3`.

But a good Idea to have this ticket lying around if someone else is googling for this!

**Comment by dimaqq** [comment]
Link: https://github.com/urllib3/urllib3/issues/2680
