### ISSUE TITLE
GraphQL server errors

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#2257]
### Problem Statement

The most popular GraphQL libraries for Python are:
- [Graphene](https://github.com/graphql-python/graphene)
- [Strawberry](https://github.com/strawberry-graphql/)
- [Ariadne](https://github.com/mirumee/ariadne)

They all use [graphql-core](https://github.com/graphql-python/graphql-core) under the hood.

### Solution Brainstorm

Write the integrations. If possible hook up to graphql-core which all the libraries use internally, otherwise write multiple integrations.

Strawberry already has [a Sentry tracing extension](https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/extensions/tracing/sentry.py) -- talk to [Patrick](https://github.com/patrick91) about it.

**Comment by Ronjea** [comment]
Thanks @sentrivana for this!
