### ISSUE TITLE
Streamline and align the "Getting Started" docs to fit in the new structure

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry-python#2292]
### Problem Statement

- The "Getting Started" documentation for sentry-python platforms may not conform to the newly defined format, which includes the steps "Install", "Configure", "Verify", and the optional "Next Steps".
    - The "Verify" step is not always available and it is a very important step that helps the user to verify that the installation and configuration were done correctly.
- New users onboarding with Sentry may find the existing documentation extensive and unclear. The "Getting Started" guide should cover the basics, while more advanced configurations shall live on the [sentry-docs website](https://docs.sentry.io/).
- Some copies and code snippets in the documentation may be outdated.

### Solution Brainstorm

The task goals are as follows:

- Thoroughly review all sentry-python platform documentation, including less commonly used sections, and reorganize their content into structured headings: 'Install,' 'Configure,' 'Verify,' and the optional 'Next Steps.'
- The onboarding documentation should strictly focus on the basics to help users get started. Advanced configurations should be available in the complete documentation on the [sentry-docs website](https://docs.sentry.io/).
- Essential information for new users should be included under the new 'Notes' section in the onboarding documentation.
- Update code snippets and copies as necessary.
- If a "Verify" step is missing, include it in the documentation.

Please refer to the "Frontendend Handbook" guide in our "Sentry" main repository for assistance in adding and updating the getting started docs: [Frontendend Handbook](https://develop.sentry.dev/frontend/working-on-getting-started-docs/). 

**Project:** https://github.com/getsentry/team-sdks/issues/23

**Comment by antonpirker** [comment]
When we go over all the "getting started guides" also make sure to check if the integration is an auto-enabling integration [1] and if yes, then remove the integration from the init snippet and add a sentence to explain that it is auto enabling. 

So every integration must be updated in two places (here Flask as an example):

- docs https://docs.sentry.io/platforms/python/guides/flask/
- and onboarding https://github.com/getsentry/sentry/blob/master/static/app/gettingStartedDocs/python/flask.tsx


1: list auf auto enabling integrations can be found here: https://github.com/getsentry/sentry-python/blob/838368cc37d162b871cc19e0185820911504af2e/sentry_sdk/integrations/__init__.py#L66-L83

**Comment by antonpirker** [comment]
Updated now almost all "Getting Started" docs on docs.sentry.io and updated also all "Getting Started" wizards in `sentry` product.

The docs that I did not update (because they are special docs that need more love):
- AWS Lambda
- Google Cloud Functions
- Apache Airflow
- Apache Beam
- Apache Spark

Two of our integrations are missing documentation entirely:
- huey 
- starlite (was renamed to litestar, not sure if it is working at all)

**Comment by antonpirker** [comment]
PRs that need to be merged in `sentry`:

- https://github.com/getsentry/sentry/pull/56545
- https://github.com/getsentry/sentry/pull/56563
- https://github.com/getsentry/sentry/pull/56645
