### ISSUE TITLE
AttributeError in arq integration

### ISSUE THREAD

**Issue by rossmacarthur** [getsentry/sentry-python#2305]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.29.2

### Steps to Reproduce

#2088 broke our usage of the `arq` Sentry integration.

The following is a perfectly valid arq configuration:

```python
async def my_coroutine(state):
    pass

class WorkerSettings:
    functions = [my_coroutine]
```

### Expected Result

No exception

### Actual Result

```sh
AttributeError: type object 'WorkerSettings' has no attribute 'cron_jobs'
```

**Comment by sentrivana** [comment]
Thanks for reporting and submitting a fix @rossmacarthur! We will take a look.
