### ISSUE TITLE
Arq integration ignores functions and cron jobs passed as keyword arguments

### ISSUE THREAD

**Issue by rossmacarthur** [getsentry/sentry-python#2306]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.29.2

### Steps to Reproduce

`arq` allows you to pass the functions as a keyword argument, not just defining on the `WorkerSettings` class.

```python
async def my_coroutine(state):
    pass

arq.run_worker(object(), functions=[my_coroutine])
```

### Expected Result

Unhandled errors in `my_coroutine` should be sent to sentry

### Actual Result

Errors are not sent to Sentry

**Comment by sentrivana** [comment]
Thanks for this report and fix as well! :)
