### ISSUE TITLE
Docs reference Scope.update_from_kwargs, but it is undocumented

### ISSUE THREAD

**Issue by zmc** [getsentry/sentry-python#2309]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.29.2

### Steps to Reproduce

1. Visit https://getsentry.github.io/sentry-python/api.html
2. Look for docs on `sentry_sdk.capture_exception()`, specifically its kwargs
3. Find this text: `For supported **scope_args see sentry_sdk.Scope.update_from_kwargs().`
4. Look for docs on `sentry_sdk.Scope.update_from_kwargs`

### Expected Result

Found docs

### Actual Result

Docs don't exist

**Comment by zmc** [comment]
Thanks @sentrivana!

**Comment by sentrivana** [comment]
No problem, thanks for notifying us! The change might be a bit slow to appear in the API docs since I think there's some caching involved but it should pop up soonish after we release.
