### ISSUE TITLE
use `importlib.metadata.version` to get package version

### ISSUE THREAD

**Issue by davidism** [getsentry/sentry-python#2316]
### Problem Statement

Modern packaging metadata provides a standard way to get the version of any package. Flask and other Pallets projects will be deprecating the `__version__` attribute. Instead, use `importlib.metadata.version` if the version is needed (or use feature detection). This will work regardless of what version is installed.

It looks like your Pyramid integration already does this, might be worth it to use the standard consistently across all integrations.

### Solution Brainstorm

Replace `from flask import __version__ as FLASK_VERSION` with `FLASK_VERSION = importlib.metadata.version("flask")`. Possibly replace all `__version__` imports.

**Comment by sentrivana** [comment]
Thanks for the heads up @davidism, we'll look into this.

**Comment by sentrivana** [comment]
Fixed by https://github.com/getsentry/sentry-python/pull/2338
