### ISSUE TITLE
Error reporting without capture_exception()

### ISSUE THREAD

**Issue by Chanmoro** [getsentry/sentry-python#232]
Error reporting to sentry is working with this code.
Is this usage recommended?
And, is `capture_exception()` not required?

``` python
import sentry_sdk

sentry_sdk.init('SENTRY_DSN')

raise Exception('this is test exception.')
```

**Comment by untitaker** [comment]
Yes, this works fine and there is nothing wrong with it. `capture_exception` is still useful.
