### ISSUE TITLE
Invoking sentry when in a path that does not exist causes a FileNotFoundError

### ISSUE THREAD

**Issue by korhojoa** [getsentry/sentry-python#2324]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.29.2

### Steps to Reproduce

Go from sentry-sdk version 1.29.0 to 1.29.2 (this is where we noticed)

[sentry-sdk](https://pypi.python.org/pypi/sentry-sdk)==1.29.0
[sentry-sdk](https://pypi.python.org/pypi/sentry-sdk)==1.29.2

This is the line mentioned in the trace: https://github.com/getsentry/sentry-python/commit/bc209e52081bc0faa5fe58d81673fb2ecfd283a0#diff-fb869cde7d11be4df35c1f0d0f45f5824cc0e76e6ada504a48e8ceefe363f739R250

### Expected Result

It would work, like it did earlier, and not break the functionality of the tool being used.

I understand that this isn't a common situation, but I think it's unfair that a tool that's supposed to help troubleshoot is breaking functionality.

### Actual Result

Running a command that uses sentry from a path that got cleaned up:

```shell
07:37:20      import sentry_sdk
07:37:20    File "/usr/local/lib/python3.11/site-packages/sentry_sdk/__init__.py", line 1, in <module>
07:37:20      from sentry_sdk.hub import Hub, init
07:37:20    File "/usr/local/lib/python3.11/site-packages/sentry_sdk/hub.py", line 10, in <module>
07:37:20      from sentry_sdk.client import Client
07:37:20    File "/usr/local/lib/python3.11/site-packages/sentry_sdk/client.py", line 34, in <module>
07:37:20      from sentry_sdk.profiler import has_profiling_enabled, setup_profiler
07:37:20    File "/usr/local/lib/python3.11/site-packages/sentry_sdk/profiler.py", line 251, in <module>
07:37:20      CWD = os.getcwd()
07:37:20            ^^^^^^^^^^^
07:37:20  FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by sentrivana** [comment]
Hey @korhojoa, thanks for reporting, we will fix this.

@Zylphrex could you please take a look? I'm assuming we need to handle potential `FileNotFoundError`s, but I'm not sure what the behavior should be like if one happens.
