### ISSUE TITLE
Exceptions captured with option "include_local_variables" are not monitored/displayed at Sentry Dashboard.

### ISSUE THREAD

**Issue by sarvesh-ridecell** [getsentry/sentry-python#2326]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.21.0

### Steps to Reproduce

We're capturing an exception in a celery task, with `capture_exception(exception, include_local_variables=True)`. This exception is not getting monitored at Sentry Dashboard. While,  `capture_exception(exception)` catches the exception, and is monitored at Sentry Dashboard. 
Captured exceptions in other Celery tasks, and API calls are working as expected - which are not using `include_local_variables` option.

### Requirements
Python:  3.8.10
Django: 3.2.19
Django Rest Framework: 3.12.4
Sentry-SDK: 1.21.0
Celery: 4.4.0

### Expected Result

`capture_exception(exception, include_local_variables=True)` should monitor the exception with local variables.

### Actual Result

`capture_exception(exception, include_local_variables=True)` is not monitoring the exception. 
`capture_exception(exception)` is monitoring the exception.

**Comment by sentrivana** [comment]
Hi @sarvesh-ridecell, thanks for reporting.

Could you please try updating to the newest version of the SDK (1.29.2 at the point of writing) and seeing if the error still occurs? We've made some updates to the Celery integration in the past couple of releases.

Does this occur only within a Celery task, specifically, or also outside/in a program that's not using Celery?

If you init the SDK with `debug=True`, is there anything interesting in the output (if you can see it while running Celery 🤔)? Do you see the msg about the error event being sent?

**Comment by sarvesh-ridecell** [comment]
Hey @sentrivana, First of all - Thanks for the reply, and helping us debug the issue. 
We tried out the steps mentioned, and found out both values for the flag include_local_variables are producing the same issue for us. 

We upgraded our SDK to the version 1.30.0, and Initialised the Sentry with `debug=True`. It returned some logs, and we actually found something interesting - and I think it'll help us debugging the issue. 

Attaching the log here - 

```
{"logger_name":"sentry_sdk.errors", "level":"ERROR", "pid":9, "module":"", "log_timestamp":"2023-08-31T14:58:02.180646+00:00", "source_line":"/usr/local/lib/python3.8/dist-packages/sentry_sdk/hub.py:417", "message": "Internal error in sentry_sdk"}
Traceback (most recent call last):
File "/src/services/tasks/services_tasks.py", line 38, in update_system_status
raise Exception("Testing Sentry's upgrade to 1.30.0 in automatically called tasks.")
Exception: Testing Sentry's upgrade to 1.30.0 in automatically called tasks.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/hub.py", line 401, in capture_exception
return self.capture_event(event, hint=hint, scope=scope, **scope_args)
File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/hub.py", line 347, in capture_event
scope = _update_scope(top_scope, scope, scope_args)
File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/hub.py", line 82, in _update_scope
final_scope.update_from_kwargs(**scope_kwargs)
TypeError: update_from_kwargs() got an unexpected keyword argument 'include_local_variables'
```
We checked the dashboard as well, but no error was monitored/caught. The same log can be found for both values for flag include_local_variables.

**Comment by sarvesh-ridecell** [comment]
Hey @sentrivana, Thank you so much for timely support! We found the issue in our codebase, and the expected exceptions are being monitored now. We really appreciate the help. Closing the issue with this.

**Comment by sentrivana** [comment]
Awesome, happy to hear that!
