### ISSUE TITLE
sentry_sdk raise FileNotFoundError:No such file or directory: 'nul'

### ISSUE THREAD

**Issue by asgter** [getsentry/sentry-python#2334]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.6.0

### Steps to Reproduce

Operate System: Window 7

File"C:\Users\Administrator\AppData\local\python\lib\site-packages\setry_sdk\hub.py", line 105, in _init
    client = Client(*args,**kwargs)  # type: ignore
File"C:\Users\Administrator\AppData\local\python\lib\site-packages\setry_sdk\client.py",line 88, in __init__
    self.options = get_options(*args,**kwargs) # type: Dict[str，Any]
File"C:\Users\Administrator\AppData\local\python\lib\site-packages\setry_sdk\client.py", line 68, in get_options
    rv["release'] = get_default_release()
File"C:\Users\Administrator\AppData\local\python\lib\site-packages\setry_sdk\utils.py" line 65, in get_default_release
    with open(os.path.devnull, "w+") as null:
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

### Expected Result

not raise error

### Actual Result

raise Error

**Comment by sentrivana** [comment]
Hey @asgter, thanks for raising this. You seem to be on an SDK version that's more than a year old -- could you please try upgrading to 1.30.0?

For what it's worth I believe you'll still get the issue though. The code that's throwing the error is still part of the [utils.py](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/utils.py#L104) module. It's apparently trying to access the [Windows equivalent](https://docs.python.org/3/library/os.html#os.devnull) of `/dev/null` called `nul` and failing. Maybe this is a Win 7 thing?

To work around it you could set the `SENTRY_RELEASE` variable explicitly yourself, then it shouldn't follow that codepath.
