### ISSUE TITLE
Create `Event` class/type

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#2357]
RIght now our `Event` type is only a dict: https://github.com/getsentry/sentry-python/blob/antonpirker/2345-new-performance-api/sentry_sdk/_types.py#L26

We should have an Event class, that makes it easier to pass events around. (and find where events are used in the code)

**Comment by allanlewis** [comment]
Perhaps a `TypedDict` would suffice, rather than a custom class?

**Comment by antonpirker** [comment]
Maybe, we will check.

**Comment by allanlewis** [comment]
> Hey @allanlewis -- `TypedDict` would be great for this, but it was only added in 3.8, and the SDK still needs to support Python versions below that (also in the new major release we're currently working on).

Versions before 3.8 are EOL 😕

**Comment by sentrivana** [comment]
> Versions before 3.8 are EOL 😕

We still want to support them though. :)

**Comment by szokeasaurusrex** [comment]
We should be able to use `TypedDict` – as long people are using at least 3.8 in their development environment, they would be able to get proper type hints. On older Python versions, we can continue to type `Event` as a `dict[str, Any]`

**Comment by szokeasaurusrex** [comment]
Following discussion with @sentrivana and @antonpirker, all items in the TypedDict should be optional, even if they are required in the event payload sent to Sentry, because we pass around a lot of under-construction events that will not have all of these items in the code
