### ISSUE TITLE
Testing rq integration fails because of version issue

### ISSUE THREAD

**Issue by vagi8** [getsentry/sentry-python#2363]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.30.0

### Steps to Reproduce

Installed sentry_sdk, in an editable mode for contribution

I tried running the rq integration tests on master

RQ version - 1.15.1

![image](https://github.com/getsentry/sentry-python/assets/43883923/298a399a-7d15-46d8-9414-cdb5bbe40ad0)

![image](https://github.com/getsentry/sentry-python/assets/43883923/254ec996-8ade-4af7-b357-1df857fb0223)

### Expected Result

Successful passed tests for rq integration

### Actual Result

all failed tests pointing towards the version issue

**Comment by antonpirker** [comment]
Hey @vagi8 !
Thanks for bringing this up.
We want to look at the RQ integration this week, so maybe this will be also fixed right away.

**Comment by antonpirker** [comment]
This was fixed in RQ already: https://github.com/rq/rq/pull/1329
