### ISSUE TITLE
Latest Sentry SDK 1.31.1 not compatible with latest Quart 0.19.2

### ISSUE THREAD

**Issue by larsblumberg** [getsentry/sentry-python#2406]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.31.1

### Steps to Reproduce

1. `requirements.txt`:

```
Quart==0.19.2
sentry-sdk[quart]==1.31.1
```

2. `pip3 install` && `python3 ...`

raises `sentry_sdk.integrations.DidNotEnable: Quart is not installed`:

```
    try:                                   
        from quart import (  # type: ignore 
            has_request_context,
            has_websocket_context,
            Request,                       
            Quart,                         
            request,                       
            websocket,
        )                                  
        from quart.scaffold import Scaffold  # type: ignore
        from quart.signals import (  # type: ignore
            got_background_exception,
            got_request_exception,
            got_websocket_exception,
            request_started,
            websocket_started,
        )                                  
        from quart.utils import is_coroutine_function  # type: ignore
    except ImportError:
>       raise DidNotEnable("Quart is not installed")
E       sentry_sdk.integrations.DidNotEnable: Quart is not installed

/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/quart.py:51: DidNotEnable
```

### Expected Result

No import errors and quart SDK detected.

### Actual Result

Import error leading to quart not being detected.

**Comment by sentrivana** [comment]
Hey @larsblumberg, thanks for reporting this! It seems someone has already [opened a PR](https://github.com/getsentry/sentry-python/pull/2403) for this, I'll block some time to give it a look in the coming week.

**Comment by catwell** [comment]
For what it's worth that someone is the author of Quart :)

**Comment by rubiali** [comment]
I have the solution
pip install --upgrade 'sentry-sdk[flask]'  # Quart is supported by the Flask SDK so then..
import sentry_sdk
from quart import Quart
from sentry_sdk.integrations.flask import FlaskIntegration

sentry_sdk.init(
    dsn="YOUR_SENTRY_DSN",
    integrations=[FlaskIntegration()],
)

app = Quart(__name__)

**Comment by sentrivana** [comment]
Hey all, support for Quart>=0.19 will be out with the next release in a couple of weeks. Thanks to Quart's maintainer @pgjones for making our integration compatible with the newest Quart!
