### ISSUE TITLE
datetime.datetime.utcnow() is deprecated

### ISSUE THREAD

**Issue by grigi** [getsentry/sentry-python#2407]
### Problem Statement

Python 3.12 deprecated `datetime.datetime.utcnow()`:
```
.pyenv/lib/python3.12/site-packages/sentry_sdk/tracing.py:148: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
```

### Solution Brainstorm

Update sentry to use `datetime.datetime.now(datetime.UTC)` instead of `datetime.datetime.utcnow()` as suggested.
Some quick testing shows that for this to work on python < 3.11 would have to do  `datetime.datetime.now(datetime.timezone.utc)` instead as the `datetime.UTC` shortcut was only added in python 3.11

**Comment by sentrivana** [comment]
Good catch @grigi! I've added this to the [list of things](https://github.com/getsentry/sentry-python/milestone/17) we need to tackle in order to support 3.12.

If you or anyone reading this feels like it, PRs are very welcome!

**Comment by mohebmithani** [comment]
Hi @sentrivana can i take this?

**Comment by sentrivana** [comment]
Hey @mohebmithani, no need to ask, feel free to just submit a PR! But seems like @rmad17 already has a solution for this issue.

Awesome @rmad17! The gist is that you need to make changes on a fork of this repo:

- fork the `getsentry/sentry-python` repo
- clone the forked repo to work on it locally
- push a new branch with the changes to your fork
- and finally open a PR from your fork (and your branch) against this repo's master branch

We should do a better job outlining this in our [CONTRIBUTING.md](https://github.com/getsentry/sentry-python/blob/master/CONTRIBUTING.md) -- I will look into that. Let me know if you need more pointers!
