### ISSUE TITLE
Support Litestar

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#2413]
### Problem Statement

[Starlite was renamed to Litestar.](https://litestar.dev/about/organization.html#litestar-and-starlite) Since we already have a Starlite integration, adding support for Litestar should in the ideal case just be a matter of checking the [changelog for the new major](https://github.com/litestar-org/litestar/releases/tag/v2.0.0) and creating a new integration based on the existing one.

### Solution Brainstorm

Write the new integration.

**Comment by sentrivana** [comment]
Hey @JacobCoffee, thanks for the support! Same goes the other way -- if anyone feels like tackling this, we're happy to provide support. The case of Litestar as an integration is special since we've already integrated with Starlite, so whoever takes this on doesn't have to start from square one but rather build on what we already have, which should make it easier.

Folks reading this, please give the original issue a 👍🏻 if this is something you want, it helps us prioritize this internally as well.

**Comment by guacs** [comment]
@sentrivana I'd like to take a crack at this. I looked at the existing integration with Starlite, and like you said it shouldn't be too difficult to use that as a base for the `Litestar` integration.

**Comment by sentrivana** [comment]
Thank you @guacs! Exactly, I'd start by just copying the Starlite integration into a new file and then taking it from there. Additionally there is a few housekeeping places that will need changing throughout the SDK, like adding Litestar to `tox.ini`, to our GitHub workflow generator script, adding some span `OP` constants, etc. -- for updating those you can just grep for `starlite` and add the same for `litestar`.

**Comment by jeanlst** [comment]
@sentrivana @guacs any news on this?

**Comment by sentrivana** [comment]
No news yet @jeanlst -- same situation as before, we probably won't get around to doing this soon, but happy to provide support if anyone wants to give it a try.

**Comment by guacs** [comment]
> @sentrivana @guacs any news on this?

Sorry I've just gotten quite busy for a while! Unfortunately, I think it may be a few weeks before I'll get a chance to work on this :/
