### ISSUE TITLE
Documentation: gql integration is not released yet

### ISSUE THREAD

**Issue by theCapypara** [getsentry/sentry-python#2421]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.31.0

### Steps to Reproduce

The documentation mentions that since `1.31.0` a GQL integration exists: https://docs.sentry.io/platforms/python/integrations/gql/

This integration was introduced in #2368

However as far as I can tell, this integration is actually not released yet as part of any release.

### Expected Result

n/a

### Actual Result

n/a

**Comment by antonpirker** [comment]
Hey @theCapypara !
Thanks for reporting this! 
You are right. The integration has not yet been released, but will so in the next couple of days. (with other graphql support)

**Comment by sentrivana** [comment]
We were a bit over eager and merged the docs before we had a release, sorry for that. It's [out now](https://github.com/getsentry/sentry-python/releases/tag/1.32.0) though!
