### ISSUE TITLE
Exception chaining

### ISSUE THREAD

**Issue by chrisroat** [getsentry/sentry-python#243]
With chained exceptions, I am only seeing the final exception in my sentry dashboard, with no information about the rest of the exception chain (i.e. the things above "During handling of the above exception, another exception occurred:")

This functionality seems to have been included in `raven-python` repo via [PR 811](https://github.com/getsentry/raven-python/pull/811).

Here's a quick snippet that will generate a chained exception.

```
import requests
import sentry_sdk

sentry_sdk.init("https://<elided>@sentry.io/<elided>")

try:
  requests.get("http://no-exist-domain.foobar")
except requests.exceptions.ConnectionError:
  raise RuntimeError("Unable to connect")
```

**Comment by untitaker** [comment]
You're right, implicit exception chains don't work. We should fix that.
