### ISSUE TITLE
Django Integration: url cleanup with multiple placeholders is broken

### ISSUE THREAD

**Issue by salomvary** [getsentry/sentry-python#2430]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.31.0

### Steps to Reproduce

1. Have a url in a Django application with multiple placeholders, like `<str:parent>/<str:child>`.
2. Make some requests to this url.
3. Find the transactions in Sentry.

### Expected Result

The transaction should be represented as `{parent}/{child}`.

### Actual Result

The transaction is represented as `{parent}` instead.

Failing test case: https://github.com/salomvary/sentry-python/commit/27b763a245a7e5b860a964e2869dc3a7fad1d90f

This is a regressions caused by https://github.com/getsentry/sentry-python/pull/1773/commits/aa5b853bfa43bb3c44caa2ca42a7cff1d6e914eb attempting to fix https://github.com/getsentry/sentry-python/issues/1527.

The linked issue claims that DjangoCMS generates URL patterns that look like `'^(?P<slug>[$\\-_.+!*(),\\w//]+)/$'` but I have not found any proof in the source code for such regex ever being generated. DjangoCMS regexes look more like `r'^(?P<slug>[0-9A-Za-z-_.//]+)/$'`.

cc @PeterW-LWL @mgaligniana

**Comment by sentrivana** [comment]
Hey @salomvary, thanks for the bug report! We're working on fixing the regex in [this issue](https://github.com/getsentry/sentry-python/issues/2392), so feel free to follow the progress there -- I'll close this as a duplicate.
