### ISSUE TITLE
Issues Sampling (like `traces_sampler`)

### ISSUE THREAD

**Issue by saippuakauppias** [getsentry/sentry-python#2440]
### Problem Statement

I ran into the same problem as was voiced in: https://github.com/getsentry/sentry/issues/28792#issuecomment-926373402, https://github.com/getsentry/sentry/issues/46670, https://github.com/getsentry/sentry/issues/27884.
In short: there is a service that periodically restarts due to heavy load on it, we can't do anything about it. At the moment of restarting the service - there is a large (hundreds of thousands) number of sending logged messages to Sentry. It is impossible to disable messages at all, because we need to control the situation when the service has stopped responding at all.

There is a way to set rate limit for tracing in the [documentation](https://docs.sentry.io/platforms/python/configuration/filtering/#using-platformidentifier-nametraces-sampler-) (and it is mentioned in https://github.com/getsentry/sentry/issues/46670#issuecomment-1496560154). But there is no way to set rate limit by message text from the logger.

We are using Django, and if we try to do according to the example in the documentation, there is no useful information about the message itself in `sampling_context`. There's just the transaction, no error, no logger message text, no traceback.

### Solution Brainstorm

Please make `issues_sampler` so that it would be possible to filter a errors before sending it to Sentry.

**Comment by antonpirker** [comment]
Hey @saippuakauppias !
Thanks for bringing this up. This is good idea and I think on another platform we support we already have something like you suggested. I put this on our todo list, but it will take some time because we are all working on something right now.

**Comment by sentrivana** [comment]
@saippuakauppias This sounds like something that could be solved by defining a custom [before_send](https://docs.sentry.io/platforms/python/configuration/filtering/#using-platformidentifier-namebefore-send-). All events but transactions will pass through it if you define one and you can decide to drop an event in it based on whatever criteria you need. Would that solve the issue?

**Comment by saippuakauppias** [comment]
@sentrivana, thanks for the idea, I'll try this, even though it looks like a hack
