### ISSUE TITLE
No breadcrumbs showing up with logging integration

### ISSUE THREAD

**Issue by gerricom** [getsentry/sentry-python#245]
Hello!

I'm starting to migrate one of our apps from raven to the new sentry_sdk. So far this is like plug and play, but I stumbled upon one thing, as I wanted to make our logging a bit better:

The [documentation of the logging integration](https://docs.sentry.io/platforms/python/logging/) says, that, even if not explicitly configured, sentry should receive log events with the level of "debug" or "info" as a breadcrumb. I'm not able to see those breadcrumbs within sentry. A "warning" will show up as breadcrumb, but not "info" or "debug".

What am I doing wrong? I even used the exact code written in the documentation but it won't work 

Thanks!

**Comment by untitaker** [comment]
@gerricom you should not have to use any code from that particular page to get those breadcrumbs. Concretely you don't have to set up any logging handlers, and you don't have to import anything from `sentry.integrations.logging`.

What breadcrumb is ultimatively logged depends on the log level of the logger though.

**Comment by gerricom** [comment]
Ugh... shoot me now. Having sleept a night and having a fresh look at it today I can now say: Everything works as expected. Sorry for bothering!
