### ISSUE TITLE
Add an option similar to shouldCreateSpanForRequest to not create certain spans. 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry-python#2458]
### Problem Statement

Similar to [this issue](https://github.com/getsentry/sentry-python/issues/1895), Sentry's Django automatic instrumentation can create a large number of spans that can be irrelevant for users.

The options to control which operations create spans are limited, it is a simple on/off switch for middleware, signals and cache spans.

### Solution Brainstorm

The [JS SDK has an option](https://docs.sentry.io/platforms/javascript/performance/instrumentation/automatic-instrumentation/#shouldcreatespanforrequest) to not create spans for certain urls, the solution can be same for spans matching a criteria (description, operation, specific signal)

**Comment by antonpirker** [comment]
Hey @rodolfoBee 
Thanks for bringing this up. We have a `traces_sampler` (see https://docs.sentry.io/platforms/python/configuration/sampling/#setting-a-sampling-function)  where users can specify a function that can decide what traces to keep and which ones to drop. 

We could add something similar for spans. A function that gets the span as an argument and it can decide to keep or drop it.

**Comment by sentrivana** [comment]
Closing in favor of https://github.com/getsentry/sentry-python/issues/3859
