### ISSUE TITLE
ip_address field always None

### ISSUE THREAD

**Issue by ibraheemalayan** [getsentry/sentry-python#2463]
### How do you use Sentry?

Self-hosted/on-premise

### Version

23.9.0.dev0

### Steps to Reproduce

I have a flask web-app that uses a sentry integration, each time a user is loaded, his information are added to the sentry context using `from sentry_sdk import set_user` as follows

```python3
set_user(
            {
                "id": str(user.id),
                "ip_address": str(request.remote_addr),
                "IP": str(request.remote_addr),
                "email": str(user.email),
            }
        )
```

I've added a custom field `IP` and passed exactly the same value as the `ip_address`, the `IP` value appeared correctly in sentry but the `ip_address` did not.

### Expected Result

Expected that the `IP` field has the same value as `ip_address`

### Actual Result

This is what appears in sentry
![image](https://github.com/getsentry/sentry-python/assets/35265448/bb684ed0-9cde-4a46-bd56-dff04e939e26)

**Comment by sentrivana** [comment]
Hey @ibraheemalayan, thanks for the report. How do you initialize the SDK? There's an option called `send_default_pii` ([see docs](https://docs.sentry.io/platforms/python/configuration/options/#send-default-pii)) which, if not set, defaults to `False` and will result in some potentially sensitive data [being scrubbed](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/scrubber.py) from the event before it leaves the SDK, including `user.ip_address`. See [Scrubbing sensitive data](https://docs.sentry.io/platforms/python/data-management/sensitive-data/) for more info on how to fine tune this.
