### ISSUE TITLE
Crons django-celery-beat timezone glitch

### ISSUE THREAD

**Issue by avilaton** [getsentry/sentry-python#2472]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.29.2

### Steps to Reproduce

1. Setup django-celery-beat
2. Create a Periodic task via the admin and set a wacked timezone for it
3. setup Sentry with CeleryIntegration(monitor_beat_tasks=True),
4. See the resulting cron monitor in sentry

The current implementation of the `_get_monitor_config` helper does not consider for the posibility that the schedule might be coming from django_celery_beat (this is understandable since this is all new).
Here is the implementation for it
https://django-celery-beat.readthedocs.io/en/latest/_modules/django_celery_beat/tzcrontab.html#TzAwareCrontab
which has a timezone property. The resulting schedule could have a different timezone from app.conf.timezone and could be per-schedule.

We traced it to here https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/celery.py#L447 and think that considering that schedule could be an instance of TzAwareCrontab would be the way to go.

Not sure how you would like to code the possible import failure of django_celery_beat and so on, so stopped there.

### Expected Result

Expectation is that the cron monitor in sentry has the Americas/Chicago timezone we have setup in django admin for our task

### Actual Result

The task cron monitor in sentry has Americas/Los_Angeles as timezone as that is the app.conf.timezone

**Comment by avilaton** [comment]
Adding a screenshot for clarity just in case 
<img width="1160" alt="image" src="https://github.com/getsentry/sentry-python/assets/2209022/4b27f8b6-6848-4a45-8b1e-d3732b40bf19">

**Comment by antonpirker** [comment]
Hey @avilaton !
Thanks for reporting this. I put it on our backlog.

**Comment by evanpurkhiser** [comment]
@antonpirker I've seen a number of reports about this actually. Let's see if we can't get this more heavily prioritized?

**Comment by sentrivana** [comment]
@evanpurkhiser I can take a look at this next week.

**Comment by antonpirker** [comment]
@evanpurkhiser the list of timezones in `django-celery-beat` has values in it, that are not in Sentry's list of timezones:
[timezones-django-celery-beat.txt](https://github.com/getsentry/sentry-python/files/13309280/timezones-django-celery-beat.txt)

When I select a timezone that is not available in Sentry's list, then the timezone `--` shows up in Sentry's UI.
Is there a way we can map those non existing timezones?
