### ISSUE TITLE
Python 3.11 Support for GCP Integration

### ISSUE THREAD

**Issue by mjedmonds** [getsentry/sentry-python#2477]
### Problem Statement

Support for Python 3.11 with GCP Cloud Function Integration.

### Solution Brainstorm

I thought that python 3.11 would be supported now due to this PR: https://github.com/getsentry/sentry-python/pull/2300

However, I can't seem to integration sentry with a python 3.11 gcp cloud function. I dug around in the code a bit and found this: https://github.com/getsentry/sentry-python/blob/0ce9021ad27797ddf226aaa1c4a7c94694acf220/sentry_sdk/integrations/gcp.py#L141

Which makes me think it may not be supported still. Is python 3.11 enabled for GCP cloud functions? How much effort would it be to enable support for python versions > 3.7.

**Comment by sentrivana** [comment]
Hey @mjedmonds, for GCP Cloud Functions [we only support 3.7 at the moment](https://docs.sentry.io/platforms/python/integrations/gcp-functions/). We'll have to investigate what changes are necessary to support newer runtimes.

**Comment by sentrivana** [comment]
I've noticed we already have an issue for this, so closing this in favor of https://github.com/getsentry/sentry-python/issues/1667
