### ISSUE TITLE
Standardize and automate event formatting

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#2505]
### Problem Statement

Since the SDK now emits a handful of different event types, we might benefit from defining the interface of each supported event type and enforcing them in a more automated fashion (as opposed to manually adding/removing specific fields from events).

### Solution Brainstorm

Find a way to define the expected fields of an event type (probably via a class) and create a mechanism that takes care of adding/removing the supported fields to/from an event based on type.

- relay: https://github.com/getsentry/relay/tree/master/relay-event-schema/src/protocol

**Comment by antonpirker** [comment]
We added some typed dict for Event, so we will close this now.
