### ISSUE TITLE
Python grpc.aio metadata is transformed to list

### ISSUE THREAD

**Issue by kindermax** [getsentry/sentry-python#2509]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.35.0

### Steps to Reproduce

Hi, in latest sentry-sdk release a new Client interceptor was added for `grpc.aio` client. The problems is that `metadata` is transformed into a list and it breaks all subsequent interceptors which expect `metadata` to be `grpc.aio.Metadata` object (https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/aio/_interceptor.py#L93C14-L93C14)

### Expected Result

Maybe metadata needs to be preserved as type `grpc.aio.Metadata`

### Actual Result

For now i see error that metadata is a list
<img width="536" alt="image" src="https://github.com/getsentry/sentry-python/assets/10552804/0b5b98bd-e2f1-4062-b9f4-752e38b07c55">

**Comment by sentrivana** [comment]
Thank you for reporting this @kindermax! We'll take a look.
