### ISSUE TITLE
Django Logging Handlers Class

### ISSUE THREAD

**Issue by clairglobal** [getsentry/sentry-python#254]
With raven I was able to control what was set to collect via logs with:
```
LOGGING = {
...
     'handlers' : {
          'sentry': {
               'level': 'ERROR',
               'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler'
          }
     }
...
}
```

But I can't seem to figure out how to get that with sentry_sdk. My logger.error() don't raise sentry issues.

**Comment by untitaker** [comment]
@clairglobal did you intend to close this issue? If so, what was your solution? the SDK is supposed to capture all errors from any logger by default
