### ISSUE TITLE
No option for de-initializing sdk

### ISSUE THREAD

**Issue by rissson** [getsentry/sentry-python#255]
There should be a function to allow for de-initialzing the sdk. As we call `sentry_sdk.init()` we should be able to use `sentry_sdk.deinit()` to prevent sending error reports.
This is useful in the case the user disables logs sending in an application and the program doesn't need to be restarted before error reporting might happen.

**Comment by untitaker** [comment]
You can call `init()` without a DSN to disable sending errors. You can also use `init()` as a context manager to enable error reporting for a particular codeblock.

We're still trying to figure out how to document things, but I think this hasn't come up often enough yet.

**Comment by rissson** [comment]
Okay thanks for your answer! This should be put in the docs though

**Comment by untitaker** [comment]
@rissson We might restructure the docs again so I'm holding off from this rn
