### ISSUE TITLE
Unexpected `sentry_trace_meta` data in RQ task `delay(...)` call

### ISSUE THREAD

**Issue by robhudson** [getsentry/sentry-python#2560]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

PR change upgrading from older sentry-sdk version to newer (1.26.0 to 1.38.0) resulted in a failing test with the `sentry_trace_meta` data showing up in a `delay(...)` call which seems unexpected.

https://github.com/mozmeao/basket/pull/1239

### Expected Result

No `sentry_trace_meta` data in the delay call.

### Actual Result

```
E           AssertionError: expected call not found.
E           Expected: delay('SUBSCRIBE', {'newsletters': ['slug'], 'email': 'dude@example.com', 'privacy': True, 'format': 'H', 'first_name': '', 'last_name': '', 'country': '', 'source_url': ''})
E           Actual: delay('SUBSCRIBE', {'newsletters': ['slug'], 'email': 'dude@example.com', 'privacy': True, 'format': 'H', 'first_name': '', 'last_name': '', 'country': '', 'source_url': '', 'sentry_trace_meta': '<meta name="sentry-trace" content="42e7d5aeba5f48138a2e2b7c12758f2b-b52eeeecb993a12e"><meta name="baggage" content="sentry-trace_id=42e7d5aeba5f48138a2e2b7c12758f2b,sentry-environment=production,sentry-release=latest">'})
```

### Product Area

Unknown

**Comment by antonpirker** [comment]
Please give more details @robhudson 
I do not know what tests you are running and what you are testing for and if the `sentry_trace_meta` showing up in you test ist a problem or you just need to update your test to work with new SDK version. I also do not know what `delay(...)`. 

If you want us to help you, you need to write a better Github issue

**Comment by robhudson** [comment]
I did more testing and verified that sentry isn't actually adding args/kwargs to our RQ tasks via the `delay(...)` call, as the failed test seemed to suggest. It appears to be unittest specific. So I've disabled sentry in our unit tests. Closing.
