### ISSUE TITLE
Django integration does not respect SCRIPT_NAME

### ISSUE THREAD

**Issue by ethrgeist** [getsentry/sentry-python#2576]
### How do you use Sentry?

Self-hosted/on-premise

### Version

self-hosted-23.11.2

### Steps to Reproduce

1. Django setup with `SCRIPT_NAME=/foo/bar` under domain `example.net`
2. Full url `https://example.net/foo/bar/`
3. Triggern an error in a view `https://example.net/foo/bar/my-view/`
4.  URL in Sentry UI is just `https://example.net/my-view/`, missing the `SCRIPT_NAME`

### Expected Result

URL should respect SCRIPT_NAME and the link in the UI should be `https://example.net/foo/bar/my-view/`

### Actual Result

URL in Sentry UI is just `https://example.net/my-view/`

**Comment by antonpirker** [comment]
Hey @ethrgeist ! Thanks for reporting this. Makes total sense. I put it on our list, but also marked it as good first issue and help wanted, so maybe someone wants to jump on this.

**Comment by Nandika-A** [comment]
Hello! Can I work on this issue?

**Comment by sarvaSanjay** [comment]
Apologies for the multiple PRs, got a bit confused but it seems like we need to add the `Trigger: tests using secrets` label to the PR in order for checks to pass. Could anyone help me out with that?

**Comment by szokeasaurusrex** [comment]
> Apologies for the multiple PRs, got a bit confused but it seems like we need to add the `Trigger: tests using secrets` label to the PR in order for checks to pass. Could anyone help me out with that?

Yes @sarvaSanjay – only maintainers can add this label. We will add the label once all other tests are passing and the change has been approved. 

I took a look at your PR and added some comments. Once you address these comments and get the tests to pass, we can hopefully get this change merged.
