### ISSUE TITLE
Crons client reports are not working

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry-python#2589]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.39.0

### Expected Result

We've recently enabled client reports for Crons, but they don't seem to be working in the Python SDK. It'd be valuable to know if check-ins are being dropped due to network issues or other causes, since our SDKs have a no-retry policy.

This works:
```py
sentry_sdk.Hub.current.client.transport.record_lost_event("event_processor", data_category="monitor")
```

My hunch is that we're either sending the incorrect data category, or client reports for crons isn't implemented.

**Comment by sentrivana** [comment]
Hey @gaprl, yep, we were sending `check_in` as `data_category`. Will be fixed in the next release.
