### ISSUE TITLE
setup_integrations() after client init doesnt seem to work

### ISSUE THREAD

**Issue by janLo** [getsentry/sentry-python#259]
If I try to install the `AioHttpIntegration` after `sentry_sdk.init(...)`. The `setup_once()` of the integration gets called but for some reason the client still does not know the integration. At least `hub.get_integration(AioHttpIntegration)` which is called in in the generated `_handle` replacement in `aiohttp.py` returns `None`.

Is this expected or is there another way to register integrations to a client after init?

**Comment by untitaker** [comment]
This is entirely expected. `setup_integrations()` is supposed to be used for early initializing monkeypatches (calling `setup_once`) but not for enabling integrations on a client (this happens in the client).

Which usecase do you have where you need to enable an integration *after* the client has been initialized?

**Comment by janLo** [comment]
My usecase is that I have a basic service setup for my microservices and want to enable integrations as needed. If all I need to enable extra integrations outside of the sentry_sdk.init() is to change the order of the statements this would work for me.

I would suggest to check if there is already a client in setup_integrations() and issue a warning + abort the setup to not have cases where the monkey-patching took place but the client is not aware of it (see #260).

**Comment by untitaker** [comment]
>where the monkey-patching took place but the client is not aware of it

This is actually a usecase we want to enable: Sometimes you need to monkeypatch much earlier than config is available:

```
init(integrations=[AioHttpIntegration()])

... # a lot of code here (maybe server startup)

config = load_app_config()
init(dsn=config.dsn, integrations=[AioHttpIntegration()])
```

In the case of aiohttp this is not necessary at all, but it might be necessary for certain monkeypatches to be effective.

I would suggest passing a list of integrations from your microservice into your base service setup. Reordering the statements will not work in your case. I don't think any usage of `setup_integrations` will serve your usecase.

**Comment by janLo** [comment]
Ah, I wasn't aware taht I can caltually call init() more than once. Then there is no need for `setup_integrations`.

Thank you.

**Comment by janLo** [comment]
Ah, wait, bugger, I have to give the integraions to the second call again :(

Why is't there any way to separate the integration setup from the client initialization?

**Comment by untitaker** [comment]
This is why I suggested this:

>I would suggest passing a list of integrations from your microservice into your base service setup.

Integrations are a client option like anything else. We generally don't support updating options after the fact, e.g. you can't just change the transport on-the-fly. At least we didn't account for it if you attempted to do so.

**Comment by janLo** [comment]
Ok. Thank you.
