### ISSUE TITLE
capture_message not working when a lot of time has passed since sentry_sdk.init

### ISSUE THREAD

**Issue by cctdev** [getsentry/sentry-python#2613]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.39.1

### Steps to Reproduce

I am having an issue where capture_message is not working and the events are being dropped if there is a lot of time that has elapsed since sentry_sdk.init was invoked.  In the example below the first capture_message works fine but if I do some long database process afterwards that takes a decent amount of time the second capture_message seems to 
timeout dropping the events. I even tried setting flush_timeout and shutdown_timeout (documentation is a little unclear how these two interact) but that didn't work either.  If the processing time between the two capture_messages is short then the second capture_message actually does go through. However if there's a significant amount of time that passes it does this timeout behavior. No idea if there's a way to get any more detail than the [sentry] ERROR: flush timed out, dropped 4 events from Debug-=True.

Some notes:

- Running this on a Azure VM that constantly internet connected, so not a connectivity issue.
- Unsure on the exact amount of time required between for this to occur but I only notice it if there's a multiple minute long process in-between.
- This is definitely dropping on the client side .This is not going up to sentry.io then being rejected or filtered by a quota or something. It never makes it up there.

```
#Initialize
sentry_sdk.init(
    dsn=secret_dict.get('LOGGING_PROCESSING_DSN'),
    traces_sample_rate=1.0, # Set traces_sample_rate to 1.0 to capture 100% of transactions for performance monitoring.
    environment=secret_dict.get('LOGGING_ENV'),
    debug=True,
    max_breadcrumbs=50,
    enable_tracing=True,
    shutdown_timeout=100
)

# Send message
with push_scope() as scope:
            capture_message(message="Start", level='info')
            flush(timeout=100)  

# Some long running processing task. DB reads/inserts etc. Just using time.sleep as an example.
time.sleep(1000)

# Send message
with push_scope() as scope:
            capture_message(message="End", level='info')
            flush(timeout=100)  
```

### Expected Result

I expect all messages to be sent to sentry.io.

### Actual Result

The first capture_message works as intended but the second one after the long running process doesn't get sent. Debug shows that the flush times out, dropping the events.

Debug Output:
[sentry] DEBUG: Flushing HTTP transport
[sentry] DEBUG: background worker got flush request
[sentry] DEBUG: Sending envelope [envelope with 2 items (error, attachment)] project:xxxxxxxxxxxx.ingest.sentry.io
[sentry] DEBUG: 2 event(s) pending on flush
[sentry] ERROR: flush timed out, dropped 2 events
[sentry] DEBUG: background worker flushed
[sentry] DEBUG: Flushing HTTP transport
[sentry] DEBUG: background worker got flush request
[sentry] DEBUG: 4 event(s) pending on flush
[sentry] ERROR: flush timed out, dropped 4 events
[sentry] DEBUG: background worker flushed
[sentry] DEBUG: atexit: got shutdown signal
[sentry] DEBUG: atexit: shutting down client
[sentry] DEBUG: Flushing HTTP transport
[sentry] DEBUG: background worker got flush request
[sentry] DEBUG: 5 event(s) pending on flush
Sentry is attempting to send 5 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit
[sentry] ERROR: flush timed out, dropped 5 events
[sentry] DEBUG: background worker flushed
[sentry] DEBUG: Killing HTTP transport
[sentry] DEBUG: background worker got kill request

**Comment by cctdev** [comment]
Just for real world example I ran this python code:
```
    flush_timeout = 100
    sentry_sdk.init(
		dsn=secret_dict.get('LOGGING_PROCESSING_DSN'),
		traces_sample_rate=1.0, # Set traces_sample_rate to 1.0 to capture 100% of transactions for performance monitoring.
		environment=secret_dict.get('LOGGING_ENV'),
		debug=True,
		max_breadcrumbs=50,
		enable_tracing=True,
		shutdown_timeout=100

    )
    
    with push_scope() as scope:
      capture_message("Configuration has been initialized.", level='info')
      flush(timeout=flush_timeout)

    # Send log.
    with push_scope() as scope:
        scope.user = { "username" : "bob" }
        scope.set_tag("test1", test1)
        scope.set_tag("test2", test2)

        scope.set_context("Detailed Message", 
            {
                "Test1": "Test1",
                "Test2": "Test2"
            }
        )

        capture_message(message="Processing has begun.", level='info')
        flush(timeout=flush_timeout)  
    print("Sleeping")
    time.sleep(300)

    data = {
        'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
        'Age': [25, 30, 22, 35, 28],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago', 'Boston'],
        'Salary': [50000, 60000, 45000, 70000, 55000]
    }

    df = pd.DataFrame(data)

    in_memory_fp = io.BytesIO()

    with pd.ExcelWriter(in_memory_fp, engine='xlsxwriter') as writer:
        df.to_excel(writer, sheet_name='Test', index=False)

    xlsx_data = in_memory_fp.getvalue()

    file_name = "Test.xlsx"

    # Send log.
    with push_scope() as scope:
        scope.user = { "username" : "bob" }
        scope.set_tag("test1", test1)
        scope.set_tag("test2", test2)

        scope.set_context("Detailed Message", 
            {
                "Test1": "Test1",
                "Test2": "Test2"
            }
        )
        scope.add_attachment(bytes=xlsx_data, filename=file_name, content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        capture_message(message="Processing has ended.", level='info')
        flush(timeout=flush_timeout) 
```

and got this debug trace:
```
 [sentry] DEBUG: Flushing HTTP transport
 [sentry] DEBUG: background worker got flush request
 [sentry] DEBUG: Sending envelope [envelope with 1 items (error)] project:4506157366771712 host:o4505274853228544.ingest.sentry.io
 [sentry] DEBUG: 2 event(s) pending on flush
 [sentry] DEBUG: background worker flushed
 [sentry] DEBUG: Flushing HTTP transport
 [sentry] DEBUG: background worker got flush request
 [sentry] DEBUG: Sending envelope [envelope with 1 items (error)] project:4506157366771712 host:o4505274853228544.ingest.sentry.io
 [sentry] DEBUG: background worker flushed
Sleeping
 [sentry] DEBUG: Flushing HTTP transport
 [sentry] DEBUG: background worker got flush request
 [sentry] DEBUG: Sending envelope [envelope with 2 items (error, attachment)] project:4506157366771712 host:o4505274853228544.ingest.sentry.io
 [sentry] DEBUG: 2 event(s) pending on flush
 [sentry] ERROR: flush timed out, dropped 2 events
 [sentry] DEBUG: background worker flushed
 [sentry] DEBUG: atexit: got shutdown signal
 [sentry] DEBUG: atexit: shutting down client
 [sentry] DEBUG: Flushing HTTP transport
 [sentry] DEBUG: background worker got flush request
 [sentry] DEBUG: 3 event(s) pending on flush
Sentry is attempting to send 3 pending events
Waiting up to 100 seconds
Press Ctrl-C to quit
 [sentry] ERROR: flush timed out, dropped 3 events
 [sentry] DEBUG: background worker flushed
 [sentry] DEBUG: Killing HTTP transport
 [sentry] DEBUG: background worker got kill request
```

**Comment by antonpirker** [comment]
Hey @cctdev thanks for the detailed report. 

Two questions:
1.) in your real world example. Between the log output `Waiting up to 100 seconds` and the `ERROR: flush timed out, dropped 3 events` are there 100 seconds or is the second line happening sooner?
2.) How big is the excel sheet you create? (maybe it takes over 100 seconds to send over the wire?)

**Comment by cctdev** [comment]
Hi Anton, I did some more testing on my end. I ran the simplified code below without the attachment. Just a barebones capture_message test with a time.sleep inbetween. I ran this on the machine I was having an issue with (An Azure VM) and then on my local machine (Windows) and it seems it doesn't have this issue on the Windows machine and only on the Azure VM.  (Both safe sdk version, python version, under WSL with same ubuntu version). I'm unsure why the machine itself would impact this? Any ideas? Both machines have a stable network connection. Just to be clear if the time.sleep is set to a low enough number, both messages get sent on both systems.  It only doesn't send the second if the time.sleep is high if its on the Azure VM.

1) It does seem to actually wait the time then the flush times out, dropping the events.
2) The file is small.  This actually is not needed so in the code below I just removed the attachment to simplify the test case.

Code:
```
import sentry_sdk
from sentry_sdk import capture_message, push_scope, capture_exception, flush, set_context
import time

dsn = "xxxxxx"

flush_timeout = 100

sentry_sdk.init(
    dsn=dsn,
    traces_sample_rate=1.0, # Set traces_sample_rate to 1.0 to capture 100% of transactions for performance monitoring.
    environment="dev",
    debug=True,
    enable_tracing=True,
    shutdown_timeout=100

)

# First Message
with push_scope() as scope:
    scope.user = { "username" : "bob" }
    scope.set_tag("test1", "test1")
    scope.set_tag("test2", "test2")

    scope.set_context("Detailed Message", 
        {
            "Test1": "Test1",
            "Test2": "Test2"
        }
    )

    capture_message(message="Azure Processing has begun.", level='info')
    flush(timeout=flush_timeout)

# Wait
print("Sleeping")
time.sleep(300)

# Second Message
with push_scope() as scope:
    scope.user = { "username" : "bob" }
    scope.set_tag("test1","test1")
    scope.set_tag("test2", "test2")

    scope.set_context("Detailed Message", 
        {
            "Test1": "Test1",
            "Test2": "Test2"
        }
    )
    
    capture_message(message="Azure Processing has ended.", level='info')
    flush(timeout=flush_timeout) 
```

**Comment by antonpirker** [comment]
Hey @cctdev 
Thanks for the additional info, this will greatly help debugging this. I don't know a lot about Azure those cloud environments are sometimes a bit strange and things are happening one can not control. 

But we will have a look. But it will be in January.

**Comment by cctdev** [comment]
> Hey @cctdev Thanks for the additional info, this will greatly help debugging this. I don't know a lot about Azure those cloud environments are sometimes a bit strange and things are happening one can not control.
> 
> But we will have a look. But it will be in January.

Thanks.  Upon more testing I'm pretty sure this does have to do with it being an Azure VM.  Apparently there is this little known TCP Idle Timeout of 4 minutes on Azure entities ([Link](https://carsonip.me/posts/azure-tcp-idle-timeout-tcp-keepalive-python/)). I'm going to make an assumption based on the amount of time lining up roughly this is the culprit.  Does the sentry_sdk.inti have any sort of function that is like a keep-alive where it will try to keep the connection open?  Because otherwise it seems that the sdk doesn't really work inside any Azure VM if it exceeds 4 minutes.

**Comment by antonpirker** [comment]
@cctdev currently we do not have an option in `sentry_sdk.init()` to keep the connection open. But we have a similar issue in Github: https://github.com/getsentry/sentry-python/issues/1198
Where the user created his own transport to set some low level TCP parameters. Maybe this is a way you also could fix your problem?

**Comment by sl0thentr0py** [comment]
@cctdev we don't expose those right now, but you can make it work like in this comment
https://github.com/getsentry/sentry-python/issues/1198#issuecomment-1802638463

**Comment by cctdev** [comment]
> @cctdev we don't expose those right now, but you can make it work like in this comment [#1198 (comment)](https://github.com/getsentry/sentry-python/issues/1198#issuecomment-1802638463)

> @cctdev currently we do not have an option in `sentry_sdk.init()` to keep the connection open. But we have a similar issue in Github: #1198 Where the user created his own transport to set some low level TCP parameters. Maybe this is a way you also could fix your problem?

Thanks for the insight. I'll try what is proposed in #1198. Is there a long term solution in the works or at least in discussion? It seems a little crazy to me that the python_sdk doesn't just default to keeping the connection alive or at least let us toggle it on.  I've been using Sentry (which in general I have been loving) to gain some visibility into some python scripts automation runs.  However these scripts do a lot of CRUD operations and can take quite a long time.  It really would be nice if I could trust that the requests are getting sent after the processing is complete instead of having to babysit the python_sdk logging integration in addition to the code itself. Thanks a lot.

**Comment by sl0thentr0py** [comment]
we can expose the tcp options in a better standardized way, but ultimately this is a networking level issue and I doubt there is one true solution because otherwise `urllib3` would itself just use those settings. See [this issue](https://github.com/psf/requests/issues/4937#issuecomment-788899804) for more discussion on the topic.

**Comment by cctdev** [comment]
> we can expose the tcp options in a better standardized way, but ultimately this is a networking level issue and I doubt there is one true solution because otherwise `urllib3` would itself just use those settings. See [this issue](https://github.com/psf/requests/issues/4937#issuecomment-788899804) for more discussion on the topic.

Thanks. I think exposing those tcp options will go a long way to it.

**Comment by szokeasaurusrex** [comment]
@cctdev Are you still experiencing this problem? Perhaps, setting [`keep_alive=True`](https://docs.sentry.io/platforms/python/configuration/options/#keep-alive) when initializing the SDK might help.
