### ISSUE TITLE
HEROKU_SLUG_COMMIT is not available for heroku container deployments, fall back to env variables that will always exist

### ISSUE THREAD

**Issue by fgregg** [getsentry/sentry-python#2615]
### Problem Statement

According to the [sentry docs](https://docs.sentry.io/product/integrations/deployment/heroku/), turning on `runtime-dyno-metadata` in heroku will expose the `HEROKU_SLUG_COMMIT` environmental variable. However, this is not true if the user is deploying a container app. In that case, `HEROKU_SLUG_COMMIT` will exist, but be empty.

### Solution Brainstorm

It would be good to fall back to also try something like 

```python
f"{os.environ['HEROKU_RELEASE_VERSION']}-{os.environ['HEROKU_APP_NAME']}"
```

this would be the relevant code to update: https://github.com/getsentry/sentry-python/blob/647006398228a3d75128fb0471ec701e93884acf/sentry_sdk/utils.py#L125-L146

**Comment by antonpirker** [comment]
Hey @fgregg ! Thanks for reporting this!

Do you know if `HEROKU_RELEASE_VERSION` and `HEROKU_APP_NAME` will always be set?
And why do we need to concatenate them, would `HEROKU_RELEASE_VERSION` not be enough to have a good release name?

**Comment by jasonkarns** [comment]
This was closed but still seems to be an issue. I'm unable to reopen.
