### ISSUE TITLE
Attachments on the global scope are added to every transaction

### ISSUE THREAD

**Issue by matutter** [getsentry/sentry-python#2619]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.39.1

### Steps to Reproduce

Sentry version 23.10.1 88c7f2d, sentry-sdk==1.39.1

# Problem:

Attachments that are added to the global scope are never "flushed" when a transaction is sent in an envelope so any attachments added throughout the lifetime of a process will be added to every subsequent transaction.

I ran into this because there is no way to explicit add an attachment to one transaction...

```python
# This does not exist
with sentry_sdk.start_transaction(op="foo", name="transaction 1") as transaction_1:
        transaction_1.add_attachment(path=attachment_1, add_to_transactions=True)
```

... so when you are using the context-manager style transactions there does not seem to be a way to avoid this.

# Workaround

The workaround I am currently using is to call this code before adding a different transaction.

```python
with sentry_sdk.configure_scope() as scope:
    if attachments := scope._attachments:
        attachments.clear()
```

# Suggestion 

Add a `hints: dict[str, Any]` to the `Transaction` class so attachments can be added directly to a transaction. Those hints would just have to be passed to the call to `hub.capture_event(event)` found here https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/tracing.py#L747.

# Screenshots

The discover tab.

![discover](https://github.com/getsentry/sentry-python/assets/2701379/6cd922e8-97fd-4fc2-8c3a-7045ff40e67a)

Transaction 1 attachments.

![transaction_1](https://github.com/getsentry/sentry-python/assets/2701379/49b96f76-f40f-422e-9c5a-900e3b5e6dff)

Transaction 2 attachments.

![transaction_2](https://github.com/getsentry/sentry-python/assets/2701379/2b97de47-509e-4cb2-87bd-08cffa73c0e9)

# Reproducer

Run the reproducer below.

```python
import sentry_sdk
from pathlib import Path

dsn = "http://dfc61781f600282e6da8353828f00434@localhost:9003/2"

sentry_sdk.init(
    dsn=dsn,
    traces_sample_rate=1.0,
    debug=True,
)

attachment_1 = Path("/tmp/attachment_1.txt")
attachment_2 = Path("/tmp/attachment_2.txt")

attachment_1.write_text("attachment 1")
attachment_2.write_text("attachment 2")

with sentry_sdk.start_transaction(op="foo", name="transaction 1"):
    with sentry_sdk.configure_scope() as scope:
        scope.add_attachment(path=attachment_1, add_to_transactions=True)
        with sentry_sdk.start_span():
            print("added attachment 1")

with sentry_sdk.start_transaction(op="bar", name="transaction 2"):
    with sentry_sdk.configure_scope() as scope:
        scope.add_attachment(path=attachment_2, add_to_transactions=True)
        with sentry_sdk.start_span():
            print("added attachment 2")

```

### Expected Result

Transaction `1` will have only `attachment_1.txt` attached.
Transaction `2` will have only `attachment_2.txt` attached.

### Actual Result

Transaction `1` will have only `attachment_1.txt` attached.
Transaction `2` will have  `attachment_1.txt` and  `attachment_2.txt` attached.

**Comment by antonpirker** [comment]
Hey @matutter thanks for reporting this!

Internally Sentry manages a stack of scopes. With `configure_scope` you change the Scope on top of the stack. In your example that is both time the same scope.

You can replace `with configure_scope()` in your example with `with push_scope()`. With this change the top scope on the stack will be duplicated and you only change the duplicated one. Leading to the result you want to have.

Some side note: We are working on refactoring Scopes to make it easier for the user to do things like you do without knowing about the internals of how Sentry manages Scopes.

**Comment by matutter** [comment]
This suggestion results in no attachments being uploaded whatsoever. 

I believe you also meant to point out that `sentry_sdk.start_transaction` must be called within the `sentry_sdk.push_scope` context manager. In that case it works as initially expected.

Correct usage:

```
with sentry_sdk.push_scope() as scope:
    with sentry_sdk.start_transaction(op="foo", name="transaction 1"):
        scope.add_attachment(path=attachment_1, add_to_transactions=True)
        with sentry_sdk.start_span():
            print("added attachment 1")

with sentry_sdk.push_scope() as scope:
    with sentry_sdk.start_transaction(op="bar", name="transaction 2"):
        scope.add_attachment(path=attachment_2, add_to_transactions=True)
        with sentry_sdk.start_span():
            print("added attachment 2")
```

So the issue is user error.

Thank you!
