### ISSUE TITLE
Allow the `type` field to be override with an argument to `capture_exception`

### ISSUE THREAD

**Issue by rsprabery** [getsentry/sentry-python#2626]
### Problem Statement

When creating exceptions, the SDK uses the name of the Exception class for the `type` field [here](https://github.com/getsentry/sentry-python/blob/8bd2f461789554f4fceff62a10cc9c46910a8429/sentry_sdk/utils.py#L758). 

It would be great to have an optional argument to `capture_exception` that allows that to be overridden.

As an aside, this is needed to enable more robust alerting rules - see https://github.com/getsentry/sentry/issues/62748 for more information. Manually specifying the type will allow code controllable grouping of issues/exceptions.

### Solution Brainstorm

Adding an optional argument to `capture_exception` to specify the type would be great.

**Comment by szokeasaurusrex** [comment]
Hi @rsprabery, thank you for suggesting this enhancement.

Just wondering, though: wouldn't it perhaps make more sense to simply raise an exception with the desired type, perhaps by wrapping the exception in your custom type? Or, could you use [`before_send`](https://docs.sentry.io/platforms/python/configuration/filtering/#using-platformidentifier-namebefore-send-)?

**Comment by rsprabery** [comment]
Definitely! Somehow I missed before_send in the docs, my bad!
