### ISSUE TITLE
username and email deesn't get included even though send_default_pii=True

### ISSUE THREAD

**Issue by nad2000** [getsentry/sentry-python#263]
I am running Flask app with Flask-Login. According to https://docs.sentry.io/platforms/python/flask/:

> If you use flask-login and have set send_default_pii=True in your call to init, user data (current user id,
> email address, username) is attached to the event.

I have set send_default_pii=True. However, the event notification payload doesn't contain username and email. It contains only ID and IP Address:

```json
user: {
ip_address: "127.0.0.1",
id: "2"
}
```

UI show "?" on the "User" section implying that there could be some extra info but it appears to be static (no link, no popup):

![2019-02-13 12-13-59](https://user-images.githubusercontent.com/177266/52674667-2c31d880-2f89-11e9-8f83-348c8a902aaa.png)

**Comment by untitaker** [comment]
That's fair, the docs are wrong here. Flask-Login on its own doesn't know usernames, only IDs, so accessing `user.email` is basically a shot in the dark.

We should still do this for Flask-User support.
