### ISSUE TITLE
Successful celery beat tasks with a duration below a threshold fails with "duration exceeded"

### ISSUE THREAD

**Issue by ezet** [getsentry/sentry-python#2651]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.39.2

### Steps to Reproduce

Using sentry with django and celery integrations, and automatic instrumentation for celery beat. We have ~40 cron jobs, most of which are working fine.
Our very short-running tasks (< 100ms) are consistently failing with "duration exceeded". The timeout is at default 30 minutes.
The same task will sporadically fail monitoring anytime there is no work to do, and it exits immediately. And it succeeds whenever there is work, and the task runs for longer. I am unsure about the exact threshold.

Example monitors:
https://hoopit.sentry.io/crons/logtasksprune_requestsprune_requests_task/?environment=production&project=248915&statsPeriod=14d
https://hoopit.sentry.io/crons/expensestasksclean_up_unconnected_expense_files/?environment=production&project=248915&statsPeriod=14d
https://hoopit.sentry.io/crons/poststasksclean_up_unconnected_post_images_task/?environment=production&project=248915&statsPeriod=14d
https://hoopit.sentry.io/crons/covid_registertasksprune_users/?environment=production&project=248915&statsPeriod=14d

I have confirmed tasks to be successful, and still fail in the monitor.
<img width="1907" alt="image" src="https://github.com/getsentry/sentry-python/assets/460611/59f6855f-8807-4986-ad17-9bd203f50035">
<img width="1416" alt="image" src="https://github.com/getsentry/sentry-python/assets/460611/98ad6585-b014-47b0-8fe5-0c7854745a44">

### Expected Result

When the task completes, the cron monitor should be successful.

### Actual Result

When the task completes, the cron monitor is not updated. It eventually fails with "duration exceeded"

**Comment by sentrivana** [comment]
Hey @ezet, thanks for the report. As the first step I'd verify whether the SDK sends check ins for the crons -- do you have the option to initialize the SDK with `debug=True`, trigger one of the short cron jobs that has the issue, and see what the debug logs look like? You should see that the SDK sends an event to the server. If that's not the case, something's wrong with the SDK; otherwise we'll need to investigate further on the server side.

**Comment by jonahgeorge** [comment]
Bumping ticket as I'm also experiencing this. Will look into collecting data via the `debug=True` option in the next few days
