### ISSUE TITLE
Investigate Sentry_sdk.scrubber to do the same as Sentry Server Scrubbing

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry-python#2654]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

Django 1.39.1/1.39.2

### Steps to Reproduce

1. Currently with the use of the scrubber it happens in some cases that the complete POST body of a request gets send. 
2. It get's scrubbed on Server side

But we want to be able to scrub it before it reaches the server. 

I am testing and the **password** field in the POST data is redacted in Sentry, but not when I intercept the event between SDK and Server.

### Expected Result

Being able to scrub on SDK side similar on what happens on Server Side

### Actual Result

I am testing and the **password** field in the POST data is redacted in Sentry, but not when I intercept the event between SDK and Server.

**Comment by sl0thentr0py** [comment]
we are scrubbing the request body here 
https://github.com/getsentry/sentry-python/blob/8bd2f461789554f4fceff62a10cc9c46910a8429/sentry_sdk/scrubber.py#L84-L85
so I need to know what is not being scrubbed from the user.
