### ISSUE TITLE
Support Python 3.13 (coming Oct 2024)

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#2664]
### Problem Statement

Python 3.13 is scheduled for release in [October 2024](https://peps.python.org/pep-0719/#schedule).

The first RC will be out in July, the second one in September.

### Solution Brainstorm

Prepare for 3.13 so that the SDK is compatible by release time.

**Comment by rominf** [comment]
I started building `python3-sentry-sdk` on Fedora 41, which will come with Python 3.13, and encountered some issues. Some Sentry SDK dependencies do not support Python 3.13 yet:
https://github.com/celery/kombu/issues/2051
https://github.com/gevent/gevent/issues/2037
https://github.com/python-jsonschema/jsonschema/issues/1264

I also created patches for the Sentry SDK itself; look for "Python 3.13" in https://src.fedoraproject.org/rpms/python-sentry-sdk/pull-request/10#request_diff. I want them to be included in the Sentry SDK. I saw you have https://github.com/getsentry/sentry-python/pull/3200 already. What is the most convenient way to submit PR(s)? Should I open PR(s) into `master` without testing them on Python 3.13, should I open PR(s) into your branch `ivana/python-3.13`, or should I base my PR(s) on top of yours in `master`?

**Comment by sentrivana** [comment]
Hey @rominf, first of all thank you for the fixes. I'd say let's go with PRs against the `ivana/python-3.13` branch for now so that we have everything tested eventually (once we manage to get the test suite to run -- looks like [pytest 8.2.1](https://docs.pytest.org/en/8.2.x/changelog.html#pytest-8-2-1-2024-05-19) works with 3.13, but e.g. `pytest-asyncio` doesn't yet).

**Comment by szokeasaurusrex** [comment]
Thanks @rominf!
