### ISSUE TITLE
Django: FileResponse causes UnicodeDecodeError

### ISSUE THREAD

**Issue by Maffooch** [getsentry/sentry-python#2668]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.39.2

## Description
When working with responses that return files, sentry SDK appears to decode the response to UTF-8 before sending to the sentry.io but fails. Unfortunately, the exception coming from sentry SDK is blocking the response from returning the file correctly. Disabling the sentry watcher allows the file to the part of the response successfully

I have tried filtering this specific path in the `before_send` function, but the exception is still being triggered. I would guess that sentry will always view the request/response and then determine whether to send to sentry if any error criteria was present

## Config
```
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

sentry_sdk.init(
    dsn=sentry_dsn, # The DSN String
    before_send=filter_paths, # Simple filter for health checks. Returning 'None' here has no effect
    enable_tracing=True,
    send_default_pii=True,
    integrations=[
        DjangoIntegration(
            transaction_style='url',
            middleware_spans=True,
            signals_spans=False,
            cache_spans=False,
        ),
    ],
)
```

## Steps to Reproduce
1. Have view that returns a FileResponse object:
```
def download_file(request):
    return FileResponse(open(abs_file_path))
```
2. Access link via browser/api
3. See the exeception in the Actual Results section

### Expected Result

Expected result is to not see any trace of an error from sentry 

### Actual Result

Exception thrown:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/wsgi.py", line 220, in __iter__
    reraise(*_capture_exception(self._hub))
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 115, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/wsgi.py", line 216, in __iter__
    chunk = next(iterator)
            ^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by sentrivana** [comment]
Hey @Maffooch, thanks for writing in. `FileResponse` [expects binary content](https://docs.djangoproject.com/en/5.0/ref/request-response/#fileresponse-objects); updating your view to open the file in binary mode like so
```python
return FileResponse(open(abs_file_path, "rb"))
```
should do the trick.

**Comment by Maffooch** [comment]
@sentrivana Thank you for your response! The proposed solution did indeed do the trick :)
