### ISSUE TITLE
Add ability for users to ensure a specific local variable gets logged in error stack trace

### ISSUE THREAD

**Issue by kylemumma** [getsentry/sentry-python#2682]
### Problem Statement

Currently not all of my local variables are showing up in my error stack trace, and the ones that show up and the ones that don't is determined arbitrarily. I want to ensure that a specific variable that I care about shows up in this stack trace.

### Solution Brainstorm

I'm not too sure how the sdk works so take my suggestions here with a grain of salt but one way I thought of is some sdk function like:
var1 = 15
ensure_capture(var1)
...

**Comment by szokeasaurusrex** [comment]
Hey @kylemumma, maybe you could try patching `sentry_sdk.serializer.MAX_DATABAG_BREADTH` and setting it to a larger value (by default it is `10`). This constant controls the number of local variables included in the stack trace, so if you increase the value, you will get more local variables in the trace.
