### ISSUE TITLE
Is there a way to include exc_info=True automatically with the errors? 

### ISSUE THREAD

**Issue by D0cR3d** [getsentry/sentry-python#271]
Basically as the title says. I'd like to have the `exc_info=True` exception information automatically included. Is there a way to do that without specifying it on every error logging command used?

**Comment by untitaker** [comment]
I assume you're in a situation where it's not feasible to rewrite your log statements to `logger.exception`? I would make a subclass of `LoggingIntegration`, and overwrite [`_handle_record`](https://github.com/getsentry/sentry-python/blob/b19b3c5f7aa9b6341a111ffc96e0a7eabe26e74c/sentry_sdk/integrations/logging.py#L50) to set `exc_info`. Then pass an instance of that logging integration type like described [here](https://docs.sentry.io/platforms/python/logging).

Not easy, but we never planned for this either.

**Comment by D0cR3d** [comment]
Thanks, I'll give that a try.

What about being able to attach the sentry handler using a logging config dict? Being able to create a dict of handlers, setting up all the standard configuration I wanted then just importing that into all of my projects made it nice and simple to do this:

```python
loggerconfig = LoggerConfig(__dsn__, __botname__, __version__)
logging.config.dictConfig(loggerconfig.get_config())
logger = logging.getLogger('root')
```

I ended up creating my own package which is where the 'LoggerConfig()' comes in and replaces the dsn and version, etc with the info I needed at the time, allowed setting the config once for all my projects.

Here's an example config dict I have:

```
{
    "version": 1,
    "formatters": {
        "default": {
            "format": "[%(asctime)s] | %(levelname)-9s | %(message)s",
            "datefmt": "%Y/%m/%d %H:%M:%S"
        }
    },

    "handlers": {
        "rotateFileHandler": {
            "class": "logging.handlers.RotatingFileHandler",
            "level": "INFO",
            "formatter": "default",
            "filename": "_DefaultName_Logs.log",
            "maxBytes": 10485760,
            "backupCount": 5,
            "encoding": "utf8"
        },

        "SentryHandler": {
            "level": "ERROR",
            "class": "raven.handlers.logging.SentryHandler",
            "dsn": "default",
            "release": "0.0.0"
        }
    },

    "loggers": {
        "root": {
            "level": "DEBUG",
            "handlers": ["rotateFileHandler", "SentryHandler"]
        }
    }
}
```

**Comment by untitaker** [comment]
I don't think there's supposed to be a need with the new SDK since it just grabs everything by default.

However, we have a `SentryHandler` in sentry-sdk as well, see here: https://docs.sentry.io/platforms/python/logging/#handler-classes
