### ISSUE TITLE
Speed up `grpc` test on py3.10

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#2721]
### Problem Statement

Our test suite is pretty snappy now with the exception of the `Networking (pinned) (3.10, ubuntu-20.04)` suite which takes 14 minutes and effectively slows everything else down.

### Solution Brainstorm

Make the Python 3.10 grpc tests faster in CI. This is the part that takes the most time:
```
  Building wheel for grpcio-tools (setup.py): started
  Building wheel for grpcio-tools (setup.py): still running...
  Building wheel for grpcio-tools (setup.py): still running...
  Building wheel for grpcio-tools (setup.py): still running...
  Building wheel for grpcio-tools (setup.py): still running...
```

**Comment by Cheapshot003** [comment]
Sooo, what if we just cache dependencies for that suite? Like this:
```
name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ matrix.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
```

That way we don't have to recompile the grpcio package. The implementation is probably wrong, don't know much about ci/cd yet. Or we can tell pip to use a prebuilt wheel. 
Ah, I love dependency management \s

**Comment by arr-ee** [comment]
_TL;DR_: caching alone might be tricky due to `tox`; pre-built wheels are super-easy to add, especially as a bandaid (patch below); long-term, pre-built wheels + exploring caching seems to be the way.

---

I've been eyeing this issue since I've been poking at how test envs are managed. Below is mostly my attempt to document current state and options — @sentrivana please correct what I got wrong!

So, we are forced to rebuild (older versions of) `grpcio-tools` against python versions released since, which is a costly operation. Current state (14 minutes for 1 python version x 3 `grpcio-tools` versions) is already a result of quite [aggressive matrix trimming](https://github.com/getsentry/sentry-python/pull/2567/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449L130-R132).

My understanding is that we're still trying to test against python 3.10 since it's the last release old versions of `grpcio-tools` build against, and we assume that if tests pass on the oldest and newest versions of python possible, they'd pass on intermediate versions as well (?)

Potential solutions:

1. Just Don't Test It
    `grpcio-1.21` is from 2019. We can try assuming that users stuck with such an old version are equally hesitant to upgrade python, and/or are okay with not using the latest version of the SDK.

    This is by far the easiest solution, but it seems to go against the whole testing approach here :)
2. Cache things
    As mentioned above, this can be done relatively easily with Github Actions, and I'm sure there are other approaches.

    Some potential shortcomings:
    
    - Due to `tox`, different CI jobs install different sets of packages => more cache keys => cache churn (depending on whether cache action treats cached data as an opaque blob or dedupes based on hashes or smth). Github's total cache allowance is 10Gb, we have 354 tox environments, with pip cache size being around 100Mb per env. Actual number of keys would be lower, but might cause issues anyway.
    - Dependencies info is spread across (at least) three files => ensuring we're actually using cache might require some additional monitoring of job runtimes.
    - As a result, we'll still have 14min jobs from time to time. Might not be end of the world, but definitely not ideal.
    
    That said, caching can help, and trying alternative approaches (e.g. having a full dep install job to cache everything, then reuse that cache for other jobs, assuming github lets us to) might be worth it.
    
    It should also be the most hands-off approach, assuming everything works: packages without wheels for new versions of python would be cached without manual intervention.
3. Backfill wheels ourselves
    `pip` has [several](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-f) [ways](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-extra-index-url) of providing alternative sources for packages, and combining that with either manually built wheels or something like [`cibuildwheel`](https://github.com/pypa/cibuildwheel) should give us consistently fast builds regardless of matrix size.

    I ran a quick-n-dirty check, and it works with barest minimum of changes:

    ```diff
    (sentry-py) m@reproduntu:~/local/sentry-python$ git diff
    diff --git a/tox.ini b/tox.ini
    index 34870b1a..bf961e2c 100644
    --- a/tox.ini
    +++ b/tox.ini
    @@ -234,6 +234,7 @@ deps =
        # in what's installed by tox (when running tox locally), try running tox
        # with the -r flag
        -r test-requirements.txt
    +    --find-links ../wheelhouse

        linters: -r linter-requirements.txt
        linters: werkzeug<2.3.0
    ```

    where `../wheelhouse` houses wheels from `pip wheel 'grpcio-tools==1.21.1'`, and can be replaced with a URL containing those. `tox -e py3.10-grpc-v1.21 -r` went from 210s to just under 15s.

    Of course, there are issues:

    - We'd need to house wheels somewhere. Any CDN, or even github repo would do, but it is still an additional bit.
    - New versions of python, new versions of dependencies, new dependencies == manual intervention in the form of building wheels or updating tooling config to build wheels.
4. An actually good solution that I have missed.

I am partial to the combination of caching and pre-built wheels, with patch above and `grpcio-tooling` wheel being hosted somewhere as a quick win for now.

I'm happy to look into this further — let me know what you think.

**Comment by sentrivana** [comment]
@Cheapshot003 @arr-ee Thank you both for weighing in on this and for researching possible solutions!

> My understanding is that we're still trying to test against python 3.10 since it's the last release old versions of grpcio-tools build against, and we assume that if tests pass on the oldest and newest versions of python possible, they'd pass on intermediate versions as well (?)

Pretty much, yes. :)

Re: caching, we often actually explicitly don't want to cache (or at least not in an "unsmart" way). Everytime the CI runs, it installs the test venvs anew, presumably using freshest versions of dependencies (unless pinned) since the CI workers are isolated. We want to preserve this behavior to catch regressions early, both in new framework/library versions (the `-latest` tests are meant to do this) as well as in other (in)direct dependencies. So it's kinda by design that this is not cached. Not saying we can't cache _anything_, but it'd be important that the dependency versions to install are considered when caching. At the same time, if we do that, there's even more potential for cache churn since it wouldn't be one cache entry per venv anymore.

Re: prebuilt wheels -- yeah this is something I had it mind too. Probably would even be fine to maintain this manually for outliers like `grpcio-tools` on py3.10. If we need/want to do this for more/all wheels, that can be done later. Just need to find a space to host this.

**Comment by sentrivana** [comment]
Hey folks, an update to this. Looks like our `grpc` tests are not doing exactly what they should be doing. We're testing with `grpcio-tools` (which is also the package that makes the whole test take too long) when we should be testing with `grpcio` directly. Looks like the `grpcio` versions that are pulled in via `grpcio-tools` are not what we would expect.

We should actually be pinning `grpcio` instead of `grpcio-tools`. If you just switch from `grpcio-tools` to `grpcio` in the `tox.ini` (and actually start testing the correct versions of `grpcio`), some tests fail because of incompatible Python version/changes in the API that we're not reflecting (...because we weren't testing the correct versions before). So this will need some cleanup.

**Comment by arr-ee** [comment]
> Not saying we can't cache anything, but it'd be important that the dependency versions to install are considered when caching. 

Yeah, the proposed approach effectively only caches downloads and wheels built during install, so venvs should be recreated from scratch as required. Maintaining this cache between envs would be a bit tricky as you say.

> Re: prebuilt wheels -- yeah this is something I had in mind too. <snip> Just need to find a space to host this.

sgtm. I looked into maybe squeezing it into (separate) repo with Actions, but it's unnecessarily annoying. If you don't mind running build/push locally (`cibuildwheel` should provide necessary isolation) it shouldn't be too bad — I can take a stab at a v0 in a bit.

> Looks like the grpcio versions that are pulled in via grpcio-tools are not what we would expect (i.e., it's just latest).

Ha, I was wondering about this when I saw `grpcio-tools==1.21.0` pull in `grpcio==1.62.0`. I took a quick look and it appears that with some bumps from `1.x0.0` we should be able to run most of the matrix. Still seeing some compilation failures with older versions of `grcpio` but this might be macos clang. Will update once I get a better understanding.

**Comment by sentrivana** [comment]
Regarding prebuilt wheels, we have an internal pypi that we can use -- I'll make a PR for that soon. And with the changes from https://github.com/getsentry/sentry-python/pull/2776 we'll already be at about 3.5 minutes for the test that's now taking 14 mins -- that's amazing! 🏃🏻
