### ISSUE TITLE
Memory leak with unclosed span in opentelemetry integration

### ISSUE THREAD

**Issue by vanchaxy** [getsentry/sentry-python#2722]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.40.3

### Steps to Reproduce

`SentrySpanProcessor` stores all open span in `self.otel_span_map` dict. This leads to a memory leak if otel span is deleted without closing. E.g. due to a bug: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/2149

### Expected Result

Sentry span should be deleted after otel span is deleted by GC.

### Actual Result

Sentry spans are stored in self.otel_span_map forever.

**Comment by sentrivana** [comment]
Thanks for the report @vanchaxy, putting this in our backlog.

**Comment by Undefined-User** [comment]
Same problem, docker crashes about once every hour without performing heavy tasks

**Comment by bruno-garcia** [comment]
isn't this a p0? it's def a p0 in .NET

**Comment by vanchaxy** [comment]
That's a very controversial solution. At least, make SPAN_MAX_TIME_OPEN_MINUTES configurable. Our system has a lot of long-running jobs that are longer than 10 minutes. I think the proper solution will be to create weak references to otel spans and remove sentry spans only if otel spans were deleted.

**Comment by DanielNoord** [comment]
@antonpirker Is there any interest in making this configurable? I have spend countless hours trying to understand why my `OpenTelemetry` spans were missing their root spans and it now turns out it is because a hidden global constant.
