### ISSUE TITLE
Performance monitoring for streaming responses

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry-python#2736]
### Problem Statement

In the Django integration, if a user wishes to performance-monitor a streaming response, the Django integration currently ends the transaction before the entire streaming response is complete. See the following for more context: https://github.com/getsentry/sentry/pull/64864#issuecomment-1934505442.

### Solution Brainstorm

The transaction should continue running until the streaming response is complete. We should either auto-detect a streaming response and automatically instrument the entire streaming response, or we should allow users to specify that they need the entire streaming response to be instrumented.

**Comment by sentrivana** [comment]
Closing in favor of https://github.com/getsentry/sentry-python/issues/3736
