### ISSUE TITLE
Fastapi: Url with path param without replacement in profiles_sampler and/or before_send_transaction

### ISSUE THREAD

**Issue by lucabergamini** [getsentry/sentry-python#2739]
### Problem Statement

Hi all,
Is it possible to get the original path without path params replacement in either the `profile_sampler` or `before_send_transaction` for a fastapi integration?

We are trying to filter out some transactions and we have generated a list of all the paths we want to exclude/subsample.

E.g. one would be `/streams/status/{camera}/data/{lens}` . However, in both functions' arguments dicts I can only see the url with the replaced path param (e.g.   `/streams/status/myCamera/data/myLens`) which can't really be compared against the string value of the route.

The transaction name is correctly reported without replacement in sentry, but I don't seem able to find that value in either `transaction_context` nor `event`. Am I missing something?

### Solution Brainstorm

I think it would be really helpful to have this value included so it can be used for subsampling and filtering

**Comment by sentrivana** [comment]
Hey @lucabergamini, thanks for writing in.

In `before_send_transaction`, the first argument (the `event`) has the unfiltered URL (not just the path) in `event["request"]["url"]`.

In `profiles_sampler` you get the sampling context as the sole argument and the path should be in `sampling_context["asgi_scope"]["path"]`.

Let me know if that helps.

**Comment by lucabergamini** [comment]
Hi @sentrivana 
thanks for the reply. That indeed works, but I've realised something after writing the original question.
`before_send_transaction` is called at the very end of the endpoint lifespan. That means that I won't be able to control the sampling and all endpoints call will be traced. This would cause a performance issue In our prod env.

`profile_sampler` seems to be called before. However the issue with that is that is called before everything else as far as I know, so even before fastapi url resolution. I've tried adding a middleware to inject context, but I believe that does not work exactly for this reason.

Is there any way to get any info to the profile_sampler or to postpone its evaluation? Currently, I resorted to running the path resolution in the function itself (which works, but it's a bit clunky)

**Comment by sentrivana** [comment]
@lucabergamini I think what you want is actually a custom [traces_sampler](https://docs.sentry.io/platforms/python/configuration/sampling/#configuring-the-transaction-sample-rate) -- it allows you to set the sampling decision for a transaction at an earlier point than `before_send_transaction` and afaik prevents child spans from being created if not sampled.

That being said, the `traces_sampler` callback happens at virtually the [same point in time](https://github.com/getsentry/sentry-python/blob/4d1b814cfc6764d9556e659327f1bf9008100289/sentry_sdk/scope.py#L720-L723) as `profiles_sampler` (with the same sampling context as well) so if you're missing information in the profile sampling context, you'll have the same issue with the `traces_sampler`. If you need more than the path in the sampling context, you might indeed need to get any additional info in the function itself, as you wrote.

**Comment by lucabergamini** [comment]
Hi @sentrivana, that makes perfect sense, thanks for your support. 
I'll close this as I consider it solved.
