### ISSUE TITLE
Make EventScrubber recursive

### ISSUE THREAD

**Issue by phb-teleclinic** [getsentry/sentry-python#2743]
### Problem Statement

We have a custom `before_send` implementation that scrubs data recursively. I was hopping to replace the custom implementation with the built-in EventScrubber but I found out that it doesn't scrub `vars` recursively.

As far as I can tell this was a consistency, perf trade-off thing but it would be nice to have a built-in option to make it recursive.

Thank you!

### Solution Brainstorm

`EventScrubber(recursive=True)`

**Comment by sentrivana** [comment]
Hey @phb-teleclinic, thanks for the suggestion, we can add this as an optional flag.

If anyone reading this feels like making a PR, please go ahead -- it'll probably take some time for us to get around to this.

**Comment by sl0thentr0py** [comment]
for completeness, we considered this here
https://github.com/getsentry/rfcs/blob/main/text/0062-controlling-pii-and-credentials-in-sd-ks.md#a-walk-whole-tree
but decided against it due to computational overhead.

**Comment by Cheapshot003** [comment]
taking a look at this. still a noob but this looks doable
