### ISSUE TITLE
Tornado integration sends broken cookies

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#276]
From [a forum post](https://forum.sentry.io/t/switching-to-sentry-python/4733/8):

>It also appears the cookies are being sent incorrectly:

```request.cookies.0.1: Discarded invalid value
Reason: expected a string
Value:
{
comment: , 
domain: , 
expires: , 
httponly: , 
max-age: , 
path: , 
secure: , 
version: 
}
```

**Comment by nickbaum** [comment]
As mentioned, I'm still not seeing the cookies.

I logged the event in beforeSend and see the below (some names REDACTED, values replaced with CHARACTER COUNT).

Note that there is a cookie object, but the cookies also seem to be sent as part of the headers.

-Nick

```
[...]
"request": {
          "cookies": {
              "_xsrf": "54 CHARACTERS",
              "__stripe_mid": "36 CHARACTERS",
              "_ga": "27 CHARACTERS",
              "_fbp": "28 CHARACTERS",
              "G_ENABLED_IDPS": "6 CHARACTERS",
              "REDACTED": "137 CHARACTERS",
              "googleAnalyticsClientId": "21 CHARACTERS",
              "REDACTED": "551 CHARACTERS",
              "_gid": "27 CHARACTERS",
              "REDACTED": "31 CHARACTERS",
              "G_AUTHUSER_H": "1 CHARACTER",
              "REDACTED": "148 CHARACTERS",
              "_gaexp": "37 CHARACTERS",
              "REDACTED": "27 CHARACTERS",
              "REDACTED": "162 CHARACTERS",
              "current_user": "5 CHARACTERS",
              "REDACTED": "128 CHARACTERS",
              "logged_in_users": "100 CHARACTERS",
              "user_email": "26 CHARACTERS",
              "_derived_epik": "108 CHARACTERS",
              "intercom-session-blwumk0q": "14 CHARACTERS",
              "REDACTED": "594 CHARACTERS"
          },
          "url": "31 CHARACTERS",
          "query_string": "",
          "method": "GET",
          "env": {
              "REMOTE_ADDR": "::1"
          },
          "headers": {
              "Host": "18 CHARACTERS",
              "Connection": "10 CHARACTERS",
              "Cache-Control": "9 CHARACTERS",
              "Upgrade-Insecure-Requests": "1 CHARACTER",
              "User-Agent": "120 CHARACTERS",
              "Accept": "118 CHARACTERS",
              "Accept-Encoding": "17 CHARACTERS",
              "Accept-Language": "32 CHARACTERS",
              "Cookie": "3555 CHARACTERS"
          }
      },
[...]
````

**Comment by untitaker** [comment]
Damn I forgot about this

**Comment by untitaker** [comment]
@nickbaum just as a quick update, I think there's a serverside bug here. I'm not sure what happens here, particularly why the Cookie header disappears. There seems to be some truncation going on with your cookies map, though I am not sure either why the server even thinks it's too large.

**Comment by nickbaum** [comment]
Got it, thanks for looking into it. Note that the cookie header is quite large (3555 characters).

Is there someone we could loop in from the server side to troubleshoot?

**Comment by untitaker** [comment]
Just as an update, I have been looking into this and was unable to reproduce this bug with https://github.com/getsentry/semaphore directly (our event parsing library).

**Comment by nickbaum** [comment]
Thanks for the update. Anything I can do on my side to help troubleshoot?

**Comment by untitaker** [comment]
I'm not sure. I also tried to send your event (with the right amount of
characters in each field) through a testproject and couldn't replicate this
behavior

**Comment by nickbaum** [comment]
Looks like cookies are coming through now, not sure if something changed on your side but as far as I'm concerned you can close this!

**Comment by untitaker** [comment]
Huh, okay let's close this until somebody reports it again.
