### ISSUE TITLE
Where to add extra data in Django

### ISSUE THREAD

**Issue by OrangutanGaming** [getsentry/sentry-python#278]
Hi,

I'm using the Sentry SDK with the Django integration and seen that you can do things like https://docs.sentry.io/enriching-error-data/context/?platform=python#capturing-the-use but I'm wondering where you could actually implement this for all requests? I think part of the reason may be because the only thing I know about how the SDK handles sessions and how it stores info is "magic." Does anyone have an example of how this could be implemented?

Thanks, Nihaal

**Comment by untitaker** [comment]
Do you want to add extra data based on the current request, but for all requests? I think writing a django middleware would be suitable for this as it's running before each view.

Do you want to add constants independent of the request to extra? Then you can run `configure_scope` at import time.

**Comment by OrangutanGaming** [comment]
For the latter do you mean using it when you init (for me in my settings.py) and that will set data for everything?

I think my main use would be per request, so I'll look at making my own middleware, and any constants can be defined there too if needed.

**Comment by untitaker** [comment]
Yes exactly.

You can combine the two approaches and it will work as well.

**Comment by OrangutanGaming** [comment]
I managed to set this up, but one problem I'm having is being able to set multiple details for the user. I am setting the `ip_address`, `id`, `username` and `email` but in the event it shows only the email and the id (the first one in the dictionary). Is there a way to give all these details?
Simplified:
```py
with configure_scope() as scope:
    scope_user = {'ip_address': ip}

    if user.is_authenticated:
        scope_user.update({'id': user.pk, 'email': user.email, 'username': user.username})

    scope.user = scope_user
```

**Comment by untitaker** [comment]
The Django integration will overwrite the `ip_address` with the request's IP address. Is there a mismatch between the two in your case?

It seems that we should not overwrite the `ip_address` with `None` if there is no IP address in the request though. So that part is a bug

As a workaround you can write this for now:

```python
with configure_scope() as scope:
    @scope.add_event_processor
    def _(event, hint):
        event['user']['ip_address'] = ip
        return event
```

Sorry for the inconvenience

**Comment by untitaker** [comment]
Actually now that I think of it, it's odd that your HTTP request has no client IP.

**Comment by OrangutanGaming** [comment]
It does, I just want to use my own methods of obtaining it. When I set the other fields though, on the website it does not show all of the fields I've added, only the email and id. Before I touched the scope, it had just the default which was the ip.

**Comment by untitaker** [comment]
That is odd. So you're saying that before you added any extra data, the events did have an IP address attached, and only after you set `username` and `id` the IP disappeared? Could it be that you're inadvertently setting the `ip` to `None` or a value that is not a string?

**Comment by OrangutanGaming** [comment]
Well even if the IP was causing an issue, the username is not shown

**Comment by untitaker** [comment]
Could you scroll down to the `User` section and check there? We don't show everything at the top.

**Comment by OrangutanGaming** [comment]
Oh, I had no idea that section was even there 🤦‍♂️ 
Is there a way to customise the tags that are shown at the top?

**Comment by untitaker** [comment]
Yes, you can use `set_tag` on the scope: https://docs.sentry.io/enriching-error-data/context/?platform=javascript#tagging-events

**Comment by OrangutanGaming** [comment]
Thanks for all the help and the fast replies!
