### ISSUE TITLE
Loguru Integration sets invalid level values on event

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry-python#2799]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.41.0

### Steps to Reproduce

N/A

### Expected Result

The Loguru integration only should set valid level values on the event and breadcrumb objects. [The only valid values](https://develop.sentry.dev/sdk/event-payloads/), according to the docs, are "fatal", "error", "warning", "info", and "debug". Relay additionally [recognizes](https://github.com/getsentry/relay/blob/e844de508c990425f3da8e9f343d2ba5771acd84/relay-event-schema/src/protocol/types.rs#L688) "log" and "critical" as aliases for "info" and "fatal", respectively.

### Actual Result

The Loguru integration sometimes sets the event or breadcrumb level to "trace" or "success" – both of which are invalid values that Relay will reject.

**Comment by sentrivana** [comment]
See also https://github.com/getsentry/sentry-python/issues/2759

We could either add the new levels to relay or preprocess them in the SDK somehow (e.g., change trace to debug).

**Comment by sentrivana** [comment]
Closing in favor of https://github.com/getsentry/sentry-python/issues/2759
