### ISSUE TITLE
Make sure we only ever send a single value in outgoing trace headers.

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#2803]
When sending outgoing `sentry-trace` or `baggage` headers make sure that they only have one value included. 

Something like this never be sent (same goes for `baggage` header):

```
sentry-trace: 6a5871d13d8441818ccc593c6c3b07c8-b252c3821bdbaceb-1, 6a5871d13d8441818ccc593c6c3b07c8-88529d2712c386fd-1
```

See also issue in Sentry where this originated: https://github.com/getsentry/sentry/issues/66701

Related issue for handling incoming headers: https://github.com/getsentry/sentry-python/issues/2802

**Comment by szokeasaurusrex** [comment]
Will be fixed with Potel #2251
