### ISSUE TITLE
Add stack information when `stack_info` is set in logging integration.

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#2804]
### Problem Statement

The stack information should be added to events send with the logging integration when `stack_info=True` is set. 

Code like this should have a stack attached in the resulting event in Sentry:
```python
logger.error(
    "Option %s set to %s. previous update channel: %s",
    key,
    value,
    channel,
    stack_info=True,
)
```

### Solution Brainstorm

Check for the parameter in logging integration and add the stack information if parameter is True.

**Comment by antonpirker** [comment]
Some info from @untitaker :

`exc_info=True` should send the stack
specifically, it sends the current stack if `sys.exc_info` is `None`, otherwise it sends the current exc info
`stack_info` appears to be new in 3.2, we made the api design decisions with py2 in mind at the time

**Comment by gmcrocetti** [comment]
Hello @antonpirker, 

Sentry's support just informed me that the stack trace is critical during the auto assignment of one event to the correct team as the path type rule is matched against all file paths of the stack.

Therefore I do have a lot of interest in resolving this issue. I did some research and I believe this is the [method](https://github.com/getsentry/sentry-python/blob/c2dfbcc3c3de1c32de516ec4268a602cb42e0694/sentry_sdk/integrations/logging.py#L182) in need of modification. Any other places or any recommendation you find useful ?
