### ISSUE TITLE
issues with self-signed cert

### ISSUE THREAD

**Issue by mcclurem** [getsentry/sentry-python#283]
I've been using raven previously without any issue. I started following the docs at [docs.sentry.io](https://docs.sentry.io/platforms/python/flask/) and it doesn't seem to work with a very simple test case:

```
#!/usr/bin/env python3
from flask import Flask, current_app
import sentry_sdk
from sentry_sdk.integrations.flask import FlaskIntegration
from sentry_sdk.integrations.logging import LoggingIntegration

app = Flask(__name__)
sentry_sdk.init(dsn="MYSECRETDSN"
                integrations=[FlaskIntegration(), LoggingIntegration(event_level="ERROR")])

@app.route("/")
def myendpoint():
    return "ok"

@app.route("/crashme")
def myendpoint2():
    current_app.logger.error("This is an error logged")
    return "not ok"

@app.route("/realcrash")
def realcrash():
    raise ValueError("This is an exception")

if __name__ == "__main__":
    app.run(debug=False)
```

I've tried with both style of DSN and no luck. Server is known good because I can get logging with raven and the same DSN if I just replace the sentry_sdk.init line with:

```
import logging
from raven.contrib.flask import Sentry
sentry = Sentry(app, logging=True, level=logging.ERROR, dsn="MYSECRETDSN")
```
It works exactly as expected

Configuration is:
cpython 3.6.5 on OSX
sentry-sdk==0.7.6
Flask==1.0.2

**Comment by untitaker** [comment]
Could you clarify what "does not work" means?

**Comment by mcclurem** [comment]
Sorry that was vague: When I hit the /crashme or the /realcrash endpoints I get no events created in my sentry instance. I also see no output in my server logs that would indicate that sentry_sdk tried to do something and failed. My expectation is that both endpoints should create an event and that expectation holds when I switch over to use raven but does not occur with sentry_sdk

**Comment by untitaker** [comment]
@mcclurem could you check with `init(.., debug=True)`? That example works for me.

**Comment by mcclurem** [comment]
So you're correct, it was an issue with self signed cert (which apparently raven didn't care about?)
Is there an initialization option for passing a path to a .pem? or is the only option to set the REQUESTS_CA_BUNDLE environment variable?

**Comment by untitaker** [comment]
Yup: https://docs.sentry.io/error-reporting/configuration/?platform=python#ca-certs

**Comment by mcclurem** [comment]
Thanks a bunch
