### ISSUE TITLE
Track number of rows affected in DB spans

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#2841]
### Problem Statement

For our performance product we want to be able to track the average number of rows returned/affected by a DB query.

### Solution Brainstorm

Add row count to DB query spans where possible. Document the new field somewhere (probably develop docs).

**Comment by gggritso** [comment]
@stephanie-anderson 👀 "completed"! Did this feature get implemented, or moved somewhere else, or deprioritized? I couldn't find any related tickets or docs
