### ISSUE TITLE
support aiohttp and sanic for python 3.6

### ISSUE THREAD

**Issue by aCLr** [getsentry/sentry-python#289]
Looks like aiohttp and sanic integrations python 3.6 can be supported, because of [backported contextvars library](https://pypi.org/project/contextvars/)

**Comment by untitaker** [comment]
afaik the issue was that this contextvars backport doesn't work with asyncio from the stdlib at all (leaking context all over the place).

We have leak tests in the sanic test suite, so if the testsuite works with that backport this would be interesting to investigate again

**Comment by aCLr** [comment]
Unfortunatelly, you are right :(
[Here](https://github.com/MagicStack/contextvars/issues/2) is an issue about asyncio support.

**Comment by untitaker** [comment]
Just curious, is something holding you on Python 3.6? Distro packages?

**Comment by aCLr** [comment]
Sure :)
