### ISSUE TITLE
[Due April 5th] Investigate potential Redis instrumentation capabilities for Cache module

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-python#2903]
This task is a prerequisite for our next Performance module for Caches. Before we add or modify any existing integration, or come up with a new one, we need to figure out what kind of data we can get. The product team working on this needs this feedback, so they can finish their planning for the displayed data.

Have a look at the overarching project issue for more details: https://github.com/getsentry/team-sdks/issues/62

We promised to work on this once we managed to upgrade Sentry to use our next Python SDK major. Using the next major is planned for the 2nd of April, investigation should be done **until 5th of April** the latest.

**Comment by antonpirker** [comment]
This has been done in the PRs mentioned in these umbrella PRs:

Redis:
https://github.com/getsentry/sentry-python/issues/2965

Django Caching:
https://github.com/getsentry/sentry-python/issues/2964
