### ISSUE TITLE
Integrations: Ariadne - `handled` tag is always `False` 

### ISSUE THREAD

**Issue by bmarkovicvega** [getsentry/sentry-python#2904]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.42.0

### Steps to Reproduce

1. Define graphql query:
```
extend type Query {
    testQuery: testPayload!
}

type TestResult {
    field1: Boolean
}

type TestPayload {
    status: Boolean!
    result: TestResult
    errors: [Error]
}
```

2. Execute the query with requesting data not defined in `TestResult`:

```
query { 
    testQuery{
        resut{
            non_existing_field
        }
    }
}
```

note: `AriadneIntegration()` is added upon `sentry_sdk.init()`

### Expected Result

Error is reported in sentry with flag -> handled: True 

### Actual Result

Error is reported in sentry with flag -> handled: False

Why the error is reported as not handled when it seems that it's handled by library and a proper message is received
Message received and reported:
```
Cannot query field 'non_existing field' on type 'TestResult'
```

**Comment by sentrivana** [comment]
Hey @bmarkovicvega, thanks for writing in. Looks like in the Ariadne integration we report all error events as unhandled, but this also seems to be a pattern in other similar integrations.

From your perspective as someone who uses the integration, what would you consider to be an unhandled Ariadne error? Would you prefer all Ariadne errors raised by Sentry to be marked as handled?

**Comment by bmarkovicvega** [comment]
> Hey @bmarkovicvega, thanks for writing in. Looks like in the Ariadne integration we report all error events as unhandled, but this also seems to be a pattern in other similar integrations.
> 
> From your perspective as someone who uses the integration, what would you consider to be an unhandled Ariadne error? Would you prefer all Ariadne errors raised by Sentry to be marked as handled?

Hi @sentrivana thanks for answering. What I would expect, from my perspective, is that unhandled error would be the error raised by the code I've added, but for errors handled by `ariadne` library such as one I mentioned in the issue I would make them handled or even I wouldn't consider them as error that should be logged and reported in sentry.
I do request with non existing field, I got message that it's not existing withing the certain query, for me it seems handled.

Giving an example and making a parallel with the REST endpoint: if we do `POST /users` that requires `username` and `password` and if I don't pass `password` which is required I will get a response with http status `400` with a usual validation error message right, this doesn't seem like unhandled error that should be reported in sentry (at least it looks like handled)

**Comment by bmarkovicvega** [comment]
> Thanks @bmarkovicvega, that makes sense to me. For web frameworks we usually don't report client (4xx) errors at all since those should be reported by the client side, so it'd make sense to do something analogous for our GraphQL integrations as well. What's at the moment not clear to me is how we can categorize the errors we see e.g. in Ariadne into client and server errors, this needs some investigation into what the different errors look like and how we can tell them apart.
> 
> In the meantime though, if you find the errors not actionable, you can always define a custom `before_send` ([docs](https://docs.sentry.io/platforms/python/configuration/options/#before-send)) where you either drop the error altogether (by returning `None`) or you manually change the `handled` field.

 I appreciate you have looked at the issue and discussed it @sentrivana. Thanks for your time and thoughts about it. Also, thank you for giving a suggestion how to solve it for now.

**Comment by sentrivana** [comment]
> I appreciate you have looked at the issue and discussed it @sentrivana. Thanks for your time and thoughts about it. Also, thank you for giving a suggestion how to solve it for now.

You're very welcome. Thank you for your time and perspective as well, it's always valuable to know how folks use the SDK so that we can make it better.

**Comment by bmarkovicvega** [comment]
> Regarding your point here [@bmarkovicvega](https://github.com/bmarkovicvega):
> 
> > Hi [@sentrivana](https://github.com/sentrivana) thanks for answering. What I would expect, from my perspective, is that unhandled error would be the error raised by the code I've added, but for errors handled by ariadne library such as one I mentioned in the issue I would make them handled or even I wouldn't consider them as error that should be logged and reported in sentry.
> 
> Marking all exceptions that are captured by a Sentry integration with `handled=False` is, in fact, the desired behavior. I [have written a detailed explanation about why this is the case](https://github.com/getsentry/sentry-python/issues/3107#issuecomment-2210457301) on a similar issue:
> 
> > In fact, the behavior you are observing here is the expected behavior. Exceptions reported by an integration are always intentionally reported to Sentry as being "unhandled" because when the exception is captured in the integration, it is impossible to know whether any code up the call stack will handle the exception. The only time an exception will be reported to Sentry as being "handled" is when the user code explicitly captures an exception by calling sentry_sdk.capture_exception.
> > While we understand that the behavior of reporting eventually-handled exceptions as "unhandled" may be unintuitive to some users, improving this behavior further in the SDK is not technically possible, since the SDK has no way to tell whether an exception it captures will eventually get handled up the stack or whether the exception is truly unhandled. The only way for us to ensure that all truly-unhandled exceptions are labelled as "unhandled" is to also label eventually-handled exceptions as "unhandled."

Hi @szokeasaurusrex, I understand what you wrote in the explanation on the link you sent and using `before_send` and `capture_exception` fits. Thanks for triage and explanation.

**Comment by gdalmau** [comment]
> it is impossible to know whether any code up the call stack will handle the exception.

Thanks @szokeasaurusrex for the reply. If ariadne in this case would always raise a specific exception for the "handled" errors, would it be possible for the integration in sentry to mark it as handled or not based on the type of exception?

**Comment by gdalmau** [comment]
> `handled=True` is, I think, typically used to indicate when an exception is captured manually by a user after handling it
@szokeasaurusrex I would argue that it does not necessarily need to be manually captured, as long as the system handled it and didn't return a 5XX error.

While I understand what you are saying, I think that we should be able to have a similar behaviour to the `DjangoIntegration` with this integration, `AriadneIntegration`.

For instance, with `DjangoIntegration` we can observe the following behaviour during an HTTP request:

- When a 5XX is returned, an event (exception) with `handled=False` is sent to sentry
- When a 4XX is returned, there is no event in sentry

This is done in [this place](https://github.com/getsentry/sentry-python/blob/2.14.0/sentry_sdk/integrations/django/__init__.py#L524-L529) in the code that uses the django signals API, which further down the line [checks the instance of an exception](https://github.com/django/django/blob/5.1.1/django/core/handlers/exception.py#L63) to determine if the signal needs to be sent or not via `signals.got_request_exception.send(sender=None, request=request)`.

> From my understanding, and exception which is captured by an integration should always have handled=False because the fact that the SDK captures the exception in the integration at all indicates that the user code failed to handle the exception prior to the exception bubbling up to the library.

I agree, but if `ariadne` (or `graphql-core`) raises an exception for handled errors, even if they are handled after sentry's code, we should mark them as handled, or see if we could capture them at the end of the Django middleware request processing.

**Comment by szokeasaurusrex** [comment]
Hey @gdalmau, with regards to the behavior in the Django integration that you are observing, I believe this happens because Django only raises exceptions for `5xx` status codes. No exception is raised for `4xx` statuses, or if one is raised, it gets handled before the Sentry instrumentation captures it.

> I agree, but if `ariadne` (or `graphql-core`) raises an exception for handled errors, even if they are handled after sentry's code, we should mark them as handled, or see if we could capture them at the end of the Django middleware request processing.

The technical problem is that there is no way for us to be certain whether a certain exception will eventually be handled. It is expected behavior that the SDK marks all exceptions which it captures through automatic instrumentation as `handled=False`. I believe we almost never send an exception with `handled=True`; this feature is mainly meant for users who manually capture an exception that they handle.

We could, however, check whether there is a way to capture the exceptions later, after Ariadne would have handled any exceptions. These handled exceptions would then not be sent to Sentry at all; only the ones unhandled by Ariadne would show up.

**Comment by gdalmau** [comment]
> The technical problem is that there is no way for us to be certain whether a certain exception will eventually be handled. It is expected behavior that the SDK marks all exceptions which it captures through automatic instrumentation as `handled=False`. I believe we almost never send an exception with `handled=True`; this feature is mainly meant for users who manually capture an exception that they handle.
> We could, however, check whether there is a way to capture the exceptions later, after Ariadne would have handled any exceptions. These handled exceptions would then not be sent to Sentry at all; only the ones unhandled by Ariadne would show up.

Thanks @szokeasaurusrex for the active conversation.

On second thought, you are absolutely right. As you said, we shouldn't even mark it as an exception (regardless of the `handled` flag) and directly "ignore" it, thus treating it like a 4XX from Django, which doesn't send any event to sentry. If we agree on this behaviour, is there any information that we need to know to implement it?

**Comment by szokeasaurusrex** [comment]
>  If we agree on this behaviour, is there any information that we need to know to implement it?

@gdalmau To be honest, I am not fully convinced that it is a good idea to start ignoring errors that the SDK currently would send to Sentry. Even if we were certain that some class of exception raised by Ariadne always gets handled, what if there are some users relying on these exceptions getting sent to Sentry for whatever reason? If we start ignoring some errors by default, these would disappear for all users, including those who rely on the current behavior.

I will admit, though, that I personally have not worked too much with Ariadne, so if you can explain which exact errors you think should be ignored and why you expect they would not be relevant to users, this might convince me that we should be ignoring these errors.

Otherwise, if you are seeing some errors in Sentry that you know Ariadne handles, and which you are not interested in, my suggestion would be to set [the `before_send` callback](https://docs.sentry.io/platforms/python/configuration/filtering/#using-before-send) to filter these out. `before_send` gives you the maximum flexibility to decide what events you want to send to Sentry based on your needs, and using it does not require any changes in the SDK.
