### ISSUE TITLE
Python CeleryIntegration accumulates baggage header data on retry

### ISSUE THREAD

**Issue by tomas-sk** [getsentry/sentry-python#2916]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.41.0

### Steps to Reproduce

1. Retry celery task within sentry transaction
2. Each retry appends one duplicate of sentry baggage data

See attached python reproduction steps.
[sentry_celery_baggage_py.txt](https://github.com/getsentry/sentry-python/files/14776531/sentry_celery_baggage_py.txt)

### Expected Result

Make CeleryIntegration, possible other not duplicate baggage headers.

### Actual Result

[sentry_celery_baggage_log.txt](https://github.com/getsentry/sentry-python/files/14776497/sentry_celery_baggage_log.txt)

**Comment by antonpirker** [comment]
Hey @tomas-sk, thanks for reporting this! Yea, this should not happen.

**Comment by antonpirker** [comment]
This issue is fixed. 

As @tomas-sk never got back, I also assume it is working for them now.
