### ISSUE TITLE
python3 dependency hell

### ISSUE THREAD

**Issue by mrx23dot** [getsentry/sentry-python#2942]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

pip install --upgrade sentry-sdk[flask]

caused this 
```
    import requests
  File "C:\Python37\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Python37\lib\site-packages\urllib3\__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.1.0h  27 Mar 2018'. See: https://github.com/urllib3/urllib3/issues/2168
```

to fix this StackOverflow suggested
`pip install urllib3==1.26.6`

but then pip complains 
`sentry-sdk 1.44.1 requires urllib3>=1.26.11; python_version >= "3.6", but you have urllib3 1.26.6 which is incompatible.`

but sentry.io still works.

**so please remove urllib3 version dependency.**

Python 3.7.0

### Expected Result

sentry shouldn't depend on version of urllib3 

### Actual Result

it depends on given urllib3 version, even though it works with older one.

### Product Area

Other

**Comment by sl0thentr0py** [comment]
@mrx23dot 
```
pip install 'urllib3<2.0'
```
should work

**Comment by sentrivana** [comment]
The SDK will still work with older `urllib3` versions -- the lower bounds were added for another reason, which is to avoid installing `urllib3` versions with known vulnerabilities: https://github.com/getsentry/sentry-python/commit/b7c0dc412a1505fff382732f567952c8a9572b60 So this is expected behavior.

**Comment by musmanafzal7** [comment]
ERROR: Requested sentry-sdk[flask] from https://files.pythonhosted.org/packages/f4/72/464966f2c60696bae0eae55270f29883e03581d12aeecddf87ef5ffb6752/sentry_sdk-1.9.1-py2.py3-none-any.whl (from -r requirements.txt (line 41)) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    urllib3 (>=1.26.11") ; python_version >= "3.6"
