### ISSUE TITLE
Runtime `TypeError`s due to incorrect conditional handling of `Event` and `Hint` types

### ISSUE THREAD

**Issue by MarkusSintonen** [getsentry/sentry-python#2975]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.44.0

### Steps to Reproduce

We get runtime errors when importing and using Sentry `Event` types (works with mypy but breaks when running):
```python
 def sentry_before_send(event: Event, hint: Hint) -> Event | None:  # CRASH TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'
    return event
```

This is due to `sentry_sdk.types` module incorrectly setting the `Event` type into `None` when not running in type checking context:
```python
if TYPE_CHECKING:
    from sentry_sdk._types import Event, Hint
else:
    Event = None
    Hint = None
```

Why is there such fallback that sets those incorrectly to `None`? That breaks at runtime when using it with `init_sentry(before_send=sentry_before_send)` hook which return type should be `Event | None`

### Expected Result

It should not crash at runtime to `TypeError`

### Actual Result

```
    def sentry_before_send(event: Event, hint: Hint) -> Event | None:
E   TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'
```

**Comment by szokeasaurusrex** [comment]
Hi @MarkusSintonen, this problem has already been fixed in [version `1.44.1`](https://github.com/getsentry/sentry-python/releases/tag/1.44.1). Please upgrade to version `1.44.1` or above to fix your problem!
