### ISSUE TITLE
Missing Span Instrumentation under Profiling

### ISSUE THREAD

**Issue by ShuaiShao93** [getsentry/sentry-python#2989]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.45.0

### Steps to Reproduce

1. Init sentry in FastAPI application, and enable profiling
2. Make an API call
3. Check sentry.io Profiling page

### Expected Result

Full Python call stack is profiled

### Actual Result

Missing Span Instrumentation

<img width="1202" alt="image" src="https://github.com/getsentry/sentry-python/assets/7556010/5cf23b32-1690-4dcc-97f8-e2db7be71b56">

**Comment by szokeasaurusrex** [comment]
Hi @ShuaiShao93, the portion of the page where you are seeing the "missing span instrumentation" message is not the profile; it is the span view, which displays the spans, not the function call stack.

The profile is located below the span view, and should contain the entire function call stack over time.

Hope that helps! If you are still having trouble, please feel free to reopen the issue.

**Comment by ShuaiShao93** [comment]
The profile below is incomplete, too. 
<img width="1480" alt="image" src="https://github.com/getsentry/sentry-python/assets/7556010/5bdc73f7-b53a-4555-8be0-b33d9c8fbb66">
There is only a `run`, which is the base function of Uvicorn worker.

**Comment by asim-shrestha** [comment]
Any updates here? @ShuaiShao93

**Comment by sl0thentr0py** [comment]
that's just the main thread, you can use the thread selector on the top left to look at the other threads
