### ISSUE TITLE
Dask and Distributed Support

### ISSUE THREAD

**Issue by crepererum** [getsentry/sentry-python#299]
(continued from #291)

It would be nice if sentry would support [dask](https://docs.dask.org/) and [distributed](https://distributed.readthedocs.io/). Namely, the following features should be supported:

1. sentry sdk initialized on the client should be carried over to the workers
2. flushing the event queue should work (e.g. on subprocess shutdown for local executors or on worker shutdown for distributed)

*feel free to split this ticket into two if required*

**Comment by untitaker** [comment]
>sentry sdk initialized on the client should be carried over to the workers

We don't support this for any task queue. I'm not sure if it's a good idea because I don't quite know how the implementation would work. We also don't transfer scopes from clients to workers.

**Comment by crepererum** [comment]
> We  don't support this for any task queue. I'm not sure if it's a good idea  because I don't quite know how the implementation would work. We also  don't transfer scopes from clients to workers.

OK. Could than at least the integration add some context to the events emitted by the workers? (like computation ID or even which part of the computation graph is currently executed)

**Comment by untitaker** [comment]
Sure. I don't want to discard the idea of carrying over scopes if it makes sense, but carrying over SDK config is probably not expected.

I'm open to all kinds of ideas, but they should be non-invasive in the sense that we shouldn't just add new arguments to a job just because we need them on the other machine.

**Comment by antonpirker** [comment]
Currently we do not have plans to support this, Sorry.
