### ISSUE TITLE
Wrong python version in the docs

### ISSUE THREAD

**Issue by jredrejo** [getsentry/sentry-python#301]
https://docs.sentry.io/platforms/python/ claims that

> The Sentry Python SDK provides support for Python 2.7 and 3.4 or later.

However, in https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/aiohttp.py  `async` is used several times

async is not available until python >= 3.5

**Comment by untitaker** [comment]
The version requirements for integrations are documented separately:
https://docs.sentry.io/platforms/python/aiohttp/

We should add this caveat to the sentence you're referring to

**Comment by untitaker** [comment]
This has been added to the docs since then
