### ISSUE TITLE
Is it possible to use Sentry with QuartTrio

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-python#3036]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

latest

### Steps to Reproduce

https://stackoverflow.com/questions/78416251/using-sentry-io-with-quarttrio-has-anyone-got-this-working

### Expected Result

sentry works ideally with Quart integration, since QuartTrio is based on this, error handling and tracing. TBD if there are aspects which do not fit

### Actual Result

Crash

full detail in the stackoverflow report

**Comment by jay-tuckey** [comment]
Turns out this was a bug in the v2.0.x release of the sentry SDK. It's fixed in the 2.1.x version, and now works correctly with both Quart and QuartTrio. 

See also: https://github.com/getsentry/sentry-python/issues/3040

This can be closed.

**Comment by szokeasaurusrex** [comment]
@jay-tuckey Correct, our Quart integration was completely broken in 2.0.x. It works from 2.1.0. Glad to hear that the same fix also fixed Quart Trio!
