### ISSUE TITLE
Add support for `add_note()` / `__notes__`

### ISSUE THREAD

**Issue by arjenzorgdoc** [getsentry/sentry-python#3050]
### Problem Statement

Python 3.11 added support for notes:

```python
async def f4():
    try:
        await f3()
    except TypeError as e:
        e.add_note('this failed while trying to blah')
        raise
```

(Source: https://blog.sentry.io/python-3-11-release-top-5-things-to-know/#adding-notes-to-exceptions)

I don't see them in sentry.

### Solution Brainstorm

Check if an exception has a `__notes__` property and add them to the "message" field.

**Comment by szokeasaurusrex** [comment]
Good idea! Seems like something we should look into supporting. We would also be happy to accept PRs for this!
