### ISSUE TITLE
Issue with _set_db_data when using psycopg3

### ISSUE THREAD

**Issue by austin-wentz** [getsentry/sentry-python#3061]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

2.1.1

### Steps to Reproduce

I created a [sample repo](https://github.com/austin-wentz/sentry-psycopg-bug) that reproduces the bug.

1. Checkout the repo 
```
git clone https://github.com/austin-wentz/sentry-psycopg-bug.git
```
2. Install requirements
```
pip install -r requirements.txt
```
3. Startup postgres
```
docker-compose up
```
4. Run test without Sentry (test will succeed)
```
./manage.py test
```
5. Run test with Sentry (test will fail)
```
export USE_SENTRY=True && ./manage.py test
```

From what I can tell, the issue is that the call to get_parameters() tries to access [pgconn.info](https://github.com/psycopg/psycopg/blob/master/psycopg/psycopg/_connection_info.py#L91), but that will throw an operational error if the connection is already closed.

A suggested fix would be something like
```
if is_psycopg3:
    connection_params = {}
    if not cursor_or_db.connection.closed
        connection_params = cursor_or_db.connection.info.get_parameters()
```

### Expected Result

The expected result is for the sentry-sdk to not try and access a bad connection in [_set_db_data](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/django/__init__.py#L693)

### Actual Result

The actual result is that the call to get_parameters() results in a psycopg.OperationalError:
```
Traceback (most recent call last):
  File "/Users/austin/workplace/sentry-psycopg-bug/spbug/tests.py", line 11, in test_bug
    connection.connect()
  File "/Users/austin/workplace/sentry-psycopg-bug/venv_3_10/lib/python3.10/site-packages/sentry_sdk/utils.py", line 1711, in runner
    return sentry_patched_function(*args, **kwargs)
  File "/Users/austin/workplace/sentry-psycopg-bug/venv_3_10/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 658, in connect
    _set_db_data(span, self)
  File "/Users/austin/workplace/sentry-psycopg-bug/venv_3_10/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 693, in _set_db_data
    connection_params = cursor_or_db.connection.info.get_parameters()
  File "/Users/austin/workplace/sentry-psycopg-bug/venv_3_10/lib/python3.10/site-packages/psycopg/_connection_info.py", line 91, in get_parameters
    for i in self.pgconn.info
  File "psycopg_binary/pq/pgconn.pyx", line 90, in psycopg_binary.pq.PGconn.info.__get__
  File "psycopg_binary/pq/pgconn.pyx", line 635, in psycopg_binary.pq._ensure_pgconn
psycopg.OperationalError: the connection is closed
```

**Comment by szokeasaurusrex** [comment]
@austin-wentz Thank you for reporting this problem, and thanks for the detailed reproduction! I can confirm that I have also observed the same error, so we will try to get a fix ready soon.

Has what you are trying to do ever worked in a previous SDK version, and if so, which version? Also, have you been able to work around the issue?

**Comment by austin-wentz** [comment]
> @austin-wentz Thank you for reporting this problem, and thanks for the detailed reproduction! I can confirm that I have also observed the same error, so we will try to get a fix ready soon.
> 
> Has what you are trying to do ever worked in a previous SDK version, and if so, which version? Also, have you been able to work around the issue?

Sorry for the delay in response. We tried previous SDK versions, but the issue was still present. Yes, we were able to work around the issue by creating a new connection rather than trying to [re]connect the existing connection object.

**Comment by antonpirker** [comment]
Thanks for the additional information. We will have a fix soon.

**Comment by szokeasaurusrex** [comment]
After further investigation, I determined the exception is actually raised on [this line](https://github.com/getsentry/sentry-python/blob/b496a7131d64f61f3473e9e1a9807760bec217c1/sentry_sdk/integrations/django/__init__.py#L707). `is_psycopg3` evaluates to `False` because `cursor_or_db.connection` is `None`.

So, we likely need to check whether `cursor_or_db.connection` is `None` before checking anything else, and set `connection_params` to `{}` in that case. For good measure, we can put the whole thing in a `with capture_internal_exceptions` block

**Comment by szokeasaurusrex** [comment]
Related to #2427
