### ISSUE TITLE
Django environment classification defaulting to `dev`

### ISSUE THREAD

**Issue by mitchdawson1982** [getsentry/sentry-python#3069]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

^2.0.1

### Steps to Reproduce

We have a Django application running across three environments (test, dev and preprod), each environment has an `ENV` variable configured with the respective value. This variable is used as the environment argument in the sdk init.

We noticed that events were being received in Sentry with an environment of `dev` only, i.e. `test` or `preprod` were never used despite being configured correctly. When validating this behaviour locally I have also found that periodically alerts will come in with the environment as `dev` despite an entirely different value being provided. I have further noticed that when this occurs, the release value is also different from a working example.

```
# Sentry Configuration
sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN"),
    enable_tracing=True,
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    traces_sample_rate=1.0,
    # Set profiles_sample_rate to 1.0 to profile 100%
    # of sampled transactions.
    # We recommend adjusting this value in production.
    profiles_sample_rate=1.0,
    environment=ENV or "local",
)
```

![image](https://github.com/getsentry/sentry-python/assets/86007219/db3886e5-7be1-4779-b241-092bc00fc189)

### Expected Result

When `ENV=new-env1` received alerts should show the environment as `new-env1`

### Actual Result

When `ENV=new-env1` received alerts periodically show the environment as `dev`

**Comment by szokeasaurusrex** [comment]
Hi @mitchdawson1982, thank you for reporting this problem. Could you provide us a link to one of the error events where the environment was set to `dev`, even though the event originated from a non-`dev` environment to help us investigate?

**Comment by Angelodaniel** [comment]
Hey @szokeasaurusrex -> Shared the link directly with you

**Comment by mitchdawson1982** [comment]
Sure here one of the [links](https://ministryofjustice.sentry.io/issues/5325577902/events/244d825b238a4cebbd95d08cb4ce29bc/)

**Comment by sentrivana** [comment]
@mitchdawson1982 Could you try using the `SENTRY_ENVIRONMENT` env var instead? If you set `SENTRY_ENVIRONMENT`, it'll be used automatically, so you could remove it from the `init`. See also [here](https://docs.sentry.io/platforms/python/configuration/environments/).

As far as I can the SDK will never set the environment to `dev` by itself. [This](https://github.com/getsentry/sentry-python/blob/40746ef9dad676c8cc704a1fb955b93047c06b93/sentry_sdk/client.py#L98-L99) is the only place I found where we set it to something (if it's not there), and we default to `production`. So my hunch is this might be originating somewhere else. Maybe something external, like a tool, is setting the `ENV` var, which is why I'm wondering if the issue goes away after switching to something more unique like `SENTRY_ENVIRONMENT`.

Since the faulty events also have a different release though, is it at all possible the `dev` events you're seeing are coming from a different place entirely? (Automated tests, etc.) Is the non-hash release something that you'd expect seeing in your local environment?

**Comment by mitchdawson1982** [comment]
> @mitchdawson1982 Could you try using the `SENTRY_ENVIRONMENT` env var instead? If you set `SENTRY_ENVIRONMENT`, it'll be used automatically, so you could remove it from the `init`. See also [here](https://docs.sentry.io/platforms/python/configuration/environments/).
> 
> As far as I can tell the SDK will never set the environment to `dev` by itself. [This](https://github.com/getsentry/sentry-python/blob/40746ef9dad676c8cc704a1fb955b93047c06b93/sentry_sdk/client.py#L98-L99) is the only place I found where we set it to something (if it's not there), and we default to `production`. So my hunch is this might be originating somewhere else. Maybe something external, like a tool, is setting the `ENV` var, which is why I'm wondering if the issue goes away after switching to something more unique like `SENTRY_ENVIRONMENT`.
> 
> Since the faulty events also have a different release though, is it at all possible the `dev` events you're seeing are coming from a different place entirely? (Automated tests, etc.) Is the non-hash release something that you'd expect seeing in your local environment?

Thanks for the suggestion I will try this out when I get time. In terms of where the events are originating from, I cant envisage them coming from anywhere else. We have tests but these are manually invoked, the scenario I have described is where the app is being run normally.

**Comment by mitchdawson1982** [comment]
Hi @sentrivana I have performed further testing this morning with and without the `SENTRY_ENVIRONMENT` variable. To clarify I am running this application utilising the current main branch on my local Macbook.  

I have been thinking about the rationale provided for this behaviour and would like to clarify some of the points. 
On the tests where we have populated the `ENV`variable and `sentry_sdk.init(environment=ENV or "local"), I have in nearly all cases printed out the value of `ENV` to the terminal _after_ `sentry_sdk.init(environment=ENV or "local")` in `settings.py` to validate the correct value is passed as expected. Where I have done so this has always been consistent for both correct and incorrect alerts and therefore gives me a high level of confidence that the right value has always been passed to the sdk environment argument. I don't see any likelihood of our code being able to manipulate the environment argument within sentry after the sdk init has been called.

Where correct alerts are seen in datahub the release hash matches the correct commit hash i.e. this [alert](https://ministryofjustice.sentry.io/issues/5325577902/events/89f8f9bc12f94311bb6faf02a9456cd5/) has the latest commit [hash](https://github.com/ministryofjustice/find-moj-data/commit/c1ce8876cbbff657c894b1ac521a8e0ba436d934) in main. However for incorrect [alerts](https://ministryofjustice.sentry.io/issues/5325577902/events/2d9b9f0dffe0455d896d7f2eb1a109eb/) we see `0.12.1.5`. We don't recognise this value and given that the code is static on my machine I can't see how our code could influence how this value is obtained within the sentry sdk.

TBC

**Comment by antonpirker** [comment]
In summary, when the wrong `environment` is set also the `release` is wrong. My hunch is that someone else is running the project that has set `ENV` to the wrong value. 

And this other one that runs the project does not run it from a Git repository. How the Sentry Python SDK sets the `release`, if there is none specified in `sentry_sdk.init()`, isdescribed here (below the code snippet): https://docs.sentry.io/platforms/python/configuration/releases/#setting-a-release

Do you have the project running in Google App Engine, Azure, AWS, Heroku, Codebuild, Circle CI, GitLab CI/CD, or Travis CI?

**Comment by mitchdawson1982** [comment]
> In summary, when the wrong `environment` is set also the `release` is wrong. My hunch is that someone else is running the project that has set `ENV` to the wrong value.
> 
> And this other one that runs the project does not run it from a Git repository. How the Sentry Python SDK sets the `release`, if there is none specified in `sentry_sdk.init()`, isdescribed here (below the code snippet): https://docs.sentry.io/platforms/python/configuration/releases/#setting-a-release
> 
> Do you have the project running in Google App Engine, Azure, AWS, Heroku, Codebuild, Circle CI, GitLab CI/CD, or Travis CI?

I'm not as yet convinced that the environment is being set wrong. On the tests where we have populated the ENV variable and sentry_sdk.init(environment=ENV or "local"), I have in nearly all cases printed out the value of ENV to the terminal **after** sentry_sdk.init(environment=ENV or "local") in settings.py to validate the correct value is passed as expected. Where I have done so this has **always** been consistent for both **correct** and **incorrect** alerts and therefore gives me a high level of confidence that the right value has always been passed to the sdk environment argument. Once this value has been passed to the sdk init, how could our code manipulate this value? I am seeing this behaviour on local developement laptop and on three separate k8's pods.

**Comment by mitchdawson1982** [comment]
Thanks, I am currently investigating this.

**Comment by sentrivana** [comment]
@mitchdawson1982 I see the linked MoJ issue is closed -- have you been able to resolve this or do you need any additional support from our end?

**Comment by sentrivana** [comment]
Closing. Please reopen if not solved.
