### ISSUE TITLE
Clarify proxy fallback behavior

### ISSUE THREAD

**Issue by crepererum** [getsentry/sentry-python#308]
I am currently working on #178 and extended the tests for the proxy selection mechanism, especially when the env variables like `HTTP_PROXY` and `HTTPS_PROXY` are present. One thing that I've observed is the fallback behavior:

- no ENV vars: HTTPS DSNs can fallback to HTTP proxies (see [test](https://github.com/getsentry/sentry-python/blob/master/tests/test_client.py#L47-L48))
- only `HTTP_PROXY` env var: no fallback for HTTPS DSNs, i.e. no proxy is auto-selected

Is that behavior intended or a bug? In either case, my PR for #178 will also include tests (and potential fixes) for that.

**Comment by untitaker** [comment]
The `http_proxy` envvar is supposed to be used for HTTPS DSNs (i.e. exact same behavior as with client options in code), so this is a bug.

I'm very grateful that you're working on this! It's been a pain point for many people but it's unclear how to fix it without writing a lot of custom code.
