### ISSUE TITLE
Add entry point for opentelemetry propagator

### ISSUE THREAD

**Issue by mender** [getsentry/sentry-python#3085]
### Problem Statement

According to the [documentation](https://docs.sentry.io/platforms/python/performance/instrumentation/opentelemetry/#usage), the recommended way to integrate with OpenTelemetry is to completely replace existing propagators using
```python
set_global_textmap(SentryPropagator())
```
In case of distributed tracing it is not correct behaviour. We have to add the `SentryPropagator` to the existing ones instead. Opentelemetry provides [environment variables](https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_propagators) as a most common way to configure it. However, propagators added via environment variables must be declared in entry points ([ref](https://github.com/open-telemetry/opentelemetry-python/blob/a156bf161d4de96766cac09a5ef4fcddbf367604/opentelemetry-api/src/opentelemetry/propagate/__init__.py#L138-L147)). And [here](https://github.com/open-telemetry/opentelemetry-python/blob/a156bf161d4de96766cac09a5ef4fcddbf367604/opentelemetry-api/pyproject.toml#L45-L47) is an example of how entry points are declared in OpenTelemetry.

### Solution Brainstorm

I propose adding entry point for `SentryPropagator` in setup.py.

**Comment by sentrivana** [comment]
Thank you for the issue and the PR @mender, we will take a look.
