### ISSUE TITLE
Temporarily disable without re-initializing the client?

### ISSUE THREAD

**Issue by fiendish** [getsentry/sentry-python#3112]
### Problem Statement

It would be nice to have a documented simple mechanism other than reinitializing the client for disabling its transmissions. 

The scenario is that I need to disable it only briefly and then reenable it again right after, but I don't have access to all of the original values that were given as part of the initial client configuration.

### Solution Brainstorm

Peeking inside at the current client's contained options seems...wrong? Though if you tell me that it's fine to do so then I'll be ok with that answer too.

**Comment by szokeasaurusrex** [comment]
@fiendish Here's an idea for you: you can replace the client's transport, which is responsible for sending events to Sentry, with a no-op transport while you wish for sending to be disabled, then replace the transport with the original value afterwards. Perhaps, something like the following would work for you:

```python
import contextlib, sentry_sdk
from sentry_sdk.transport import Transport


class NoOpTransport(Transport):
    def capture_envelope(
        self, _  # type: Envelope
    ):
        # type: (...) -> None
        pass


@contextlib.contextmanager
def sentry_sending_disabled():
    client = sentry_sdk.get_client()
    old_transport = client.transport
    client.transport = NoOpTransport()

    try:
        yield
    finally:
        client.transport = old_transport


# Code block where you wish to disable Sentry sending:
with sentry_sending_disabled():
    ... # nothing that happens here will get sent to Sentry
```

Please note, I have not tested this snippet yet, so please make sure to test it before you use it 🙂 

Let me know whether this works for you!

**Comment by fiendish** [comment]
Thank you @szokeasaurusrex!

I'm now using a variant of your suggestion (`capture_event` too for old-sentry-version compat)
```
class NoOpTransport(sentry_sdk.transport.Transport):
    capture_envelope = capture_event = lambda self, _: None  # type: ignore
 
with patch.object(sentry_sdk.Hub.current.client, "transport", NoOpTransport()):
    ...
```
and it appears to be working.

**Comment by fiendish** [comment]
> Just one clarification: what Sentry SDK version are you running? 1.x 

1.x still for now.
