### ISSUE TITLE
Fix Migration Guide regarding removal of last_event_id()

### ISSUE THREAD

**Issue by lovetox** [getsentry/sentry-python#3118]
### How do you use Sentry?

Self-hosted/on-premise

### Version

2.2.0

### Steps to Reproduce

Migration Guide says, method last_event_id() was removed, but it was reintroduced in 2.2.0

### Expected Result

Correct Migration Guide

### Actual Result

> The API function last_event_id() was removed

**Comment by szokeasaurusrex** [comment]
Good catch, @lovetox – I already opened a PR to fix the migration guide as you have suggested
