### ISSUE TITLE
Incorrect signature for capture_exception

### ISSUE THREAD

**Issue by akx** [getsentry/sentry-python#313]
The type hint for `capture_exception()` implies only `ValueError`s can be passed in, which causes a type check warning in IDEs such as PyCharm when you pass in a non-ValueError exception.

https://github.com/getsentry/sentry-python/blob/62e3a647e5787957dcabc889bce5d53538dc423e/sentry_sdk/api.py#L53-L54

I suppose the hint should be more like

```python
# type: (BaseException) -> Optional[str] 
```

**Comment by untitaker** [comment]
You're completely right. The type hints were partially generated using [pyannotate](https://github.com/dropbox/pyannotate) and are therefore still quite a bit too restrictive. Do you want to make a PR? Otherwise I will fix it soon (tm).
