### ISSUE TITLE
Test Celery Beat regression (2.4.0 through 2.5.0 inclusive)

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry-python#3145]
We had a regression in our Celery Beat integration that prevented Cron checkins from being sent at the end of the cron job from version 2.4.0 through (including) 2.5.0.

We isolated the cause to c80cad1e6e17790f02b29115013014d3b4bebd3c, which we reverted in #3144. We released the fix in 2.5.1.

We should investigate the exact cause of this regression and add tests to ensure we cannot introduce a similar regression again.

**Comment by antonpirker** [comment]
The tests in the linked PR have been merged. This is done!
