### ISSUE TITLE
Statically initialized StrawberryIntegration leads to runtime exception: There is no current event loop in thread

### ISSUE THREAD

**Issue by Speedy1991** [getsentry/sentry-python#3153]
### How do you use Sentry?

Self-hosted/on-premise

### Version

2.5.1

### Steps to Reproduce

I use a mixed app with starlette and django where the starlette router resolves the route into a starlette websocket (async) or a django app (sync). The problem is, that the strawberry extensions guess the async scope [here](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/strawberry.py#L397). So I get an async middleware in my sync stack if a query is executed. As far I can see from the codebase I can't opt out this behaviour, because it is added via the default integrations [here](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/__init__.py#L103).

I guess there is a general design problem with the strawberry integration. E.g. the DjangoIntegration does not require to specify the `async_execution` like the StrawberryIntegration does [here](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/strawberry.py#L55C24-L55C39).  The DjangoIntegration request is evaluated while runtime.

FYI & Ping @patrick91

### Expected Result

depending on the request the sync or async resolver is called. Currently, this is statically injected on integration creation (or default integration injection)

### Actual Result

An async middleware is added to a wsgi request

![image](https://github.com/getsentry/sentry-python/assets/15920408/0f075dfd-a772-437f-aa11-2d9bacb82cba)
![image](https://github.com/getsentry/sentry-python/assets/15920408/fbf01446-809b-4d4d-b6d9-f71e9c80402a)

**Comment by sentrivana** [comment]
Hey @Speedy1991, you can override the behavior by adding the integration explicitly to your `sentry_sdk.init` with `async_execution=False`, see here: https://docs.sentry.io/platforms/python/integrations/strawberry/#synchronous-vs-asynchronous-execution Does that solve the issue for you?

**Comment by sentrivana** [comment]
Thanks for the follow up. Do I understand correctly that you want to use the `StrawberryIntegration` both in the Django app (sync) and in the Starlette app (async)? That is not possible with the current setup without initializing Sentry in both apps. You could either force the use of the sync extension everywhere, or disable the `StrawberryIntegration` altogether (via `auto_enabling_integrations=False`, see [docs](https://docs.sentry.io/platforms/python/configuration/options/#auto-enabling-integrations)) and use the extension directly.

IIRC the reason why the integration needs to know if you want the sync or async version at startup is that it works via injecting an extension which is done at schema creation. So this would need a bigger revamp to support guessing the context during runtime.
