### ISSUE TITLE
get locals on all stack frames

### ISSUE THREAD

**Issue by wiltzius** [getsentry/sentry-python#316]
I find the with_locals feature really useful. It helps give the data context needed to spot issues quickly in many cases.

Unfortunately, we only seem to get locals for the first ~12 and last ~12 stack frames in our Python project. Because almost all of that is framework code in both cases (request handling up top, error handling at the bottom), we rarely get the locals relevant to our business logic.

Is there some way to get stack locals for all (or at least most) frames? I understand this might be arbitrarily expensive, but just having a way to increase the limit would be helpful

**Comment by untitaker** [comment]
@wiltzius you can set `in_app_include` and `in_app_exclude` to mark specific frames as part of your application vs not being part: https://docs.sentry.io/error-reporting/configuration/?platform=python#in-app-include

E.g. if your app is in a python module `foobar`, set `init(in_app_include=["foobar"])`.

The server should then start trimming framework frames first.

Which framework are you using?

**Comment by wiltzius** [comment]
Cool, thank you. in_app_include is just what we need.

The framework in question sorta depends on the bug. We use Pyramid as a web framework and Celery as the task runner, so those are at the top of the stack, but at the bottom sometimes its a deep SqlAlchemy stack trace or Python logging framework.

We aren't on the latest version so I'll update it when I modify in_app_include and see if the auto-detect works better.

**Comment by untitaker** [comment]
Sorry for the confusion: The latest version doesn't do it any better. I only created a follow-up ticket to do this at some point.

**Comment by wiltzius** [comment]
I'm still having trouble with this. I upgraded to the unified client, 
 but in_app_excludes doesn't seem to work unless you also set in_app_includes. I eventually tracked it down to here:

https://github.com/getsentry/sentry-python/blob/3735cb5fb155c24dadacd53bf0e7ce8b1a3cd34f/sentry_sdk/utils.py#L610

the fallback for any_in_app over-triggers if you don't have in_app_includes set to anything (since nothing is explicitly marked in). I'd expect anything that isn't excluded would be included, but not so.

Docs don't mention this behavior, is it intended? It's unfortunately an annoyance for us, since we've got a large number of packages that are "ours" and we would want to include, and nobody's going to remember to update this list when they add a new one.

**Comment by untitaker** [comment]
The fact that `init(in_app_exclude=[...])` doesn't work is definetly a bug. I will make a note in #320, thanks for reporting. I will prioritize fixing this in the next week because I can't think of a workaround you could use right now.

I would set `in_app_include` regardless. I wonder if you could hack something together where you discover installed packages at runtime and filter them by author information (assuming all those packages of yours do have the same author set). Presumably `pkg_resources` has metadata about this.

**Comment by wiltzius** [comment]
Thanks for filing the bug.

It's actually even a little bit more confusing, I think. You need to set both the `in_app_exclude` _and_ the `in_app_include` for it to have any effect. If you set only one, the rest default to the same value (it seems).

I was able to use `setuptools.find_packages` to get a list of the packages we care about, so that handles the include issue I mentioned above.

**Comment by wiltzius** [comment]
I think fixing this is as simple as adding a tiny bit of logic in the line I mentioned above to default stack frames to the "other" value if only one of in_app_exclude or in_app_include is set.

**Comment by untitaker** [comment]
Yeah, I have a PR open and hope to make a release soon. Thanks for taking
the time to investigate this yourself.

**Comment by untitaker** [comment]
@wiltzius 0.7.10 should allow you to use `in_app_exclude` properly. #320 is still open for doing this for most frameworks automatically.
