### ISSUE TITLE
Make disabling individual integrations easier

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#3166]
### Problem Statement

With the release of 2.0, [most of our integrations are now auto enabling](https://docs.sentry.io/platforms/python/integrations/). Conversely, turning a specific integration off is now much more tedious (have to set `auto_enabling_integrations=True` and enumerate all integrations that you want to keep).

### Solution Brainstorm

There should be an easier way to turn off an extension without having to then turn all other integrations on manually.

We should add an optional config param that is essentially an ignore list of integrations to explicitly exclude. (See if any other SDKs have this for naming the option.)

**Comment by rusmux** [comment]
This would be very helpful
