### ISSUE TITLE
Missing git tag (and sdist) for 2.6.0

### ISSUE THREAD

**Issue by mgorny** [getsentry/sentry-python#3187]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

2.6.0

### Steps to Reproduce

Open https://github.com/getsentry/sentry-python/tags and https://pypi.org/project/sentry-sdk/2.6.0/#files respectively.

### Expected Result

Tag and sdist for 2.6.0.

### Actual Result

Last tag is 2.5.1. PyPI has only a wheel but no sdist.

**Comment by antonpirker** [comment]
Thanks for reporting this @mgorny 
Yes, there was a hickup with PyPI yesterday, we will try to fix this. Worst case would be we need to yank 2.6.0 and release 2.6.1

**Comment by antonpirker** [comment]
Redeployed and this worked. Files and tags are there now.

**Comment by mgorny** [comment]
Thanks!
