### ISSUE TITLE
Set in_app in integrations

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#320]
In many integrations we currently don't set in_app, but we should because it affects trimming. See #316

**Comment by untitaker** [comment]
It would probably make sense to think of new heuristics to discover packages of "the current app" in this context. For example based on whether the module's fs path is within current working directory.

**Comment by antonpirker** [comment]
This looks like a nice enhancements, so I will put it into the internal backlog (at low priority)

**Comment by mecampbellsoup** [comment]
This would be super nice to have!
