### ISSUE TITLE
How to get "extra" information from exceptions into events

### ISSUE THREAD

**Issue by wiltzius** [getsentry/sentry-python#324]
I'm trying to replicate the setup we had with the old Raven client and I'm running into a few conflicting issues.

Previously, we were relying on a subclass of the `SentryHandler` and adding that to our logging config. We'd then simply `logging.error` exceptions from our web app, and inside the handler we'd use [http_context](https://raven.readthedocs.io/en/stable/api.html#raven.Client.http_context) to populate request information.

Now there isn't an equivalent of `http_context`, as far as I can tell. Fortunately, there _is_ a Pyramid integration (and WSGI integration). Great, we'll just use that instead of a custom `SentryHandler` subclass.

Unfortunately this also is missing some data we used to collection, because in the `logging.error` call we'd pass along `extra={...}` where we pull some application-specific information out of our exception classes to populate the extra field. There's no equivalent in the Pyramid integration, and there aren't any hooks in the integration to add more context to the scope.

The closest thing I can find is the `before_send` filter, but by the time that runs we've lost the exception and only have the `event` passed to the function. In general this before_send function seems like its designed to remove data from the event, not add it.

Is there a way to replicate our old behavior? I'm happy to either write a handler subclass or even subclass the WSGI integration.

As a total aside / unsolicited comment: In general the design of all the integrations seems to be that they take an exception or log record and then emit an event, but with no hooks to modify behavior along the way. In particular, even if I sub-classes the WSGI integration or the Pyramid integration most of the functionality is in module-level functions, not the class itself. That means there's no way to override the module function behavior. OTOH, the integration classes themselves usually bundle a fair amount of behavior into their methods. This is subclass-able, but I don't want to change what's in there I want to basically add another processing function to go from log record/exception -> event info (i.e. modify a module-level utility function or add another one). This design doesn't seem very extensible? I realize that's probably not a design goal, but just food for though.

**Comment by untitaker** [comment]
If you want to run special logic, the original exception is still available in `before_send` as `hint['exc_info']`. Otherwise I would recommend calling `scope.set_extra` in your request handler/view: https://docs.sentry.io/enriching-error-data/context/?platform=python#extra-context

**Comment by untitaker** [comment]
>but with no hooks to modify behavior along the way.

The intent was mostly to minimize API surface, not to prevent extensibility just for the sake of it. I'm not entirely sure what you're trying to achieve but I believe `before_send` should make it possible in principle (although probably not very ergonomically, so there's room for improvement there).

**Comment by wiltzius** [comment]
Yeah, I toyed around with the extra context thing. I eventually realized that to handle logging and exceptions in a bunch of different contexts it would be much easier to just consolidate everything to minimize code impact, but maximize use of the Sentry utilities. I ended up writing this `before_send` function to pull info from the integration code without using the integrations themselves:

```python
from sentry_sdk.integrations.pyramid import PyramidRequestExtractor
from sentry_sdk.integrations.wsgi import _make_wsgi_event_processor

def before_send(event, hint):
  try:
    event['user'] = attempt_get_user_info()
    event['tags'] = {
      'server_color': Config().server_color(),
      'app_name': Config().app_name_best_effort()
    }

    req = request_context.instance().get()

    if req:
      event = _make_wsgi_event_processor(req.environ)(event, hint)
      PyramidRequestExtractor(req).extract_into_event(event)
      # filter out some sensitive headers
      try:
        event['request']['headers'] = {k: v for k, v in event['request']['headers'].items()
                                       if k not in HEADER_BLACKLIST}
      except KeyError:
        pass
  except Exception as e:
    # never fail here because its better to skip info than to crash (harder)
	pass

  return event
```


Anyway, closing this issue, but I still think it would be helpful to have some hooks to:

a) set the request context through scope, as the raven client let you previously, and
b) somehow hook or extend the default LoggingIntegration code to use its logic but add some exception/log record processing (like attaching request info) along the way.

**Comment by untitaker** [comment]
Glad you figured it out.

>a) set the request context through scope, as the raven client let you previously, and

This is not yet documented (we should do that), but the method `scope.add_event_processor` takes a callback with the same signature and semantics as `before_send` and attaches it to the current scope. Since you are within a new scope for each request, you could define and attach the callback within the request handler:

```python
def my_pyramid_view(request):
    with configure_scope() as scope:
        @scope.add_event_processor
        def _(event, hint):
            event['request'] = derive_request_context(request)
            return event


However, what you're doing with the `RequestExtractor` should not be necessary at all, as the headers should already have been written into the event at the point `before_send` is called. To be clear, I would expect that the lines that call `_make_wsgi_event_processor` and `PyramidRequestExtractor` can be deleted and your code would still work. If it doesn't, it's a bug.

Also note that you can call `configure_scope()` at import time because there is a global scope. So at least some attributes could be set more eagerly, unless there is another reason `Config()` can't run at import time:

```python
with configure_scope() as scope:
    scope.set_tag('server_color', Config().server_color())
    scope.set_tag('app_name', Config().app_name_best_effort())
```

>b) somehow hook or extend the default LoggingIntegration code to use its logic but add some exception/log record processing (like attaching request info) along the way.

We really want to avoid having an API for this per integration, but maybe I am misunderstanding you here. To me it sounds like your feature requests (a) and (b) serve the same exact usecase.
