### ISSUE TITLE
UI Indication when data has been truncated > 10 limit

### ISSUE THREAD

**Issue by pg1671** [getsentry/sentry-python#3262]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

latest

### Steps to Reproduce

in django create a log entry with extra data containing a list with 20 entriies.

### Expected Result

I know there is a 10 entry limit.

When I view the UI for the issue and go to extra data I should see the list with 10 entries (due to the limit).

But there should be an indication that this data was truncated. Even better to indicate how much data was truncated. Eg. 50 entries for a list or dict.

### Actual Result

Sentry just shows a list with 10 entries. The list looks complete. This is very confusing to the debugger as there is no indication that list entries were truncated.

**Comment by sl0thentr0py** [comment]
thanks @pg1671 we already have several issues on the product side tracking this problem, so I will add a link to this there and close this one.
https://github.com/getsentry/sentry/issues/68426
