### ISSUE TITLE
Cannot be run wtih -OO flag

### ISSUE THREAD

**Issue by cramosc** [getsentry/sentry-python#327]
After installing the version 0.7.9. I cannot run sentry with the python flag -OO (discard docstrings). This is because in `sentry_sdk/integrations/__init__.py` the following was addded:
`iter_default_integrations.__doc__ += "\n- `{}`".format(import_string)`
which in case of running with -OO `__doc__` is `None` and you get the exception:
`TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'`

**Comment by untitaker** [comment]
Yeah, this code has been around for a while. I would accept a patch but we don't support `-O` on Python.

**Comment by medns** [comment]
I have the same issue

**Comment by untitaker** [comment]
Thanks for the PR @medns. Out of curiosity: Why do you use that flag?

**Comment by allanlei** [comment]
We migrated from https://github.com/getsentry/raven-python, which works with `-O` and `-OO`, and encountered this problem.  The [migration guide](https://forum.sentry.io/t/switching-to-sentry-python/4733) also does not mention this.

The PR https://github.com/getsentry/sentry-python/pull/341 works with `-O`, but the error still happens with `-OO`.

**Comment by untitaker** [comment]
@allanlei Since you edited your comment, do you encounter any issues with this SDK right now?

**Comment by allanlei** [comment]
No problems with 0.7.12

**Comment by untitaker** [comment]
Cool. I'll close this issue then.
