### ISSUE TITLE
Exception extra data

### ISSUE THREAD

**Issue by decaz** [getsentry/sentry-python#329]
I use SDK with default integrations (and some additional also) and I have exception class like the following:
```python
class MyError(Exception):
    def __init__(self, message=None, **extra):
        super().__init__(message)
        self.extra = extra

raise MyError('User not found', user_id=7)
```
How can I propagate extra data of raised `MyError` exception to the SDK's scope extra data? I guess it'll be a lot of work to rework all integrations, - maybe it worth to include within `utils.event_from_exception` or `utils.event_hint_with_exc_info` some handling like this:
```python
try:
    exc_extra_data = exc_info.get_sentry_data()
except AttributeError:
    exc_extra_data = {}
```

**Comment by untitaker** [comment]
You can write a `before_send` function that accesses the data: https://docs.sentry.io/learn/filtering/?platform=python#before-send

```python
def before_send(event, hint):
    try:
        if 'exc_info' in hint:
            event.setdefault('extra', {}).update(hint['exc_info'][1].get_sentry_data())
    except AttributeError:
        pass
    return event
```

**Comment by decaz** [comment]
@untitaker cool, thanks!
