### ISSUE TITLE
Don't capture entire environ in wsgi event processor

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#33]
@mitsuhiko could you look over https://github.com/getsentry/sentry-python/blob/98399ca5f03f2ac69ae98308cc4fd6dfb76ad457/sentry_sdk/integrations/_wsgi.py#L205? I wonder if it would make sense to just write to the scope eagerly instead. Weakref on the environ dict is kind of shitty: Any middleware or web framework could do `dict(environ)` and the weakref is broken

**Comment by untitaker** [comment]
@mitsuhiko needed + worth it or not, what do you think?

**Comment by mitsuhiko** [comment]
It’s okay postponing then.
