### ISSUE TITLE
Running on App Engine is causing 500 responses

### ISSUE THREAD

**Issue by mwillmott** [getsentry/sentry-python#330]
I've implemented the Sentry client on a Django application that i'm running on Google App Engine. When it catches an exception it causes the request to hang until, i'm assuming Google, kill it and i receive a generic `500` response with the following appearing in the logs `Thread running after request`.

I've seen various posts relating to the old Raven client about using a separate transport client when running on App Engine due to the single thread. I can't see anything at all about the current Sentry SDK. Looking at this repo it seems like it is set to us `HttpTransport` by default anyway, which is what people recommend using on App Engine.

Any thoughts? It works fine when not using Sentry (the error is thrown and my response fails straight away rather than hanging).

**Comment by untitaker** [comment]
Hi, the `HttpTransport` in this SDK is equivalent to `ThreadedHttpTransport` in the Raven SDK. We currently don't support environments without threads at all.

**Comment by mwillmott** [comment]
Ah right, thanks for the help @untitaker
