### ISSUE TITLE
Not able to see sentry traces(transaction + spans) in sentry

### ISSUE THREAD

**Issue by rajjay1996** [getsentry/sentry-python#3301]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.16.0

### Steps to Reproduce

I am trying to see the distributed tracing using sentry version 1.16.0 and django version 1.7.7. Let me explain in details.
1.) I have frontend application and backend application plus database call in microservice. 
2.) I am using django framework version 1.7.7 for each microservice and I am using python version 3.8.0.
3.) I have multiple hop from one microservice to another microservice and in between there might be database call. I want to see complete traces with above version only for now.

Steps I am doing to initiate the sentry.
1.) I am doing sentry initialization using below code

from __future__ import absolute_import, unicode_literals
import sentry_sdk 
from django.apps import AppConfig
from django.conf import settings

class SentryConfig(AppConfig):
    print('Enter into Sentry Config')
    name = 'sentrylogger'
    verbose_name = "Sentry Error integration"

    def ready(self):
        if hasattr(settings, 'SENTRY_DSN'):
            sentry_sdk.init(
                dsn=settings.SENTRY_DSN,
                debug=False,
                attach_stacktrace=True,
                enable_tracing=True,
                auto_enabling_integrations=True,
                send_default_pii=True,
            )
Now each microservice has it own DSN value because each microservice has it's own project. Now I want a single trace id where I can see multiple transactions or spans in it.

I am facing issue is that I am not able to see any http call that inlclude (client + server)  and also database query call. I am not sure because I am using old version of djanjo and sentry version that's why I am not able to see and if yes then how I can achieve it in old djanjo and sentry?
      

### Expected Result

I want to see complete trace call that include http call, database call, with span details.

### Actual Result

when I use enable_tracing=True with django version 1.7.7 and sentry 1.16.0 I am not able to see transaction. I have to manually write my own custom transaction on every method, but I want to be centralized so every microservice don't have to write their own transaction calls.

**Comment by antonpirker** [comment]
Hey @rajjay1996 , 
thanks for writing in. 

Your setup looks ok. Just to get it right:
You have for example service1, service2 and service3. All have the same Django and Sentry versions and every service has a different DSN (which is totally fine).
If I make a request to service1, it will request service2 that calls service3. And all/some of the services do database queries (using the Django ORM I suppose?).


### Questions:
1. What library are you using for making the outgoing HTTP requests?
2. What version of self-hosted Sentry are you using?
3. Can you upgrade Sentry SDK to the newest version? (if you do not do any custom instrumentation using `hub` it should just work without changing your code) and check again?
4. Are you seeing any Transactions for your services or nothing at all?
5. Are you seeing errors for your services?

### Things you can check:

- Set `debug=True` and check the console output has log messages that are like: `[Tracing] Adding `{key}` header {value} to outgoing request to {url}.`
- Check the HTTP request in the service that does the outgoing request, and the service that receives the request if it contains the `sentry-trace` and `baggage` HTTP headers. (Those are the header that are used for trace propagation)

**Comment by rajjay1996** [comment]
Hi @antonpirker , thanks for the update. Please find my anwsers for below questions.

Questions:
What library are you using for making the outgoing HTTP requests?
Ans: I am using django version 1.7.7
What version of self-hosted Sentry are you using?
Ans: I am using sentry version 1.16.0
Can you upgrade Sentry SDK to the newest version? (if you do not do any custom instrumentation using hub it should just work without changing your code) and check again?
Ans: I can't upgrade the sentry version to latest because I am using older django verion 1.7.7, urllib3 version, etc. 
Are you seeing any Transactions for your services or nothing at all?
Ans: I am seeing traces for a function when I manually start transaction using sentry_sdk.startTransaction(op='', name='') at method level.
Are you seeing errors for your services?
Ans: Yes I am able to see errors for a service. errors are good but I am not able to see the complete traces.

Follow up questions.
1.) if I am using django version 1.7.7 with python version 3.8 and sentry-sdk version=1.16.0, do you think django version cause the sentry tracing to get full traces?
2.) In python if I want tracing logic to be centarlized, means not every function has to manually start transaction, how I can achieve it?

Thanks,
Jay

**Comment by szokeasaurusrex** [comment]
Hi @rajjay1996, thanks for your response! Some of your answers are a bit unclear, so I would appreciate if you could clarify the following:

> What library are you using for making the outgoing HTTP requests?
> Ans: I am using django version 1.7.7

Could you please tell us what library you are using to make _outgoing_ HTTP requests? Your original issue already stated that you use Django 1.7.7 as your server framework to handle _incoming_ requests, but we would like to know what library you use to make _outgoing_ requests to your other micro-services?


> What version of self-hosted Sentry are you using?
> Ans: I am using sentry version 1.16.0

1.16.0 is the version of the SDK. We already knew that you were using this version from your original issue description. What version of the [Sentry self-hosted server](https://github.com/getsentry/self-hosted) are you using?

> Are you seeing any Transactions for your services or nothing at all?
> Ans: I am seeing traces for a function when I manually start transaction using sentry_sdk.startTransaction(op='', name='') at method level.

Thank you for clarifying that you only see traces when manually starting the transaction using `sentry_sdk.start_transaction`. To clarify, can you see the _transaction_ itself (regardless of whether you can see any spans below it in the trace) when you log into Sentry if you remove your manual `start_transaction` calls?


_________________

Regarding your follow up questions:

> 1.) if I am using django version 1.7.7 with python version 3.8 and sentry-sdk version=1.16.0, do you think django version cause the sentry tracing to get full traces?

I do not understand the question, could you please clarify? Are you asking whether Sentry is compatible with Django `1.77.7`?

> In python if I want tracing logic to be centarlized, means not every function has to manually start transaction, how I can achieve it?

We would expect tracing logic to work automatically, out of the box with Django as long as you set `enable_tracing=True` when initializing the SDK.


### Next step

I understand that you are not able to upgrade to the latest Sentry SDK version, but could you please try to see whether upgrading to version 1.45.0 fixes the problem? 1.45.0 is the latest 1.x version, and it is fully backwards-compatible with 1.16.0.
