### ISSUE TITLE
Make sentry-python emit data that does not need to be normalized by semaphore.

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#332]
We should try to emit data exactly as semaphore would normalize it (timestamps as floats etc). This will make it easier to enforce a stronger invariant in the testsuite, which would have caught a bug.

**Comment by untitaker** [comment]
Also add a `--store` flag to `semaphore process-event`.

**Comment by untitaker** [comment]
For context: https://github.com/getsentry/sentry-python/commit/2f5487235848e3bda9eae150facb0bb9e0c490a4

**Comment by antonpirker** [comment]
Moved this into the internal backlog at a low priority
