### ISSUE TITLE
Unified sentry-sdk integration does not have support to add stack trace in python logger using 'stack': True in extra dict.

### ISSUE THREAD

**Issue by gagan-chawla** [getsentry/sentry-python#336]
Migration from raven to unified sentry sdk, affected extended functionalities to python logging provided by raven. _extra_from_record - excludes keywords 'stack' and 'data'. Is there a known workaround?

**Comment by untitaker** [comment]
Set `exc_info=True`, it's used for both callstack and exception stack now.

**Comment by gagan-chawla** [comment]
About 'data' key in extra. It is also used for breadcrumbs, is that the reason we can't use it in python logging?

**Comment by untitaker** [comment]
Good point, this seems like a bug. Likely a copy paste error from raven.
Would certainly appreciate a PR!

**Comment by gagan-chawla** [comment]
Here https://github.com/getsentry/sentry-python/pull/337
