### ISSUE TITLE
Get rid of `sentry_sdk._types.TYPE_CHECKING`

### ISSUE THREAD

**Issue by sentrivana** [getsentry/sentry-python#3426]
We define our own `TYPE_CHECKING` constant here: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/_types.py This seems to be due to backwards compatibility with older Python versions.

The stdlib `typing` module added [`TYPE_CHECKING`](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING) in 3.5.2 (we support 3.6+), we can get rid of our alias and use `typing.TYPE_CHECKING` directly.

**Comment by szokeasaurusrex** [comment]
... and this does not need to be a breaking change because the `_types` module is private 🎉

**Comment by dev-satoshi** [comment]
Hi, I'd like to work on this issue!

**Comment by sentrivana** [comment]
Hey @dev-satoshi, go ahead, PRs are welcome 🚀
