### ISSUE TITLE
Does this client truncate long strings and lists?

### ISSUE THREAD

**Issue by Siecje** [getsentry/sentry-python#344]
In the raven config there was `'list_max_length'` and `'string_max_length'` but they don't exist for the new client.

I see there is this function for strings but I don't see one for lists.
https://github.com/getsentry/sentry-python/blob/2f5487235848e3bda9eae150facb0bb9e0c490a4/sentry_sdk/utils.py#L242-L248

**Comment by untitaker** [comment]
We have this: https://github.com/getsentry/sentry-python/blob/263a0bd92bdf85c6b23c889c8cd5a28adfd81ea2/sentry_sdk/utils.py#L823

People have reported that this is too lenient, but we haven't figured out why yet.

**Comment by Siecje** [comment]
So if I have a list with 1000 items I will only get the first 20 items?

https://github.com/getsentry/sentry-python/blob/263a0bd92bdf85c6b23c889c8cd5a28adfd81ea2/sentry_sdk/utils.py#L844

**Comment by untitaker** [comment]
Yes exactly. We intend to make this configurable but keep in mind that you will likely run into serverside limits as well.

**Comment by rhcarvalho** [comment]
The original question has been answered, closing to clean up the issue tracker.
