### ISSUE TITLE
DjangoIntegration not picking IP from X-Forwarded-For

### ISSUE THREAD

**Issue by rik** [getsentry/sentry-python#350]
The IP address reported is the first proxy (aka `REMOTE_ADDR`) rather than the first entry in `X-Forwarded-For`.

In the sentry events, `X-Forwarded-For` is correctly populated by all the proxies my app is running behind.

**Comment by untitaker** [comment]
Could you link a sample event so I can take a look?

**Comment by rik** [comment]
https://sentry.io/organizations/temporary-name/issues/999033107/events/15574af3980046a6b5cec4d7772b357b/

**Comment by untitaker** [comment]
I see no `REMOTE_ADDR` there. This leads me to conclude you didn't set `send_default_pii` to `True`. But that would mean there should be no IP address reported.

I think something outside of the SDK sets this IP address.

Is the correct user IP in `X-Forwarded-For`?

**Comment by rik** [comment]
> I see no `REMOTE_ADDR` there. This leads me to conclude you didn't set `send_default_pii` to `True`. But that would mean there should be no IP address reported.

Should `REMOTE_ADDR` appear in the Headers list? It's not an HTTP header.

I have not set `send_default_pii` to `True`, I'll try that to see if it changes anything.

> I think something outside of the SDK sets this IP address.

I'm starting a Django project on Heroku with Cloudflare. So far I have no application code, what could set this IP?

> Is the correct user IP in `X-Forwarded-For`?

Yes, it is showing my IP and CloudFlare's IP.

**Comment by untitaker** [comment]
Below headers there is an environment section where you should see a small
subset of wsgi env vars. REMOTE_ADDR is there iff the pii option is true.

I don't know about Heroku, I was more thinking about something your code
does.

**Comment by rik** [comment]
Setting `send_default_pii` to `True` fixed it.

I wonder if the IP address recorded was the server sending the event.

**Comment by untitaker** [comment]
I would be very interested how it got there without that option. This is a privacy issue that we need to fix if it's the sdk doing thst

**Comment by rik** [comment]
Happy to help how I can. Are you interested to be added as a collaborator on the private project?

**Comment by untitaker** [comment]
Feel free to add me! This seems important.

**Comment by untitaker** [comment]
I can't find anything that would add this IP address. If people run into this again let's reinvestigate. We have tests for this so IP addresses should not be generally added by default.

**Comment by bwesen** [comment]
I'm sorry to necro this, but I'm trying to figure out how to get the Sentry Django integration to pick up the X-Forwarded-For IP address (which seems to be set correctly) and not the Django nginx server's IP as it seems it does now (shown under the User IP in Sentry). I have no REMOTE_ADDR set under Environment.

I'm kind of at a loss figuring out where in the chain this issue occurs and if there is a setting or some issue in the DjangoIntegration I'd be happy to hear any hints :)

I have an AWS ELB doing HTTPS termination => (nginx => uwsgi => Django) 

Stuff in parantheses run on the same host on an internal network.

The IP I keep getting in User IP, is the nginx host's IP (a 10.* address), and in the Headers section I get this which seems correct, I assume this is set by the ELB, and then passed on by nginx:

X-Forwarded-For | 91.114.yy.xx
X-Forwarded-Port | 443
X-Forwarded-Proto | https

I realize there can be any combination of issues here, including nginx.conf proxy forward rules, real-ip configs etc. But it does seem that the actual IP reaches the sentry_sdk and still isn't used.

There was some Django-setting I read about:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
but I don't see how this would affect this issue..

**Comment by untitaker** [comment]
@bwesen we extract the IP address using this function: https://github.com/getsentry/sentry-python/blob/733662d417a7c272764baeeb41b947e5eccc1ad5/sentry_sdk/integrations/wsgi.py#L132-L149

As you can see `X_FORWARDED_FOR` should be picked up before the actual IP address.

Do you have any other request data in your events?

**Comment by bwesen** [comment]
@untitaker  Thanks, I looked through the file you quoted and I think it's a misconfiguration where I didn't sent "send_default_pii=True" in the init-call of the sdk integration. Testing it now. Without that, the codepath you showed isn't called as far as I could see.

The funny thing is, the IP is still sent to Sentry (but in the HEADERS as the X-Forwarded-For) even with the pii option False then, so while it probably prohibits other personally identifiable infos to be sent, it doesn't prevent all of them (the forwarded-for IPs should probably be wiped as well then I think).

**Comment by untitaker** [comment]
You're right, I will get on that.
