### ISSUE TITLE
Install requires urllib3 without explicitly specifying a version

### ISSUE THREAD

**Issue by ardenn** [getsentry/sentry-python#351]
The sdk requires urllib3 as a dependency in `setup.py` line `24`, but doesn't explicitly specify a version number. This causes a dependency conflict in projects that require a different version of urllib3 as the sentry-sdk will always try to install the latest version of urllib3.

![image](https://user-images.githubusercontent.com/17312279/56732048-d6d22e80-6764-11e9-9bb5-8fe488720944.png)

![image](https://user-images.githubusercontent.com/17312279/56732676-c6bb4e80-6766-11e9-8e2c-d79ea40aae06.png)

**Comment by untitaker** [comment]
Which tool shows you this dependency conflict? I'd argue it's broken for assuming no version range means always latest version.

**Comment by ardenn** [comment]
> Which tool shows you this dependency conflict? I'd argue it's broken for assuming no version range means always latest version.

I'm using a number of libraries, google-cloud-storage, nameko, requests among some others. They all specify the version range of `urllib3` as `>=1.21.1,<1.25`. However, `urllib3` recently (yesterday) released a new version hence the conflict

**Comment by untitaker** [comment]
We don't require the latest version of urllib3. It even shows `required: Any` in your screenshot. I don't understand where the conflict is, or more importantly, what the actual problem is that results out of this for you.

My theory is that you have multiple `pip install` commands, some of which run with `-U`, that overwrite parts of the dependency tree that the previous commands have built. But that would not be the problem of the Sentry SDK, or even something we could fix or work around in any way.

**Comment by ardenn** [comment]
Without pinning a specific version of urllib, sentry will always install the latest version (which is not what other libraries might need). To avoid conflicts with other libraries that also require urllib (could be a different version), I have to list sentry as the first item in my `requirements.txt` just to make sure any other dependency that comes after sentry uninstalls the version already installed by sentry and replaces it with the specific version that it requires. Wouldn't it be better to pin a specific version so as to keep producing reproducible builds?

**Comment by untitaker** [comment]
>Wouldn't it be better to pin a specific version so as to come up with reproducible builds?

I don't see how reproducible builds or anything close to it solve your problem. You're asking me to pin urllib3 in sentry-sdk to the version your other dependencies use just so there is no conflict specifically in your application. This will introduce more conflicts for people whose dependency tree looks different.

The fact that `pip install` does not deal with version conflicts is not something this library can solve. You have to work around it somehow else.

**Comment by picturedots** [comment]
Having the same problem, with two different libraries -- botocore and requests.  I now get these errors from doing a pip install if I don't explicit fix a version of urllib3:

```
ERROR: botocore 1.12.145 has requirement urllib3<1.25,>=1.20; python_version >= "3.4", but you'll have urllib3 1.25.2 which is incompatible.
ERROR: requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.
```

It doesn't seem that sentry is doing anything wrong per se, but it isn't playing by the same rules as these other libraries.

**Comment by untitaker** [comment]
I really have no idea how to even work around this in the sdk without breaking the dependency trees of even more people. Install a specific version of urllib3 explicitly to solve this problem or use something with reasonable dependency resolution, like poetry.
