### ISSUE TITLE
0.7.10 CeleryIntegration captures task Ignore exception

### ISSUE THREAD

**Issue by jerr0328** [getsentry/sentry-python#353]
Similar to #252, I've noticed that the Sentry client with the CeleryIntegration is capturing task Ignore exceptions, which are often used with dynamic tasks (see also https://github.com/celery/celery/issues/3437). I believe that since Retries are ignored, the `Ignore` exception should also be ignored.

The exception in Sentry is showing `celery/app/task.py in replace at line 894`:
```python
raise Ignore('Replaced by new task')
```

celery: 4.3
sentry-sdk: 0.7.10
python: 3.6

**Comment by untitaker** [comment]
Thanks for the bugreport, fixing with #355.
