### ISSUE TITLE
Issue with `facebookexternalua` user agent

### ISSUE THREAD

**Issue by jlariza** [getsentry/sentry-python#354]
Good day,

We have a Django application using sentry that manages a facebook chatbot. All the chatbot logic runs with it and the chatbot is on production right now.

The issue is that the application receives requests from Facebook directly but when an error is raised inside the view that receives this information the error never reaches sentry.

Facebook's user agent is `facebookexternalua`. I started printing logs directly on the sentry-python packages and everything works fine but, at the end, when it sends the information to sentry, sentry returns a 403 error with this message:

```
'X-Sentry-Error': 'Event dropped due to filter: web-crawlers'
```

What should we do to allow logging this kind of messages on sentry even if they are raised by the facebook user agent?

Thank you,

**Comment by untitaker** [comment]
Hi, is it possible in your situation to disable the "Ignore known web crawlers" filter? See screenshot at https://blog.sentry.io/2017/11/27/setting-up-inbound-filters

**Comment by jlariza** [comment]
@untitaker perfect! I checked the project settings but I did not see that option. 


Thank you!

**Comment by untitaker** [comment]
Great! If anybody else sees this issue, there are ways to work around this when you're interested in errors from a specific crawler. Just ask!
