### ISSUE TITLE
When I set up Managers and/or Admins in Django, Sentry seems to stop working.

### ISSUE THREAD

**Issue by pupeno** [getsentry/sentry-python#356]
I asked the question on Stackoverflow and it's starting to look like a bug (or feature):

https://stackoverflow.com/questions/55469240/sentry-vs-managers-and-admins-in-django-whats-the-correct-setup

**Comment by untitaker** [comment]
Hi, which Django version is this? Were you able to reproduce this with a simpler app than your real one, or outside of Heroku?

**Comment by pupeno** [comment]
I believe it happened in Django 2.1 or 2.2. I didn't try outside of Django.

**Comment by untitaker** [comment]
@pupeno I attempted to test this with a local django app and failed. I ensured:

* `DEBUG = False`
* `ADMINS` set to my email addr
* `sentry_sdk.init()` in `settings.py`
* Copypasted your logging config

**Comment by pupeno** [comment]
On my local Django app it's not happening, but when I deploy to Heroku it does. Having defined an ADMIN makes Sentry not work at all.

**Comment by pupeno** [comment]
I just followed up, and it seems when I have the ADMINS and MANAGERS set up, both happen, the email and the Sentry report. I don't know why I was missing the Sentry report before. My apologies.
