### ISSUE TITLE
Possibility to send error through the shell.

### ISSUE THREAD

**Issue by tolgahanuzun** [getsentry/sentry-python#360]
Normally I used the `raven` library for sentry. As of yesterday, I decided to move to the new library. (sentry-sdk) I tried to test the error via shell to test. But nothing happened.

When I examined the codes I saw an `if` to block it. I think this decision can be made optional. If you think so, I have prepared a PR. You can check and ask for edits..

(It also gave a great pleasure to visit the codes inside the library. :) )

Pr link : https://github.com/getsentry/sentry-python/pull/361

**Comment by untitaker** [comment]
Keeping this open because the feature request is still valid. I don't want to have this as option on `init` but if people want to, we can have it as option on the integration (`init(integrations=[ExcepthookIntegration(always_run=True)])`)
