### ISSUE TITLE
How to log other level like info or warning to Django

### ISSUE THREAD

**Issue by blodone** [getsentry/sentry-python#366]
Previously with the sentry_sdk i got this configuration:
```
sentry_logging = LoggingIntegration(
     level=logging.INFO,  # Capture info and above as breadcrumbs (in sentry)
     event_level=logging.WARNING  # Send no events from log messages
)
```

How should i transform this to the DjangoIntegration?
currently only messages with level >error are being logged

**Comment by untitaker** [comment]
You don't need to transform anything:

```python
init(..., integrations=[sentry_logging, DjangoIntegration(...)])
```

**Comment by untitaker** [comment]
I hope this helped. I'll close this since this issue is becoming stale... ping me when there's something left to discuss
