### ISSUE TITLE
Missing raven-like management commands

### ISSUE THREAD

**Issue by GitRon** [getsentry/sentry-python#367]
Hi guys,

Just went through your docs for django integration and could not find any equivalents to the old raven management commands like `manage.py raven test`.

Where do I find the docs for this?

Thanks!
Ronny

**Comment by untitaker** [comment]
We don't support test messages anymore. Just pop open a Django shell and run:

```
from sentry_sdk import capture_message
capture_message("hi")
```

**Comment by GitRon** [comment]
Thanks! Might be awesome to put this in the django part of your docs. We used `raven test` all the time.

**Comment by untitaker** [comment]
We're revamping the SDK docs at the moment and it's on the roadmap now
