### ISSUE TITLE
Grouping events caught with the Flask integration

### ISSUE THREAD

**Issue by wmonk** [getsentry/sentry-python#373]
Hi I have been following the guide to group a bunch of issues using fingerprints as laid out here - https://docs.sentry.io/data-management/rollups/?platform=python#example-merge-a-lot-of-groups-into-one-group-groups-are-too-small.

I am trying to group various `pymysql.err.InternalError` into a few different groups, one for deadlocks and one for lock wait timeouts. The code to do this is fairly straightforward:

```py
if isinstance(exc_value, InternalError) and exc_value.code == LOCK_WAIT_TIMEOUT:
    event['fingerprint'] = ['lock-wait-timeout']

if isinstance(exc_value, InternalError) and exc_value.code == LOCK_DEADLOCK:
    event['fingerprint'] = ['deadlock']
```

From the guide, being able to run this code is predicated on the fact that `hint['exc_info']` is passed. I've had a quick dig into the `FlaskIntegration` code, and it seems that because of the way the error is created the exception won't be accessible in this way. Is this the intended behaviour? Is there a way to accomplish what I'm trying to do above while still using the `FlaskIntegration`?

Many thanks!

**Comment by untitaker** [comment]
`exc_info` may not always be there in case it's not an error event. I don't quite see why `FlaskIntegration` wouldn't create a hint for crashing request handlers. Here it calls `capture_event` with the hint dictionary explicitly created: https://github.com/getsentry/sentry-python/blob/cf9eda29fa713edaece4be50ce5208b04a8a4d7e/sentry_sdk/integrations/flask.py#L187

**Comment by wmonk** [comment]
Ah whoops missed that part of the integration code. I will do some more digging and see what happens. Thanks for your prompt reply!

**Comment by wmonk** [comment]
Just to clear this up in case anyone else comes across this issue. I was being somewhat stupid checking the instance against the wrong class. Both `pymysql` and `sqlalchemy` export an `InternalError`, with the `sqlalchemy.InternalError` wrapping the `pymsql` one.

**Comment by untitaker** [comment]
Thanks for the update, much apprechiated!
