### ISSUE TITLE
Add PEP 561 support

### ISSUE THREAD

**Issue by chdsbd** [getsentry/sentry-python#375]
It would be useful to be able to use the type hints defined in this library with mypy. This library needs to add support for PEP 561 for this to work.

**Comment by untitaker** [comment]
Thanks for bringing this to my attention, I think this should be fixed in the next release.

**Comment by RDIL** [comment]
Mypy is still complaining for me.

**Comment by d33tah** [comment]
Same here. Pinging @untitaker

**Comment by untitaker** [comment]
can you go into more detail about what actually happens?

**Comment by d33tah** [comment]
@untitaker consider the following Dockerfile:

```
FROM python
RUN pip install mypy sentry-sdk
RUN echo 'import sentry_sdk\nsentry_sdk.init("a")' > a.py
RUN mypy --strict a.py
```

Here's what happens when you run `docker build .`:

```
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM python
 ---> d6a7b0694364
Step 2/4 : RUN pip install mypy sentry-sdk
 ---> Using cache
 ---> 2e54c901f49a
Step 3/4 : RUN echo 'import sentry_sdk\nsentry_sdk.init("a")' > a.py
 ---> Running in f5b0ac401a61
Removing intermediate container f5b0ac401a61
 ---> 33e2ee6286de
Step 4/4 : RUN mypy --strict a.py
 ---> Running in edd714b6961b
a.py:2: error: Module has no attribute "init"
Found 1 error in 1 file (checked 1 source file)
The command '/bin/sh -c mypy --strict a.py' returned a non-zero code: 1
```

**Comment by untitaker** [comment]
Okay right, `--strict` does not work. I don't know how to fix that. Patches welcome :)

**Comment by rafales** [comment]
@untitaker mypy can't deal with dynamic `__all__`. Copying all entries and making it a simple list solves the problem.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/919812/79972536-64d71700-8496-11ea-84a3-405b23e2a024.png">

**Comment by intgr** [comment]
I created a PR #892 that enables type hints for the top-level `sentry_sdk` module.

It seems that should address the problems brought up in this issue?
