### ISSUE TITLE
Masonite support

### ISSUE THREAD

**Issue by vaibhavmule** [getsentry/sentry-python#378]
It would be great to have support for Masonite Framework 

Masonite Repo: https://github.com/MasoniteFramework/masonite
Docs: https://docs.masoniteproject.com

**Comment by untitaker** [comment]
That's interesting, I never heard of this framework. I see you're a core developer on it. Do you know who uses it in production?

**Comment by vaibhavmule** [comment]
@untitaker I use it, for https://websiteopedia.com. I also use sentry for it. I have put up this issue if you guys are interested to have support for Masonite

**Comment by untitaker** [comment]
Understood. I'd be happy to merge support for it, but I can't maintain it. This part of the SDK would have to be community-maintained.

**Comment by antonpirker** [comment]
If there is a pull request from the community with a Masonite integration for the python SDK we are more then happy to merge it, but right now Sentry can not maintain such an integration, so I will close this issue.

If you stumble upon this issue and want to create Masonite support for Sentry, please open up another Issue. Thanks!
