### ISSUE TITLE
Fingerprints are not working with logging

### ISSUE THREAD

**Issue by xuhcc** [getsentry/sentry-python#383]
With raven it was possible to group events using the **fingerprint** extra parameter:

```python
logger.warning(
    'connection failed',
    exc_info=error,
    extra={'fingerprint': ['my-connection-error']},
)
```

After migration from raven-python to sentry-sdk such events are no longer grouped by sentry.

**Comment by untitaker** [comment]
Do this: 

```python
with push_scope() as scope:
    scope.fingerprint = ...
    logger.warning(..)
```

**Comment by xuhcc** [comment]
@untitaker Thanks!

**Comment by xuhcc** [comment]
I found a way to keep existing logging calls intact by using a custom integration class with this log handler:

```python
class CustomEventHandler(EventHandler):

    def emit(self, record):
        if hasattr(record, 'fingerprint'):
            with push_scope() as scope:
                scope.fingerprint = record.fingerprint
                super().emit(record)
        else:
            super().emit(record)
```

@untitaker Does it make sense to add a similar check directly to `sentry_sdk.integrations.logging.EventHandler`? I can create a PR.

**Comment by untitaker** [comment]
No, sorry I don't want to discover random attributes from there anymore (all should just go into extra).

I added a small fix into master that will allow you to do this:

```
def before_send(event, hint):
    if hint and hasattr(hint['log_record'], "fingerprint"):
        event['fingerprint'] = hint['log_record'].fingerprint
    return event

init(before_send=before_send)
```

**Comment by xuhcc** [comment]
I tried this with current master and it worked. Thank you!

**Comment by ascrookes** [comment]
@untitaker Thank you for sharing this approach. We are using this and appreciate the insight.

We ran into a small issue with it that we wanted to highlight for others who might end up here. Not all hints have the key `log_record`. In the cases where an unhandled exception was raised trying to access the log record caused the before send to raise an exception. That resulted in Sentry not sending the event and failing silently. Checking that the hint has `log_record` before trying access it fixed that issue for us.

We are currently running `sentry-sdk==1.9.0`
