### ISSUE TITLE
Some code structures are not conducive to static typing

### ISSUE THREAD

**Issue by bluetech** [getsentry/sentry-python#386]
This package now declares that it includes typings so I tried to whitelist it in one of my projects. Unfortunately I got various errors like `error: Module has no attribute "push_scope"` for `sentry_sdk.push_scope()`.

I haven't tried it but I suspect that dynamic code structures like

https://github.com/getsentry/sentry-python/blob/64ca9a97fcfe342b0ef080532b1b0574f8655d68/sentry_sdk/__init__.py#L35-L43

https://github.com/getsentry/sentry-python/blob/64ca9a97fcfe342b0ef080532b1b0574f8655d68/sentry_sdk/api.py#L24-L52

are too hard for mypy to understand. I was wondering if you'd be willing to forgo these (nice) shortcuts in order to help mypy. I'll be happy to send a PR if so.

**Comment by untitaker** [comment]
@bluetech I'd be happy to merge a PR that does this! For testing, could you add an `examples` folder with a simple script that imports the SDK and does some things with it? We could try to typecheck that example then.
