### ISSUE TITLE
should_hide_frame fails to consider __hide_traceback__ in any frame with a __name__

### ISSUE THREAD

**Issue by millimat** [getsentry/sentry-python#387]
https://github.com/getsentry/sentry-python/blob/8b3de2c80e9c4bc23fe860855d63e6eb294e987d/sentry_sdk/utils.py#L211-L226

If `__name__` is in `frame.f_globals` and is a string, then no check for `__hide_traceback__` is ever performed, which effectively makes that variable unusable to hide a frame from a stacktrace.

**Comment by untitaker** [comment]
0.9.1 is out with this fix :)
