### ISSUE TITLE
gunicorn with gevent worker - is this supported?

### ISSUE THREAD

**Issue by amir-hadi** [getsentry/sentry-python#392]
We see 'mixed' events in our Sentry installation. We recently activated the gevent worker for gunicorn, to get more concurrent requests (our service is highly IO dependent).

In the docs on sentry.io I couldn't find any documentation if gevent workers are supported or not.

I have seen some older tickets that state that it is not supported at all, but not sure if this is still the case? If it is not supported, how could we make it supported? I guess we would need to put tracking information into a Greenlet local? Would that be the right way to do it?

Thanks for any information.

**Comment by untitaker** [comment]
@amir-hadi do you have the gevent monkeypatches enabled (i.e. gevent monkeypatching the stdllib)? Those are necessary for sure.

**Comment by amir-hadi** [comment]
To my knowledge the Gevent worker of Gunicorn is patching everything for us, [see this line in the Gunicorn source code](https://github.com/benoitc/gunicorn/blob/dc7b5d5c4876b49f86ea2460698a335d0f5ef7c9/gunicorn/workers/ggevent.py#L160).

**Comment by untitaker** [comment]
Understood, in this case everything should be supported. At this point it becomes a bug. Which Python version is that?

**Comment by amir-hadi** [comment]
We are using Python 3.7.3 in our docker containers, but I am not sure if this is a bug on the UI or not. The code path we are seeing is impossible to reach for the API URL path visible in Sentry. Also, it seems like that impossible (for our system) combinations of Browser information is being done (okhttp client for native apps and Chrome for one of our management UIs).

Let me know how I can help you further to track this issue down.

**Comment by untitaker** [comment]
All of this is likely an artifact of leaking scopes. I will take a look
soon.

**Comment by untitaker** [comment]
@amir-hadi I think you're running into https://github.com/gevent/gevent/issues/1407, opened a PR

**Comment by amir-hadi** [comment]
@untitaker This basically means we cannot do anything about it right now I guess.

**Comment by untitaker** [comment]
@amir-hadi No, I will release a workaround in the SDK soon

**Comment by michaelschem** [comment]
Was there ever a workaround or patch released on this? Running into the same issue.

**Comment by antonpirker** [comment]
I am not sure, but I guess not.

Could you put together a minimal project where we can reproduce the problem so we can investigate this?
