### ISSUE TITLE
Sentry events not being received

### ISSUE THREAD

**Issue by ayushmittal** [getsentry/sentry-python#396]
I recently started using sentry for my Django Project. Everything was working fine in the development environment, but when i pushed it to prod, even though exception were getting thrown, but sentry wasn't reporting them on the dashboard. I tried enabling the debug setting in sentry config, and in the logs it said "Sending error event", but the event is still not being received.

Can someone help with this issue?

Python - 3.6.7
Sentry-sdk - 0.9.0

**Comment by untitaker** [comment]
After `sending error event` there might be extra log lines for whether it actually succeeded sending or not. For example you might see a 403 error.

**Comment by ayushmittal** [comment]
No, actually nothing gets logged after that line

**Comment by untitaker** [comment]
Actually I see you have created a SO question as well, let's debug there: https://stackoverflow.com/questions/56701574/sentry-not-receiving-exceptions

**Comment by RajBusa** [comment]
I initialized Sentry in wsgi.py, and it worked for me.
