### ISSUE TITLE
Exceptions in before_send are silenced

### ISSUE THREAD

**Issue by xuhcc** [getsentry/sentry-python#402]
Exceptions raised in `before_send` leave no trace in the logs (and event is not being reported to sentry).

```python
def before_send(event, hint):
    raise ValueError
```

**Comment by untitaker** [comment]
Those exceptions are logged when you set `init(debug=True)`. Reporting to Sentry is an interesting idea though.

**Comment by untitaker** [comment]
@xuhcc still some kinks to be worked out. For example we probably don't want to call before-send again if it was causing issues. More generally we might not want to add any scope data at all?

**Comment by xuhcc** [comment]
Yes, probably it's OK for internal errors.

For me, reporting of the original error is more important. If before-send fails, sentry-python should try to report an event nevertheless. From the user perspective, it is certainly better to get alert without additional info than to not get it at all (as it was in my case).

**Comment by untitaker** [comment]
People use `before_send` to remove sensitive information so I think just skipping over that logic if it crashes is legally problematic for those users.

**Comment by xuhcc** [comment]
Then yes, let's report only "internal" error.

**Comment by untitaker** [comment]
I think we need to shortcut a lot of logic for reporting internal errors, as it can happen that we still report the entire event with sensitive information as part of local variables.

Either that or we decide to print crashes out regardless of `debug=True`, that would probably be easiest.

**Comment by chingc** [comment]
I'm on sentry-sdk 0.11.2, and I spent most of the day trying to figure out why the codebase I work on suddenly appear to be 100% error free.  The only change was that I started using `before_send` to filter out some trivial errors.

@untitaker mentioned setting `debug=True` during `init` in the first reply, but it doesn't seem to have any affect.  Exceptions raised anywhere in my codebase gets swallowed up by `before_send` and never shows up on the Sentry dashboard.

**Comment by untitaker** [comment]
@chingc debug=True should help you figure out whether your before-send is crashing, which I assume is the case. It doesn't do anything by itself, you also need to look at stdout/stderr.

**Comment by antonpirker** [comment]
I think the conclusion of this issue is: `before_send` is used to strip sensitive data, and there we will not send errors happening in there to Sentry, because this could send sensitive information to Sentry.

If there are problems in `before_send` you need to run sentry with `debug=True` set to see errors on the console.
This is how the state of things is right now. 

I am closing this issue.

If you want to provide a way to better handle errors in `before_send` please go ahead and create a new issue linking to this one. Thanks!
