### ISSUE TITLE
Attach a custom message to an exception event

### ISSUE THREAD

**Issue by whatisaphone** [getsentry/sentry-python#403]
I'm migrating a project from raven. In a couple places, we send exceptions that have a custom message. The old code looked like this:

```
captureException(
    exc_info=...,
    message='This failed, but succeeded after a retry. Here's the original exception just in case',
    level='info',
)
```

Such events are supported by Sentry-the-server just fine. The message is displayed before the stack trace:

![Message, then exception](https://i.imgur.com/1s37yeY.png)

I can't find a way to do this in the new SDK. Is there something I missed?

**Comment by untitaker** [comment]
You can use a regular logger:

```python
mylogger.exception("My custom error message")
```

If you really want `info` as level, you can do:

```python
with push_scope() as scope:
    scope.level = 'info'
    mylogger.exception("my message")
```

**Comment by whatisaphone** [comment]
Oh of course, that'll do it.

Thanks for the quick answer!
