### ISSUE TITLE
0.9.3 Sentry init function may have a ValueError bug

### ISSUE THREAD

**Issue by luozhaoyu** [getsentry/sentry-python#404]
https://github.com/getsentry/sentry-python/compare/0.9.2...0.9.3

```
   File "/var/api/env/local/lib/python2.7/site-packages/sentry_sdk/hub.py", line 83, in _init
     client = Client(*args, **kwargs)  # type: ignore
   File "/var/api/env/local/lib/python2.7/site-packages/sentry_sdk/client.py", line 75, in __init__
     self.options = options = get_options(*args, **kwargs)  # type: ignore
   File "/var/api/env/local/lib/python2.7/site-packages/sentry_sdk/client.py", line 43, in _get_options
    options = dict(*args, **kwargs)  # type: ignore
 ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
Currently 0.9.2 works for us

**Comment by untitaker** [comment]
I assume you pass a unicode string as DSN on Python 2, and that's why it broke. Sorry, will release a new version.

**Comment by luozhaoyu** [comment]
@untitaker interesting, I just copy the DSN from https://sentry.io/settings/myorg/projects/myproject/keys/
which looks like:
`https://abcdefghijklmnopqrstuvwxyz1234@sentry.io/123456`
And yes, we are still on Python2 currently

**Comment by untitaker** [comment]
@luozhaoyu I assume you have `from __future__ import unicode_literals` at the top of the file or something like that

**Comment by luozhaoyu** [comment]
good point. I only did `import absolute_import`, sure I should also do that in case

**Comment by untitaker** [comment]
@luozhaoyu That's not necessary, I thought that you have the `unicode_literals` import already and that's why it broke. Could you try the master branch? I believe I fixed it either way.

**Comment by luozhaoyu** [comment]
@untitaker thanks for the update. While we are discussing this incident now, we may just stay with 0.9.2 and not always make our lib stay with the latest release from now on

**Comment by untitaker** [comment]
That's sad to hear but understandable. We do aim for stable releases.

**Comment by untitaker** [comment]
0.9.4 is released, sorry for the inconvenience

**Comment by luozhaoyu** [comment]
Thank you Markus!
