### ISSUE TITLE
inspect.getargspec() is deprecated since Python 3.0

### ISSUE THREAD

**Issue by epingolt** [getsentry/sentry-python#405]
Since release 0.9.3 this method raises a DeprecationWarning in Python3:

`.../sentry_sdk/consts.py:61: in _get_default_options`
`    a = inspect.getargspec(ClientConstructor.__init__)`
`.../python3.6/inspect.py:1078: in getargspec`
`    DeprecationWarning, stacklevel=2)`
`E   DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
`

**Comment by untitaker** [comment]
Thanks, I will release 0.9.5.

**Comment by epingolt** [comment]
Wow, that's quite a response time. Thank you!
