### ISSUE TITLE
Restrict context information variables

### ISSUE THREAD

**Issue by horida** [getsentry/sentry-python#407]
"Context": When sending an exception to sentry.io also information about the variables is send. For example, for the following code
```python
def my_func():
    an_instance = MyClass(secret='fubar')
    1/0
```
we get, appart from the exception traceback, also information about the `an_instance` object. Basically it depends on how `MyClass.__str__` is defined. This is because the method `sentry_sdk.util.safe_repr` calls it. 

In this example, also the secret could be show, depending on the `__str__` method.

It is quite hard with a huge code base to assure that no `__str__` method actually "shows" sensitive data.

**Proposal**
It would be way easier if the `repr` call in `sentry_sdk.util.safe_repr` could be customized, for instance by passing a method, conditions or similar. For example, to print only an object's class name and ID.

**Comment by untitaker** [comment]
What's wrong with [before-send](https://docs.sentry.io/learn/filtering/?platform=python#before-send) for this? You can modify everything in the payload we send to Sentry.

**Comment by horida** [comment]
It's really hard to dive into the event in order to get to the information. Furthermore, you only have the repr return value there, not the object.

**Comment by untitaker** [comment]
ok then we still have `sentry_sdk.serializer.add_global_repr_processor` which should satisfy your usecase. I think it's practically stable (documentation story is a broader issue which we hope to tackle this year). Usage example here:

https://github.com/getsentry/sentry-python/blob/b72292c3575c0b115bb684f1f374fa333e365a78/sentry_sdk/integrations/django/__init__.py#L175-L200

**Comment by horida** [comment]
Thanks for the blazing fast answer @untitaker !

Yes, that does the job. It took me a while to figure out the flow but in the end this snipped does the job for me:
```python
def anonymize_models(obj, hint):
    if '.models' in obj.__class__.__module__:                                                     
        return "<{} id: {}>".format(obj.__class__.__name__,
                                    obj.id if hasattr(obj, 'id') else '-')  
    return NotImplemented                                                                         

sentry_sdk.init(...)
sentry_sdk.add_global_repr_processor(anonymize_models)
```

I will close the Issue.
