### ISSUE TITLE
Django configuration fails when using Django Rest Framework

### ISSUE THREAD

**Issue by hedleyroos** [getsentry/sentry-python#408]
The instructions at https://docs.sentry.io/platforms/python/django/ suggest putting the Sentry configuration into `settings.py`.; however, when using DRF Sentry SDK has extra logic that may cause an "apps aren't loaded yet" error.

The solution is to simply move the configuration into the `ready` method of your AppConfig. That avoids any pitfalls and is safe to use in all cases, provided your Django project / app uses AppConfig (it should!).

**Comment by untitaker** [comment]
I think this bug has been fixed in 0.9.2 (#397)

**Comment by untitaker** [comment]
@hedleyroos calling `init` in AppConfig.ready might prevent errors of the first HTTP request from being captured. We heavily monkeypatch Django (and really everything we integrate with) and the earlier we get to do it the better.
