### ISSUE TITLE
SDK is using "logging" mechanism for uncaught exceptions in Flask app with Flask integration

### ISSUE THREAD

**Issue by aniforprez** [getsentry/sentry-python#411]
I've used the FlaskIntegration step as described in the documentation but clearly I'm doing something wrong because sentry.io still recommends I use the flask integration at the bottom of error messages and the mechanism is always "logging".

The SDK used to work properly when configured with raven

**Comment by untitaker** [comment]
@aniforprez could you post some code, when you init what?

**Comment by aniforprez** [comment]
Here's how I'm initializing the sentry SDK

```python
# Sentry initialization for Flask app
sentry_sdk.init(
    dsn=SENTRY_DSN,
    integrations=[FlaskIntegration(transaction_style="url")],
    environment=SENTRY_ENVIRONMENT,
)

mainapp = Flask(__name__)
```

But the tags in Sentry show up as follows

![image_blur_Screenshot from 2019-07-05 18-00-21](https://user-images.githubusercontent.com/993132/60722686-49267280-9f4f-11e9-9eef-72a35a58db8c.png)

with the "We recommend you enable the 'flask' integration" at the bottom. Do you need any more info on this?

**Comment by untitaker** [comment]
Could you share one of those events (just post the URL you visit, not the share URL)? I am just poking in the dark right now as to what the issue is and also what kind of data I actually need to debug it.

**Comment by aniforprez** [comment]
https://sentry.io/organizations/esthenos-qn/issues/1099335900/?project=1360851&query=is%3Aunresolved

Is this sufficient? Once again terribly sorry for making it difficult for you. I'm quite confused as well because I'm quite sure we're doing something wrong but I have no idea what it is

**Comment by untitaker** [comment]
No worries, it seems like a bizzarre issue. Could you check what happens with `init(debug=True)`? It should tell you what integrations it's going to enable

**Comment by aniforprez** [comment]
Hey I'm terribly sorry for potentially wasting your time. I figured it out. The problem was that I was initialising sentry_sdk with flask once but there was separate code tat was running with only the celery integrations that was overriding these settings. I'll close this issue. Thank you so much for your help!

**Comment by untitaker** [comment]
Yeah I would just use the same `init()` everywhere. It will enable integrations that you don't need (and import celery in your web workers even though there's no need), but it's just easier to reason about

**Comment by aniforprez** [comment]
Yes the cost of the unnecessary integrations is negligible in favor of all our exceptions being captured accurately with the related data available
