### ISSUE TITLE
Collections.abc deprecation warning

### ISSUE THREAD

**Issue by tirkarthi** [getsentry/sentry-python#415]
The below line generates a warning regarding importing from collections.

https://github.com/getsentry/sentry-python/blob/7c4683f0cd2a32738ba5e22c4a9bc6040ea13f15/sentry_sdk/tracing.py#L27

```
  /home/karthi/freezegun-venv/lib/python3.9/site-packages/sentry_sdk/tracing.py:27: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    class EnvironHeaders(collections.Mapping):  # type: ignore
```

This can be fixed like similar fix done in other file

https://github.com/getsentry/sentry-python/blob/44b8949fe2ff0f6319dd586d15c3e76b239971d6/sentry_sdk/serializer.py#L30-L37

**Comment by untitaker** [comment]
Thanks, since this has happened twice now I am working on a bigger fix for this in https://github.com/getsentry/sentry-python/pull/416
