### ISSUE TITLE
Tracing Popen monkey patch breaks environment

### ISSUE THREAD

**Issue by hartror** [getsentry/sentry-python#417]
In `0.10.0` the new tracing functionality wipes the environment for subprocesses.

As calls to `_get_argument` modify input (surely an anti-pattern) the subprocess call becomes `POpen(..., env={sentry trace values only})` which wipes the environment from the parent process.

https://github.com/getsentry/sentry-python/blob/ca0ba7f6c417d9ce7ee157149ddddce5add893a9/sentry_sdk/integrations/stdlib.py#L143

**Comment by untitaker** [comment]
Thanks for the bugreport, we will fix this today!

**Comment by untitaker** [comment]
0.10.1 has been released!
