### ISSUE TITLE
Celery exceptions are logged twice

### ISSUE THREAD

**Issue by WhyNotHugo** [getsentry/sentry-python#433]
All my celery exceptions get logged twice. I _think_ this might be related to #124, but I'm not honestly sure.

This is my setup:

```python
init_sentry(
    attach_stacktrace=True,
    integrations=[
        CeleryIntegration(),
        DjangoIntegration(),
        LoggingIntegration(event_level=logging.WARNING),
    ],
    release=version,
)
with configure_scope() as scope:
    scope.set_tag("site", DEFAULT_HOST)
```

Each event get logged twice, however, one copy says `mechanism=logging, handled=yes`, and the other `mechanism=celery, handled=no`.

This did not happen with raven, but happens every time with the newer sentry client.

**Comment by untitaker** [comment]
Hey @WhyNotHugo, what is the name of the logger? It should be in a tag called `logger`.

**Comment by untitaker** [comment]
To be clear, what I suspect is going on here is that one of these events is celery logging a stringified version of your exception. We already deduplicate error events by exception identity (so even explicitly calling capture_exception twice on the same exception object only gives you one event).

**Comment by WhyNotHugo** [comment]
One of the events have `logger=celery.app.trace`. The other doesn't specify a logger.

Would the event JSON help? I can strip out the few sensitive details of it and included, if useful.

**Comment by WhyNotHugo** [comment]
> To be clear, what I suspect is going on here is that one of these events is celery logging a stringified version of your exception. We already deduplicate error events by exception identity (so even explicitly calling capture_exception twice on the same exception object only gives you one event).

Hmm... odd that this did not happen with raven. Any ideas on how to work around it?

**Comment by untitaker** [comment]
@WhyNotHugo This happens because the new Python SDK intercepts all loggers more aggressively compared to Raven. It's possible that Raven didn't capture errors from that logger even if they were legitimate.

You can work around it by ignoring the logger: https://docs.sentry.io/platforms/python/logging/#ignoring-a-logger

If this is on SaaS feel free to post a link here, otherwise, yes, the JSON would be useful! Thanks

**Comment by WhyNotHugo** [comment]
Alright, I can ignore the logger, that works for me.

If you feel it's worth inspecting this to avoid sentry duplicating in the first place, here's a set of events that are actually the same:

https://sentry.io/organizations/hobarrera/issues/1108917799/?query=is%3Aunresolved
https://sentry.io/organizations/hobarrera/issues/1108917797/?query=is%3Aunresolved

**Comment by untitaker** [comment]
I don't quite understand what happens here but it seems that those two exceptions have slightly different stacktraces (one has extra frames at the bottom). I assume that something in Celery pickles an exception, unpickles it and reraises it.

**Comment by WhyNotHugo** [comment]
Hmm... I see. I can't say I've very any good insight on this.

Yes, it seems that `celery` picks up the exception, and trims two items from the stacktrace (probably to make it more friendly for developers).

I'm curious though: if the initial exception get caught before it's re-thrown, why does Sentry actually pick it up? Isn't it "just another handled exception"?

**Comment by untitaker** [comment]
>I'm curious though: if the initial exception get caught before it's re-thrown, why does Sentry actually pick it up? Isn't it "just another handled exception"?

Could you elaborate on this? I don't understand the queston

**Comment by yarinb** [comment]
We are facing the exact scenario, with the new Python SDK.
A celery job handles an exception from a thirdparty library, then raises our application exception.
What happens in Sentry is this:
1. One event coming from the logging mechanism, with the thirdparty exception (**mechanism=logging, handled=yes**)
2. Another event for our own exception, with the thirdparty lib exception stacked in, with (**mechanism=celery, handler=no**)

I can't ignore the logger as it's coming from our app.
I'd expect Sentry to dedup these two.

**Comment by untitaker** [comment]
Does that mean you are explicitly logging? Where are you logging? In the worker where the exception happened, or somewhere else?

**Comment by yarinb** [comment]
@untitaker I jumped to conclusions too fast after finding this issue to be exactly what we're experiencing. Looking again at the code, yes. We were explicitly `logging.exception(thirdparty_exception)`. My bad.

**Comment by untitaker** [comment]
@yarinb that should still not cause duplicate exceptions. If you can't remove this logging call, feel free to open a new issue!

**Comment by yarinb** [comment]
I can remove the logging call. But If you’d like me to open a new issue and help troubleshoot I’d love to.

Sent via Superhuman iOS ( https://sprh.mn/?vip=yarin@vayo.io )

**Comment by untitaker** [comment]
yes please do that

**Comment by WhyNotHugo** [comment]
> I'm curious though: if the initial exception get caught before it's re-thrown, why does Sentry actually pick it up? Isn't it "just another handled exception"?

So, my celery task throws an exception (exception 1) which celery captures, and re-throws as a new one (exception 2).

It makes sense that "exception 2" gets logged, by why is the first one logged? I though handled exceptions were not logged by default. In other words, this is kind of:

```python
try:
    raise Exception()  # This shouldn't get logged, right?
exception Exception as e:
    raise Exception from e  # This one should get logged

# Both seem to be logged...?
```

**Comment by untitaker** [comment]
We capture celery errors as they occur in tasks. Celery then re-raises the exceptions when you try to get the result of a task.

We capture exception 1 because we cannot be sure that anybody will ever fetch the result of a task.

**Comment by WhyNotHugo** [comment]
> Celery then re-raises the exceptions when you try to get the result of a task.

I never try to get the result of the task. I've nothing result-related anywhere.
Are you sure that's actually the case?

**Comment by untitaker** [comment]
I mean *if* you do that [like here](https://stackoverflow.com/a/30760142/1544347) then I would have an idea what happens (`result.get()` re-raises).

Would you have time to give me a self-contained repro case of some sort?

**Comment by sl0thentr0py** [comment]
I'm cleaning up stale issues and seems like there are already some solutions above.
If this is still an issue, please reopen.
