### ISSUE TITLE
Problem with Popen arguments passed as map

### ISSUE THREAD

**Issue by lorinkoz** [getsentry/sentry-python#436]
Greetings!

I am having an issue when using the package `sorl.thumbnail` on a Django project. That package produces thumbnails from images using system installed programs (called engines.)

When `sorl.thumbnail` makes a `Popen` call here:

https://github.com/jazzband/sorl-thumbnail/blob/22ccd9781462a820f963f57018ad3dcef85053ed/sorl/thumbnail/engines/convert_engine.py#L57

The arguments that are received in your patched `Popen` are not being interpreted correctly. This is the suspect of the problem:

https://github.com/getsentry/sentry-python/blob/2c0a2ea96882adf69742bd7e79e588564ff5b85c/sentry_sdk/integrations/stdlib.py#L143

Arguments are handled in such a way that the original `popen` crashes when trying to access `args[0]`, as the `args` parameter is interpreted (or actually becomes) an empty list.

In my opinion, the problem arises because in `sorl.thumbnail` the arguments to `Popen` are passed to a `map` function first, so that a `map` object is what gets passed as arguments. I am not sure what's the effect of a `map` object being received in your `*a` of the patched `Popen`.

Here's the relevant part of the traceback I am getting:

```
File "/mnt/d/Proyectos/ginseng/.venv/lib/python3.6/site-packages/sorl/thumbnail/base.py", line 131, in get_thumbnail
    thumbnail)
  File "/mnt/d/Proyectos/ginseng/.venv/lib/python3.6/site-packages/sorl/thumbnail/base.py", line 164, in _create_thumbnail
    default.engine.write(image, options, thumbnail)
  File "/mnt/d/Proyectos/ginseng/.venv/lib/python3.6/site-packages/sorl/thumbnail/engines/convert_engine.py", line 57, in write
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/mnt/d/Proyectos/ginseng/.venv/lib/python3.6/site-packages/sentry_sdk/integrations/stdlib.py", line 165, in sentry_patched_popen_init
    return old_popen_init(self, *a, **kw)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1248, in _execute_child
    executable = args[0]
IndexError: list index out of range
```

If I remove the Sentry integration altogether from the Django project, `sorl.thumbnail` is able to effectively call `Popen` with the "mapped" arguments, and everything works.

Thanks in advance!

**Comment by lorinkoz** [comment]
The problem is basically here:

https://github.com/getsentry/sentry-python/blob/2c0a2ea96882adf69742bd7e79e588564ff5b85c/sentry_sdk/integrations/stdlib.py#L160

The `args` (which is the object reference of the original arguments and not a copy) is walked entirely, thus "depleting" the `map` object. Next time the map is called inside the original `Popen`, it is interpreted as an empty iterable.

**Comment by WilliamMayor** [comment]
I experienced this with Django's collectstatic command running pysassc. I had to downgrade to version 0.9.5 (the last working version I'd used) to get my Heroku deploys to start working again.

**Comment by untitaker** [comment]
I think it would make sense to report this against the upstream projects that cause these problems as well. As far as I understand it's not legal to pass the return value of `map(.., ..)` to `subprocess.Popen`, as it expects a sequence that has to e.g. be indexable.

Those invocations just happen to work under CPython but probably fail under PyPy 3.

A fix will be out soon.

**Comment by untitaker** [comment]
Bug reported for PyPy: https://bitbucket.org/pypy/pypy/issues/3050/subprocesspopen-only-accepts-sequences

@lorinkoz @WilliamMayor I would greatly apprechiate if you carry this issue into Django and its extensions, because I lack context there.

**Comment by WilliamMayor** [comment]
@untitaker Happy to help if I can. Just to check...

The issue is that the upstream projects are passing generators into Popen? Sentry depletes the generators when trying to save the subprocess call's details. So when Popen is called "for real", it's passed an empty generator.

The Python docs say that you shouldn't pass a generator into Popen. So the upstream projects need to update, not Sentry?

**Comment by untitaker** [comment]
@WilliamMayor to be clear we will fix the SDK to not change the real-world behavior of subprocess. I am just saying that those upstream libraries are *also* broken in the sense that they use the stdlib in an undocumented way and are unlikely to work on PyPy.
