### ISSUE TITLE
sentry-sdk is being suppressed by the Elastic APM

### ISSUE THREAD

**Issue by msamoylov** [getsentry/sentry-python#438]
We have both sentry-sdk and [apm-agent-python](https://github.com/elastic/apm-agent-python) installed. For some reason our [Django configuration](https://docs.sentry.io/platforms/python/django/) has stopped capturing any view errors, but Celery is still fully covered.

Any ideas how to fix that?

**Comment by untitaker** [comment]
Are you saying that you no longer seeing Django errors in Sentry after adding Elastic's APM agent?

**Comment by msamoylov** [comment]
@untitaker yes, we're seeing zero events for views. I suppose their middleware prevents Sentry from tracking view errors.

**Comment by untitaker** [comment]
Considering how #442 was closed, can you tell me the WSGI server you're using?

**Comment by untitaker** [comment]
I don't have an immediate idea what's wrong. Did you talk to elastic/opbeat
about this too?

**Comment by msamoylov** [comment]
This is what breaking Sentry, see https://github.com/elastic/apm-agent-python/blob/master/elasticapm/contrib/django/apps.py#L68

**Comment by untitaker** [comment]
@msamoylov what do you mean by that? The only way I can see this breaking our instrumentation is if their signal handler raises an exception. Do you see exceptions in your logs coming from Elastic APM?

At this point I believe this is Elastic's bug, not ours.

**Comment by msamoylov** [comment]
@untitaker I mean that Elastic is intercepting all exceptions in views and nothing gets to Sentry. We had to ditch Elastic to get Sentry working again.

**Comment by msamoylov** [comment]
It has been addressed in Elastic APM.

**Comment by untitaker** [comment]
Thank you! Do you have a commit that I can take a look at?

**Comment by msamoylov** [comment]
> Thank you! Do you have a commit that I can take a look at?

@untitaker https://github.com/elastic/apm-agent-python/commit/38c40e81c385cec4e0d081cdcd71f63ab4e208ce#diff-8e73ec7527e895598b09a3c22836a76f
