### ISSUE TITLE
logging breadcrumb collection time is incorrect

### ISSUE THREAD

**Issue by karliy** [getsentry/sentry-python#441]
![sentry](https://user-images.githubusercontent.com/28345280/61774444-71f0a800-ae29-11e9-8074-f3c88154b432.png)

I found the breadcrumbs timestamp converted to the local time zone
datetime.datetime.fromtimestamp(record.created)

> ```python
> # /sentry_sdk/integrations/logging.py:90
> def _breadcrumb_from_record(record):
>     # type: (LogRecord) -> Dict[str, Any]
>     return {
>         "ty": "log",
>         "level": _logging_to_event_level(record.levelname),
>         "category": record.name,
>         "message": record.message,
>         "timestamp": datetime.datetime.fromtimestamp(record.created),
>         "data": _extra_from_record(record),
>     }
> ```

**Comment by untitaker** [comment]
Thanks, yes this is a bug. Will fix this week!

**Comment by untitaker** [comment]
@karliy could you try the master branch to see if your issue was fixed?

**Comment by karliy** [comment]
fixed,thx😃
