### ISSUE TITLE
sentry-sdk is being suppressed by Honeycomb beeline (Django)

### ISSUE THREAD

**Issue by fitzoh** [getsentry/sentry-python#442]
In a similar vein to #438 , it looks like the honeycomb.io agent ([beeline-python](https://github.com/honeycombio/beeline-python) ([beeline issue](https://github.com/honeycombio/beeline-python/issues/71))) is preventing sentry from reporting.

Details:
I'm activating sentry in the top of settings.py ([docs](https://docs.sentry.io/platforms/python/django/))
```
sentry_sdk.init(
    dsn=dsn,
    environment=env,
    integrations=[DjangoIntegration()],
)
```

beeline is being initialized in the gunicorn config file ([docs](https://docs.honeycomb.io/getting-data-in/python/beeline/#gunicorn))
```
def post_worker_init(worker):
    beeline.init(
        writekey=honeycomb_key,
        dataset=dataset,
        service_name=service
    )
```

I can manually send events via `capture_message` and friends, but automatic error reporting doesn't work unless honeycomb is removed.

Partially redacted requirements.txt
```
Django~=2.1.9
djangorestframework~=3.9.1
gunicorn~=19.9.0
sentry-sdk~=0.10.2
honeycomb-beeline~=2.6.1
libhoney~=1.8.0
statsd~=3.3.0
```

**Comment by fitzoh** [comment]
Figured it out on the honeycomb side, don't think there's anything to do here.

**Comment by untitaker** [comment]
@fitzoh what was the fix?

**Comment by fitzoh** [comment]
Following [this portion](https://docs.honeycomb.io/getting-data-in/python/beeline/#using-the-python-beeline-with-gevent) of the honeycomb docs:

---

<img width="719" alt="Screen Shot 2019-07-31 at 12 30 07 PM" src="https://user-images.githubusercontent.com/131809/62230048-fb0a6080-b38e-11e9-9970-dd1937b0ae3f.png">

The late gevent monkeypatching was causing honeycomb reporting to fail with a `RecursionError` and knocking out sentry in the process.

**Comment by untitaker** [comment]
That's bizarre, thanks for figuring this out!
