### ISSUE TITLE
jazzband django push notification using DEBUG=True

### ISSUE THREAD

**Issue by elcolie** [getsentry/sentry-python#443]
This is my [issue](https://github.com/jazzband/django-push-notifications/issues/510) with `push notification`.

**Problem:**
With `DEBUG=True`. My server will not send out the crash report to `sentry.io`, but my server can do push notification to iOS.

**Question:**
How can I activate sentry agent in my server, but keep using `DEBUG=True`?
If it no such a thing. May I request a dedicated variable in `Django` environment to activate sentry. For example `SENTRY_AGENT=True` to let my server sends the report to `sentry.io`

**Comment by untitaker** [comment]
The sdk reports errors even with debug=True, so this is a bug then. Could you tell me the Django version and if removing push notifications fixes the problem?

**Comment by elcolie** [comment]
@untitaker 
Confirm that regardless of `DEBUG=True/False`. My server always sends the report
I have test with simple URL

```
@api_view(['GET'])
@permission_classes(())
def trigger_sentry(request):
    raise Exception("test sentry DEBUG=True")
```
![image](https://user-images.githubusercontent.com/18206728/61993112-1de7fc80-b091-11e9-920b-fa5016710089.png)

`django==2.2.3`

After remove `push_notification` from my `pyenv`. `Sentry` works like expected
`DEBUG=True` no report sent out
`DEBUG=False` has a report
![image](https://user-images.githubusercontent.com/18206728/61993373-3e19ba80-b095-11e9-9b8a-77505d2ba4b9.png)

**Comment by antonpirker** [comment]
Hey @elcolie 
Could you try this again and see if this is still the case with the newest Sentry SDK? A lot of time passed since then, and I am just wandering if time solved this problem?

Thanks for your feedback!

**Comment by elcolie** [comment]
So sorry. Project is suspended already 😞
