### ISSUE TITLE
Allow the IP address to be collected even if `send_default_pii=False`

### ISSUE THREAD

**Issue by jarshwah** [getsentry/sentry-python#445]
We're in a situation where it's extremely difficult to track how many customers are affected by an issue since the IP Address is always being logged as our load balancer. This may be a separate issue that I'll look into more closely.

Still, I think lumping in the client ip address with headers like the cookie is overkill. An IP address is extremely useful for debugging issues even when we don't wish to collect other PII fields.

Is it possible to collect the IP address without collecting other PII? If not, can we consider some kind of option to do so?

Thanks :)

**Comment by untitaker** [comment]
I think I saw your question on the forum already, and the answer is that using either the datascrubber settings in the UI or a custom `before-send` hook together with `send_default_pii=True` seems like the best option right now.

Alternatively attach the IP address explicitly to the event like this:

```
with configure_scope() as scope:
    scope.user = {"ip_address": get_ip_addr()}
```

Unfortunately I don't have a better solution for you right now.

**Comment by untitaker** [comment]
Revisiting this during triage. send_default_pii=False is our "safe default" so the original suggestion of just sending IP addresses by default is a no-go. I think the workaround given above is adequate. You can additionally choose to `send_default_pii=True` and then remove most of the PII via server-side scrubbing. It seems to work well for most people.
