### ISSUE TITLE
logbook Integration

### ISSUE THREAD

**Issue by miracle2k** [getsentry/sentry-python#450]
The old raven client integrated with logbook. Is this planned for the new SDK as well?

**Comment by untitaker** [comment]
It's not planned yet but if people are asking for it we will prioritize of course.

**Comment by nip3o** [comment]
I just discovered this as we are migrating from Raven to the new SDK. Going to try to hack something together, might submit a PR if it turns out good.

**Comment by anton-tagunov** [comment]
@nip3o did you migrate Logbook handler from raven to sentry_sdk?

**Comment by nip3o** [comment]
Ohh, I forgot about this. Yes, I ended up copy-pasting https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/logging.py#L153-L210 but inheriting from `logbook.Handler` instead of from `logging.Handler`, and changing some attribute names from `record`.

**Comment by anton-tagunov** [comment]
thank you. It seem like you have implemented raven logic to handle record. I mean you have manually added new event handler to logbook handler's stack. 
But logging integration patching logging library. Anyway thank you, i have missed EventHandler when looking to the code.

**Comment by miracle2k** [comment]
@nip3o I forked your code to add breadcrumb support: https://gist.github.com/miracle2k/a3eb2350e73ca025eaca84ced48fdabf

**Comment by antonpirker** [comment]
Logbook seems abandoned:
https://github.com/getlogbook/logbook

I will close this issue. 

If you come across this issue and you want to supply a Logbook integration we are more then happy to help merge your PR!
