### ISSUE TITLE
Annotate @celery.task as spans

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-python#458]
There's a pattern I have commonly that is something like this:

```
@celery.task
def do_bulk_thing():
    for item in list:
        do_single_thing(item)

@celery.task
def do_single_thing():
    # ...
```

When looking at a span tree - while understandable - its hard to reason about boundaries. We could provide span wrappers for every task which would actually make this kind of trace much more easily reasoned about.

(This is different than us just instrumenting the outbound .delay/apply_async call)

**Comment by untitaker** [comment]
Ah, had to read that twice. Would it make sense to create a new transaction or do you absolutely want this to be just a span?

**Comment by antonpirker** [comment]
Status update. Sounds like a nice thing to have. We plan an update to the SDK for supporting Django 4 and in this update we could also put some Celery improvements. We will keep this in mind.
