### ISSUE TITLE
Use unparsed query for descriptions from Django ORM

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-python#459]
By using the parsed query we inject params which might be sensitive or PII (which then means we'd have to strip the whole description). Right now we dont have scrubbing on spans, but if it did it would make a bunch of them fairly useless.

I think we should either:

- Change the description to be 100% unparsed (so placeholder variables)
- Change the description to be [statement type] [tables] (SELECT table1, table2)

We can still keep parameters in the context and apply data scrubbing logic there.

**Comment by untitaker** [comment]
Sending the query without params is less code than what is happening right now, and I would appreciate it because it makes the job for sqla easier as well. Do you want this behavior for breadcrumbs as well?

**Comment by dcramer** [comment]
Yeah probably would want to do the same. Its still very high value. For example Atlas has a query which is "WHERE access_token = X" which would fall under our sensitive data concerns, which means we'd have to parse and revoke that bit, or strip the whole query using our standard dumb logic.

**Comment by untitaker** [comment]
just so I understand you correctly, that means we are going from:

    SELECT * FROM table WHERE x = 123

to:

    SELECT * FROM table where x = %s

for both breadcrumb msgs and span descriptions.

**Comment by dcramer** [comment]
Yeah that's what I'd prefer. If we have params available, stuff them into the context/extras payload.

**Comment by untitaker** [comment]
This is done since #462 is merged
