### ISSUE TITLE
Event reporting within sub process does not work without time.sleep

### ISSUE THREAD

**Issue by vzts** [getsentry/sentry-python#473]
```python
import sentry_sdk
from multiprocessing import Process
from time import sleep


def child_process():
    try:
        test_child = 1 / 0
    except Exception as e:
        sentry_sdk.capture_exception(e)
        sleep(1)  # I have to give this sleep


sentry_sdk.init(
    '...',
    debug=True
)
proc = Process(target=child_process)
proc.start()
proc.join()
```
Without giving sleep, the event reporting is not correctly triggered. Why is this? Is it because the worker thread is a daemon thread? (but I have tried to comment [`self._thread.setDaemon(True)`](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/worker.py#L66) out, but it still shows the same symptom)

**Comment by untitaker** [comment]
`multiprocessing` introduces odd interpreter behavior for subprocesses. See #291.

Your best fix is to add `sentry_sdk.Hub.current.flush()` after `capture_exception()`, which ensures that the process sleeps as long as it's necessary to send events out.

For the main process this is done automatically via `atexit`, but those hooks do not run in `multiprocessing`.

**Comment by vzts** [comment]
@untitaker Thank you for your quick response! (probably the fastest I received in github)
All make sense to me and the flushing did resolve the issue.
Thanks again for the explanation :)

**Comment by untitaker** [comment]
See this question: https://stackoverflow.com/a/34507557/1544347

It's very unfortunate behavior. We even work around this in the Celery integration, but the fix is Celery-specific (and has to be).

Theoretically you could monkeypatch `os._exit` to make things work "automatically", but that's dangerous.
