### ISSUE TITLE
Large variables hide small ones in stackframes

### ISSUE THREAD

**Issue by phihag** [getsentry/sentry-python#479]
If a stackframe contains a variable with a large value, then the other variables with smaller values will not get reported. Take the following example:
```
import os
def main():
    a = 1
    x = 2
    large = [['a' * 32] * 32] * 32
    b = 3
    y = 4
    raise ValueError('testing sentry')

import sentry_sdk
sentry_sdk.init(dsn=os.environ['SENTRY_DSN'])
main()
```

It seems to depend on some implementation details, but with Python 3.6.5 on my system, this will report `a`, `b`, and a part of `large`:

![image](https://user-images.githubusercontent.com/779568/63610046-bc0bab80-c5d8-11e9-9cb0-d1b24875ce62.png)

The old raven client seems to select randomly instead of alphabetically, although I'm not sure why. In either case, the report is suddenly cut off.

This is unhelpful, as important information is much more likely to be in `x` and `y` than in the 100th character of `large`. This is just a toy example, but in production it's a serious problem.

Any of the following would solve my problem:
1. Sort by value size, ascending.
2. Add an option to limit large values, say, to 100 characters.
3. First pick all values with a configurable max size, then try to pick the larger ones.
4. Allow larger stackframes, i.e. cut off less in the first place.
4.

**Comment by untitaker** [comment]
Yes this is a serverside bug, it just mainfests differently because variables are shown in a different order (although I believe the order is not necessarily preserved on the server too).

I will take a look next week, thanks!

**Comment by sl0thentr0py** [comment]
closing because stale, please reopen if this is still an issue.
