### ISSUE TITLE
logger.exception does not send error to sentry with new sdk django integration

### ISSUE THREAD

**Issue by darahsten** [getsentry/sentry-python#480]
When sentry is configured with the new sdk in the default format in this format.
```import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
sentry_sdk.init(
  dsn="https://<key>@sentry.io/<project>",
  integrations=[DjangoIntegration()]
)
```

logs are not sent when `logger.exception` is called. The only way to get logs to captured by
sentry is to use `capture_exception` or to do customised logging as suggested in the post [https://github.com/getsentry/sentry-python/issues/365](Issue) #Not tested it my self.

This implies that one has to replace all instances of `logger.exception` with `capture_exception` or `capture_message` if one wants to do an upgrade to the new sentry_dsn format.

I have made a minimal project demonstrating this [https://github.com/darahsten/sentry_nologger_demo](url).

You can see the discussion [https://stackoverflow.com/questions/57274935/configuring-sentry-handler-for-django-with-new-sentry-sdk-without-raven/57294650#57294650](url)

**Comment by untitaker** [comment]
Please add debug=True to your call of init to see what goes wrong. This is
supposed to work

**Comment by darahsten** [comment]
@untitaker , When one adds `debug=True`, the sentry error is logged. When `debug=True` is removed the error is not logged.
``` 
[sentry] DEBUG: Enabling integration atexit
[sentry] DEBUG: Enabling integration dedupe
[sentry] DEBUG: Enabling integration stdlib
[sentry] DEBUG: Enabling integration threading
Performing system checks...

System check identified no issues (0 silenced).
August 25, 2019 - 12:27:24
Django version 2.0, using settings 'config.settings'
Starting development server at http://127.0.0.1:9000/
Quit the server with CONTROL-C.
ERROR 2019-08-25 12:29:22,860 urls 16092 140472718829312 ZeroDivisionError('division by zero',)
Traceback (most recent call last):
  File "/home/user/Projects/logger_exception_failure/config/urls.py", line 29, in sentry_nologs_error
    division_by_zero = 1/0
ZeroDivisionError: division by zero
 [sentry] DEBUG: Sending event, type:null level:error event_id:8461f42c7a7c41d2990f6c64468cab39 project:1380327 host:sentry.io
DEBUG 2019-08-25 12:29:22,874 transport 16092 140472590001920 Sending event, type:null level:error event_id:8461f42c7a7c41d2990f6c64468cab39 project:1380327 host:sentry.io
[25/Aug/2019 12:29:22] "GET /sentry-nologs-error/ HTTP/1.1" 302 0
```

**Comment by darahsten** [comment]
![image](https://user-images.githubusercontent.com/7501274/63650510-8f2bd580-c74b-11e9-93de-dc7200fe8d05.png)
@untitaker , I can no longer replicate the failure to log errors after inserting and removing `debut=True.` The apparent failure to log mentioned above is (was) due to the delay of sentry to capture the event as the event eventually appears in the sentry-console after about two minutes.

The image attached shows errors logged yesterday and today. All sentry-nologs-error (logger.exception) are events for today. 

I even did a fresh reclone of the repo and worked with a new fresh virtual environment. I dont know what advice you got for this.

**Comment by untitaker** [comment]
@darahsten this is undesirable but not unheard of. Sometimes we get a load spike on sentry.io and have to go through a backlog of events to process and store.
