### ISSUE TITLE
Django mechanism should not log PermissionDenied

### ISSUE THREAD

**Issue by WhyNotHugo** [getsentry/sentry-python#481]
Raising `PermissionDenied` in django is a shortcut to returning 403.

This shouldn't be logged by default, since it's normal behaviour. It [does](https://sentry.io/organizations/hobarrera/issues/1163570899/?project=124552&referrer=RegressionActivityEmail) get logged however.

Also, my event has no `logger`, so I'm not even sure how to manually ignore it.

**Comment by untitaker** [comment]
We are only listening on https://docs.djangoproject.com/en/2.2/ref/signals/#got-request-exception and in a regular application this signal doesn't fire on 403s. Here is the code that shortcuts for PermissionDenied: https://github.com/django/django/blob/03dbdfd9bbbbd0b0172aad648c6bbe3f39541137/django/core/handlers/exception.py#L49-L55

Two possibilities come to mind:

1. You have another exception that just happens to be called the same
2. A extension on top of Django triggers this hook. I tested this theory with Django Rest Framework and it seems to work as expected, so I am not sure what that could be.

**Comment by untitaker** [comment]
@WhyNotHugo I am not really sure how to reproduce this.

**Comment by WhyNotHugo** [comment]
> You have another exception that just happens to be called the same

Actually, yes, I've two exceptions with that name:

```python
from rest_framework.exceptions import PermissionDenied as one
from django.core.exceptions import PermissionDenied as two

one == two  # False
```

I didn't have any logs for this issue in the last 90 days, but just confirmed that raising the former results in sentry logging it.

However, I'm raising the DRF exception on a non-DRF view, so I'd say my code is wrong and sentry is right here.

**Comment by WhyNotHugo** [comment]
Thanks for the clues to figuring this one out, sorry for the false lead!

**Comment by untitaker** [comment]
oh, that was unexpected! nice find
