### ISSUE TITLE
Apache Spark integration

### ISSUE THREAD

**Issue by harpaj** [getsentry/sentry-python#491]
With the recently released integration for Apache Beam and the general push of [Sentry for Data Pipelines](https://sentry.io/for/data/) - is there an integration of Sentry with Apache Spark (especially with PySpark) planned?

https://github.com/apache/spark/pull/20151 explicitly mentions that one reason for creating that PR was to make a Sentry integration easier. However, I didn't manage to even find some example code for using Sentry to capture Spark errors, and so far I failed when trying to build an integration using the feature introduced by the PR myself.

**Comment by untitaker** [comment]
We're looking into this but don't want to give out an ETA :) We've just started market research, so to speak.

**Comment by AbhiPrasad** [comment]
Hey @harpaj! We have PR open for a WIP PySpark integration - https://github.com/getsentry/sentry-python/pull/519.

We would love to get some early feedback and thoughts on the Spark integration, please reach out to me at aprasad@sentry.io if you are interested! It would be great to hear how you are using Spark (and how Sentry can best help!).

**Comment by AbhiPrasad** [comment]
The Spark integration is live - https://docs.sentry.io/platforms/python/pyspark/
