### ISSUE TITLE
last_event_id is not cleared after request finish with Flask integration

### ISSUE THREAD

**Issue by kamilglod** [getsentry/sentry-python#493]
I was expecting that `last_event_id` for Flask integration will be assigned to `flask.g` or will have other implementation working in the same way that for another successful request `last_event_id` will be `None`.
 
Currently after `capture_exception`, `last_event_id` returns the same value regardless of there are any error during the request. Is this an expected behaviour or it is a bug?

**Comment by untitaker** [comment]
Hi, which version of the SDK is this? And which wsgi server are you using? While we don't use `flask.g` (because `last_event_id` is not Flask-specific) we use something similar so this should not happen.

**Comment by kamilglod** [comment]
SDK version: 0.11.2
Flask version: 1.0.2
Werkzeug version: 0.15.2

**Comment by untitaker** [comment]
Are you saying you are seeing this behavior with the development server of
Flask, not gunicorn/uwsgi, etc? I would not be able to reproduce that.

Please tell me exact steps you are taking to reproduce the issue.

**Comment by kamilglod** [comment]
Sure, here is an example:

```python
from flask import Flask, escape, request
from sentry_sdk import init as init_sentry, last_event_id
from sentry_sdk.integrations.flask import FlaskIntegration

SENTRY_CONFIG = {
    'dsn': 'xxxx',
}
sentry = init_sentry(**SENTRY_CONFIG)
sentry.integrations = [FlaskIntegration()]

app = Flask(__name__)

@app.route('/exception')
def hello():
    1/0
    name = request.args.get("name", "World")
    return f'Hello, {escape(name)}!'


@app.route('/last-event-id')
def get_last_event_id():
    return str(last_event_id())
```

And I noticed that when I add `integrations` as described in docs (through constructor instead of assigning to property) it works properly. So it's my fault. Question is: is it possible to assign `integrations` after instance creation? My case is that I have one function that creates sentry objects for different projects (some are flask servers, some are long running jobs etc) and some requires `FlaskIntegration()` but not all.

**Comment by untitaker** [comment]
No that's not possible, and I will make the array private or read only to prevent this mistake. (this is really good feedback) I would enable all integrations in all cases, it does not do any harm.

**Comment by kamilglod** [comment]
Ok, @untitaker thanks for quick help, I'm closing this issue as resolved
