### ISSUE TITLE
Create custom tags doesn't work 

### ISSUE THREAD

**Issue by ivancarrancho** [getsentry/sentry-python#501]
Hi, i'm trying to log a new custom tag with the name `project` but in the slack notification just appear the original tags (like logger),

In sentry if I put:
![Sentry](https://user-images.githubusercontent.com/13756563/64977788-b3c22b80-d879-11e9-9f8a-48a91420e8d6.png)

![Slack___capek-dev___Capek___1_nuevo_elemento](https://user-images.githubusercontent.com/13756563/64984881-5504ae00-d889-11e9-8a77-a638feb9d451.png)

* _doesn't work ^_

but if use  a `logger` tag:
![Sentry](https://user-images.githubusercontent.com/13756563/64977825-c3417480-d879-11e9-97ec-c02afce1ca0b.png)

![Slack___capek-dev___Capek](https://user-images.githubusercontent.com/13756563/64984423-75803880-d888-11e9-9551-4724c742abba.png)

* _`logger` is a custom tag, works fine! ^_

## creating a custom tag

*Mode 1*
i'm working on python with flask and try to create the custom tag on that way:
![Untitled-1_—_renovacion-urbana-full-stack](https://user-images.githubusercontent.com/13756563/64977539-372f4d00-d879-11e9-9430-59c87f0b3dba.png)

*Mode 2*
![Untitled-1_—_renovacion-urbana-full-stack](https://user-images.githubusercontent.com/13756563/64977524-30083f00-d879-11e9-8d1e-c5cf025d2963.png)

neither of these cases work for me, what i'm doing bad?

Thanks

**Comment by untitaker** [comment]
where are you actually invoking `configure_scope` and set_tag in your code? Within the view?

**Comment by ivancarrancho** [comment]
> ¿Dónde estás realmente invocando `configure_scope`y set_tag en tu código? Dentro de la vista?

Thanks for answering, is Flask so in the main.py app.

![main_py_—_capek-full-stack](https://user-images.githubusercontent.com/13756563/64985301-2fc46f80-d88a-11e9-8789-b2d30bcbb8eb.png)

**Comment by ivancarrancho** [comment]
Hi, already find the issue:
In the init function, need to put the `environment`

![image (7)](https://user-images.githubusercontent.com/13756563/64998826-40d1a880-d8ab-11e9-8fc7-165fea1beecc.png)

thanks.
