### ISSUE TITLE
lifespan protocol not implemented?

### ISSUE THREAD

**Issue by Trim21** [getsentry/sentry-python#505]
Offical spec https://asgi.readthedocs.io/en/latest/specs/lifespan.html

I'm using uvicorn and fastapi. I originally using [encode/sentry-asgi](https://github.com/encode/sentry-asgi) and these days I found that there is a AsgiMiddleware in sentry-sdk. So i try to start using `sentry_sdk.integrations.asgi.SentryAsgiMiddleware` But I got

```bash
INFO: ASGI 'lifespan' protocol appears unsupported.
```
I got this error in asyncio debug mode:
```
WARNING: Executing <Task pending coro=<Server.serve() running at C:\Users\Trim21\.venv\www\lib\site-packages\uvicorn\main.py:322> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000019878C3C468>()] created at C:\Users\Trim21\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py:391> cb=[_run_until_complete_cb() at C:\Users\Trim21\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py:153] created at C:\Users\Trim21\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py:558> took 1.265 seconds
ERROR: Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "C:\Users\Trim21\.venv\www\lib\site-packages\uvicorn\lifespan\on.py", line 44, in main
    await app(scope, self.receive, self.send)
  File "C:\Users\Trim21\.venv\www\lib\site-packages\starlette\applications.py", line 133, in __call__
    await self.error_middleware(scope, receive, send)
  File "C:\Users\Trim21\.venv\www\lib\site-packages\starlette\middleware\errors.py", line 142, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Trim21\.venv\www\lib\site-packages\starlette\middleware\base.py", line 21, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Trim21\.venv\www\lib\site-packages\starlette\middleware\base.py", line 21, in __call__
    await self.app(scope, receive, send)
  File ".\app\middlewares\log.py", line 12, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Trim21\.venv\www\lib\site-packages\sentry_sdk\integrations\asgi.py", line 71, in _run_app
    span = Span.continue_from_headers(dict(scope["headers"]))
KeyError: 'headers'
```

It's not a http event so there is no `headers` key in scope

env:
```
uvicorn version: 0.8.6
fastapi version: 0.38.1
python version: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
sentry-sdk version: 0.12.1
```

**Comment by untitaker** [comment]
hmm cc @tomchristie.

The middleware in this SDK is a fork of encode/sentry-asgi, with the intent to deprecate sentry-asgi (afaik @tomchristie agreed to this plan). But it seems that both are now maintained?

I would like to keep the one inside the SDK, because I can then build integrations for Channels and other web frameworks on top.

**Comment by untitaker** [comment]
>I got this error in asyncio debug mode:

This seems like a recent regression, and I'll fix that in 0.12.2, sorry about that

**Comment by untitaker** [comment]
0.12.2 has been released yesterday with the crash fixed

**Comment by Trim21** [comment]
@untitaker yeah, I just found that. Thanks for your work.

**Comment by tomchristie** [comment]
> The middleware in this SDK is a fork of encode/sentry-asgi, with the intent to deprecate sentry-asgi (afaik @tomchristie agreed to this plan). But it seems that both are now maintained?

Correct - I'd like to move `encode/sentry-asgi` into archived or something now.

**Comment by untitaker** [comment]
Thanks! Just wanted to make sure

**Comment by untitaker** [comment]
@tomchristie is the lifespan thing something you think we could instrument in Sentry somehow?

**Comment by tomchristie** [comment]
@untitaker I'm not quite sure what that means.

Certainly you could have "shutup" and "shutdown" event types, if that's a thing?

And yes, you could tag any errors that occur during ASGI startup/shutdown messaging against one of those two contexts.

There's also the period in the lifespan context between startup/shutdown, which app frameworks might start using for lightweight clock events, without having to reach for tools like celery, which again, yeah, could be properly tagged - though I'd need to take a more in depth look at sentry's interface as it currently stands.

**Comment by untitaker** [comment]
Nevermind my question, I looked into lifespans and now I believe my
question doesn't make sense.
