### ISSUE TITLE
Memory leak when using celery and django with bulk queries

### ISSUE THREAD

**Issue by MickVermeulen** [getsentry/sentry-python#507]
Hi! Recently I discovered that our celery server kept running out of memory in production. We have a Celery server that fetches ~1.000.000 products from a feed and then bulk-upserts them in batches of 15.000 into our database. As you can imagine, these bulk upsert queries are massive SQL queries: about 15MB each.

For some reason, Django logs these queries, which are then kept in memory by Sentry. This meant that after a run of 1.000.000 products, 1000MB of memory would be used. I know for certain that this leak was caused by Sentry, I used heapy to find the SQL queries in memory and discovered that the massive strings were owned by a Sentry instance.

For now, we have Sentry turned off on our Celery servers and now all memory issues are resolved. Of course, this is not ideal. Sadly, I haven't been able to pinpoint where the memory leak originates from.

Some more info regarding our setup:
- We are running Django with `Debug=False`
- `conn_max_age` is not defined
- Both `gc.collect()` and `django.db.reset_queries()` do not resolve the issue

(Part of) our venv:
```
django==2.1.3
django-elasticsearch-dsl==0.5.1
elasticsearch-dsl==6.1.0
psycopg2-binary==2.7.5
gunicorn==19.9.0
celery==4.3.0
django-celery-beat==1.5.0
django-postgres-extra==1.22
```

We use `django-postgres-extra` for the bulk-upsert operations.

I hope we can resolve this issue such that we can run Sentry again in production!

**Comment by untitaker** [comment]
What version of the sdk is that? We recently released a new version of the SDK that fixes an issue that sounds just like yours (0.12.1)

**Comment by MickVermeulen** [comment]
We use version `sentry-sdk==0.5.1`, I'll update and look if the issue persists!

**Comment by MickVermeulen** [comment]
This update seems to have resolved the issue, what a coincidence that this was fixed yesterday. I'll close the thread, thank you very much for the quick help!
