### ISSUE TITLE
Sentry not logging Gunicorn timeout errors

### ISSUE THREAD

**Issue by hyperknot** [getsentry/sentry-python#510]
We have quite a standard gunicorn setup with the default sync worker with the default 1 thread, running a Python app.

Gunicorn is started with this command line:
```
gunicorn \
    --workers=16 \
    --timeout=120 \
    -b 127.0.0.1:8082 \
    --paste production.ini \
    2>> api-err.log 1>> api-out.log
```

The Python Sentry integration is loaded with the following:
```
import sentry_sdk
from sentry_sdk.integrations.pyramid import PyramidIntegration

sentry_sdk.init(
    dsn="https://xxx@sentry.io/123",
    integrations=[PyramidIntegration()],
    release='1.2.3'
)

config = Configurator(settings=settings)
...
```

The issue is that whenever a Gunicorn worker timeout occurs, it is not logged to Sentry.
The only way we can see that there was a timeout is when we see "[CRITICAL] WORKER TIMEOUT" in api-err.log and the matching error code 499 lines in nginx.log.

It'd be important to log these timeout events to Sentry.

**Comment by untitaker** [comment]
Could you write a python script that contains the same thing as your gunicorn executable, but calls sentry_sdk.init before running gunicorn? Trying to confirm something

**Comment by hyperknot** [comment]
This is the gunicorn executable:

```
#!/opt/conda/bin/python
# -*- coding: utf-8 -*-
import re
import sys

from gunicorn.app.wsgiapp import run

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
````

**Comment by untitaker** [comment]
Yes, could you edit it to call `sentry_sdk.init()` (with your DSN) before it calls `run()`? I believe this could "fix" the problem already.

**Comment by darwinyip** [comment]
Bump on the issue. Similar configuration but with gunicorn + falcon + sentry sdk.

**Comment by aleehedl** [comment]
> Yes, could you edit it to call `sentry_sdk.init()` (with your DSN) before it calls `run()`? I believe this could "fix" the problem already.

@untitaker I tried this but saw no effect :shrug:

**Comment by lminer** [comment]
I'm having this problem as well. I can't log any performance stats using gunicorn/falcon. Is there a work around?

**Comment by antonpirker** [comment]
I have now reproduced the problem with the information above. I have a Falcon project running under Gunicorn:
https://github.com/antonpirker/sample-projects-for-sentry/tree/main/falcon-project

I run gunicorn like this:
```bash
gunicorn \
    --workers=16 \
    --timeout=1 \
    -b 127.0.0.1:8000 \
    falcon-project:app
```
In my view I have a `time.sleep(2)` so the sample project always runs into a timeout.

To capture the Gunicorn Timeout you need to change the gunicorn executable. This is how you do it:

* Find the gunicorn executable script:
```bash
$ which gunicorn
/Users/antonpirker/code/sample-projects-for-sentry/falcon-project/.venv/bin/gunicorn
$ _
```

* Edit this file and Init Sentry SDK in it. Before it looks something like this: 
```python
#!/Users/antonpirker/code/sample-projects-for-sentry/falcon-project/.venv/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from gunicorn.app.wsgiapp import run

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
``` 

* Edit this file and Init Sentry SDK in it. After editing and initializing the Sentry sdk it looks like this:
```python
#!/Users/antonpirker/code/sample-projects-for-sentry/falcon-project/.venv/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from gunicorn.app.wsgiapp import run

import os
import sentry_sdk
from sentry_sdk.integrations.falcon import FalconIntegration
sentry_sdk.init(
   dsn=os.environ.get('SENTRY_DSN', None),
   integrations=[FalconIntegration()]
)

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
```

* Now start your project with the same Gunicorn command
* The timeout errors should end up in your Sentry Issues:
<img width="1889" alt="Screenshot 2022-02-21 at 11 45 13" src="https://user-images.githubusercontent.com/202325/154941885-10068849-7497-4548-850e-6ba7672b8c79.png">

This should solve this issue.
