### ISSUE TITLE
Invalid project in DSN 2019

### ISSUE THREAD

**Issue by chicks-net** [getsentry/sentry-python#528]
I'm trying to run the sample code to get started with Sentry in Python, but even with just calling `init()` I get `sentry_sdk.utils.BadDsn: Invalid project in DSN ('Internal')`.  In looking at the code it seems this field is expected to be numeric, but with Sentry 8.21 I have named non-numeric projects.  I also get this error when I try a non-Internal project: `sentry_sdk.utils.BadDsn: Invalid project in DSN ('Firefly')`.  So how can I find the numeric project ID or get sentry-python to accept a non-numeric one?

This is not the same issue as #87 since my URL in `/manage/settings/` has no slash on the end.

Versions:
* sentry-sdk 0.12.3
* python 3.6.8
* pipenv 2018.11.26
* Sentry 8.21

**Comment by untitaker** [comment]
I strongly recommend updating to the latest version of Sentry (9.1.2). I don't know what the issue is with Sentry 8, but it seems you're passing something that is not a DSN at all into the SDK.

**Comment by chicks-net** [comment]
So projects can be non-numeric?

**Comment by untitaker** [comment]
@chicks-net The DSN contains the numeric project ID and some credential (public key, optionally secret key). I honestly don't know where you can find the DSN for your project in Sentry 8.
