### ISSUE TITLE
How do I send a manual exception in python?

### ISSUE THREAD

**Issue by abkiran** [getsentry/sentry-python#534]
When I'm using a try-catch block, when it fails in the try, I want manual send the exception info using sentry. 

Exactly like this in Java
https://docs.sentry.io/clients/java/usage/

```
try {
            unsafeMethod();
        } catch (Exception e) {
            // This sends an exception event to Sentry.
            sentry.sendException(e);
        }
```

**Comment by untitaker** [comment]
https://docs.sentry.io/platforms/python/#capturing-errors
