### ISSUE TITLE
Bring back support for including stacktrace

### ISSUE THREAD

**Issue by nijel** [getsentry/sentry-python#537]
Raven had support for including stacktrace from logging by passing `stack` parameter. In sentry_sdk it accepts only boolean and it's not useful in case when logging includes stack trace from other thread.

This is approach used by [dogslow](https://pypi.org/project/dogslow/) to report slow requests. It worked fine with raven but with sentry_sdk the stacktraces are gone, making the reports pretty much useless.

**Comment by untitaker** [comment]
you can pass `exc_info=True` for non-exception logs to attach a stacktrace. Hope that helps

**Comment by nijel** [comment]
That includes stacktrace from the current thread, what is not helpful at all in this case.

**Comment by untitaker** [comment]
Ah, I see what dogslow does now. So to be clear, we do not want to bring back the logging parameter specifically, for the reasons listed here: https://github.com/getsentry/sentry-php/pull/844#issuecomment-510120197

I believe we should have an API for sending arbitrary stacktraces. Since dogslow already had raven-specific integration I believe it would be ok if the solution includes changes in dogslow?

**Comment by nijel** [comment]
Yes, that should not be a problem (I'm not sure how much actively maintained the code currently is, but in worst case I can fork it).

What would be even better is ability to use also scope the from other thread, so that all request related data is collected as well.

**Comment by untitaker** [comment]
>What would be even better is ability to use also scope the from other thread, so that all request related data is collected as well.

This is really tricky. If you have control over that thread you're monitoring you could take `Hub.current` in that thread and pass it off to your monitoring thread. Then you can call `hub.capture_event()` on it and all scope data will be included.

The stacktrace thing is tricky though. We have a bunch of stuff in `sentry_sdk.utils` that you could already cobble together (already used by the logging integration for example), but it's not stable API.

I wish there was a way to interrupt the monitored thread such that you can run the entire error capturing in the "right" thread.

**Comment by intgr** [comment]
FYI I have created a fork of dogslow -- `dogslow-sentry` -- which uses Sentry APIs and some traceback trickery to include the full stack trace, and Sentry request context, fingerprint for issue grouping, breadcrumbs etc.

https://github.com/intgr/dogslow-sentry
