### ISSUE TITLE
Problem with sending data with exceptions on Sentry

### ISSUE THREAD

**Issue by kurama-cube** [getsentry/sentry-python#538]
Hi there.
I have a problem with python Sentry SDK
When I want to capture an exception with the capture_exception method,  I set a context with set_context and pass all the extra data to it as a dict and in the sentry web panel, I can't find fields which have None values or in some exceptions, some fields are missing, Sentry will remove these fields. how can I send a JSON object with an exception?

**Comment by untitaker** [comment]
@kurama-cube please use the forum as discussed in https://github.com/getsentry/sentry/issues/15215
