### ISSUE TITLE
0.12.0 breaks Django function-based middleware

### ISSUE THREAD

**Issue by schinckel** [getsentry/sentry-python#539]
Similar to #504, but a different stack trace:

    AttributeError: 'method-wrapper' object has no attribute '__module__'
      File "django/core/handlers/exception.py", line 41, in inner
        response = get_response(request)
      File "functools.py", line 33, in update_wrapper
        setattr(wrapper, attr, getattr(wrapped, attr))

According to sentry (kind-of neat how I get this in this case...), the `get_response` object at that point in time is `<sentry_sdk.integrations.django.middleware.AuditMiddleware object at 0x7f37d64d4450>`.

This problem only occurs in 0.12.0 and newer, and with Django 1.11.x

**Comment by untitaker** [comment]
>`sentry_sdk.integrations.django.middleware.AuditMiddleware`

I am highly confused, such a class does not exist, so I believe the repr is buggy because of our monkeypatch. Could you figure out where AuditMiddleware really comes from? There must be something peculiar about it that makes our monkeypatch break the world.

**Comment by schinckel** [comment]
Ah, I do have an AuditMiddleware installed. 

I am running some tests to see if this is triggered by the middleware span stuff, but I need to wait until tomorrow to get it onto our staging environment.

**Comment by schinckel** [comment]
It appears that it is not directly caused by the middleware span feature. I'll have to try to get the error to occur in development to be able to troubleshoot it further.

**Comment by schinckel** [comment]
FWIW, the `AuditMiddleware` looks like:

    def AuditMiddleware(get_response):
        def middleware(request):
            from .receivers import set_audit_variables
            set_audit_variables(request)
            return get_response(request)

        return middleware

So, it's different to the rest of my middleware that all inherit from `django.utils.deprecation.MiddlewareMixin`.

**Comment by schinckel** [comment]
So, it seems that using a middleware function is the problem. I'll try to work up a test case.

**Comment by schinckel** [comment]
Okay, I have a failing test at https://github.com/schinckel/sentry-python/tree/django-function-middleware

For reference, both types of middleware are documented/supported by django: https://docs.djangoproject.com/en/2.2/topics/http/middleware/#writing-your-own-middleware

There's no mention of a restriction on middleware in the documentation: https://docs.sentry.io/platforms/python/django/

**Comment by schinckel** [comment]
And, last thing for now is that the stack trace from running tests is slightly more helpful, I believe:

    exception.py               135 ERROR    Internal Server Error: /message
    Traceback (most recent call last):
      File "/Users/matt/Development/sentry-python/.tox/py2.7-django-1.11/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
        response = get_response(request)
      File "/Users/matt/Development/sentry-python/sentry_sdk/integrations/django/middleware.py", line 119, in __call__
        self._call_method = f = _get_wrapped_method(self._inner.__call__)
      File "/Users/matt/Development/sentry-python/sentry_sdk/integrations/django/middleware.py", line 67, in _get_wrapped_method
        @wraps(old_method)
      File "/Users/matt/.pyenv/versions/2.7.16/lib/python2.7/functools.py", line 33, in update_wrapper
        setattr(wrapper, attr, getattr(wrapped, attr))
    AttributeError: 'method-wrapper' object has no attribute '__module__'

**Comment by untitaker** [comment]
thanks @schinckel I will fix this asap!
