### ISSUE TITLE
Captured logs don't include file path and line number

### ISSUE THREAD

**Issue by karolinepauls** [getsentry/sentry-python#545]
It seems the only way to capture logs' origin lines is [attach_stacktrace](https://docs.sentry.io/error-reporting/configuration/?platform=python#attach-stacktrace), which seems rather heavy-handed.

LogRecord objects already contain source file and source line data. It should be very cheap to extract them.

My memory may be tricking me but didn't filepath:lineno get captured in Raven?
 
Looks like `pathname` didn't used to be removed in [Raven](https://github.com/getsentry/raven-python/blob/8e7de70c5f099600480e08bdc708041dc581929e/raven/handlers/logging.py#L22-L26) but is in [sentry_sdk](https://github.com/getsentry/sentry-python/blob/639f2ba5c9f3ec7bc4a601b26196e0b2a72e12a5/sentry_sdk/integrations/logging.py#L130)

It's trivial to add these in `before_send` - for now i've done:
```
try:
    log_record = hint['log_record']
except KeyError:
    return event

event.setdefault('tags', {})['pathname'] = log_record.pathname
event.setdefault('extra', {})['origin'] = '{}:{}'.format(log_record.pathname, log_record.lineno)

return event
```

**Comment by untitaker** [comment]
I see! I didn't think of it this way when porting the logic from Raven, I simply believed that the omission from the list was an error.

I believe it would be nicer to construct a stacktrace out of this information if possible, if `attach_stacktrace` is not set.

**Comment by karolinepauls** [comment]
I don't think it's possible to get the stack trace from the LogRecord in Python 2. In Python 2, maybe - there's `sinfo`, though I've never used it myself. https://docs.python.org/3.8/library/logging.html#logging.LogRecord

**Comment by antonpirker** [comment]
As this is a very old Issue I will close this. 

If you came across this Issue and want to help fixing it, please create a new Issue and link to this one. Thanks!
