### ISSUE TITLE
Bytes Objects serialized as list of integers in Python 3

### ISSUE THREAD

**Issue by xvillaneau** [getsentry/sentry-python#550]
Using `sentry_sdk` version 0.13.0 in Python 3.7.3, strings encoded as `bytes` objects are serialized as lists of integers:

```
>>> from sentry_sdk.serializer import serialize
>>> serialize(b'123abc')
[49, 50, 51, 97, 98, 99]
>>> serialize(b'123abc', should_repr_strings=True)
['49', '50', '51', '97', '98', '99']
```

This doesn't seem like the expected behavior, instead it could be:
```
>>> serialize(b'123abc')
'123abc'
>>> serialize(b'123abc', should_repr_strings=True)
"b'123abc'"
```

I was able to reproduce the issue with Python 3.7.3, 3.6.7, 3.5.6 and 3.4.10. The serialization seems to behave properly with Python 2.7.

**Comment by untitaker** [comment]
I would like this to be `"b'...'"` on Python 3 and `"'...'"` on Python 2.

**Comment by xvillaneau** [comment]
It looks like that's already the case:
```
Python 2.7.15 (default, Mar 21 2019, 11:27:54) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sentry_sdk.serializer import serialize
>>> serialize('123abc')
u'123abc'
>>> serialize('123abc', should_repr_strings=True)
u"'123abc'"
```

**Comment by untitaker** [comment]
Right, the bugfix would affect py3 only. Do you want to make a PR? Otherwise I'll do it next week

**Comment by xvillaneau** [comment]
I'm currently working on it, the fix for the serializer itself should be pretty simple, it's just about making sure we're testing for `bytes`.

The bigger challenge is to fix `safe_repr` so that it escapes non-printable characters. Thankfully `repr` in Python 3 has the good behavior, but fixing this in Python 2 without breaking support for non-latin characters is proving to be challenging.

**Comment by xvillaneau** [comment]
I'm still working on `safe_repr` at the moment. The problem with this tool is that does not safely serialize control characters such as `\n` or `\x00`.

With Python 2.7.15:
```py
>>> from sentry_sdk.utils import safe_repr
>>> safe_repr(u'лошадь\n\x00')
u"u'\u043b\u043e\u0448\u0430\u0434\u044c\n\x00'"
>>> safe_repr(u'лошадь\n\x00'.encode('utf-8'))
u"'\xd0\xbb\xd0\xbe\xd1\x88\xd0\xb0\xd0\xb4\xd1\x8c\n\x00'"
```

With Python 3.7.3:
```py
>>> from sentry_sdk.utils import safe_repr
>>> safe_repr(u'лошадь\n\x00')
"'лошадь\\n\\x00'"  # This is correct
>>> safe_repr(u'лошадь\n\x00'.encode('utf-8'))
"b'Ð»Ð¾Ñ\x88Ð°Ð´Ñ\x8c\n\x00'"
```

Fixing this for Python 3 is very straightforward, all we need is `repr`. For Python 2 however that would break the current behavior where non-ascii characters are preserved in the output:
https://github.com/getsentry/sentry-python/blob/b784d63d059cecd3b2dc20a6f865d7a47b6ebdad/tests/utils/test_general.py#L35-L36

I can think of three ways to go at this issue:
1. Only fix the behavior in Py3, leave the Py2 behavior (and bugs) as-is
2. Write a custom new `repr` function for Py2 that back-ports the Py3 behavior (outputs unicode, and only escape non-printable characters). This might come at the cost of performance, unless there's a binary out there that we are willing to add to the dependencies.
3. Just use the `repr` output as-is in all cases, which will be a regression for Python 2.

What's the best option, given the functional priorities of the SDK? Is this worth fixing as a separate issue maybe?

**Comment by untitaker** [comment]
I think it's best to only fix those bugs in Py3.

**Comment by xvillaneau** [comment]
Good, I'll do that, thanks for the guidance!
