### ISSUE TITLE
Why is tornado.application logger ignored?

### ISSUE THREAD

**Issue by blacelle** [getsentry/sentry-python#553]
It appears Sentry do not report any logs from tornado.application logger

https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/tornado.py#L53
    ignore_logger("tornado.application")

However, it seems the default logger used by Tornado to report unhandled exceptions:

https://github.com/tornadoweb/tornado/blob/682ff8dec2d095b339b62d875252be932ae4a5f2/tornado/web.py#L1762

    def log_exception(
        self,
        typ: "Optional[Type[BaseException]]",
        value: Optional[BaseException],
        tb: Optional[TracebackType],
    ) -> None:
        """Override to customize logging of uncaught exceptions.
        By default logs instances of `HTTPError` as warnings without
        stack traces (on the ``tornado.general`` logger), and all
        other exceptions as errors with stack traces (on the
        ``tornado.application`` logger).
        .. versionadded:: 3.1
        """
        if isinstance(value, HTTPError):
            if value.log_message:
                format = "%d %s: " + value.log_message
                args = [value.status_code, self._request_summary()] + list(value.args)
                gen_log.warning(format, *args)
        else:
            app_log.error(  # type: ignore
                "Uncaught exception %s\n%r",
                self._request_summary(),
                self.request,
                exc_info=(typ, value, tb),
            )

How are we supposed to propagate uncaught exceptions in a Tornado based application to Sentry with Tornado integration?

Thanks

**Comment by untitaker** [comment]
The Tornado integration hooks into tornado via other means to handle uncaught exceptions. Specifically we monkeypatch `log_exception` with our own version that reports the exception and calls the old version.

Generally we ignore loggers that have stringified stacktraces logged on them, but this does not seem to be the case here. I can't remember the reason in this specific instance.

I believe we could change the tornado integration to remove this `ignore_logger` call, and perhaps even rely on the logger for crash reporting instead of the monkeypatching.

Is this currently a problem for you?

**Comment by blacelle** [comment]
Our Python developper suggests to drop Sentry TornadoIntegration ; I would rather keep it but I would expect it to capture uncaught exceptions without additional coding on our part.

 -> The workaround is easy (dropping TornadoIntegration) but not satisfying.

**Comment by untitaker** [comment]
The TornadoIntegration is supposed to capture uncaught exceptions, just not via the logging mechanism. Is your problem that you don't see crash reports in Sentry when enabling the integration?

**Comment by blacelle** [comment]
Sorry for not having been clear about this: yes, we do not receive any report in Sentry. I asked our python developper to check locally why the monkeypatch did not work.

**Comment by untitaker** [comment]
when having disabled the integration, could you post a link to an issue that is not captured otherwise?

**Comment by blacelle** [comment]
This is on a closed-source project. I could send the json of the report by another mean.

**Comment by untitaker** [comment]
could you post an abbreviated version of the json here? I only care about the exception message and non-app frames in any case

**Comment by blacelle** [comment]
```
KeyError: 'SomeMessage'
  File "tornado/web.py", line 1697, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "v2/handlers/custom.py", line 45, in get
    someVar = someValue
```



```
tornado/web.py in _execute at line 1697
                    await self.request._body_future
                except iostream.StreamClosedError:
                    return
            method = getattr(self, self.request.method.lower())
            result = method(*self.path_args, **self.path_kwargs)  <-------------
            if result is not None:
                result = await result
            if self._auto_finish and not self._finished:
                self.finish()
        except Exception as e:
```


Name | sentry.python
Version | 0.13.2

tornado | 6.0.3
tornado-http-auth | 1.1.1

**Comment by untitaker** [comment]
Hmm. There should be a log message attached in addition to this. Above the
stacktrace.

**Comment by blacelle** [comment]
My bad:

```
Uncaught exception GET /2.0/azaz/XXX?YYY= (127.0.0.1)
"HTTPServerRequest(protocol='http', host='localhost:1234', method='GET', uri='/2.0/azaz/XXX?YYY=', version='HTTP/1.1', remote_ip='127.0.0.1')"
```

**Comment by untitaker** [comment]
That's troubling. It does seem like the monkeypatch doesn't work. Where are you initializing the SDK? Do you override `log_exception` in a subclass?

**Comment by cgiraudeau** [comment]
We're initializing the Sentry SDK in the __main__ part of our entry script.  
We don't override log_exception.  
But We've overridden the log_function which we set to Application.log_request.

**Comment by cgiraudeau** [comment]
Removing the overridden log_exception fixed our issue.  
Thank you for your time.

**Comment by untitaker** [comment]
Ok, we will fix this. You should not have to fix your code because of this, just as workaround.

**Comment by untitaker** [comment]
Actually @cgiraudeau , do you call the old `log_exception` from within your override? Or do you only run your code

**Comment by cgiraudeau** [comment]
I was only running my code without calling the old log_exception.  
I had a try keeping my overridden log_exception with a call to the old log_exception and it was successful. 500 errors were reported to sentry.  
So I think it's not a bug from yours. Maybe adding a line about this in the documentation would be helpful.  
Again thank you for your time.

**Comment by untitaker** [comment]
we re-enabled the logger for now
