### ISSUE TITLE
[celery integration] before_send function executed twice

### ISSUE THREAD

**Issue by gerazenobi** [getsentry/sentry-python#555]
Doing a simple test with sentry and celery integration I see the function `before_send`
gets executed twice when an exception is raised while the `on_failure` celery task mechanism gets executed correctly once.

Setup:
```python
    # within my make_celery() function to create the celery app

    def before_send(event, hint):
        print('before_send celery integration')
        return event

    sentry_sdk.init(dsn=url, integrations=[CeleryIntegration(), SqlalchemyIntegration()], before_send=before_send)
```
`on_failure` celery callback handler
```python
def on_failure(task, exc, task_id, args, _, exception_info, **__):
    logger.error("on_failure error print")
```
 celery task:
```python
@celery.task(bind=True, name="test_sentry_integration", on_failure=on_failure, ignore_result=True)
def test_sentry_integration(_, message):
    raise Exception(message)
```
output:
```
[2019-11-15 11:02:13,148: WARNING/ForkPoolWorker-1] test the sdk
[2019-11-15 11:02:13,152: WARNING/ForkPoolWorker-1] before_send celery integration
2019-11-15 11:02:13,159::comfortmanager.common.tasks::ERROR::on_failure error print
[2019-11-15 11:02:13,161: WARNING/ForkPoolWorker-1] before_send celery integration
[2019-11-15 11:02:13,161: ERROR/ForkPoolWorker-1] Task test_sentry_integration[2f5848b3-1e12-4a0d-92e2-0b4dec63e7c8] raised unexpected: Exception('test the sdk',)
```

Versions:
```
celery 4.3.0
sentry-sdk 0.13.2
```

**Comment by untitaker** [comment]
`logger.error` will create a sentry event. My theory is that you get `before_send` for your celery crash, and then for `"on_failure error print"`.

**Comment by gerazenobi** [comment]
Thanks for the rapid response! You were right, by removing the `logger.error` I get the expected output for the test (which aims to produce 1 event):
```
[2019-11-15 12:29:40,671: WARNING/ForkPoolWorker-1] test the sdk
[2019-11-15 12:29:45,694: WARNING/ForkPoolWorker-1] before_send celery integration
2019-11-15 12:29:59,481::comfortmanager.common.tasks::INFO::on_failure error print
[2019-11-15 12:29:59,484: ERROR/ForkPoolWorker-1] Task test_sentry_integration[82c78b19-ae00-4ed3-8be1-8a4788d9e11b] raised unexpected: Exception('test the sdk',)
```
I was not aware of the `logging` integration! By quickly reading at the [documentation](https://docs.sentry.io/platforms/python/logging/) I understand that this integration, by default, will only produce sentry events when logging at the `error` level, though I don't fully understand what happens by default with the option `level=logging.INFO` for breadcrumbs: let's say I am logging info statements in `module a` and later in the code, in an unrelated situation, an exception happens in `module b` the will ultimately be sent to sentry, would the `info` logs be involved in this exception ?

**Comment by untitaker** [comment]
`level` controls creation of breadcrumbs (that is, writing them into a local "scrollback" buffer) and `event_level` controls creation of events. So yes, the INFO logs may appear in the event. However, we wipe breadcrumbs between celery tasks and between HTTP requests (depending on framework), and the buffer is per-thread. So they should be somewhat related to the crash.

**Comment by gerazenobi** [comment]
I see, thanks for the clarifications 👍

**Comment by untitaker** [comment]
Glad to be of help!
