### ISSUE TITLE
TypeError using SentryAsgiMiddleware with FastAPI/Starlette app

### ISSUE THREAD

**Issue by Stigjb** [getsentry/sentry-python#556]
I cannot get `SentryAsgiMiddleware` to work with our FastAPI app. We tried to follow the example in the [Sentry docs](https://docs.sentry.io/platforms/python/asgi/), so the app module basically looks like this:

```python
from fastapi import FastAPI
from sentry_sdk.integrations.asgi import SentryAsgiMiddleware
...
app = FastAPI()

@app.post()
...

app = SentryAsgiMiddleware(app)
```

This gives an error on all requests, see the following stack trace:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
    await instance(receive, send)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/asgi.py", line 54, in run_asgi2
    scope, lambda: self.app(scope)(receive, send)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/asgi.py", line 93, in _run_app
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/asgi.py", line 90, in _run_app
    return await callback()
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/asgi.py", line 54, in <lambda>
    scope, lambda: self.app(scope)(receive, send)
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
```

Library versions:

- python==3.7.5
- sentry-sdk==0.13.2
- uvicorn==0.10.8
- fastapi==0.42.0
- starlette==0.12.9

**Comment by untitaker** [comment]
It seems like uvicorn might inspect the function signature to figure out which ASGI version to use. Our function signature is `*args, **kwargs`, because we choose the ASGI version depending on how many parameters we are called with.

Could you try setting this option: https://www.uvicorn.org/settings/#application-interface (try all values except auto)

**Comment by Stigjb** [comment]
We run the server with `gunicorn` and `uvicorn.workers.UvicornWorker`, which makes it a bit inconvenient to change options in Uvicorn. We found a suggestions to subclass the `UvicornWorker` to change the config, will try that and report back.

**Comment by Stigjb** [comment]
The service is running now, after specifying ASGI3 interface using the following worker class:

```python
from uvicorn.workers import UvicornWorker


class GunicornUvicornWorker(UvicornWorker):
    CONFIG_KWARGS = {"loop": "uvloop", "http": "httptools", "interface": "asgi3"}
```

**Comment by untitaker** [comment]
ok we will fix this in the sentry sdk in any case. thanks for reporting!

**Comment by untitaker** [comment]
@Stigjb could you try out https://github.com/getsentry/sentry-python/pull/557 while reverting your workaround?

**Comment by Stigjb** [comment]
I deployed the project using the standard UvicornWorker and the PR branch at #557, and it worked fine! 👍

**Comment by Stigjb** [comment]
We really appreciate the quick response! When is the next release planned?

**Comment by untitaker** [comment]
@Stigjb sometime this week

**Comment by untitaker** [comment]
0.13.3 has been released, sorry for the delay
