### ISSUE TITLE
Question: Scrub sensitive variables in client side

### ISSUE THREAD

**Issue by Odelya** [getsentry/sentry-python#558]
I would like to scrub sensitive variables in client side.

```
sentry_sdk.init(
    dsn=settings.get('SENTRY_DSN', ""),
    before_breadcrumb=truncate_breadcrumb_message,
    with_locals=False,
    integrations=[FlaskIntegration()],
    before_send=sanitize_sentry_event,
)

def sanitize_sentry_event(event, hint):
    pass

def truncate_breadcrumb_message(crumb, hint):
    pass

def raise_execption(password):
    auth = 5
    raise Exception()
```

I am not sure how to scrub the local variables sent to Sentry in the methods `sanitize_sentry_event` and `truncate_breadcrumb_message` can you please help?

**Comment by untitaker** [comment]
`event` is a JSON payload that contains the same exact JSON you see in the "JSON" download in Sentry's UI. So you have a event like this:

```json
{
  "exception": {
    "values": [
      {
        "stacktrace": {
          "frames": [
            {"vars": ...}
          ]
    ]
  }
}
```

And you want to remove `vars`, you need to do this:

```
def sanitize_sentry_event(event, hint):
    for exception in event.get("exception", {}).get("values", {}):
        for frame in exception.get("stacktrace", {}).get("frames", []):
            frame.pop("vars", None)

    for exception in event.get("threads", {}).get("values", {}):
        for frame in exception.get("stacktrace", {}).get("frames", []):
            frame.pop("vars", None)


    return event
```

You probably want to wrap the entire function body with a try-except. If the function raises an exception the event is dropped. Make sure to test this using `init(debug=True)` to see all exceptions your `before_send` hook might throw

**Comment by untitaker** [comment]
I see you posted the same question on stackoverflow. Please choose one, not both.
