### ISSUE TITLE
aiohttp4.0.0a1 integration error

### ISSUE THREAD

**Issue by Fogapod** [getsentry/sentry-python#560]
I'm running `aiohttp==4.0.0a1` and `sentry-sdk==0.13.2` on python 3.8.
Each request causes the folowing exception:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 414, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 92, in sentry_app_handle
    return await asyncio.get_event_loop().create_task(inner())
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 66, in inner
    weak_request = weakref.ref(request)
TypeError: cannot create weak reference to 'Request' object
```
Was something changed in aiohttp that prevents current integration from working?

**Comment by untitaker** [comment]
Possibly. We will fix this once there is a stable release of aiohttp 4 :)

**Comment by Fogapod** [comment]
Looks like [this commit](https://github.com/aio-libs/aiohttp/commit/c6e40e78ae8de51c02b5a17b8e5e882c910d3770#diff-6e3c6d0970cb316846993e9d988175fd) broke integration.
Request class uses `__slots__` now and can't be weak referenced.

**Comment by untitaker** [comment]
It's fine, we can work around it too. This was just useful to avoid using too much memory, we can probably hold a strong reference as well.

**Comment by untitaker** [comment]
@Fogapod wow, just looked back into this... thanks for tackling this!

**Comment by Fogapod** [comment]
There is a fix in aiohttp master, it will be resolved in the next release
