### ISSUE TITLE
sentry-sdk skipes None parameters in request

### ISSUE THREAD

**Issue by syurchenko** [getsentry/sentry-python#567]
In my django app I have view which accepts 3 parameters in POST request: login, password, device_id.
If code in view crashes somewhere while processing I see only 2 parameters in sentry (body&curl).
Bug is caused to serialisation issue with None values.
Example curl without bug (device_id is not None):

`curl -v -X POST -H "Accept: application/json" --data "{\"username\":\"000\",\"password\":\"qwerty\",\"device_id\":\"iphone\"}" "http://my_host/api/auth/login/"` 

in sentry I see:
`{
device_id: iphone, 
password: [Filtered], 
username: 000
}`

Example curl with bug (device_id is None):
`curl -v -X POST -H "Accept: application/json" --data "{\"username\":\"000\",\"password\":\"qwerty\",\"device_id\":null}" "http://my_host/api/auth/login/"`

My code has crashed. 
In sentry I see:

`{
password: [Filtered], 
username: 000
}`

but I actually have sent **3 parameters in body**!

Expected behaviour in sentry:
`{
device_id: None,
password: [Filtered], 
username: 000
}`

[Merge request 566](https://github.com/getsentry/sentry-python/pull/566)

Several tests fail in my MR because None values appeared in assertion statements, but MR fixes problem with body parameters.
So I have a question to contributors: should I fix all tests to add None values or I did something wrong in my MR and None values are expected to be skiped for some reasons.
As I see in failed tests many None values are really useless but in my case they are necessary. Also there is no separation in serialisation code between this cases (serialising of body params and some others).
I need your advice to complete my MR.

**Comment by untitaker** [comment]
@syurchenko I think it's better to update all the code that unnecessarily emits `None` rather than updating the assertions.

You could also change `_should_repr_strings` to return `True` for `request.data` path. This is a drastic behavior change but preserves `None` (as string in JSON). I wonder what that would look like in the UI

**Comment by syurchenko** [comment]
![image](https://user-images.githubusercontent.com/1917493/69633220-d5e9de00-1060-11ea-8f48-d90b2e630fb3.png)

In UI everything looks good.
All tests are fixed.
@untitaker take a look please
