### ISSUE TITLE
Ignoring KeyboardInterrupt

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry-python#581]
Hi there,

Is there a standard way to ignore Ctrl-C ? We have a project that has many such errors and they are not that interesting. Should we just override the SIGINT signal handler the default way, which will make sentry ignore the exception ?

Thanks !

**Comment by Kevin-Cherish** [comment]
`ignore_errors = [KeyboardInterrupt]`
`sentry_sdk.init(dsn, ignore_errors=ignore_errors)`

**Comment by bsergean** [comment]
That solves it. Thanks @Kevin-Cherish !

**Comment by untitaker** [comment]
Thanks @Kevin-Cherish!
