### ISSUE TITLE
AwsLambdaIntegration and Scope?

### ISSUE THREAD

**Issue by flyinbutrs** [getsentry/sentry-python#582]
When using this SDK with the `AwsLambdaIntegration`, the SDK is performing some sort of magic to create scope on the lambda handlers. The question is, with that, is there a global method to add tags to the current scope, or do I need to create a new scope? The documentation isn't exactly clear. It seems like I should be able to do it without creating a separate scope, but I'm not sure how.

**Comment by untitaker** [comment]
Please refer to https://docs.sentry.io/enriching-error-data/context/?platform=python#tagging-events

You do not have to create another scope, you have to mutate the existing one
