### ISSUE TITLE
Sentry django integration not catching all 500

### ISSUE THREAD

**Issue by Jihadik** [getsentry/sentry-python#590]
In continuation of [this thread](https://forum.sentry.io/t/sentry-not-picking-up-all-500-errors/2099/8):

There were a couple of exceptions in DRF serializers which were not caught by Sentry. It looks like a known issue.
1. How to resolve the issue quickly? Write my own middleware? Any examples?
2. How to resolve the issue in the long term, so other users won't hit it?

**Comment by Jihadik** [comment]
@untitaker, could you take a look please, as I'm following your advice and posting it as an issue. Thanks!

**Comment by denizdogan** [comment]
I'm suspecting I have the same problem and if it's true, then it's extremely critical that we fix this.

```python
    sentry_sdk.init(
        dsn=os.environ.get("SENTRY_DSN"),
        integrations=[DjangoIntegration(), CeleryIntegration(), RedisIntegration()],
        send_default_pii=True,
    )
```

We recently switched from Rollbar to Sentry, so this is kind of disappointing. :(

**Comment by untitaker** [comment]
So there are multiple issues here: 

* In the original thread somebody said their errors from requests made by Slack are not showing up. Please go to your project settings and disable [Inbound Filters](https://docs.sentry.io/accounts/quotas/#inbound-data-filters), specifically the web crawlers filters.

* The SDK may have crashed internally. Please run `init()` with `debug=True` as keyword argument, maybe this starts printing out errors.

**Comment by Jihadik** [comment]
My issue was resolved. Our sentry was a bit misconfigured and it was crashing in post processing when getting exceptions. Feel free to close the issue.

**Comment by untitaker** [comment]
ok @denizdogan please open a new issue with more information
