### ISSUE TITLE
No stacktrace after migrating from raven to sentry-python (OSError)

### ISSUE THREAD

**Issue by marcelolima** [getsentry/sentry-python#592]
Hello

After migrating from `raven-python` to `sentry-python`, we noticed that one type of issue ("OSError", probably raised by uwsgi) started to appear without stacktrace/logging information in sentry. All we get is:

![image](https://user-images.githubusercontent.com/3869097/72537765-ff630100-387c-11ea-9aaa-fdbbfff99a12.png)

Is there some configuration we are missing? Before, with raven-sdk, we could see the stacktrace

Thanks in advance
Marcelo

**Comment by untitaker** [comment]
How did that error appear in Raven?

**Comment by marcelolima** [comment]
Not sure how it appeared in Raven. Maybe because it had the log handler?

Not sure if relevant, but this is the Breadcrumbs section:
![image](https://user-images.githubusercontent.com/3869097/72545416-4820b700-3889-11ea-91ad-07c180baaa29.png)

**Comment by denizdogan** [comment]
I have the exact same problem. Same OSError, same lack of stack trace, same git log command, same Python 3.7, etc.

**Comment by untitaker** [comment]
Please refer to https://stackoverflow.com/a/45393743/1544347.

This is a real error happening. I am still wondering which stacktrace you saw with raven. It seems there is no stacktrace even in uwsgi output.
