### ISSUE TITLE
0.8.0 -> 0.13.4 Performance Regression

### ISSUE THREAD

**Issue by HakShak** [getsentry/sentry-python#594]
We are still investigating, but it seems #368 has regressed as we are seeing large CPU spikes during nominal exception reporting in production environments. It looks like nuanced changes to `sentry_sdk/serializer.py` might be the culprit.

Since https://github.com/getsentry/sentry-python/releases/tag/0.13.5 or https://github.com/getsentry/sentry-python/releases/tag/0.14.0 don't seem to address any performance issues we may have to revert back to 0.8.0 in the mean time.

**Comment by untitaker** [comment]
My best guess is that the regression happened in 0.12.3. Could you test preceding/succeeding versions such as 0.12.2 and 0.13.0 to confirm?

**Comment by Xamber** [comment]
Good morning, <>!

I have been investigating our problem with CPU and I hope I have found the issue.
So I would like to share my investigation. I tested script with two versions 0.8.0 and 0.13.3.

I used next code for testing:
import sentry_sdk
import datetime


```python
class TestException(BaseException):
    pass


sentry_sdk.init()


class Timer():
    def __enter__(self):
        self.start = datetime.datetime.now()

    def __exit__(self, exc_type, exc_val, exc_tb):
        print("\n\n")
        print(datetime.datetime.now() - self.start)


print("Sentry_SDK_VERSION", sentry_sdk.consts.VERSION)
f = open('my_file', 'r')  # 100 mb file
a1 = f.read(1024 * 1024 * 10)

# Creating variables
for i in range(2, 20, 1):
    globals()["a{0}".format(i)] = globals()["a{0}".format(i - 1)]


with Timer():
    try:
        1 / 0
    except Exception as e:
        sentry_sdk.capture_exception(e)
```

Python 3 works ok and both SDK provides the same result. Yes, it's x100 more time for 0.13.3 but it's still fast. 
```
-- Python3.7 | SDK 0.8 ---
C:\Python37\python.exe C:/Users/artem/Code/sentry-local-test/sentry_sdk_0.8/test-0.8.py
Sentry_SDK_VERSION 0.8.0
0:00:00.001001
```

```
-- Python3.7 | SDK 0.13.3 ---
C:\Python37\python.exe C:/Users/artem/Code/sentry-local-test/sentry_sdk_0.13.3/test-0.13.3.py
Sentry_SDK_VERSION 0.13.4
0:00:00.103672
```

Example with Python 2.7 is more demonstrative

```
-- Python2.7 | SDK 0.8 ---
C:\Python27\python.exe C:/Users/artem/Code/sentry-local-test/sentry_sdk_0.8/test-0.8.py
('Sentry_SDK_VERSION', '0.8.0')
0:00:00.001000
```

```
-- Python2.7 | SDK 0.13.3 ---
C:\Python27\python.exe C:/Users/artem/Code/sentry-local-test/sentry_sdk_0.13.3/test-0.13.3.py
('Sentry_SDK_VERSION', '0.13.4')
0:00:10.507000
```

So the 0.13.3 version of SDK with Python2.7 is **10000x** slower.

I have pstat file:
![image](https://user-images.githubusercontent.com/1732107/72976681-f3ba9180-3dca-11ea-8875-938b4031f314.png)

Looks like it uses **safe_repr()** a lot. It returns full file chunk (10mb)  in our case but heavy without file if there are a lot of local variables and links between them. 

If I hack the SDK and change safe_repr to be:
```python
if PY2:
    def safe_repr(value):
        # type: (Any) -> str
        try:
            #rv = repr(value)

            rv = '<{0}.{1} object at {2}>'.format(
                value.__module__,
                type(value).__name__,
                hex(id(value))
            )
    ...
```

**Comment by Xamber** [comment]
Good morning, @untitaker !

I have been investigating our problem with CPU and I hope I have found the issue.
So I would like to share my investigation. I tested script with two versions 0.8.0, 0,12.2 and 0.13.3.

I used next code for testing:

```python
import sentry_sdk
import datetime
class TestException(BaseException):
    pass


sentry_sdk.init()


class Timer():
    def __enter__(self):
        self.start = datetime.datetime.now()

    def __exit__(self, exc_type, exc_val, exc_tb):
        print("\n\n")
        print(datetime.datetime.now() - self.start)


print("Sentry_SDK_VERSION", sentry_sdk.consts.VERSION)
f = open('my_file', 'r')  # 100 mb file
a1 = f.read(1024 * 1024 * 10)

# Creating variables
for i in range(2, 20, 1):
    globals()["a{0}".format(i)] = globals()["a{0}".format(i - 1)]


with Timer():
    try:
        1 / 0
    except Exception as e:
        sentry_sdk.capture_exception(e)
```

and I hacked `self.options["with_locals"]` to be always true.

Python 3 works ok and both SDK provides the same result. Yes, it's x100 more time for 0.13.3 but it's still fast. 
```
-- Python3.7 | SDK 0.8 ---
C:\Python37\python.exe C:/Users/artem/Code/sentry-local-test/sentry_sdk_0.8/test-0.8.py
Sentry_SDK_VERSION 0.8.0
0:00:00.001001
```

```
-- Python3.7 | SDK 0.13.3 ---
C:\Python37\python.exe C:/Users/artem/Code/sentry-local-test/sentry_sdk_0.13.3/test-0.13.3.py
Sentry_SDK_VERSION 0.13.4
0:00:00.103672
```

Example with Python 2.7 is more demonstrative

```
-- Python2.7 | SDK 0.8 ---
C:\Python27\python.exe C:/Users/artem/Code/sentry-local-test/sentry_sdk_0.8/test-0.8.py
('Sentry_SDK_VERSION', '0.8.0')
0:00:00.001000
```
12.2 is good as well:
```
C:\Python27\python.exe C:/Users/artem/Code/sentry-local-test/sentry_sdk_0.12.2/test-0.12.2.py
('Sentry_SDK_VERSION', '0.12.2')
0:00:00.001000
```
But 13+ version is slower:
```
-- Python2.7 | SDK 0.13.3 ---
C:\Python27\python.exe C:/Users/artem/Code/sentry-local-test/sentry_sdk_0.13.3/test-0.13.3.py
('Sentry_SDK_VERSION', '0.13.4')
0:00:10.507000
```


So the 0.13.3 version of SDK with Python2.7 is **10000x** slower.

I have pstat file:
![image](https://user-images.githubusercontent.com/1732107/72976681-f3ba9180-3dca-11ea-8875-938b4031f314.png)

Looks like it uses **safe_repr()** a lot. It returns full file chunk (10mb)  in our case but repr() could be heavy without file if there are a lot of local variables and links between them. 

If I hack the SDK and change safe_repr to be:
```python
if PY2:
    def safe_repr(value):
        # type: (Any) -> str
        try:
            #rv = repr(value)

            rv = '<{0}.{1} object at {2}>'.format(
                value.__module__,
                type(value).__name__,
                hex(id(value))
            )
    ...
```
the script finishes with  0:00:00.119000 seconds. 
As I understand the **safe_rep** implementation for python2 is the same for 0.8.0 and 0.13.3 and it looks like the only call count is different. (It's 43 vs 0, actually)

### Additional screens:
Call count for 0.12.2 (left) vs 0.13.3 (right):
![image](https://user-images.githubusercontent.com/1732107/72979367-1602de00-3dd0-11ea-8f71-b9dba70f2689.png)

Call graph for 0.12.2 (left) vs 0.13.3 (right):: 
![image](https://user-images.githubusercontent.com/1732107/72979488-55312f00-3dd0-11ea-93ec-d775d4ecbe5e.png)

if you stop at the start of **safe_repl** function you will see huge stack here but it could be ok if expected =) 
![image](https://user-images.githubusercontent.com/1732107/72980317-48153f80-3dd2-11ea-900d-0ce9f3f830cd.png)


Could you please take a look?

**Comment by untitaker** [comment]
Thanks for the detailed report @Xamber! I'll be sure to take a look.

At first glance there seems to be a lot of stuff missing from the left callgraph that I would expect to find there. For example I do not see any invocation of capture_exception at all, so it seems that your run of 0.12 only imported and initialized the SDK, but did not actually produce an exception. Maybe I am reading things wrong. Am I correct in assuming that all of this is done in PyCharm?

**Comment by untitaker** [comment]
```
sentry_sdk.init()
```

fwiw this will cause basically everything to become a noop if there is no `SENTRY_DSN` envvar.

**Comment by Xamber** [comment]
@untitaker Looks like you are right. 
With your code the results are the same. 
I will try to debug it again and hopefully find the difference.

**Comment by HakShak** [comment]
@untitaker seems we can't artificially reproduce this which means it might be more nuanced. @Xamber found discrepancies in the reported callstacks which, long story short, may imply that something changed in the local variable expansion which might be triggering network object calls within our environment post v0.8.0.

That's the closest theory we have at this point. We will backlog this for now.

**Comment by untitaker** [comment]
Ok. One suggestion I have is to time every safe-repr call in prod to figure
out which types cause the slowdown. You can just patch the sdk for that,
but you can also use the private api "repr_processors" for
wrapping/replacing safe-repr. It is already used by the Django integration
to avoid calling repr on certain types.

**Comment by sl0thentr0py** [comment]
closing because stale
