### ISSUE TITLE
DjangoIntegration breaks Django Channels after reinitialization

### ISSUE THREAD

**Issue by svenstucki** [getsentry/sentry-python#597]
After initializing Sentry, I'm using `sentry_sdk.init()` to disable error reporting in some cases. However, when using Django Channels and the Django integration, this breaks something in the Daphne webserver. After this second call to `init`, any request leads to the following error:

 ```
Traceback (most recent call last):
  File "<virtual env>/daphne/http_protocol.py", line 180, in process
    "server": self.server_addr,
TypeError: __call__() missing 1 required positional argument: 'send'

HTTP GET / 500 [0.01, 127.0.0.1:51170]
```

You can find a minimal example with that behaviour in [this repo](https://github.com/svenstucki/sentry-problem).

The problem seems to be that the second call is missing the `DjangoIntegration`, it goes away when passing a new instance.

This might seem like a weird use of the SDK, but there does not seem to be another way to disable error reporting after `init` was called. This approach was suggested [here](https://stackoverflow.com/a/52781369/182689) as a workaround, since it removes the DSN. It should definitely not break the application though or at least be documented.

**Comment by untitaker** [comment]
Hi, thanks for raising this. Could you try #598 and see if it fixes your issue?

**Comment by svenstucki** [comment]
Thanks for the quick feedback. This solves the problem for me.
