### ISSUE TITLE
Sentry not sending messages because of a script CLI arguement

### ISSUE THREAD

**Issue by noamelf** [getsentry/sentry-python#599]
Hi,
This is sooooo strange. I tried updating the Sentry version from 0.6.5 to 0.13.2 and had a strange problem where events wasn't sent to Sentry. Digging into the issue it seems that event are not sent only when I run my script with a command line argument `--execution-date 27/1/2020`. See the following failed snippet:

```python
# test_snipet.py

import os
import sentry_sdk


sentry_sdk.init(
                dsn=os.getenv('SENTRY_DSN'),
                ca_certs=os.getenv('REQUESTS_CA_BUNDLE'))

raise Exception('test sentry')
```

And then when running it, the event doesn't appear in Sentry:

```bash
python test_snippet.py --execution-date 27/1/2020
```

Running with other arguments works:

```
python test_snippet.py --foo bar
```

I tried to cut it down to a smaller snippet:

```bash
python test_snippet.py --ex 123
```

Testing on different versions of sentry_sdk shows that the change that is causing this issue was introduced in version `0.6.7`. I looked at the [change set](https://github.com/getsentry/sentry-python/compare/0.6.6...0.6.7) swiftly but didn't find anything clear. 

The Python version is 3.6.

What do you think?

**Comment by untitaker** [comment]
Are you sure that this is stable to reproduce? In each of the setups/scenarios you described, could you run the script a few thousand times and observe consistent behavior?

**Comment by noamelf** [comment]
Hi, I did more testing in does reproduce. Running it in a loop produces the same output, likewise for testing on another machine.
