### ISSUE TITLE
Sentry doesn't capture  billiard.exceptions.TimeLimitExceeded from Celery

### ISSUE THREAD

**Issue by maxmalysh** [getsentry/sentry-python#613]
Hi,

I've noticed that sentry-sdk doesn't capture `billiard.exceptions.TimeLimitExceeded` when a task fails. 

I've tried Celery 3.1.26 and 4.4. Sentry-sdk is 0.14.1.

Example:
```
# tasks.py
from time import sleep
from celery import shared_task

@shared_task(time_limit=2)
def test_time_limit():
    sleep(5)
```
Logs:
```
[2020-01-30 15:07:59,614: ERROR/MainProcess] Task handler raised error: TimeLimitExceeded(2,)
Traceback (most recent call last):
  File "/Users/mmalysh/Development/my-website/venv/lib/python3.6/site-packages/billiard/pool.py", line 684, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
billiard.exceptions.TimeLimitExceeded: TimeLimitExceeded(2,)
[2020-01-30 15:07:59,627: ERROR/MainProcess] Hard time limit (2s) exceeded for api.tasks.test_foobar[e4f46f20-2311-4417-9ade-53e735430c65]
```

We didn't have this problem with `raven`. All other exceptions are reported properly. For example, this exception is reported as expected:
```
@shared_task
def test_bazqux():
    raise Exception('BUY BITCOIN!')
```

**Comment by untitaker** [comment]
Is soft_timeout reported correctly for you?

**Comment by maxmalysh** [comment]
I've double-checked everything and found out that everything works with Celery 4.4. So the problem affects only `celery==3.1.26.post2`. Sorry for the confusion!

`SoftTimeLimitExceeded` is reported correctly on 3.1.26:

```
@shared_task(soft_time_limit=2)
def test_soft_limit():
    sleep(5)


@shared_task(time_limit=2)
def test_hard_limit():
    sleep(5)
```

**Comment by untitaker** [comment]
huh ok. Would you benefit from a workaround for that version or do you intend to just switch versions?

**Comment by maxmalysh** [comment]
We'll just switch to `soft_time_limit`. Thanks!

**Comment by untitaker** [comment]
Ok, but hard limits work for you in 4.4 as well?

**Comment by maxmalysh** [comment]
Yes, hard limits work in 4.4

**Comment by untitaker** [comment]
Ok! Then let's close this one, we generally only aim to support stable releases of Celery unless somebody requires more.
