### ISSUE TITLE
Django integration: make parsing query params for Django ORM configurable

### ISSUE THREAD

**Issue by rybakm** [getsentry/sentry-python#614]
At the moment Django queries are logged unparsed and you can send params by passing `_experminets={'record_sql_params': True}` in the `sentry_sdk.init()` (howerer it is not described in the docs).

I'm aware of issue https://github.com/getsentry/sentry-python/issues/459 and that parsing queries was removed because of PII data. On the other hand, you can configure `send_default_pii=True`. Doing so enables Django integration sending user data, but not parsed queries.

Having parsed queries in, for example, breadcrubms, was very convinient. One could simply copy it and run against database - in my case some logged queries are very long (I also needed to monkey patch string limit).

I think it would be good to:
- make Django queries logging check `send_default_pii` and bring back pre https://github.com/getsentry/sentry-python/issues/459 behaviour if set `True`
- document `record_sql_params` and move it out from `_experiments` to `.init()`;

**Comment by allan-simon** [comment]
+1 , @rybakm  do you have the snippet to monkey patch the size of logged queries?

I found your issue when trying to find how to get the long queries logged (and actually in django orm, as all columns are selected individually, in our case there's no a single query for which we see the `FROM` part, even less the `WHERE` , which make all the queries not usable at all in the breadcrum, which is a pity as it's often the most interesting part of the breadcrum)

**Comment by rybakm** [comment]
@allan-simon sorry for late response, if you didn't fix your issue already, you need to set `MAX_STRING_LENGTH`. Example config:
```
import sentry_sdk.utils
sentry_sdk.utils.MAX_STRING_LENGTH = 2048  # monkey patch first
...
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
...
sentry_logging = LoggingIntegration(
        level=logging.INFO,          # Capture info and above as breadcrumbs
        event_level=logging.WARNING  # Send warnings as events
)
sentry_sdk.init(
    dsn=SENTRY_DSN,
    integrations=[
        sentry_logging,
        DjangoIntegration(),
    ],
    # Associate users to errors (if using django.contrib.auth)
    send_default_pii=True,
    _experiments={
        'record_sql_params': True
    }
)
```

**Comment by allan-simon** [comment]
@rybakm  ah thanks, no I didn't explore it further, so your message is quite helpful :)
