### ISSUE TITLE
SSLError processing loop

### ISSUE THREAD

**Issue by vanzi** [getsentry/sentry-python#623]
We've had a problem with an expired SSL cert on our Senty instance over the weekend and it seems to have caused the sentry-sdk to enter some sort of retries loop which caused major CPU and memory usage (e.g. 1 process used 10GB memory over 3 hours).

Logs showed hundreds of thousands of retries one after another, like this:

    Feb 15 01:39:34 worker-1 r-worker-1-4cbe4c8e[106416] WARNING 2020-02-15T01:39:34.380505 connectionpool Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1056)'))': /api/5/store/  
    Feb 15 01:39:34 worker-1 r-worker-1-4cbe4c8e[106416] WARNING 2020-02-15T01:39:34.460969 connectionpool Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1056)'))': /api/5/store/  
    Feb 15 01:39:34 worker-1 r-worker-1-4cbe4c8e[106416] WARNING 2020-02-15T01:39:34.503272 connectionpool Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1056)'))': /api/5/store/  

This was on sentry-sdk==0.13.2 so not the current one, but I did not see any mention of this issue in the change log.

**Comment by untitaker** [comment]
I think 0.14.1 contains a fix for that. I am not sure about CPU usage but memory consumption when the internal queue is backed up definetly improved with that release.

**Comment by untitaker** [comment]
I'm gonna close this since I am fairly certain about that bugfix.
