### ISSUE TITLE
Request for Bugfix version release

### ISSUE THREAD

**Issue by Ivo-Donchev** [getsentry/sentry-python#635]
Hi,

We're trying to upgrade the python client for Sentry by replacing raven with `sentry-sdk` in the production Django application that we're working on.

But unfortunatelly we're facing this error - https://github.com/getsentry/sentry-python/issues/597

I saw it was fixed here - https://github.com/getsentry/sentry-python/pull/598 and tried to install the latest code (from latest master) and it wortked :tada: 

The fix is from **Jan 22** but the last release(`0.14.1`) is from **Jan 21**.

Can you guys release a bugfix version please :pray: ? 

Thanks,
Ivo Donchev

**Comment by untitaker** [comment]
Yup, we'll release 0.14.2 today!

**Comment by Ivo-Donchev** [comment]
Thanks :raised_hands: :slightly_smiling_face:

**Comment by maxmalysh** [comment]
I think 0.14.2 has broken django integration for us. We receive no events at all. We use both django and django-channels. Didn't have a chance to investigate further yet.

**Comment by untitaker** [comment]
Can you change your `init(...)` to `init(..., debug=True)`? This reveals 70% of all problems.

**Comment by maxmalysh** [comment]
I couldn't reproduce this, so everything is OK. Sorry for the false alarm.
