### ISSUE TITLE
Deployment Django Management Command

### ISSUE THREAD

**Issue by jensenbox** [getsentry/sentry-python#638]
I think the addition of https://docs.sentry.io/api/releases/post-release-deploys/ into a django management command would be fantastic. This way, during the same step as running the migrations we could simply trigger a deploy and all the appropriate settings would be automatically included.

**Comment by untitaker** [comment]
For the sake of simplicity/maintainability we offer just one platform-independent CLI to create releases: https://docs.sentry.io/cli/releases/#creating-deploys

Let me know if that is close enough or if you are already aware of this.

**Comment by untitaker** [comment]
We're probably not going to work on this. sentry-cli has a very large API surface and we cannot replicate it for every language.
