### ISSUE TITLE
Sanic Integration: Exceptions captured even when ignored on exception routes

### ISSUE THREAD

**Issue by jordangarside** [getsentry/sentry-python#650]
When an exception route is exposed via Sanic and the Sentry SDK is used, the "exception" is captured regardless of whether or not that exception is ignored.

The `_capture_exception` function can be a bit expensive.

Simple exception route without Sentry integration:
```
Running 5s test @ http://localhost:8080/404
  6 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.86ms    1.95ms  24.45ms   72.12%
    Req/Sec     2.75k   338.93     3.27k    72.67%
  82225 requests in 5.01s, 10.90MB read
  Non-2xx or 3xx responses: 82225
Requests/sec:  16403.63
Transfer/sec:      2.17MB
```

Simple exception route with Sentry integration.
```
Running 5s test @ http://localhost:8080/404
  6 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    62.64ms   17.68ms 109.91ms   60.98%
    Req/Sec   255.03     47.26   400.00     64.55%
  7743 requests in 5.10s, 1.03MB read
  Non-2xx or 3xx responses: 7743
Requests/sec:   1517.53
Transfer/sec:    205.99KB
```

Example Code:
```py
import sentry_sdk
from sanic import Sanic
from sanic.exceptions import NotFound
from sanic.response import text
from sentry_sdk.integrations.sanic import SanicIntegration

app = Sanic()

@app.exception(NotFound)
def handle_404s(request,exception):
    return text("404 Not Found", 404)

if __name__ == "__main__":
    sentry_sdk.init(
        dsn="http://00000000000000000000000000000011:00000000000000000000000000000011@sentry/11",
        integrations=[SanicIntegration()],
        ignore_errors=[NotFound],
    )
    
    app.run(host="localhost", port=8080, debug=False, access_log=False, workers=1)
```

Flamegraph:
![image](https://user-images.githubusercontent.com/6321824/76781761-70833f80-676c-11ea-92c3-868441844753.png)

**Comment by untitaker** [comment]
I think this should be a trivial performance improvement. Do you think you could open a PR for this one?

**Comment by vishalkuo** [comment]
Hi! This would be helpful for us as well. Can we get the above PR reviewed? It seems like a small change for a big win.

**Comment by untitaker** [comment]
@vishalkuo I commented on the PR but I think a better perf fix would be inside of `event_from_exception` (or somehow else generic across integrations)

**Comment by antonpirker** [comment]
Hello @jordangarside and @vishalkuo 

This issue looks kind of stale. Is there still one of you willing to work on the PR to get this merged? I am happy to help to review the PR.
But if no one is having time to work on this, I will close the issue.
