### ISSUE TITLE
Disable sending errors on local

### ISSUE THREAD

**Issue by rain01** [getsentry/sentry-python#659]
We have a Django setup where we `init()` sentry in the main settings file but I have not found a simple way of disabling sentry for local development.

With Raven I was able to just overwrite logging params in local settings file that overwrites main settings file but I no I find myself just editing the main settings file to comment out the sentry `init`.

Is there a better way to disable sentry init without touching the settings file?

I also checked the community forums for an answer to this but it seems there are less answers than here and couldn't find anything about it in docs.

**Comment by untitaker** [comment]
You can call init multiple times. Each time you call it the previous
settings are replaced. Calling init() with no arguments will disable the
sdk.
