### ISSUE TITLE
Breadcrumbs type error

### ISSUE THREAD

**Issue by misja** [getsentry/sentry-python#67]
We're having an issue with v0.3.2 where `popleft` is called on a list type:

```
File "/srv/frontend/project/lib/python3.5/site-packages/sentry_sdk/hub.py" in add_breadcrumb
  209.             scope._breadcrumbs.popleft()

Exception Type: AttributeError at /
Exception Value: 'list' object has no attribute 'popleft'
```

**Comment by chrisapplegate** [comment]
Getting this issue as well with v0.3.0. It is occurring for me when I run `collectstatic` as part of the deployment of a Django application, during the cross-loading of static files to S3 using `boto`.

**Comment by untitaker** [comment]
Sorry for this tire fire, 0.3.3 is released.

**Comment by chrisapplegate** [comment]
No worries, thanks for such a fast turnaround!
