### ISSUE TITLE
Instrumenting WSGI apps with meinheld is broken

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#678]
Instrumenting a WSGI application using specifically Chausette with Meinheld backend is broken and raises weird connection errors in the transport

**Comment by untitaker** [comment]
related; https://github.com/getsentry/sentry-python/issues/677

**Comment by pablopda** [comment]
Same issue.

**Comment by antonpirker** [comment]
Added this information to this ticket: https://github.com/getsentry/sentry-python/issues/677

Closing this in favor of https://github.com/getsentry/sentry-python/issues/677
