### ISSUE TITLE
Missing request.sentry.id in Django

### ISSUE THREAD

**Issue by jaap3** [getsentry/sentry-python#679]
We migrated from `raven` to `sentry-sdk` a while ago. Today we noticed that we don't actually show the Sentry error id on error pages anymore, as we did before. 

From my quick analysis It seems that the `sentry` object is no longer added to the `request`. Was this feature removed/never ported to sentry-sdk or am I missing something?

**Comment by untitaker** [comment]
It's not backward compatible but documented here
https://docs.sentry.io/enriching-error-data/user-feedback/?platform=django#collecting-feedback

**Comment by jaap3** [comment]
Thank you, I'm usually pretty good at finding things in the docs. But for this I didn't know where to look/what to search for. Simply searching "django error request sentry id" didn't bring up the correct page.

For some reason Google really seems to like recommending this page:

https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/clients/python/integrations.md

which talks about Raven a lot
