### ISSUE TITLE
Setting transaction name in pyramid

### ISSUE THREAD

**Issue by ergo** [getsentry/sentry-python#683]
Hi is it possible to set transaction name when using PyramidIntegration?
I tried setting `scope.transaction = "mycustomname"` but it seems that integration itself does:

        try:
            if integration.transaction_style == "route_name":
                event["transaction"] = request.matched_route.name
            elif integration.transaction_style == "route_pattern":
                event["transaction"] = request.matched_route.pattern
        except Exception:
            pass

And I suspect that overwrites anything I've set up earlier?

**Comment by untitaker** [comment]
thanks for reporting, opened a fix at #686. A workaround you can use is:

```
@scope.add_event_processor
def _set_transaction(event, hint):
    event['transaction'] = "mycustomname"
```

This circumvents the priority bug until the fix is released
