### ISSUE TITLE
Duplicate issues with no differences

### ISSUE THREAD

**Issue by WhyNotHugo** [getsentry/sentry-python#693]
These last weeks I've been getting an overflow of issues which are exactly the same (eg: same line, same error).

If I click on "Similar Issues", they're listed there. If I click `Diff`, the diff is empty (eg: no differences!?).

Here are some example:
https://sentry.io/organizations/hobarrera/issues/1670442219/?project=124552
https://sentry.io/organizations/hobarrera/issues/1513060802/?project=124552
https://sentry.io/organizations/hobarrera/issues/1663437698/?project=124552
https://sentry.io/organizations/hobarrera/issues/1670442303/?project=124552

Sample Diff:

![2020-05-17T11:36:35,632281993+02:00](https://user-images.githubusercontent.com/730811/82140931-aeffae00-9832-11ea-9ce6-0d1c50efd831.png)

**Comment by untitaker** [comment]
Yeah the diffing in its current state is suboptimal as it does not really diff the exact things that are being used for grouping.

You were hitting at least one known issue, which is that when you change anything about any line that appears in the stacktrace (in your case reformatting code from `logger.error('...')` to `logger.error("...")`), you get a new issue. That alone should divide your events into two groups. There is another issue where a stackframe within celery suddenly changed and caused two new groups as well. That may not be apparent in the diff but if you attempt to download one event from each issue and attempt to diff it in vim it should become apparent.

I think most of your issues could be solved by setting `in_app_include=["idf"]` as arg to your `init()` call.

**Comment by untitaker** [comment]
I'm closing this since the SDK can't do a lot here and fixing Similar Issues is on our roadmap now.
