### ISSUE TITLE
Silent async breakage on Python 3.6

### ISSUE THREAD

**Issue by marco-neumann-jdas** [getsentry/sentry-python#694]
# Abstract
`aiocontextvars` is required on Python 3.6 to make async integrations work (e.g. ASGI), but this is only obvious from reading the source code.

# Technical Background
[Here](https://github.com/getsentry/sentry-python/blob/f399cae617290c0acdff6382d983dd6e5d242d78/sentry_sdk/utils.py#L760-L766) the `aiocontextvars` is optionally used under Python 3.6 to setup async-aware context vars. Without the package, async integrations just silently break (e.g. the ASGI integration misses a bunch of metadata, likely because under some conditions the current Hub/client is not found).

# Potential Solutions
- **log message:** emit a message indicating the missing requirement (maybe only if the `debug=True` flag is set)
- **warning:** same as previous point, but as a Python warning (not logging)
- **optional requirement:** add an optional requirement (like `async`) that under Python 3.6 requires `aiocontextvars` [here](https://github.com/getsentry/sentry-python/blob/f399cae617290c0acdff6382d983dd6e5d242d78/setup.py#L27-L40).
- **docs:** add a note to [the integration docs](https://docs.sentry.io/platforms/python/asgi/)

# Refs
#289, #293

**Comment by untitaker** [comment]
you're absolutely right, we do this for async framework integrations but not for the middleware
