### ISSUE TITLE
server_name not logged properly

### ISSUE THREAD

**Issue by caleb15** [getsentry/sentry-python#698]
In our cloud-hosted sentry UI events from our celery server consistently show up with 
`server_name: celery-8c78c4545-n987w`

The server name should be celery0.

```
caleb@celery0.cloud51:~$ hostname
celery0

caleb@celery0.cloud51:~$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostname()
'celery0'
```

We initialize our sentry config like so:
```python
def init_sentry_sdk(sentry_config):
    sentry_sdk.init(
        dsn=sentry_config['dsn'],
        integrations=[
            sentry_logging_integration,
            DjangoIntegration(),
            CeleryIntegration()
        ],
        send_default_pii=True,
        release=sentry_config['release'],
    )
```

**Comment by untitaker** [comment]
The SDK determines `server_name` using the same exact code you're using on the REPL to show a different hostname. I am somewhat sure you're just running the REPL outside of the docker container while your app runs inside.

If you want a different server_name, pass `server_name` as argument to `init`.

**Comment by caleb15** [comment]
> I am somewhat sure you're just running the REPL outside of the docker container while your app runs inside.

Nope, we are not using docker on that server. It's a ec2 instance that I ssh'd into. Python runs under celery which is launched via systemd

**Comment by caleb15** [comment]
Also not sure if you're a sentry employee but if you are this a link to the sentry incident with the incorrect server name:

> https://sentry.io/organizations/15five/issues/1661181013/?project=1385044&query=is%3Aunresolved+server_name%3Acelery%2A&statsPeriod=14d

**Comment by untitaker** [comment]
My point still stands that we use the same exact code that you presented in your REPL to determine the hostname as part of the SDK. That leads me to believe that your celery worker runs in a very different context than your REPL as the function call here: https://github.com/getsentry/sentry-python/blob/464ca8dda09155fcc43dfbb6fa09cf00313bf5b8/sentry_sdk/client.py#L70 seems to return the "wrong" result.

A good repro case would be to spawn a celery task on those machines to compute and return the hostname. Again I have severe doubts that this would produce something other than the SDK does.

**Comment by caleb15** [comment]
Turns out the error was coming from a kubernetes instance I was unaware of, sorry about that.
