### ISSUE TITLE
Convert django app to ASGI

### ISSUE THREAD

**Issue by alper** [getsentry/sentry-python#704]
I converted my app to ASGI but then the Sentry integration stopped working like here:

`TypeError: sentry_patched_load_middleware() got an unexpected keyword argument 'is_async'`

If I comment out the Sentry integration `uvicorn` runs th eapp just fine.

**Comment by rasulkireev** [comment]
I'm getting the same error on Django 3.2.4. Used to be fine, but is not working anymore once I switched to uvicorn.
