### ISSUE TITLE
Allow setting ca_certs from environment variable

### ISSUE THREAD

**Issue by dacameron** [getsentry/sentry-python#705]
Hey,

to get sentry sdk working in my environment we have to specify the ca_certs option. To allow developers to easily use sentry without having to specify the ca_certs option in their code could it be specified via an environment variable similar to the way release, environment and dsn work at the moment.

I am happy to make the change as the code is trivial. Is this something you would accept?

Thanks, David.

**Comment by untitaker** [comment]
We would like to avoid adding more environment variables, the existing ones are there because they are very popular, but ca_certs is not such an option.

You can do this with any option as `sentry_sdk.init(ca_certs=os.environ.get("CA_CERTS"))` so I don't really see the need for it
