### ISSUE TITLE
using sentry-python with flask application factory init_app

### ISSUE THREAD

**Issue by tedglee** [getsentry/sentry-python#709]
Hello,

I use factories in my flask app and initialize sentry with init_app:

```
from raven.contrib.flask import Sentry
sentry = Sentry(dsn='YOUR_DSN_HERE')

def create_app():
    app = Flask(__name__)
    sentry.init_app(app)
    ...
    return app
```

I'd like to migrate from raven to sentry-python, but it doesn't seem to support init_app.

Thanks!

**Comment by untitaker** [comment]
You do not need to pass the app object to the new sdk. Please refer to https://sentry.io/for/flask which really does show all the code you need.

**Comment by tedglee** [comment]
Oh, that worked! I didn't realize it didn't need the app object. Thanks for the link and the prompt reply.
