### ISSUE TITLE
Celery Integration breaks celery_once

### ISSUE THREAD

**Issue by jdavisp3** [getsentry/sentry-python#718]
The Celery integration appears to conflict with https://github.com/cameronmaske/celery-once.

In particular, the use of the `keys` https://github.com/cameronmaske/celery-once#keys option will cause a `KeyError` when the task attempts to run.

Somehow the issue seems to be that the argument signature of task functions is different when the integration is installed.

When [this code](https://github.com/cameronmaske/celery-once/blob/08fb3aa8797719109d5ba9c4897c6e0a6ae8eff4/celery_once/tasks.py#L110-L111) runs it fails to find a correctly-specified argument in the call arguments.

**Comment by jdavisp3** [comment]
Somewhat related to https://github.com/getsentry/sentry-python/issues/421 but I don't think that fix dealt with the use of `keys` in `celery-once`.

**Comment by jdavisp3** [comment]
Commenting out the patching [here](https://github.com/getsentry/sentry-python/blob/1f6743cd89223d5fd9525afafc3230ce3d1e7bd3/sentry_sdk/integrations/celery.py#L63) fixes the issue.

**Comment by jdavisp3** [comment]
Oh you know what, I think the latest point release of celery once may fix this... https://github.com/cameronmaske/celery-once/blob/master/HISTORY.rst#301

**Comment by jdavisp3** [comment]
Yep, to fix is to use `celery-once` 3.0.1.

**Comment by untitaker** [comment]
Oh ok. Thanks again @cameronmaske for fixing this issue! If such issues occur again due to sentry-python monkeypatching things I would default to opening an issue with the SDK, or at least I would see the resonsibility with the SDK rather than trying to work around it somewhere else. But either works for me.
