### ISSUE TITLE
Initialize sentry instance (or a distributed tracing transaction/span) with external/pre-existing trace_id

### ISSUE THREAD

**Issue by dirkdevriendt** [getsentry/sentry-python#728]
I might be missing something, but I would think that, in a microservices solution, we need to have a way of linking together transactions and spans with an overarching trace_id and I can't find any documentation on how to do that.

In our case we pass this common trace_id on in different ways (HTTP headers, message properties etc) and when initializing a sentry instance, I would like to pass this trace_id to sentry so sentry can add its own transaction/span magic but still match up the frontend, backend and messaging processes.

Is there a way to do that or could it be added to the API?

**Comment by untitaker** [comment]
Right now the Python SDK will do automatic trace propagation by injecting a HTTP header to outgoing requests and making sure spawned celery/rq tasks's transactions are linked via trace_id and parent_span_id.

I don't *think* the API for explicitly passing trace propagation info (which btw includes trace_id/span_id and sampling decision) is stable yet, but I'll ask around as to what our plans for that are.

**Comment by dirkdevriendt** [comment]
It would be nice if they'd be following the CloudEvents.io (https://github.com/cloudevents/spec) and/or W3C (https://w3c.github.io/trace-context/) specs.

Digging a bit deeper, I see:
- traces mentioned as predefined data: https://docs.sentry.io/enriching-error-data/additional-data/?platform=python#predefined-data
- a tracing data model with parameters: https://docs.sentry.io/performance/distributed-tracing/#tracing-data-model
- trace_id and parent_span_id as init parameters in the Span class: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/tracing.py#L117

The "Setting up tracing - Python" documentation skips those options, but if I piece it together, it looks like we could either use a (still unclear to me) combination of scope options or run the manual instrumentation with:
```
with sentry_sdk.start_span(trace_id="...", parent_span_id="...", op="doing/the/thing"):
    do_the_thing()
```

The transaction and span metadata parameters seem to be documented at:
https://develop.sentry.dev/sdk/event-payloads/transaction/

**Comment by untitaker** [comment]
The SDK's data model matches that of the W3C trace context spec, in that trace_id, parent_span_id and the sampled flag are subsets of the data found in the `traceparent` header: `trace_id`, `parent_id`, and the least significant bit of the trace flags for sampling.

We use a proprietary header name as there is an unresolved concern with how the spec interacts with auto-instrumentation as provided by Sentry: https://github.com/w3c/trace-context/issues/335

As you found out already you can pass trace_id and parent_span_id (and sampled) directly to `start_span` if you were to parse that header yourself, but as far as interaction with "standard" tracing systems go we still have not fleshed out our story. We might integrate with open telemetry at some point but their data model is also still too unstable to be relied upon. So right now the only thing we can provide is a system where sentry-instrumented applications that communicate with each other can form a distributed trace, but not interact with third-parties in that way without a lot of legwork done by the user.

**Comment by dirkdevriendt** [comment]
I think I get what you're saying, but:
- I don't understand why you want/need to "own" the root trace_id
- the following is now not clear to me:
  - if I create my own W3C compliant trace info and initialise the span with it, wil sentry accept that and understand the different (sentry-equipped) micro services belong together?
  - will sentry interoperability magically work. E.g. if I happen to use a redis message between two microservices and both services have start a sentry instance with tracing enabled, will the necessary headers just be exchanged? Or will they clash just like with third parties because they both expect to be using their own top level trace_ids?

Side note: you can obviously use your own headers, but you could also use/investigate the standard ones and if a tracing reference exists, adopt it (or pretend to adopt it, still create/keep your own ID and link up the two in your backend).

The "lot of legwork" is not required, imo. I understand things can get hairy if you want to merge two pre-existing trace trees; but that's not what I'm talking about here. In essence the only thing needed is that a user can initialise the sentry SDK instance (or transaction or span) with (a subset of the information in) the traceparent/tracecontext header and everything else follows from that.

**Comment by untitaker** [comment]
Okay, just to clarify: the API for passing in a trace context and getting one out of the SDK is a legitimate feature request. What *I* think the SDK should never do is to attempt to set or read the W3C trace context header in its automatic instrumentation, at least not by default. The spec guarantees no conflict resolution of any kind and I think as long as it doesn't there will always be conflict (leading to random disjoint traces) if there is none that all implementors agree on.

>In essence the only thing needed is that a user can initialise the sentry SDK instance (or transaction or span) with (a subset of the information in) the traceparent/tracecontext header and everything else follows from that.

Yes, this already exists in the Python SDK but it's not an API we have stabilized yet. You won't find it in the JS SDK.

**Comment by untitaker** [comment]
>will sentry interoperability magically work

To some extent. For example: Two Flask microservices communicating with each other via HTTP should propagate trace context (Sentry's context) automatically, meaning that the transactions sent from those services can be correlated in the Sentry UI. This correlation is completely disjunct from any opentelemetry trace since it's a dedicated `sentry-trace` header.

The same goes for spawned celery tasks: If I spawn a celery task from an endpoint in Django, you will be able to see which Django web transaction spawned the celery task transaction

>If I happen to use a redis message between two microservices

I don't know what that means but we don't have any kind of trace propagation for redis. I am not sure how that would work given that redis is primarily a kv store

**Comment by dirkdevriendt** [comment]
Excellent info, thanks!
Some clarification (FYI):

I understood the (agreed, very naive) conflict avoidance offered by the W3C is that once you set a trace_id, it won't get overwritten (at least not by anyone following the spec). Which obviously also means that, when you do encounter a conflict (e.g. in the form of two traces joining), you're on your own.

From your description I deduce that an individual incoming flask request will start out with an "empty" span and adopt the trace info coming in on the `sentry-trace` header as a parent. Meaning it will have no tracing relation to other (unrelated) requests coming in. If so, this would seem to be compatible with the approach proposed by he W3C.
- no need to get into this for my sake, we don't have such a use case -

We use redis streams as a message queue / hub and I saw sentry includes redis operations as spans. I now get that this is a shallow integration and sentry does not add anything to the envelope or content of the redis operations to propagate the traces.

Thanks again for your clear explanations, I'll close the issue now

**Comment by gowrizrh** [comment]
@untitaker 

This is what I am looking for. I have several AWS lambdas orchestrated by step functions. They aren't necessarily communicating by HTTP. There's no way to correlate transaction using a single trace ID. Trying to do so manually results in a "Multiple root transactions have been found with this trace ID."

What exactly is the way to tie these different lambdas together? There's heaps of documentation around what distributed tracing is but almost no useful examples.

**Comment by sl0thentr0py** [comment]
@gowrizrh if they aren't communicating via HTTP, you'll have to do write a fair bit of code to make it work.

You basically need 
* some way of communicating the trace info between the lambdas
* read this trace metadata in each lambda and start a transaction with [this method](https://github.com/getsentry/sentry-python/blob/fa4f5b03c2d686e1dfb40543d0d099e5391850a9/sentry_sdk/tracing.py#L258-L262). [These three fields](https://github.com/getsentry/sentry-python/blob/fa4f5b03c2d686e1dfb40543d0d099e5391850a9/sentry_sdk/tracing_utils.py#L240-L244) are the information you need to propagate traces successfully.
* Propagate these same fields to other Lambdas when you interact with them.

>  There's heaps of documentation around what distributed tracing is but almost no useful examples.
Yes, this is definitely valid feedback, (thank you!) and we're aware of the shortcomings to some degree. It's long been on the roadmap to clean up the distributed tracing docs but it's mostly a matter of time/resources. We'll try, please bear with us. :)

**Comment by gowrizrh** [comment]
That was very quick! Thank you for linking me through that. I'm happy to contribute to the docs once I get it to work

**Comment by gowrizrh** [comment]
I'm not sure if it's okay post here. Let me know if you want to open future comments somewhere else. I don't think `getsentry/sentry-python` would be the right place because I'm using the Javascript SDK.

So I've managed to get it working and I believe have my head wrapped around it now. This is AWS Lambda invoked by Step Functions with Distributed Tracing

![image](https://user-images.githubusercontent.com/40108018/187570058-b7a1ac60-e70d-42e5-8abb-aa35bea5fc69.png)

I'll look into adding some how-tos in the documentation repository.

**Comment by sl0thentr0py** [comment]
@gowrizrh nice, glad you got it working. Yes, a docs PR for this would be greatly appreciated!
