### ISSUE TITLE
RedisIntegration does not throw DidNotEnable when there is no redis module

### ISSUE THREAD

**Issue by soutys** [getsentry/sentry-python#735]
Most of integrations have ``ModuleDoesNotExist`` / ``ImportError`` try...except block throwing ``DidNotEnable`` exception (see: celery, flask, sqlalchemy).

``RedisIntegration`` have ``redis`` module import inside ``setup_once`` method because of monkey-patching.

This causes some sort of problems during wide-range integrations autodetection.

**Comment by untitaker** [comment]
>This causes some sort of problems during wide-range integrations autodetection.

RedisIntegration is not part of auto-enabling integrations so it should not even try to import or enable by itself. https://github.com/getsentry/sentry-python/blob/3a7f4f26a40ec1a0965f4d43b6ba7b24a3a69c8b/sentry_sdk/integrations/__init__.py#L55
