### ISSUE TITLE
Flaky test in `test_aws.py`

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-python#739]
Got a test failure in `test_aws.py`:

https://travis-ci.com/github/getsentry/sentry-python/jobs/352702298#L1612-L1616

<img width="818" alt="image" src="https://user-images.githubusercontent.com/88819/85422737-3816ad00-b576-11ea-95f5-9ab3e5f3bc9a.png">

Quick glance at the test implementation and I guess it could be flakey.

A subsequent run in the same PR resulted in passing tests.

_Originally posted by @rhcarvalho in https://github.com/getsentry/sentry-python/pull/731#issuecomment-648235744_

**Comment by antonpirker** [comment]
did not happen in the last couple of months.
