### ISSUE TITLE
iter_default_integrations() missing 1 required positional argument: 'with_auto_enabling_integrations'

### ISSUE THREAD

**Issue by koreno** [getsentry/sentry-python#757]
```
TypeError: iter_default_integrations() missing 1 required positional argument: 'with_auto_enabling_integrations'
```
This iterator used to be parameter-less. It appear it should still be that way, and that it should use the outer `with_auto_enabling_integrations` variable.

https://github.com/getsentry/sentry-python/blob/bf48bd0681c68239ee651224b59b9d8aee78f514/sentry_sdk/integrations/__init__.py#L28

**Comment by koreno** [comment]
oops, I misread the code...

**Comment by untitaker** [comment]
Hey Ofer, is this error triggered in the sdk somewhere?

**Comment by koreno** [comment]
I was using the function directly, and previously it didn't require a parameter. When I upgraded the SDK it broke my code.
But it's all good now, I've adapted the code.

Though generally I would say there should be an simple and documented way of selecting which integrations to include/exclude.

**Comment by untitaker** [comment]
@koreno not entirely sure why you need that. You can pass `default_integrations=False` and then enable each integration one-by-one (importing it explicitly)

**Comment by koreno** [comment]
Then it's all-or-nothing. In my case we just needed to exclude the logging
integration since we're using a different logging framework.

- Ofer
