### ISSUE TITLE
Support for mTLS

### ISSUE THREAD

**Issue by chhetripradeep** [getsentry/sentry-python#771]
Hi,

I am not sure if this feature is already there but i would like to see mTLS(https://en.wikipedia.org/wiki/Mutual_authentication) support in sentry-sdk. I would be interested in trying to contribute it if the feature isn't available already.

**Comment by untitaker** [comment]
I think at this point it's better for you to subclass the HTTPTransport and pass the subclass as `init(transport=MyCustomHTTPTransport)`. I think this feature is out of scope for the SDK.
