### ISSUE TITLE
Sets are not breadth-limited

### ISSUE THREAD

**Issue by vmarkovtsev** [getsentry/sentry-python#780]
I've got huge repr-s of sets that are included in the stack trace variables without truncation. As I see in `serializer.py`, `Mapping` and `Sequence` are limited to 10 items, but `typing.Set` is not handled yet.

![image](https://user-images.githubusercontent.com/2793551/89883967-2a21f780-dbc9-11ea-8993-28d3b229667b.png)

**Comment by untitaker** [comment]
Thanks, will be fixed in next release :)

**Comment by vmarkovtsev** [comment]
Many thanks for a super fast resolution :+1:
