### ISSUE TITLE
Python/Django -exceptions reported in error log

### ISSUE THREAD

**Issue by sdnall** [getsentry/sentry-python#789]
Hello,

We've been using sentry for quite a while and it's been amazing. Thank you for providing such a useful tool!

The team I work with has started a new project, and we recently noticed what appears to be some sentry-specific error log output. We were wondering if this was something to be expected or not. We haven't noticed it on any of our previous projects running older versions of Python.

### Details
These exceptions (captured below) occur when touching wsgi.py (reload), but do not seem to happen when restarting the entire web server.

These errors don't seem to affect requests/responses, but it _seems_ like it has lead to some undesired behavior with reporting exceptions/bugs in our code (no email notifications received).

I enabled debug output via sentry_sdk.init in case that could possibly be useful.

### Environment Info
```
OS: Ubuntu 20.04 LTS
Web server: Apache/2.4.41
WSGI: mod_wsgi 4.7.0
Python: 3.8.2
```

```
Django==3.0.7
sentry_sdk==0.16.3
```

```python
sentry_sdk.init(
        dsn="our_dsn",
        integrations=[DjangoIntegration()],
        send_default_pii=True,
        debug=True,
)
```

### Error Output
```
[Fri Aug 14 11:40:19.522117 2020] [wsgi:error] [pid 84917:tid 140085233822784]  [sentry] DEBUG: atexit: got shutdown signal
[Fri Aug 14 11:40:19.522193 2020] [wsgi:error] [pid 84916:tid 140085233822784]  [sentry] DEBUG: atexit: got shutdown signal
[Fri Aug 14 11:40:19.522371 2020] [wsgi:error] [pid 84916:tid 140085233822784]  [sentry] DEBUG: atexit: shutting down client
[Fri Aug 14 11:40:19.522520 2020] [wsgi:error] [pid 84916:tid 140085233822784]  [sentry] DEBUG: Flushing HTTP transport
[Fri Aug 14 11:40:19.522660 2020] [wsgi:error] [pid 84916:tid 140085233822784]  [sentry] DEBUG: background worker got flush request
[Fri Aug 14 11:40:19.522797 2020] [wsgi:error] [pid 84916:tid 140085233822784]  [sentry] DEBUG: background worker flushed
[Fri Aug 14 11:40:19.522801 2020] [wsgi:error] [pid 84917:tid 140085233822784]  [sentry] DEBUG: atexit: shutting down client
[Fri Aug 14 11:40:19.522929 2020] [wsgi:error] [pid 84916:tid 140085233822784]  [sentry] DEBUG: Killing HTTP transport
[Fri Aug 14 11:40:19.523053 2020] [wsgi:error] [pid 84916:tid 140085233822784]  [sentry] DEBUG: background worker got kill request
[Fri Aug 14 11:40:19.523182 2020] [wsgi:error] [pid 84916:tid 140085233822784]  [sentry] DEBUG: Killing HTTP transport
[Fri Aug 14 11:40:19.523187 2020] [wsgi:error] [pid 84917:tid 140085233822784]  [sentry] DEBUG: Flushing HTTP transport
[Fri Aug 14 11:40:19.523298 2020] [wsgi:error] [pid 84916:tid 140085233822784]  [sentry] DEBUG: background worker got kill request
[Fri Aug 14 11:40:19.523444 2020] [wsgi:error] [pid 84917:tid 140085233822784]  [sentry] DEBUG: background worker got flush request
[Fri Aug 14 11:40:19.523628 2020] [wsgi:error] [pid 84917:tid 140085233822784]  [sentry] DEBUG: background worker flushed
[Fri Aug 14 11:40:19.523790 2020] [wsgi:error] [pid 84917:tid 140085233822784]  [sentry] DEBUG: Killing HTTP transport
[Fri Aug 14 11:40:19.523964 2020] [wsgi:error] [pid 84917:tid 140085233822784]  [sentry] DEBUG: background worker got kill request
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f6815b3bdc0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
Exception in thread raven-sentry.BackgroundWorker:
Traceback (most recent call last):
  File "/usr/lib/python3.8/queue.py", line 170, in get
  File "/usr/lib/python3.8/threading.py", line 311, in invoke_excepthook
UnboundLocalError: local variable 'self' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/web/django_apps/.virtualenvs/emgv_intranet/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/srv/web/django_apps/.virtualenvs/emgv_intranet/lib/python3.8/site-packages/sentry_sdk/worker.py", line 132, in _target
  File "/usr/lib/python3.8/queue.py", line 182, in get
  File "/usr/lib/python3.8/threading.py", line 250, in __exit__
RuntimeError: release unlocked lock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/srv/web/django_apps/.virtualenvs/emgv_intranet/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 68, in run
NameError: name 'Exception' is not defined
Exception ignored in: <function Transport.__del__ at 0x7f6814f57820>
Traceback (most recent call last):
  File "/srv/web/django_apps/.virtualenvs/emgv_intranet/lib/python3.8/site-packages/sentry_sdk/transport.py", line 97, in __del__
NameError: name 'Exception' is not defined
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f6815b3bdc0>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
NameError: name 'ResourceWarning' is not defined
double free or corruption (out)
```

**Comment by untitaker** [comment]
Are you saying that after seeing those errors in your logs, error monitoring stops working entirely while Apache still happily serves requests?

**Comment by sdnall** [comment]
Apache definitely continues to happily serve requests after seeing the errors. However, the sentry error reporting seems to be intermittent. Sometimes they get reported, sometimes not.

**Comment by untitaker** [comment]
Does the server continuously spit out this error when Sentry is not working properly?

```
Exception in thread raven-sentry.BackgroundWorker:
Traceback (most recent call last):
  File "/usr/lib/python3.8/queue.py", line 170, in get
  File "/usr/lib/python3.8/threading.py", line 311, in invoke_excepthook
UnboundLocalError: local variable 'self' referenced before assignment
```

BTW I just looked at the threading code again and am not sure how `self` could disappear. I think there's a bug in Python core or something is seriously messing with your runtime. Though most other errors I see in your logs are also about variables suddenly going missing (`Exception`, `self`, `ResourceWarning`)

Also, this:

```
double free or corruption (out)
```

**Comment by sdnall** [comment]
Thanks you for taking a look at this.

The logs definitely aren't spewing or repeatedly outputing the raven-sentry.BackgroundWorker exception. It seems limited to the number of wsgi processes (in this specific case, 2).

After touching wsgi.py, the next request which results in everything being reloaded seems to be the trigger.

**Comment by untitaker** [comment]
This is an involved debugging step but the only thing I can think of. Can you set `default_integratons=False` in your `init()` and re-add the [Default Integrations](https://docs.sentry.io/platforms/python/default-integrations/) explicitly one-by-one (like the `DjangoIntegration`) until you are able to reproduce the issue again?

**Comment by sdnall** [comment]
I think this issue has been resolved by making a configuration tweak to mod_wsgi

I happened to stumble upon this issue https://github.com/GrahamDumpleton/mod_wsgi/issues/81

It would seem that specifying the following in my virtual host config resolves the issue. I am now unable to generate the sentry exceptions.

`WSGIApplicationGroup %{GLOBAL}
`

Here's the documentation from mod_wsgi for that config setting:

> Any WSGI applications in the global application group will always be executed within the context of the first interpreter created by Python when it is initialised, of the process handling the request. Forcing a WSGI application to run within the first interpreter can be necessary when a third party C extension module for Python has used the simplified threading API for manipulation of the Python GIL and thus will not run correctly within any additional sub interpreters created by Python.

Thank you for all of your assistance troubleshooting this.

**Comment by untitaker** [comment]
Okay cool. Fwiw we don't use C extensions or manipulate the GIL so I don't think it's us. Let me know if you ever figure out which of your dependencies surfaced this issue because it would help me in further debugging efforts.
