### ISSUE TITLE
AioHttp integration does not work if aiohttp.web.Application is subclassed

### ISSUE THREAD

**Issue by ojii** [getsentry/sentry-python#798]
AioHttp integration does not work if aiohttp.web.Application is subclassed, as in this example:

```python
import sentry_sdk
from sentry_sdk.integrations.aiohttp import AioHttpIntegration

sentry_sdk.init(
    dsn="<your dsn here>",
    integrations=[AioHttpIntegration()],
)

from aiohttp import web


async def hello(request):
    raise Exception("bar")


class CustomApp(web.Application):
    pass


app = CustomApp()
app.add_routes([web.get("/", hello)])

if __name__ == "__main__":
    web.run_app(app)
```

Is there a workaround for this?

**Comment by untitaker** [comment]
I'm sorry but can you go into more detail as to what doesn't work?

**Comment by ojii** [comment]
My bad, it simply does not send errors to sentry. In the example above, accessing `localhost:8080/` gives you a 500 in the browser, but sentry stays quite.

If you replace `app = CustomApp()` with `app = web.Application()` the errors are reported as expected.

**Comment by ojii** [comment]
Sorry, it looks like the problem is somewhere else.

**Comment by untitaker** [comment]
Yeah I tried reproducing this yesterday within the testsuite and couldn't... lmk what the issue was.

**Comment by ojii** [comment]
> Yeah I tried reproducing this yesterday within the testsuite and couldn't... lmk what the issue was.

The app was simply missing the `SENTRY_DSN` environment variable. I thought it was injected into the environment of the application, but misconfigured the deployment system and the variable never got set. Sorry for the trouble.
