### ISSUE TITLE
Deadlock (Hangs) during Garbage Collection because of logging in destructor and lock on `Queue`.

### ISSUE THREAD

**Issue by reivilibre** [getsentry/sentry-python#803]
Sentry uses a `Queue` internally which can lead to a deadlock when a destructor causes logging.

One notable cause of this issue is Twisted and its `Deferred`s.

This is because:

* The Sentry worker thread locks the Sentry queue to remove an item.
* Whilst the lock is held, garbage collection occurs.
* An object with a destructor is collected and has its `__del__` method called — in which it logs.
* Because it logs, that grabs the logging lock.
* It also tries to lock the Sentry worker's Queue — but it has to wait, because it's already locked.
* ⨳ Deadlock — GC/destructor needs Sentry lock to continue, but the Sentry lock is held by the Sentry worker which is blocked waiting for GC to complete.
* Because the logging lock is held, all other threads in the Python process lock up as soon as they try to log something.

After we discovered this issue, we found this article which talks about the same problem with Python's `Queue`: https://codewithoutrules.com/2017/08/16/concurrency-python/ .

The article proposes `SimpleQueue` as an alternative which does not have this problem (though I don't know about the limitations).

Notably, though, it was added in Python 3.7 — I'm not sure if Sentry would be happy to depend on Python >= 3.7 at this stage.

Nevertheless, I hope this issue saves someone else when they come to this issue tracker and search 'deadlock', even if nothing can be done to immediately solve the problem.

Thanks and best wishes.

**Comment by untitaker** [comment]
Thanks, I should have enough to repro this problem.

**Comment by untitaker** [comment]
my first instinct was to subclass and use RLock, but RLock also has problems: https://bugs.python.org/issue13697

This bug can happen during GC and signal handling. I wonder if it would make sense to drop events if the lock is not immediately acquired. That seems to be the safest way to deal with this.

**Comment by richvdh** [comment]
it's a bit of a heinous hack, but have you considered simply disabling garbage collection during the call to `Queue.get` ?

**Comment by richvdh** [comment]
https://bugs.python.org/issue13697 seems like it is only an issue on Python 2.7, so it might at least solve the problem for modern python versions?

**Comment by untitaker** [comment]
I haven't repro'd it yet, but I think this issue might also happen with signals (so independently of gc). Which leads me to believe we should invest in deadlock detection in `capture_event` and then start dropping events, as that seems to be the most generic solution

**Comment by richvdh** [comment]
The problem is, I'm not sure there is a way to do deadlock detection reliably without hitting all the same problems. What exactly do you have in mind?

Python signal handlers always run on the main thread, which means that I don't think you can hit the same problem with lines being logged from within Queue.get.

**Comment by untitaker** [comment]
@richvdh the problem is reproducible by only inserting into the queue, as that acquires the same mutex. I should have something ready soon

**Comment by untitaker** [comment]
The workaround in #814 is the same as sqlalchemy uses. We also didn't check in tests for this as they would take too long.

The previous concern about RLock is not important as it only happens with the Python impl of RLock, and we have not been able to repro any of this with signals either, so I suppose it's harder to hit.

**Comment by untitaker** [comment]
We've spent a week working on this now and I think we need to drop events if gc is running. I think generally it's not a great idea to log or even print in `__del__`.

**Comment by untitaker** [comment]
approaches:

* disable GC. ~How do you restore the prev value under concurrent put?~ actually put is now properly synchronized so the only problem are user-defined gc.disable, which should happen at import anyway
* stackwalk to find del and drop event, or use `gc.callbacks`, etc
* merge #814 and say "the python sdk has undefined behavior if you do this but at least it doesn't deadlock now".
* ship c extension (lol)
* rewrite using pure deque, use spin + sleep in flush, background thread just quits if queue is empty (and is started again later). I kinda like this approach
