### ISSUE TITLE
SSL Handshake Error on communication with Sentry

### ISSUE THREAD

**Issue by jp438-2** [getsentry/sentry-python#806]
I have been having issues integrating Sentry into a Django application. When I run the application locally with Sentry configured in settings.py (imported and initialised with a modern-style DSN) everything works perfectly with all errors showing up on Sentry as expected. However, when running the application on a server it is rare for errors encountered to actually be reported to Sentry, but it does happen occasionally. Looking at the logs for the docker container the application is running in, I can see the following SSL error occasionally appearing when an error is expected to appear on Sentry (although this doesn't happen very often or account for all the times the error doesn't appear on Sentry):

`Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),)': /api/<hidden_sentry_id>/store/`

This is how I have carried out the Sentry initialisation:

```
sentry_sdk.init(
    dsn="https://<hidden>@<hidden>.ingest.sentry.io/<hidden>",
    environment="dev",
    integrations=[DjangoIntegration()],
    traces_sample_rate=1.0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)
```
With different settings.py files used depending on the environment. Only the value for "environment" has been changed in the configuration on the server.

Does anybody have any advice on how to resolve this issue?

EDIT:
Another interesting thing to note is that causing errors **sometimes** pushes through old errors which are back-dated and appeared to be lost, even though the new error doesn't show up itself (for instance, I just caused a series of errors and sentry suddenly started showing a few errors timestamped from 42 minutes ago). It isn't 1:1 though, so causing 10 errors causes fewer than 10 old errors to appear - in fact, I just did 10 and 1 old error appeared.

**Comment by Katafalkas** [comment]
We are experiencing the same issue with AWS Lambdas (`integrations=[AwsLambdaIntegration()]`).
We are using `sentry-sdk==0.19.2`

**Comment by untitaker** [comment]
@jp438-2 I think you're actually forgetting to use the AwsLambdaIntegration here.

@Katafalkas are you getting exactly the same error message? What happens if you use `sentry_sdk.flush()` after capturing the error to make sure the event got sent out?

```
sentry_sdk.capture_exception(e)
sentry_sdk.flush()
```

**Comment by Katafalkas** [comment]
This is our wrapper:
```
def sentry_logging(func):
    @functools.wraps(func)
    def wrapper_decorator(*args, **kwargs):
        sentry_sdk.init(
            dsn=os.environ['SENTRY_DSN'],
            integrations=[AwsLambdaIntegration()]
        )
        try:
            value = func(*args, **kwargs)
        except Exception as e:
            logger.error(e, exc_info=True)
            raise
        return value
    return wrapper_decorator
```

I will try adding `sentry_sdk.flush()` after `logger.error(e, exc_info=True)`.

**Comment by untitaker** [comment]
Yes that sounds good, although to be clear this should happen automatically.

**Comment by Katafalkas** [comment]
@untitaker This happens only if the same instance of lambda is being re-used a lot.
Somehow it drains all the memory and times-out.

Just made the change - looking good so far. will run this for another hour.

**Comment by untitaker** [comment]
Usually aws's suspension is causing our background thread to not send data out fast enough. The `flush()` basically reserves more time (which in serverless translates to money spent) to send out this data. There's no remedy other than that.

The AwsLambdaIntegration should do this out of the box though: call flush() when the handler returns.

**Comment by Katafalkas** [comment]
After adding flush `SSLError` errors disappeared. The avg. duration of lambda did increase.

**Comment by untitaker** [comment]
actually @Katafalkas, instead of flushing can you try initializing the SDK during import time? I think that's the problem.

**Comment by bml1g12** [comment]
@untitaker  I also have this problem and am also initialising inside of the lambda handler currently with Python 3.7 and the following:
```
boto3==1.17.8
botocore==1.20.8
colorama==0.4.4
coverage==5.0.3
numpy==1.20.1
mypy==0.761
mypy-extensions==0.4.3
Pillow==8.1.2
pycodestyle==2.7.0
pylint==2.6.2
pylint-quotes==0.2.1
pylint-runner==0.6.0
pytest==4.4.0
pytest-timeout==1.4.1
pytest-xdist==1.27.0
pytz==2021.1
requests==2.25.1
scipy==1.6.0
sentry-sdk==1.1.0
typeguard==2.10.0
aws-lambda-powertools==1.15.1
typeguard==2.10.0
``` 

Could I clarify why initialising inside the lambda is incorrect? 

If so, it would be great if this was signposted quite clearly in the docs (sorry if it already is). I know the example shows declaration in global scope, but was not aware it was forbidden to declare it in local scope - we have been doing this throughout many repos. 

Also in what situations is flush() usage is expected to be required? I suppose we could add this to all our lambda handler top-level exception handlers if needed - but its a lot of boilerplate changes to do.

**Comment by untitaker** [comment]
flush() is a workaround, everything is supposed to work out of the box.

Initializing inside of the lambda is often too late and does not catch all errors that happen, but that it would cause SSLError is only a hunch as well.

**Comment by bml1g12** [comment]
I see thanks; well I will try initialising in global scope and get back to you.

**Comment by untitaker** [comment]
Yeah to be clear I am suggesting some workarounds here, if they work then we have a better idea of where the problem lies. A backwards approach to debugging but I don't see a better way to do remote diagnostics :(

**Comment by bml1g12** [comment]
@untitaker  indeed I can confirm moving the initialisation of sentry from the start of the handler into global scope seems to resolve this issue. I will proceed with making this change across our repo's when I get the time. This issue is specific to enabling the AWSLambdaIntegration integration.

**Comment by antonpirker** [comment]
So the issue here was that the `sentry_sdk.init()` was called to late (not in the global scope, but in the handler of the Lambda function). If Sentry is initialized as in the documentation shown (and linked in the previous comment above) than everything works as expected. 

I am closing this issue.
