### ISSUE TITLE
Is there a way to silent "Sentry is attempting to send N pending error messages"?

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [getsentry/sentry-python#810]
I'm experimenting using Sentry in an internal cli tool to submit performance metrics. On the completion of a cli command, the message

```
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

is shown. This may be useful for a long-living process such as a web app however this is disturbing with the cli usage because it doesn't give any value to the end user - they shouldn't even know about Sentry.

This issue was raised with raven at https://github.com/getsentry/raven-python/issues/904, but maybe this is now configurable with the new SDK?  It should be possible to attempt to redirect the stdout after the cli command has finished its work, but I would very much prefer using the configuration if that's possible.

Many thanks.

**Comment by untitaker** [comment]
if you call `sentry_sdk.flush()` yourself before, the message will not print. I think the documentation on https://docs.sentry.io/platforms/python/configuration/draining/ could be improved
