### ISSUE TITLE
Is there support for saving events on disk to be sent later?

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [getsentry/sentry-python#815]
I have a use case when a cli tool will run a command and the computer may not have the Internet connection so the events/performance metrics won't be sent. I want to save these events on disk and then send them when the user runs the cli tool again having the Internet connectivity (if one doesn't have the Internet again, it will be appended to the stored events to be sent later).

I am struggling to find documentation on how dump/load events that Sentry produces and then send them later. There is a [post](https://stackoverflow.com/questions/60801638/how-to-capture-an-easily-serialisable-exception-event-with-sentry) related but it's incomplete and [this post](https://forum.sentry.io/t/python-client-offline-record/9292) is about offline records for legacy Python client, but it doesn't describe saving/loading events from disk that can be used by subsequent runs of the cli program.

Many thanks.

**Comment by untitaker** [comment]
no support right now. it's been in discussion but right now we don't have anything at all. certainly nothing that works out of the box

**Comment by alexey-tereshenkov-oxb** [comment]
Thanks a ton @untitaker. 

Is there a mechanism to construct events from scratch to send them manually? I'd consider dumping the events data into some structured format to reconstruct later and then send them manually. Is using a simple 

```
from sentry_sdk import capture_message
capture_message('Some details about saved event I read from disk')
``` 

my only option?

**Comment by untitaker** [comment]
well you can do this:

```python
event_buffer = []
init(transport=event_buffer.append)

# use SDK APIs here normally
capture_message("hello world!")

# serialize/deserialize event buffer from/to disk, applicaiton restarts here
# at later point in time:

init("https://...")

for event in event_buffer:
    capture_event(event)
```

This would be the very simple option when you know you have internet at this point for sure.

I would recommend looking into `sentry_sdk.transport` and actually forking that code instead of calling `capture_event`, as this gives you more control about network retry and error recovery etc.
