### ISSUE TITLE
last_event_id() returns None after SentryAsgiMiddleware.__call__() finished

### ISSUE THREAD

**Issue by kamilglod** [getsentry/sentry-python#816]
I'm unable to access `last_event_id` of `SentryAsgiMiddleware` on exception handler in `Starlette` framework.
```python
from sentry_sdk import last_event_id
from sentry_sdk.integrations.asgi import SentryAsgiMiddleware
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route


async def test_endpoint(request):
    raise RuntimeError("test")


def exception_handler(*args, **kwargs):
    return JSONResponse({"last_event_id": last_event_id()})


app = Starlette(
    routes=[Route('/', test_endpoint)],
    exception_handlers={
        Exception: exception_handler,
    }
)
app.add_middleware(SentryAsgiMiddleware)
```  

the problem is probably with usage of Hub's context manager in `SentryAsgiMiddleware._run_app()` - after throwing exception you are clearing local `ContextVar` so `last_event_id` function tries to access wrong Hub instance.

**Comment by untitaker** [comment]
Can you try replacing the last line with `app = SentryAsgiMiddleware(app)`? (and move it as far down the file as necessary)

**Comment by kamilglod** [comment]
still doesn't work, response shows `{"last_event_id": null}` and if I add 
```python
                        from sentry_sdk import last_event_id
                        print(last_event_id())
```
to line https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/asgi.py#L144 it prints proper event id to console but response still shows null.

**Comment by untitaker** [comment]
Ok but if you wrap your entire app in that middleware, surely the exception handler runs also in the context manager? not sure what's going on

**Comment by kamilglod** [comment]
here is the full example to reproduce this issue:

```python
from sentry_sdk import last_event_id, init
from sentry_sdk.integrations.asgi import SentryAsgiMiddleware
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route


async def test_endpoint(request):
    raise RuntimeError("test")


def exception_handler(request, exc):
    return JSONResponse({"last_event_id": last_event_id()})


init(dsn='***')

app = Starlette(
    routes=[Route('/', test_endpoint)],
    exception_handlers={
        Exception: exception_handler,
    }
)
app = SentryAsgiMiddleware(app)
```

**Comment by kamilglod** [comment]
Probably if you wrap whole starlette app into `SentryAsgiMiddleware` (as in example above) the exception handler does not see last_event_id as it is generated later, in SentryAsgiMiddleware exception catch block.

**Comment by untitaker** [comment]
oh damn you're right. I suppose the workaround for now is to do `capture_exception` in your exception handler, but... yeah. I think that's just how it works if you are a generic asgi middleware and don't know about errorhandlers.

**Comment by untitaker** [comment]
Actually I have an idea, give me a couple hours

**Comment by untitaker** [comment]
Can you try this: https://github.com/getsentry/sentry-python/pull/817

**Comment by kamilglod** [comment]
confirm - works fine with double `SentryAsgiMiddleware` middleware and this fix.
