### ISSUE TITLE
SentryAsgiMiddleware doesn't set the "message" field in FastAPI

### ISSUE THREAD

**Issue by kozhushman** [getsentry/sentry-python#818]
I don' know why exactly, but **`SentryAsgiMiddleware`** doesn't set the "message" field in FastAPI. In result, all events have title `<no message value> ` in issues feed.
I managed to fix problem through this code:
```
def before_send(event, hint):
    error_name = event['exception']['values'][0]['type']
    event.update({"message": error_name})
    return event
```
All parts except this one are working great (so far) and I very appreciate this library, but I don' think this is expected behavior.

**Comment by untitaker** [comment]
can you post the link to an issue? sounds like a server issue to me

**Comment by kozhushman** [comment]
Sadly i can't, because this is enterprise. If you can say me what you need, i can generate test message and post necessary data.

**Comment by untitaker** [comment]
I guess I am just interested in a screenshot of the issues stream and the issue detail page, with redactions as necessary, though the exception type and mechanism would be most useful unredacted

**Comment by kozhushman** [comment]
![Screenshot from 2020-09-11 13-14-52](https://user-images.githubusercontent.com/22664873/92912089-24226f00-f432-11ea-92dd-2db1878177d0.png)
![Screenshot from 2020-09-11 13-19-51](https://user-images.githubusercontent.com/22664873/92912094-24bb0580-f432-11ea-8581-2fec978fdcd9.png)

**Comment by untitaker** [comment]
That Sentry installation is extremely old. I think your workaround is appropriate if you can't upgrade, but fwiw newer Sentry installations backfill from exception value and message

**Comment by untitaker** [comment]
Ah, `logger=uvicorn.error`. Nevermind. This is interesting! Can you show me how the JSON looks like in `before_send`?

**Comment by kozhushman** [comment]
How can you now it is old? I tried to not include any additional info and still! :)
Hm, i can try, but JSON is enormous. I need some time to reduct it

**Comment by untitaker** [comment]
>How can you know it is old? I tried to not include any additional info and still! :)

because the UI is themed differently at least. See https://docs.sentry.io/product/sentry-basics/guides/getting-started/

>Hm, i can try, but JSON is enormous. I need some time to reduct it

I only need `exception`, `logentry` and `message` toplevel keys, if that helps

**Comment by kozhushman** [comment]
[data.zip](https://github.com/getsentry/sentry-python/files/5208522/data.zip)
There it is. In that JSON `message` is not presented, because that's the issue :)
JSON is `event` from `before_send`.

**Comment by untitaker** [comment]
Right but you have `logentry` in there, that is supposed to be shown instead. Sentry 10 deprecates `message` in favor of `logentry`. If you want the Sentry 10 behavior I suggest copying `event['logentry']['message']` into `event['message']`

We support old SDKs in newer Sentry, but not newer SDKs in older Sentry. To enable support we would have to send the `message` attribute as well as `logentry`. I think we could add something to the SDK to enable support for older Sentries, but it would be a kind of option or an integration of some sort and definetly community maintained.

I recommend updating to Sentry 9 at least.

**Comment by kozhushman** [comment]
Oh, I see! Thanks for the clarification!
I can't influence the Sentry update, but now i know what is happening :)
