### ISSUE TITLE
sentry and asgi 'lifespan' scope type: documentation, bug or configuration issue?

### ISSUE THREAD

**Issue by tony** [getsentry/sentry-python#820]
Hi there, I'm not sure if issues relating to `lifespan` and asgi on sentry are resolved yet.

I got this error today after following [the instructions for `SentryAsgiMiddleware`](https://docs.sentry.io/platforms/python/guides/asgi/):

```
ValueError generic ASGI request error
No application configured for scope type 'lifespan'
```

sentry docs on asgi middleware: https://docs.sentry.io/platforms/python/guides/asgi/
asgi docs on lifespan: https://asgi.readthedocs.io/en/latest/specs/lifespan.html

Here are some related issues:
- https://github.com/getsentry/sentry-python/issues/505 - closed, but what's the conclusion?
- https://github.com/encode/sentry-asgi/issues/8 (archived repo)
- https://github.com/django/channels/issues/1216 - 

  > Any new development on this issue? It is really killing us on our sentry quota.
  > https://github.com/django/channels/issues/1216#issuecomment-678276662

I'm using uvicorn with sentry-sdk 0.16.5 (example event if you're sentry staff: b47f9e1ecd9547709404d84d51b9a0b9)

**Comment by untitaker** [comment]
#505 has been fixed as per comments. This seems like @tomchristie may have more info on it, but if all you need for now is to get rid of the error in Sentry to save money, use Sentry features: https://github.com/django/channels/issues/1216#issuecomment-691919943

**Comment by tony** [comment]
This has happened so long ago, I am going to close now.

If anyone bumps into this again, feel free to refer to this issue and create a new one.

**Comment by antonpirker** [comment]
As the original poster already closed this. I will again close this and post his same message: 

If anyone bumps into this again, feel free to refer to this issue and create a new one.
