### ISSUE TITLE
Failed to parse error

### ISSUE THREAD

**Issue by MasonLyons** [getsentry/sentry-python#823]
Python: 3.8.2
Dajngo: 1.11.29

from the init an sending I'm just receiving the following error:
`urllib3.exceptions.LocationParseError: Failed to parse: https://o******.ingest.sentry.io/api/*******/envelope/`
with the asterix replaced with my sentry URL

**Comment by untitaker** [comment]
What version of urllib3 are you using?

**Comment by MasonLyons** [comment]
urllib3 version is 1.25.8

**Comment by untitaker** [comment]
Could it be that this applies to you? https://github.com/psf/requests/issues/5476

**Comment by MasonLyons** [comment]
Thank you very much. upgrading six has solved the issue.

**Comment by AlyaGomaa** [comment]
upgrading six didn't fix it for me
```
pip uninstall requests 
pip install requests==2.21.0
```
fixed it
