### ISSUE TITLE
[Tech Support] How to use this with django?

### ISSUE THREAD

**Issue by devxpy** [getsentry/sentry-python#83]
Where exactly am I supposed to put `sentry_sdk.init()`?

If I put it in `settings.py`, I see no error messages being reported.

The [docs](https://docs.sentry.io/clients/python/integrations/django/?platform=python) say nothing about dajngo + new `sentry-sdk`, except the fact that `raven` one is deprecated!

**Comment by untitaker** [comment]
Hi, you can find the docs for Django using `sentry-sdk` here: https://docs.sentry.io/platforms/python/django/?platform=python

**Comment by untitaker** [comment]
(We're aware of the structural deficiencies of the new doc system. The intent was that you would have discovered it in "Getting started" using this alert:)

<img width="841" alt="screen shot 2018-09-25 at 22 28 08" src="https://user-images.githubusercontent.com/837573/46041126-643b9a80-c112-11e8-92fb-a42a35bb7a47.png">

**Comment by devxpy** [comment]
Wow! this thing JUST WORKS. Hope everyone can find this easily. 

Thanks for making this work so well.

**Comment by untitaker** [comment]
That's heartwarming to hear :)

Have you had experience with the previous raven SDK or are you new to Sentry?

**Comment by devxpy** [comment]
Yes. I was using raven earlier. 

Not only did I find 3 different configs at 3 different places (the django `LOGGING` dict) to do the logging, but I was also presented with a load of debugging logs in my ssh console, which was very disturbing.

This one just worked as I wanted it to.

**Comment by untitaker** [comment]
Glad to hear that! That was definetly the intention, to clean that up.

**Comment by devxpy** [comment]
Here is how you do it, for ref:

**settings.py**
```python
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
sentry_sdk.init(
     "<sentry-dsn>", release="<version-info>", integrations=[DjangoIntegration()]
)

```

**Comment by coler-j** [comment]
Should also add install instruction (with pip for sentry_sdk), most docs include this in setup instructions. Takes 30 seconds to find, but usually this is just included.

**Comment by untitaker** [comment]
The other integration pages already have this. Would be glad about a PR.

**Comment by untitaker** [comment]
Opened #183 so I don't forget
