### ISSUE TITLE
Default Integrations not working when init with sort of specified Integrations 

### ISSUE THREAD

**Issue by lubocheng** [getsentry/sentry-python#834]
https://docs.sentry.io/platforms/python/integrations/default-integrations/
What i mean is that, when I read document and some code  from above, i know there are some default-integrations
```python
_AUTO_ENABLING_INTEGRATIONS = (
    "sentry_sdk.integrations.django.DjangoIntegration",
    "sentry_sdk.integrations.flask.FlaskIntegration",
    "sentry_sdk.integrations.bottle.BottleIntegration",
    "sentry_sdk.integrations.falcon.FalconIntegration",
    "sentry_sdk.integrations.sanic.SanicIntegration",
    "sentry_sdk.integrations.celery.CeleryIntegration",
    "sentry_sdk.integrations.rq.RqIntegration",
    "sentry_sdk.integrations.aiohttp.AioHttpIntegration",
    "sentry_sdk.integrations.tornado.TornadoIntegration",
    "sentry_sdk.integrations.sqlalchemy.SqlalchemyIntegration",
)
```
But in the mean time, i want to config some other integrations, as below:
```python
import sentry_sdk
from sentry_sdk.integrations.excepthook import ExcepthookIntegration
from sentry_sdk.integrations.logging import LoggingIntegration

def init_sentry(app):
    sentry_sdk.init(
        **app.config["SENTRY_CONFIG"],
        environment=app.config["SENTRY_ENVIRONMENT"],
        integrations=[
            LoggingIntegration(event_level=None),
            ExcepthookIntegration(always_run=True),
        ],
    )
```

What i was hoping for is default-integrations should also work too, but it's not!  FlaskIntegration and CeleryIntegration won't work!
What should i do with sentry init? Hope for your help. Just now i must import all the integrations  needed.

**Comment by lubocheng** [comment]
find that i should config as below to enable all integrations(add "the _experiments" option)
but why not turn it on by default? Does this affect performance?
```python
def init_sentry(app):
    sentry_sdk.init(
        **app.config["SENTRY_CONFIG"],
        environment=app.config["SENTRY_ENVIRONMENT"],
        _experiments={
            "auto_enabling_integrations": True,
        },
        integrations=[
            LoggingIntegration(event_level=None),
            ExcepthookIntegration(always_run=True),
        ],
    )
```

**Comment by untitaker** [comment]
The list of default integrations is the list in the docs you linked. The list in the sourcecode is unrelated. Please pass celery and flask to `integrations` array. Btw this is documented... I am not sure why you need to read the sourcecode.

https://docs.sentry.io/platforms/python/guides/celery/
https://docs.sentry.io/platforms/python/guides/django/

>but why not turn it on by default? Does this affect performance?

Current concerns:

* Updating to newer SDK enables random integrations, impacts version compatiblity policy we have
* init is slower (in theory, should not be a real issue)

one day :)

**Comment by lubocheng** [comment]
what i want is to save some time with "less import"...but it turn to be wrong
i will write code as above

**Comment by untitaker** [comment]
Yes so we're looking for ways to make auto_enabling_integrations the default, but it would be a breaking change, and there are definetly drawbacks with too much magic.
