### ISSUE TITLE
Incorrect timeout warnings when using AWS Lambda integration

### ISSUE THREAD

**Issue by haranjackson** [getsentry/sentry-python#846]
sentry-sdk version: 0.17.8
AWS Lambda runtime: Python 3.8

My lambda function has a timeout of 29 seconds, but typically completes in <1s. When the lambda function is called multiple times in quick succession, the container for the lambda function is reused. When this happens, the threads that Sentry creates to manage the timeout warnings produce their warnings in subsequent function invocations (long after the function that they were created in has completed).

**Comment by koleror** [comment]
I think I have the same issue using sentry-sdk 0.18.0 and Python 3.7.9
