### ISSUE TITLE
About `ignore_errors`

### ISSUE THREAD

**Issue by WhyNotHugo** [getsentry/sentry-python#850]
Hi! I'm wondering if `ignore_errors` is something I can use of if it's deprecated.

The documentation has no mentions of the parameter at all, so I'm not sure if it's a "new, still no stabilised" thing, or an "old, discouraged" parameter.

The docs seem to indicate I can pass a string to it, can I pass the exception class path (eg: `myapp.mymodule.MyException`)?

**Comment by untitaker** [comment]
Feel free to use it, it's not going away at this point. You're right about its usage, you can pass strings and types

**Comment by untitaker** [comment]
we have #149 as task to document so I am closing this one

**Comment by WhyNotHugo** [comment]
Thanks!

I missed #149 when searching. Looking for "ignore exceptions" had too many results :sweat_smile:

**Comment by akx** [comment]
So [the final comment](https://github.com/getsentry/sentry-python/issues/149#issuecomment-1056642777) in #149 flat out says "`ignore_errors` does not exist", but... I mean, it still does exist? https://github.com/getsentry/sentry-python/blob/38a8a3d4ef69def7c0fc50a48a49786c9b12686f/sentry_sdk/client.py#L467-L487
