### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by samsont** [getsentry/sentry-python#86]
AttributeError 
'Identifier' object has no attribute 'postponed_alerts_counts'
ID: 8099fd1f8815496eaa1f815657918b9d
Sept. 26, 2018, 7:37:17 p.m. UTC
Exception

AttributeError: 'Identifier' object has no attribute 'postponed_alerts_counts'
  File "interfaces.py", line 43, in start
    self.startInternal()
  File "identifier.py", line 63, in startInternal
    send_time=send_time)
  File "identifier.py", line 128, in match_batch
    accepted = self.correct_by_past_history(match.person_guid, confident_score)
  File "identifier.py", line 91, in correct_by_past_history
    self.postponed_alerts_counts[guid] += 1

**Comment by untitaker** [comment]
Hi, what does this have to do with Sentry's Python SDK? A little bit more context about your problem would be useful.

**Comment by samsont** [comment]
My bad. Wrong data. Wrong problem. Sorry @untitaker
