### ISSUE TITLE
How to silent "Sentry is attempting to send N pending error messages" when exception is raised?

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [getsentry/sentry-python#862]
I am using an on-premise version of the Sentry, `Sentry 20.10.0.dev06e8f61c` and Python package `sentry-sdk 0.19.0`.

I have [asked previously](https://github.com/getsentry/sentry-python/issues/810) how to silent `"Sentry is attempting to send N pending error messages"` message when collecting _performance metrics_ and it works great by calling `sentry_sdk.flush()`:

```
def sentryperf(func):
    """Decorator to be used for submitting perf metrics to Sentry."""
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        with sentry_sdk.configure_scope():
            with sentry_sdk.start_transaction(
                    op="task",
                    name=f"cli:{func.__name__}",
            ):
                result = func(*args, **kwargs)
            sentry_sdk.flush()
            return result
    return wrapper
```

I use this decorator to wrap the functions I'd like to collect performance metrics on.

However, if an exception is raised, the `flush()` method won't be called simply because the interpreter never gets to that line of code.

```
import sentry_sdk

sentry_sdk.init(
    "address",
    traces_sample_rate=1.0,
)

@sentryperf
def foo():
    print("hello!")
    1/0
    return

foo()
```

This means that for situations when an exception is raised, the message

```
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

will still be shown. 

I've experimented wrapping the function call in the decorator above in `try/except/finally` block:

```
                try:
                    result = func(*args, **kwargs)
                except Exception as err:
                    sentry_sdk.capture_message(err)
                    print("Error!")
                    result = None
                finally:
                    sentry_sdk.flush()
```

and this works if I catch the exception, but as soon as I re-raise the exception, the message from Sentry that it's attempting to send error messages is shown.

Is there any way to silent this error message even when exceptions are raised?

That is, how do I silent the message from Sentry about sending the error messages with this case:

```
import sentry_sdk

sentry_sdk.init(
    "address",
    traces_sample_rate=1.0,
)

def foo():
    print("hello!")
    1/0
    return

foo()
```

**Comment by untitaker** [comment]
you can use bare `try: ... finally: ...` without catching the exception. Just delete the except: block.

If you want to do that anyway, use `capture_exception(err)` instead.

**Comment by alexey-tereshenkov-oxb** [comment]
Thank you, @untitaker , that's very helpful.

Posting a solution that worked for me - maybe it will be helpful for future self or others.

```python
def sentryperf(func):
    """Decorator to be used for submitting perf metrics to Sentry."""
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        with sentry_sdk.configure_scope():
            with sentry_sdk.start_transaction(
                    op="task",
                    name=f"cli:{func.__name__}",
            ):
                try:
                    sentry_sdk.flush()
                    result = func(*args, **kwargs)
                except Exception as err:
                    sentry_sdk.capture_exception(err)
                    sentry_sdk.flush()
                    raise err
                finally:
                    sentry_sdk.flush()

            sentry_sdk.flush()
            return result
    return wrapper


@sentryperf
def foo():
    print("hello!")
    1/0
    print("done")
    return


foo()
print("complete")
```

and it works great without showing me the message. If I understand it correctly, the current design of the `sentry_sdk` assumes that the only way to suppress the message is to wrap all the program code into `try/except` block which is fairly easy to do using a decorator as in example above.

**Comment by untitaker** [comment]
Yes but to be clear those lines should not be necessary:

```
                except Exception as err:
                    sentry_sdk.capture_exception(err)
                    sentry_sdk.flush()
                    raise err
```

**Comment by alexey-tereshenkov-oxb** [comment]
@untitaker thanks for the comment! It appears that they are actually required.

Run output is below.

With my original post:

```
hello!
Traceback (most recent call last):
  File "sentry_example_dec.py", line 42, in <module>
    foo()
  File "sentry_example_dec.py", line 25, in wrapper
    raise err
  File "sentry_example_dec.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "sentry_example_dec.py", line 37, in foo
    1/0
ZeroDivisionError: division by zero
```

Without the `except` block:

```
hello!
Traceback (most recent call last):
  File "sentry_example_dec.py", line 42, in <module>
    foo()
  File "sentry_example_dec.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "sentry_example_dec.py", line 37, in foo
    1/0
ZeroDivisionError: division by zero
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by ddzmanashvili** [comment]
Hello everyone, so I dont understand, isnt there any very simple solution to just not print those? This is very simple code of mine:
```python
import sentry_sdk
from sentry_sdk.integrations.aws_lambda import AwsLambdaIntegration
from sentry_sdk import capture_exception

sentry_sdk.init(
    dsn="DSN HERE",
    traces_sample_rate=1.0,
)

if __name__ == '__main__':

    print('Before')
    capture_exception(Exception('This is a test'))
    print('After')
```

So how can I silent it here?

**Comment by untitaker** [comment]
That exact question was answered three messages down from the top.
