### ISSUE TITLE
Can't configure transaction name for aiohttp integration

### ISSUE THREAD

**Issue by asovchar** [getsentry/sentry-python#878]
Aiohttp integration doesn't allow to configure transaction naming style. 
I was trying to configure tracing and filter service endpoints from being reported to Sentry by their routes. Aiohttp integration names transactions after request handler and doesn't support any other naming styles, like other framework's integrations do.

**Comment by untitaker** [comment]
I saw you opened https://github.com/getsentry/sentry-python/pull/876, I left a comment there -- You can always set the transaction manually using `sentry_sdk.set_transaction`. That's not ideal though.
