### ISSUE TITLE
Performance monitoring and probe/monitoring service [LivenessProbe,ReadinessProbe]

### ISSUE THREAD

**Issue by ldath** [getsentry/sentry-python#887]
Hi,

I was trying to exclude my web `/probe` endpoint from performance monitoring but based on the current documentation this is very hard to achieve. I was checking `before_send` but looks like this is only working for events like Errors and totally ignored for the Transactions.

99.99% of my transactions are probe events created by the Kubernetes which are having 0 importance for me and I'm forced to use: `traces_sample_rate=0.01,`  to not burn my Subscription in no time.

How to stop transaction for an endpoint like this in Flask:

```
@main.route('/probe', methods=['GET', 'HEAD'])
def probe():
    return jsonify(status="success", message="I'm alive")
```

Please help - I was so happy with this new feature that I upgraded to the paid plan in sentry.io

**Comment by untitaker** [comment]
Please refer to https://github.com/getsentry/sentry-python/issues/775
