### ISSUE TITLE
please add middleware.SentryResponseErrorIdMiddleware

### ISSUE THREAD

**Issue by find456789** [getsentry/sentry-python#889]
https://github.com/getsentry/raven-python/blob/master/raven/contrib/django/middleware/__init__.py#L67

**Comment by untitaker** [comment]
You can call `sentry_sdk.last_event_id()` to get the last event ID at any point in time. But we will not add a 5-line middleware to the sdk.

I'll see this as a documentation issue, because this used to be documented but apparently is now missing.

**Comment by ad-m** [comment]
That middleware is still references in that section of Sentry documentation: https://docs.sentry.io/clients/python/integrations/#django

**Comment by pheanex** [comment]
As there does not seem to be a drop in replacement with the new sdk, has anyone come up with a good workaround?
