### ISSUE TITLE
assign different traces_sample_rate values to different urls

### ISSUE THREAD

**Issue by Lynaj** [getsentry/sentry-python#895]
I have recently enabled tracking in my Django project. I did set `traces_sample_rate=0.2`. I want to assign different `traces_sample_rate` values to different urls. 

What's more, I would like to ignore some of the urls.py from the performance report, but in the documentation there are no information, that could help me achieving it.

What is the most sophisticated way of doing that?

**Comment by untitaker** [comment]
Please always go through the open issues before filing a new one: https://github.com/getsentry/sentry-python/issues/775
