### ISSUE TITLE
set_context type hint incorrectly set to `Any`

### ISSUE THREAD

**Issue by rossettistone** [getsentry/sentry-python#899]
From reading the Sentry docs (https://docs.sentry.io/platforms/python/enriching-events/context/) and the source code for `set_context(key: str, value: Any)`, we tried the following in our codebase:

```python
with push_scope() as scope:
    scope.set_context('source_key', 'foo')  # 'source_key' is a term in our application
```

Unfortunately, this led to an error in the UI with the reason "expected an object".
<img width="422" alt="Screen Shot 2020-10-27 at 4 43 08 PM" src="https://user-images.githubusercontent.com/1834981/97365323-806f1000-1873-11eb-9fce-5b53c923b288.png">

I may be misunderstanding something, but it seems that `set_context` should be annotated with `value: Dict`, and the docs updated accordingly. Is this correct?

**Comment by untitaker** [comment]
Do the docs actually need changing? the docs use a dict value.

**Comment by rossettistone** [comment]
The example in the docs does show a dict example, it's true. The first line of the docs seems like it might be inaccurate, though: "Custom contexts allow you to attach arbitrary data (strings, lists, dictionaries) to an event."

That line could be interpreted as meaning that strings, lists, and dicts can be passed as values within the top-level dict, which is accurate. To me, though, it's unclear at best that this was the intended meaning, particularly in light of the `Any` type hint.

I defer to you on what the right behavior and annotation are here. From my user perspective, though, the docs are confusing as is.

**Comment by untitaker** [comment]
You're totally right, I will update both (see referenced PRs)

**Comment by rossettistone** [comment]
Thanks very much! The changes look great.
