### ISSUE TITLE
Django Rest Framework, 403 Forbidden

### ISSUE THREAD

**Issue by alexjpm** [getsentry/sentry-python#900]
Hi,

When posting to my site api with sentry enabled, I get a 403 Forbidden response (and nothing appears on the sentry issue dashboard).  When I disable sentry, however, it works.  Otherwise sentry is working well and reporting other issues.

With sentry enabled:
Posting using python's requests.post. Example post format is:
headers: {'Authorization': 'Token token', 'Content-type': 'application/json'}
data: {'full_name': 'A M', 'email_address': ''}
Response:
403
b'{"detail":"Authentication credentials were not provided."}'

Version 0.9.1 of sentry, 3.9.4 of rest-framework.

I saw the issue:
https://github.com/getsentry/sentry-python/issues/24
which looks similar, but I'm using a later version than given in the solution.

Can anyone help with this?

**Comment by untitaker** [comment]
@alexjpm I can't help you like this. Can you create a demo app that exhibits this issue?

**Comment by alexjpm** [comment]
@untitaker I have, and in the process discovered the issue (which was in my setup).

Turns out that the sentry_sdk.init() call was taking place before the AUTHENTICATION_BACKENDS were set in my settings.py.  Moving sentry_sdk.init() to the end of the settings.py file fixed the issue.

Thanks for your time.
