### ISSUE TITLE
sentry_sdk crash on exc_info

### ISSUE THREAD

**Issue by dpgaspar** [getsentry/sentry-python#904]
Hi,

Getting this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/logging.py", line 164, in emit
    return self._emit(record)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/logging.py", line 178, in _emit
    if record.exc_info is not None and record.exc_info[0] is not None:
TypeError: 'int' object is not subscriptable
```

ver: `sentry-sdk[flask,sqlalchemy]==0.14.2`

**Comment by untitaker** [comment]
I'm sorry but I need more info to go by. How can I reproduce this?

**Comment by dpgaspar** [comment]
It seems that happens immediately after a celery process crash
```
Process 'ForkPoolWorker-7' pid:418 exited with 'signal 9
```

**Comment by untitaker** [comment]
Okay. What is your celery version + version of dependencies?

**Comment by untitaker** [comment]
Nevermind I found the bug!

**Comment by untitaker** [comment]
so this is celery billiard logging with `exc_info=0`, which we don't handle. However, we are not supposed to. The logging stdlib module internally is supposed to mutate teh record such that `exc_info` is never a bool or int.

Celery is doing something weird to bypass that part of the pipeline.

**Comment by dpgaspar** [comment]
Could you just do:
```
if record.exc_info is not None and isinstance(record.exc_info, list) and record.exc_info[0] is not None:
```
To play safe?

**Comment by untitaker** [comment]
Sure I am mostly concerned with figuring out where that bad value even comes from. Surely celery can't misuse loggers that badly?

**Comment by dpgaspar** [comment]
True, let me re check on my side also, I'll came back with more info

**Comment by untitaker** [comment]
Actually, this does not handle exc_info=0:

https://github.com/python/cpython/blob/5241e189e77972d3a07acbbb3f0c0cbc2aeeb681/Lib/logging/__init__.py#L1588-L1592

**Comment by dpgaspar** [comment]
Checked on my side, actually found that I'm assuming that `exec_info` always is a tuple with `(class type, Exception, traceback)`
