### ISSUE TITLE
Rq Integration does not seem to capture exceptions when initiated in Flask app. (Question)

### ISSUE THREAD

**Issue by nmb2405** [getsentry/sentry-python#907]
This is sort of what my `app.py` looks like. The entire code is found [here](https://github.com/nmb2405/demo-sentry-flask-rq)
Exceptions raised in flask in the `/error` route are caught by sentry, but the errors raised in `broken_function` after I enqueue it in the route `/enqueue` do not seem to get caught.
Will I have to initialize it separately for each, or am I doing something wrong which is most likely the case.

app.py
```python
import sentry_sdk
from sentry_sdk.integrations.rq import RqIntegration
from sentry_sdk.integrations.flask import FlaskIntegration

sentry_sdk.init(os.environ['SENTRY_DSN'], integrations=[FlaskIntegration(), RqIntegration()])

app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'

@app.route('/error')
def error():
    return 1/0    #Works and is caught by sentry

@app.route('/enqueue')
def enqueue():
    q = Queue(connection=Redis())
    result = q.enqueue(broken_function, "Error within RQ job.")   #does not work
```

worker.py
```python
from rq import Connection, Worker, Queue

with Connection():
	worker = Worker(map(Queue, ['default']))
	worker.work()
```

pip freeze
```
blinker==1.4
certifi==2020.6.20
click==7.1.2
Flask==1.1.2
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
pkg-resources==0.0.0
redis==3.5.3
rq==1.5.2
sentry-sdk==0.19.1
urllib3==1.25.11
Werkzeug==1.0.1
```

I run app.py like `SENTRY_DSN={sentry_dsn_url} app.py` and worker.py as simply `python worker.py`.

**Comment by untitaker** [comment]
Right, that's because you don't initialize the SDK in the RQ worker at all. You need to initialize it in both, or import the flask app in your worker, for anything to function.
