### ISSUE TITLE
[dev] Flask-dev tests failing

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry-python#917]
I think it has something to do with this: https://github.com/pallets/flask/pull/3827, but I'm not sure quite how to fix it.

If it _is_ to do with the above, it sounds from the description there like the problem might resolve itself in time. In the meantime, what's the best solution to keep master from being perma-red?

**Comment by untitaker** [comment]
Let's wait 24h, then master will restart

**Comment by lobsterkatie** [comment]
🤔

I'm not sure what you mean. The issue isn't master itself - the issue is that our `flask-dev` tests currently almost all fail, through no changes of ours. (This happens on branches, too, but since it's not caused by a branch's changes, it also applies to master.)

**Comment by untitaker** [comment]
>there like the problem might resolve itself in time.

I am referring to this. The master build of sentry-python will restart every 24h and if this PR fixes the issue the build should become green.

**Comment by lobsterkatie** [comment]
No, that was referring to 

> Tox always tests with the latest code of the other Pallets projects. This will be changed back once the new versions are released.

in the PR I linked.

In any case, am going to comment out the flask-dev tests for the moment as we agreed IRL.

**Comment by lobsterkatie** [comment]
This was fixed here: https://github.com/getsentry/sentry-python/commit/fae6d62abd761184adc11b21f90b213dcb1814d5#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449R302-R311

We should revisit this at some point, to see if we can bump werkzeug to a more recent version.
