### ISSUE TITLE
Sentry events aren't triggered by API errors (djangorestframework)

### ISSUE THREAD

**Issue by sunweiyang** [getsentry/sentry-python#918]
I have switched my Heroku Django project (which uses `djangorestframework`) from raven to sentry-python. I can trigger manual errors and Sentry issues get reported just fine, but API errors (400's, etc.) aren't getting reported as expected.

I tried investigating some related issues (#397, #408, #900), but it seems that they are unrelated. Am I missing something in my config to support DRF?

My project details:
* django==3.1.3
* djangorestframework==3.12.1
* sentry-sdk==0.19.2
* gunicorn==20.0.4
* uvicorn[standard]==0.12.2

My Heroku Procfile (Python 3.8.5 runtime):
```
release: python manage.py migrate
web: gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker
worker: celery -A skale.taskapp worker -l info
beat: celery -A skale.taskapp beat -l info -S django
```

My init in settings.py:
```
import environ

import sentry_sdk
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration

env = environ.Env()

# This is placed at the very end of my settings.py file

SENTRY_DSN = env('DJANGO_SENTRY_DSN')
sentry_sdk.init(
    dsn=SENTRY_DSN,
    integrations=[DjangoIntegration(), CeleryIntegration()],
    traces_sample_rate=1.0,
    send_default_pii=False
)
```

**Comment by untitaker** [comment]
This is expected behavior. If you want those errors to be reported you need to capture them manually. We don't consider a 400 to be inherently actionable, so we decided not to capture it. I recommend instrumenting your frontend or whichever http client then crashes as a result of that 400.
