### ISSUE TITLE
Error with sentry_streaming_body_read

### ISSUE THREAD

**Issue by darwinyip** [getsentry/sentry-python#922]
> File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/boto3.py", line 96, in sentry_streaming_body_read
>	    for value in stream:

This comes from getting a `ConnectionResetError` from a stream in boto3's `StreamingBody`.

**Comment by untitaker** [comment]
We wrap boto3 and as such there will be a frame of the SDK in every error involving boto3, regardless of whether we are responsible for it or not. I don't think this is a SDK bug based on the information you provided.
