### ISSUE TITLE
Integration for Selenium

### ISSUE THREAD

**Issue by eduardovra** [getsentry/sentry-python#929]
Currently when integrating with selenium, sentry produces httplib breadcrumbs on every browser interaction, but not much detail is revealed about the action being executed.
I think it would be nice to show things link the URL when we perform a GET operation, or the element selector when we're reading or writing to the DOM.

Does anyone else have interest in this feature ? I could help implementing it.

**Comment by antonpirker** [comment]
Hello @eduardovra 
Thanks for writing in. As it looks, there is not that much demand for this feature. Sorry.
I will close this issue now.

If someone is coming to this issue and is also interested in this feature, please open a new issue!
