### ISSUE TITLE
Integration for aioredis

### ISSUE THREAD

**Issue by yoav-orca** [getsentry/sentry-python#931]
`aioredis` is an async client for Redis. It's a very useful primitive for getting the most out of async code that works with redis.

Sticking with the format of other feature requests: 

Please vote with 👍 on this post if you're interested in this.

**Comment by rushilsrivastava** [comment]
Keeping this issue alive.

**Comment by Zhenay** [comment]
Hey, @antonpirker!

`aioredis` is now part of `redis-py` since 4.2 package version.

I'm going to try to make this. Should I support both or only `redis-py`?

**Comment by antonpirker** [comment]
Hey @Zhenay !

Thanks for jumping in! Really amazing! 
If you are just starting with the implementation just `redis-py`, no need to support already dead projects!
