### ISSUE TITLE
Not getting exceptions using RQ integration

### ISSUE THREAD

**Issue by vincentwoo** [getsentry/sentry-python#935]
Hi there,

I'm using sentry with RQ, Python, and Flask. I have no problems receiving sentry exceptions in Flask endpoints, but have not gotten any sentry issues from exceptions thrown within my async worker. My `worker.py` is roughly as follows, and is invoked on Heroku with `python worker.py`

```python
sentry_sdk.init(
  os.environ['SENTRY_DSN'],
  integrations=[RqIntegration()],
  environment=os.environ['FLASK_ENV']
)

def expensive_work_function():
   # app-specific worker stuff here

listen = ['high', 'default', 'low']
redis_url = os.getenv('REDIS_URL', 'redis://localhost:6379')
conn = redis.from_url(redis_url)
if __name__ == '__main__':
  with Connection(conn):
    worker = Worker(map(Queue, listen))
    worker.work(with_scheduler=True)
```

Am I missing something obvious? I can't find any documentation about additional steps that would be necessary. This is on Sentry 0.19.4, Flask 1.1.2, and Python 3.8.6.

**Comment by untitaker** [comment]
If you have a Flask app it could be that your SDK initialization for the Flask app overrides the one for RQ, as it is likely imported from RQ at some point. I would recommend to always turn on all integrations all the time, and actually only have one SDK initialization that gets imported from everywhere.

**Comment by vincentwoo** [comment]
This seemed to help!
