### ISSUE TITLE
Django 3.1 async views working "synchronously" with sentry_sdk

### ISSUE THREAD

**Issue by Ivo-Donchev** [getsentry/sentry-python#937]
Hi,
I have the following case:
I'm running a production Django (3.1) application with the following **sentry configuration**:
```
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            LoggingIntegration(
                event_level=logging.WARNING
            )
        ],
        send_default_pii=True,
        release=SENTRY_RELEASE,
        traces_sample_rate=1.0
    )
``` 

**The problem** is that the when I initialize the sentry_sdk **my async view is running synchronously**.

After a bit of a **research** in the sentry_sdk code: I was trying to isolate the code that causes that and check if it's an error in my setup, and I got to the following:
https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/django/middleware.py#L105-L137 . So if I comment the `SentryWrappingMiddleware` **my view is back to async**. I assume that the `SentryWrappingMiddlware` is making the middleware chain synchronous which blocks the requests handling and makes the View "sync" at the end.
 
So my question is: Is it an issue in the sdk, or is it my configuration wrong? :slightly_smiling_face: 

It's the last wall that stops me to migrate my views to async version:( 

Thanks,
Ivo

**Comment by untitaker** [comment]
hey @Ivo-Donchev, I think this is an issue with the SDK. I'm going to put this as bug in our backlog but I can't tell you yet when we get to it. Sorry for the inconvenience!

**Comment by untitaker** [comment]
It may be possible to work around this issue by passing `middleware_spans=False` to `DjangoIntegration`, but I am not entirely sure.

**Comment by Ivo-Donchev** [comment]
Hi @untitaker ! Thanks for the quick response :bow: 

I just tried the `middleware_spans=False` and I got the same result:(

Btw, do you accept contributions ? I could fork and open a PR with a proposal for solution ?

**Comment by untitaker** [comment]
Yes we 100% accept contributions!

**Comment by Ivo-Donchev** [comment]
Great! will try to make it this week :slightly_smiling_face:

**Comment by Ivo-Donchev** [comment]
Hey @untitaker 
I managed to solve the problem here - https://github.com/getsentry/sentry-python/pull/938/

The tests are passing so I hope I haven't introduce a regression. It'd be great if you can take a look :slightly_smiling_face:
