### ISSUE TITLE
Blinker dependency

### ISSUE THREAD

**Issue by decaz** [getsentry/sentry-python#940]
Why Flask integration depends on blinker if it's not used within sentry-sdk? Maybe it worth to remove it because it's unnecessary?

**Comment by untitaker** [comment]
The dependency is necessary because signals in Flask do not work without blinker.

**Comment by decaz** [comment]
@untitaker yeah, I know about it, and even Flask itself doesn't depend on blinker (you have to install it manually if you need signals). But I don't understand why sentry-sdk needs blinker, - does it use blinker?

**Comment by untitaker** [comment]
Yes, we subscribe to signals of Flask so we know when requests start/end.

**Comment by decaz** [comment]
Ah, I didn't notice the place where they are used, sorry.
