### ISSUE TITLE
Lambda via ApiGateway Console has no headers

### ISSUE THREAD

**Issue by raphael-riel** [getsentry/sentry-python#944]
When testing a Lambda via ApiGateway (HTTP Call) everything's fine.

But when I call the same endpoint using [AWS' ApiGateway Console](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-test-method.html#how-to-test-method-console), I get this error.
Since headers are not passed in this specific context, `headers = None`.

```
{
   "errorMessage":"'NoneType' object has no attribute 'get'",
   "errorType":"AttributeError",
   "stackTrace":[
      "  File \"/var/task/sentry_sdk/integrations/aws_lambda.py\", line 138, in sentry_handler\n    transaction = Transaction.continue_from_headers(\n",
      "  File \"/var/task/sentry_sdk/tracing.py\", line 291, in continue_from_headers\n    headers.get(\"sentry-trace\"), **kwargs\n"
   ]
}
```

**Comment by yongzhi2** [comment]
Same issue here.
