### ISSUE TITLE
Minor: readme.md logo could use a white border

### ISSUE THREAD

**Issue by alexmcroberts** [getsentry/sentry-python#946]
Today, GitHub released Dark Mode. This has the side effect of making the Sentry logo invisible on the readme.md page

Might be useful to modify the logo for visibility - add a small white border or replace with a colour logo

**Comment by untitaker** [comment]
I tried a bunch of things, they all look bad in one way or another. All of them look worse than black on white in light mode.

Tried to do something with media queries in svg too, but, well, github dark mode does not actually use media queries.
