### ISSUE TITLE
aiohttp integration failed when application method returns None

### ISSUE THREAD

**Issue by abcdenis** [getsentry/sentry-python#951]
Hi,
I made a mistake on my code and forgot to write return on the end of aiohttp method.
So there was an exception inside sentry integration on response.status calculation and no message on sentry.
I think it will be nice to catch such exceptions.
Thank you.

sentry-sdk version 0.14

Somewhere in log:
```
December 11th 2020, 18:38:33.031    return await asyncio.get_event_loop().create_task(inner())
December 11th 2020, 18:38:33.031AttributeError: 'NoneType' object has no attribute 'status'
December 11th 2020, 18:38:33.031    resp = await task
December 11th 2020, 18:38:33.031Traceback (most recent call last):
December 11th 2020, 18:38:33.031  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/aiohttp.py", line 99, in sentry_app_handle
December 11th 2020, 18:38:33.031ERROR:aiohttp.server:Error handling request
December 11th 2020, 18:38:33.031  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/aiohttp.py", line 93, in inner
December 11th 2020, 18:38:33.031  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start

```

**Comment by antonpirker** [comment]
Hey @abcdenis 
Thanks for reporting this and sorry for the late reply.
Could you check if this is still an issue with the latest SDK? Thanks!

**Comment by jxtcman** [comment]
I'm still experiencing this on version 1.19.1

`ERROR:aiohttp.server [2023-04-19 09:56:49,829] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/aiohttp.py", line 128, in sentry_app_handle
    transaction.set_http_status(response.status)
AttributeError: 'NoneType' object has no attribute 'status'
`
