### ISSUE TITLE
How to make performance monitoring for Django count requests?

### ISSUE THREAD

**Issue by Fazel94** [getsentry/sentry-python#966]
Currently, my performance tab just counts `celery` tasks.  
I want it to sample requests too, but I can't figure out a way to do it besides writing a middleware and starting a transaction on each processed request.  
I think it isn't elegant enough.  
Am I missing something? or is it just default behavior? I couldn't find a simple proper way to activate it on requests.
  
`sentry_sdk == 0.19.5`  
`Django == 2.2.17`  
`Python == 3.8.2`  
Setting:  
```python
sentry_sdk.init(
     dsn=SENTRY_LEGACY_DSN,
     traces_sample_rate=0.05,
     integrations=[DjangoIntegration(), CeleryIntegration()]
)

```

**Comment by untitaker** [comment]
It should do this by default. Are you initializating the sdk in two places
perhaps?

**Comment by Fazel94** [comment]
That was exactly what happened.
Thank you .
