### ISSUE TITLE
sentry django integration: Incorrect request name is returned in transaction_context in the Dynamic Tracing

### ISSUE THREAD

**Issue by savvagen** [getsentry/sentry-python#969]
I am using `django:2.2` and `sentry-sdk:latest`
The function of dynamic tracing is:

```
def traces_sampler(sampling_context):
    name = sampling_context["transaction_context"]["name"]
    if "/api/articles" in name:
        return 0.5
    else:
        # Default sample rate
        return 0

sentry_sdk.init(
    dsn="....",
    integrations=[DjangoIntegration()],
    traces_sampler=traces_sampler,
)
```
According to [documentation](https://docs.sentry.io/platforms/python/guides/django/performance/sampling/) I am expecting human readable `transaction_context` name to be returned  in `sampling_context`
Expected: 
`
"transaction_context": {  "name": <string>  # human-readable identifier, like "GET /users" }
`
Actual:
`"transaction_context": {  "name":  "generic WSGI request" } 
`
According to this I am not able to sort request transactions ...
Is there is any way how to fix this?

**Comment by untitaker** [comment]
Yes, this is a known issue. Instead we should show examples where the request URL is accessed.

The unfortunate issues is that a transaction ideally should start before routing takes place. With how the SDK currently works that means the sampling decision has to be made before routing.

**Comment by untitaker** [comment]
@lobsterkatie I'm assigning you since you probably know best what we are supposed to recommend here

**Comment by lobsterkatie** [comment]
You can get the original URL from the `wsgi_environ` entry in the sampling context, and then either decide on that directly or run it through the resolver. We actually [just started doing that](https://github.com/getsentry/sentry/pull/22993) as well.

**Comment by untitaker** [comment]
need to fix docs then

**Comment by untitaker** [comment]
Perhaps one generic caveat that the sampling context is captured before the transaction starts, or change the example for `"name"` to something else. Not entirely sure.

(see link in OP)

**Comment by lobsterkatie** [comment]
Ah, yes. That code snippet was ported over from JS, where `name` _is_ human readable... Didn't catch that that wouldn't be true for Python. I'll update.
