### ISSUE TITLE
AWS Lambda integration cannot detect awslambdaric bootstrap correctly

### ISSUE THREAD

**Issue by adam-olema** [getsentry/sentry-python#972]
Environment:

* python 3.8.5
* awslambdarie (v1.0)
* awslambdaric (v1.0.0)
* sentry-sdk==0.19.5
* handler in a submodule, ie run with:

      aws-lambda-rie python -m awslambdaric my_module.app_module

Error:

     Not running in AWS Lambda environment, AwsLambdaIntegration disabled (could not find handle_event_request)

I have not tried this in production.

The problem appears to be in "get_lambda_bootstrap" which is choosing sys.modules["\_\_main\_\_"] when in fact, the correct module is sys.modules["\_\_main\_\_"].bootstrap

**Comment by adam-olema** [comment]
Have a PR for this, but it doesn't look like the CI runs the tests at all, and thus it is failing the coverage check and I can't figure out how to get the tests to run in my local env at all.  They just skip.  Stuck on that.

**Comment by untitaker** [comment]
I think this is fixed as well
