### ISSUE TITLE
AWS Lambda Integration crash: local variable 'timeout_thread' referenced before assignment

### ISSUE THREAD

**Issue by adam-olema** [getsentry/sentry-python#974]
Environment:

* python 3.8.5
* awslambdarie (v1.0)
* awslambdaric (v1.0.0)
* sentry-sdk==0.19.5
* handler in a submodule, ie run with:

   aws-lambda-rie python -m awslambdaric my_module.app_module

* After fixing: https://github.com/getsentry/sentry-python/issues/972

After handling an exception and sending it to sentry.io, sentry handler crashes with:

```
    UnboundLocalError: local variable 'timeout_thread' referenced before assignment
    Traceback (most recent call last):
       File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/integrations/aws_lambda.py", line 160, in sentry_handler
        if timeout_thread:
```

Sentry event does appear on sentry.io, so it was successfully sent before this error.  However this error acts as a lambda request failure as far as the ric and rie are concerned.

**Comment by adam-olema** [comment]
Have a PR for this, but it doesn't look like the CI runs the tests at all, and thus it is failing the coverage check and I can't figure out how to get the tests to run in my local env at all.  They just skip.  Stuck on that.

**Comment by untitaker** [comment]
I think this is fixed now, thanks again for the fix
