### ISSUE TITLE
Performance Monitoring with Starlette (asgi) Leads to Doubling of Response Time

### ISSUE THREAD

**Issue by cancan101** [getsentry/sentry-python#987]
I am using Starlette (asgi) + Ariadne for GraphQL responses. I was trying to track down why I am seeing performance traces like this:
where all of the DB / resolvers complete pretty quickly:
![image](https://user-images.githubusercontent.com/51059/105556879-f51de300-5cd8-11eb-8cda-35d0a666939e.png)
but then then the return happens much later (slightly different instance of the transaction but these were for the same request payload):
![image](https://user-images.githubusercontent.com/51059/105556921-0cf56700-5cd9-11eb-9acb-0712fd1a5816.png)
where the response is taking ~ 25-30 seconds. When I disabled Sentry performance the time goes down ~ 12-15 seconds

I used the New Relic thread profiler. W/o sentry I see:
![image](https://user-images.githubusercontent.com/51059/105557065-5b0a6a80-5cd9-11eb-9cc5-d4402164de56.png)
but with it I see:
![image](https://user-images.githubusercontent.com/51059/105557102-6a89b380-5cd9-11eb-97c9-08ff96cdea9b.png)

It seems like there might be some blocking occurring due to Sentry reporting the data.

*UPDATE* With some additional testing the differences in response time do not seem as extreme; however, I would still like to understand better if the time spent shown by the thread profiler should be cause for concern.

**Comment by untitaker** [comment]
The Python SDK spawns a regular background thread for sending messages to unblock the main thread. I am not sure how the NewRelic profiler works but it's entirely expected that there's a second callstack, but not that that second thread runs synchronously with the main/gunicorn one.

One question I have is how you measure response time. Is that on the load balancer or also from within the app?
