### ISSUE TITLE
How can I send long string information (or text files) using capture_message or capture_error?

### ISSUE THREAD

**Issue by PasaOpasen** [getsentry/sentry-python#996]
I need to see both things:
1. exception trace
2. some data I can collect before raising exception

I'm using next code:
```python
        sys.stdout = open("OUTPUT.txt", "w") # to log from print()
        
        try:
        # some actions, some calls

        except Exception as err:
            sys.stdout.close() # save file of outputs

            # read all lines from file
            with open("OUTPUT.txt", 'r') as file:
                lines = file.readlines()
            
            capture_message(''.join(lines)) # capture this data
            raise err # and exception
```

It works not so well because the length of message is highly bounded. Also I wanna to get all this data as one event: exception + my info

Can I send text or text file with raising exception?

**Comment by untitaker** [comment]
https://docs.sentry.io/platforms/python/enriching-events/context/, or attachments API for larger data

it seems that we did not document attachemnts in python for whatever reason. I will open a new issue for that

**Comment by untitaker** [comment]
https://github.com/getsentry/sentry-python/issues/997

**Comment by iker-barriocanal** [comment]
Similar to https://github.com/getsentry/sentry-python/issues/997.
